/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL || 'https://www.nursefiti.co.ke',
  generateRobotsTxt: true,
  generateIndexSitemap: false,
  changefreq: 'weekly',
  priority: 0.7,
  sitemapSize: 5000,
  exclude: [
    // Auth & private routes
    '/login',
    '/signup',
    '/signup-tutor',
    '/forgot-password',
    // Student dashboard (requires auth)
    '/dashboard',
    '/practice',
    '/mock-exam',
    '/flashcards',
    '/analytics',
    '/achievements',
    '/groups',
    '/revision-plan',
    '/bookings',
    '/settings',
    '/onboarding',
    // Tutor dashboard (requires auth)
    '/tutor-dashboard',
    '/tutor-schedule',
    '/tutor-students',
    '/tutor-studio',
    '/tutor-earnings',
    '/tutor-reviews',
    '/tutor-profile',
    '/tutor-pending',
    // Admin routes
    '/admin',
    '/admin/*',
    // API routes
    '/api/*',
    '/auth/*',
  ],
  robotsTxtOptions: {
    policies: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/api/',
          '/auth/',
          '/dashboard',
          '/practice',
          '/mock-exam',
          '/flashcards',
          '/analytics',
          '/achievements',
          '/groups',
          '/revision-plan',
          '/bookings',
          '/settings',
          '/onboarding',
          '/tutor-dashboard',
          '/tutor-schedule',
          '/tutor-students',
          '/tutor-studio',
          '/tutor-earnings',
          '/tutor-reviews',
          '/tutor-profile',
          '/tutor-pending',
          '/admin',
          '/admin/',
        ],
      },
    ],
    additionalSitemaps: [],
  },
  // Manually add high-priority pages
  additionalPaths: async (config) => [
    await config.transform(config, '/'),
    await config.transform(config, '/help'),
    await config.transform(config, '/privacy'),
    await config.transform(config, '/terms'),
    await config.transform(config, '/blog'),
    await config.transform(config, '/blog/nck-exam-preparation-guide-kenya'),
    await config.transform(config, '/blog/krchn-exam-revision-tips'),
    await config.transform(config, '/blog/bscn-nursing-exam-kenya'),
    await config.transform(config, '/blog/nck-past-papers-practice'),
    await config.transform(config, '/blog/digiproctor-nck-exam-guide'),
    await config.transform(config, '/tutors'),
  ],
};
