import type { Metadata } from 'next';
import { createClient } from '@/lib/supabase/server';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { NurseFitiLogo } from '@/components/shared/NurseFitiLogo';

export const dynamic = 'force-dynamic';

export async function generateMetadata({ params }: { params: { token: string } }): Promise<Metadata> {
  return {
    title: 'NCK Revision Plan',
    description: 'A personalised NCK exam revision plan generated by NurseFiti.',
    robots: { index: false, follow: false },
  };
}

export default async function SharedRevisionPlanPage({ params }: { params: { token: string } }) {
  const supabase = createClient();

  const { data: plan } = await supabase
    .from('revision_plans')
    .select('plan_html, cadre, exam_date, student_id')
    .eq('share_token', params.token)
    .single();

  if (!plan || !(plan as any).plan_html) {
    notFound();
  }

  const p = plan as any;

  return (
    <div className="min-h-screen bg-neutral-cream dark:bg-dark">
      {/* Minimal header */}
      <header className="bg-white dark:bg-dark border-b border-[var(--color-border)] px-4 py-3 flex items-center justify-between">
        <Link href="/">
          <NurseFitiLogo variant="full" size={36} />
        </Link>
        <div className="flex items-center gap-3">
          <span className="text-xs text-neutral-mid hidden sm:block">
            {p.cadre} · Exam: {new Date(p.exam_date).toLocaleDateString('en-KE', { day: 'numeric', month: 'short', year: 'numeric' })}
          </span>
          <Link
            href="/signup"
            className="px-4 py-2 text-sm font-bold bg-accent text-dark rounded-lg hover:bg-accent-dark transition-colors"
          >
            Create My Plan
          </Link>
        </div>
      </header>

      {/* Plan HTML rendered in an iframe-like container */}
      <div
        className="w-full"
        dangerouslySetInnerHTML={{ __html: p.plan_html }}
      />

      {/* CTA footer */}
      <div className="bg-primary py-10 px-4 text-center text-white mt-8">
        <h2 className="text-2xl font-heading font-bold mb-2">Want your own personalised plan?</h2>
        <p className="text-primary-light mb-6 max-w-lg mx-auto text-sm">
          NurseFiti generates a day-by-day NCK revision schedule built around your exam date, study hours, and weak areas.
        </p>
        <Link
          href="/signup"
          className="inline-flex items-center gap-2 px-8 py-3 font-bold bg-accent text-dark rounded-xl hover:bg-accent-dark transition-colors"
        >
          Start Free — No Credit Card
        </Link>
      </div>
    </div>
  );
}
