export const POSTS = [
  {
    slug: 'after-nck-exam-kenya',
    title: 'After the NCK Exam: Results, Jobs & Upgrades (2026)',
    excerpt: 'Learn verified next steps after the NCK exam: results, registration, job applications and planning a nursing specialty upgrade in Kenya.',
    category: 'NCK News',
    readTime: '11 min read',
    date: '2026-08-14',
    cadres: ['KRCHN', 'BScN', 'Higher Diploma'],
  },
  {
    slug: 'nursing-cv-kenyan-jobs',
    title: 'Nursing CV for Kenyan Jobs: Sections and Evidence (2026)',
    excerpt: 'Learn how newly qualified nurses in Kenya can build a clear CV with NCK evidence, clinical-placement achievements and job-specific proof for first roles.',
    category: 'Study Strategy',
    readTime: '10 min read',
    date: '2026-08-13',
    cadres: ['KRCHN', 'BScN', 'Higher Diploma'],
  },
  {
    slug: 'higher-diploma-renal-nursing-kenya',
    title: 'Higher Diploma Renal Nursing Kenya: How to Prepare (2026)',
    excerpt: 'Discover NurseFiti’s Higher Diploma renal resources, entry evidence and renal-nursing preparation priorities for Kenyan specialist-nursing candidates.',
    category: 'Study Guide',
    readTime: '10 min read',
    date: '2026-08-13',
    cadres: ['Higher Diploma'],
  },
  {
    slug: 'nurse-salary-kenya',
    title: 'Nurse Salary in Kenya: What Changes Your Pay (2026)',
    excerpt: 'How much do nurses earn in Kenya? See what changes pay across roles and employers — job grades, intern stipends, allowances, county, private and abroad.',
    category: 'Community',
    readTime: '12 min read',
    date: '2026-08-06',
    cadres: ['KRCHN', 'BScN', 'Higher Diploma'],
  },
  {
    slug: 'community-health-nursing-kenya',
    title: 'Community Health Nursing in Kenya: Roles & Skills (2026)',
    excerpt: 'Discover community health nursing in Kenya: the roles, skills, and practice settings — from CHPs and KRCHN training to the 2023 Primary Health Care Act.',
    category: 'Study Guide',
    readTime: '11 min read',
    date: '2026-08-06',
    cadres: ['KRCHN', 'BScN'],
  },
  {
    slug: 'nursing-school-transition-real-practice-kenya',
    title: 'What Nursing School Does Not Prepare You For: The Transition to Real Practice (2026)',
    excerpt: "The theory-practice gap is real. Discover the 4 phases of nursing reality shock, Kenyan nurses' experiences, and how to survive the transition from student to professional.",
    category: 'Community',
    readTime: '9 min read',
    date: '2026-07-31',
    cadres: ['KRCHN', 'BScN', 'Higher Diploma'],
  },
  {
    slug: 'nursing-jobs-in-kenya-legitimate-vacancies',
    title: 'Nursing Jobs in Kenya: Where to Find Legitimate Vacancies (2026)',
    excerpt: 'Passed the NCK exam but struggling to find employment? Discover where to find legitimate nursing jobs in Kenya, the required clearance certificates, and how to avoid scams.',
    category: 'Community',
    readTime: '9 min read',
    date: '2026-07-31',
    cadres: ['KRCHN', 'BScN', 'Higher Diploma'],
  },
  {
    slug: 'common-pharmacology-mistakes-nck-exam',
    title: 'Common Pharmacology Mistakes in NCK Exams (2026)',
    excerpt: 'Pharmacology is tested in every NCK paper. Discover the 7 most costly mistakes Kenyan nursing candidates make — and exactly how to avoid each one.',
    category: 'Study Guide',
    readTime: '10 min read',
    date: '2026-07-28',
    cadres: ['KRCHN', 'BScN', 'Higher Diploma'],
  },
  {
    slug: 'nck-indexing-60-day-deadline-kenya',
    title: 'NCK Indexing Kenya 2026: The Complete 60-Day Deadline Guide',
    excerpt: 'Discover the crucial 60-day NCK indexing deadline on the OSP portal. Learn the step-by-step process to ensure your BScN training is fully recognized in Kenya.',
    category: 'Study Guide',
    readTime: '6 min read',
    date: '2026-07-23',
    cadres: ['BScN', 'KRCHN'],
  },
  {
    slug: 'surviving-first-clinical-placement-kenyan-public-hospital',
    title: 'Surviving Your First Clinical Placement in a Kenyan Public Hospital',
    excerpt: 'Learn how to survive your BScN nursing clinical placement in Kenya. Discover how to bridge the theory-practice gap and avoid burnout on the wards.',
    category: 'Study Guide',
    readTime: '8 min read',
    date: '2026-07-22',
    cadres: ['BScN', 'KRCHN'],
  },
  {
    slug: 'nck-exam-foreign-trained-nurses-kenya',
    title: 'NCK Exam for Foreign-Trained Nurses in Kenya: Complete Guide (2026)',
    excerpt: 'Complete guide for foreign-trained nurses seeking licensing in Kenya (2026). Learn about transcript verification, clinical adaptation, and the NCK exam.',
    category: 'Study Guide',
    readTime: '10 min read',
    date: '2026-07-21',
    cadres: ['KRCHN', 'BScN'],
  },
  {
    slug: 'nck-exam-centres-kenya-guide',
    title: 'NCK Exam Centres in Kenya: Full List & Guide (2026)',
    excerpt: 'Find the full list of NCK exam centres in Kenya for 2026. Discover what to expect on exam day, how to register, and how to pass on your first attempt.',
    category: 'Study Guide',
    readTime: '11 min read',
    date: '2026-07-21',
    cadres: ['KRCHN', 'BScN', 'Higher Diploma'],
  },
  {
    slug: 'moh-nursing-internship-deployment-kenya-2026',
    title: 'Ministry of Health 2026 Internship Deployment: What You Must Do By June 29',
    excerpt: 'The Ministry of Health has confirmed the July 1st, 2026 deployment of 6,360 healthcare interns, including 2,000 BSc Nursing Officers. Here is how to collect your offer letter.',
    category: 'NCK News',
    readTime: '4 min read',
    date: '2026-06-27',
    cadres: ['BScN'],
  },
  {
    slug: 'nck-may-2026-exam-results-released',
    title: 'NCK May 2026 Exam Results Released: How to Check (2026)',
    excerpt: 'The Nursing Council of Kenya has officially released the May 2026 licensure examination results. Find out how to check and your next steps.',
    category: 'NCK News',
    readTime: '6 min read',
    date: '2026-06-27',
    cadres: ['KRCHN', 'BScN', 'Higher Diploma'],
  },
  {
    slug: 'nck-exam-warning-unaccredited-colleges-kenya-2026',
    title: 'NCK Exam Warning 2026: The Unaccredited College Alert You Must Know',
    excerpt: 'The Nursing Council of Kenya has issued a formal warning regarding unaccredited training institutions. Verify your college status to avoid NCK exam disqualification.',
    category: 'NCK News',
    readTime: '6 min read',
    date: '2026-06-25',
    cadres: ['KRCHN', 'BScN', 'Higher Diploma'],
  },
  {
    slug: 'nck-june-2026-update',
    title: 'NCK June 2026 Update: Exam Results, May Cycle Wrap‑up & Unaccredited College Warning',
    excerpt: 'Latest NCK news: February results released, May exam concluded, and a formal warning on unaccredited nursing colleges. Stay informed and prepare.',
    category: 'NCK News',
    readTime: '9 min read',
    date: '2026-06-25',
    cadres: ['KRCHN', 'BScN', 'Higher Diploma'],
  },
  {
    slug: 'nursefiti-for-nursing-students-undergrads',
    title: 'NurseFiti Is Not Just for NCK Exam Prep — It Works for Undergrads Too',
    excerpt: 'Think NurseFiti is only for licensing exam candidates? Nursing undergrads use it to ace unit exams, master clinical concepts, and build study habits that last.',
    category: 'Study Guide',
    readTime: '8 min read',
    date: '2026-06-25',
    cadres: ['KRCHN', 'BScN', 'Higher Diploma'],
  },
  {
    slug: 'fathers-day-appreciation-dads-role',
    title: "The Unsung Heroes: Celebrating the Significance of Dads this Father's Day",
    excerpt: 'A heartfelt reflection on the evolving role of fathers, their impact on our resilience, and why their presence is irreplaceable in our lives.',
    category: 'Community',
    readTime: '3 min read',
    date: '2026-06-21',
    cadres: ['KRCHN', 'BScN', 'Higher Diploma'],
  },
  {
    slug: 'nck-exam-study-internship-guide',
    title: 'How to Study for NCK Exam While Working as an Intern (2026)',
    excerpt: 'Demanding nursing internship in Kenya? Learn a practical study routine, high-yield topics, and how to prepare for the NCK exam and pass first attempt.',
    category: 'Study Strategy',
    readTime: '9 min read',
    date: '2026-06-20',
    cadres: ['KRCHN', 'BScN'],
  },
  {
    slug: 'nck-august-2026-exam-prep-plan',
    title: 'NCK August 2026 Exam: Dates, Registration & 8-Week Prep',
    excerpt: 'The NCK August 2026 sitting is roughly 8 weeks away. Here are the confirmed dates, registration steps, and a week-by-week prep plan to pass first attempt.',
    category: 'NCK News',
    readTime: '10 min read',
    date: '2026-06-15',
    cadres: ['KRCHN', 'BScN', 'Higher Diploma'],
  },
  {
    slug: 'nck-latest-news-june-2026',
    title: 'NCK June 2026: Feb Results, May Exam & Unaccredited College Warning',
    excerpt: 'NCK releases February 2026 results, May 2026 exam wraps up, and a formal warning is issued against Northlands NIMTC. Here is everything verified.',
    category: 'NCK News',
    readTime: '6 min read',
    date: '2026-06-05',
    cadres: ['KRCHN', 'BScN', 'Higher Diploma'],
  },
  {
    slug: 'nck-exam-preparation-guide-kenya',
    title: 'NCK Exam Preparation Guide: Pass First Attempt (2026)',
    excerpt: 'Everything Kenyan nursing graduates need — exam structure, DigiProctor tips, and a proven 8-week study strategy for KRCHN, BScN and Higher Diploma.',
    category: 'Study Guide',
    readTime: '12 min read',
    date: '2026-05-01',
    cadres: ['KRCHN', 'BScN', 'Higher Diploma'],
  },
  {
    slug: 'krchn-exam-revision-tips',
    title: 'KRCHN Exam: How to Pass Paper I and Paper II (2026)',
    excerpt: 'Targeted revision for KRCHN candidates — what each paper tests, the ABCDE framework for MCQs, a 4-week plan, and the key numbers NCK will test you on.',
    category: 'KRCHN',
    readTime: '9 min read',
    date: '2026-05-05',
    cadres: ['KRCHN'],
  },
  {
    slug: 'bscn-nursing-exam-kenya',
    title: 'BScN NCK Exam: High-Yield Topics & 6-Week Study Plan (2026)',
    excerpt: 'Unit breakdown for BScN Paper I and Paper II, the highest-yield topics, and a structured 6-week plan built around the NCK competency exam format.',
    category: 'BScN',
    readTime: '10 min read',
    date: '2026-05-10',
    cadres: ['BScN'],
  },
  {
    slug: 'nck-past-papers-practice',
    title: 'NCK Past Papers: How to Use Them (Most Students Get This Wrong)',
    excerpt: 'Passive reading of past papers is almost useless. Learn the retrieval-practice method, how to categorise errors, and when to switch to timed mock exams.',
    category: 'Study Strategy',
    readTime: '8 min read',
    date: '2026-05-15',
    cadres: ['KRCHN', 'BScN', 'Higher Diploma'],
  },
  {
    slug: 'digiproctor-nck-exam-guide',
    title: 'DigiProctor NCK Exam Interface: What to Expect (2026)',
    excerpt: 'The NCK exam runs on DigiProctor CBT. Here is exactly what the interface looks like, how the navigator grid works, and how to practise so it is not new on exam day.',
    category: 'Exam Day',
    readTime: '7 min read',
    date: '2026-05-20',
    cadres: ['KRCHN', 'BScN', 'Higher Diploma'],
  },
  {
    slug: 'nck-exam-anxiety-how-to-manage-it',
    title: 'NCK Exam Anxiety: 7 Evidence-Based Strategies That Work (2026)',
    excerpt: 'Exam anxiety costs Kenyan nursing candidates real marks. Here are 7 strategies backed by cognitive and clinical research — practical, not generic.',
    category: 'Study Strategy',
    readTime: '9 min read',
    date: '2026-06-08',
    cadres: ['KRCHN', 'BScN', 'Higher Diploma'],
  },
  {
    slug: 'nck-pharmacology-calculations-guide',
    title: 'NCK Pharmacology & Drug Calculations: Complete Guide (2026)',
    excerpt: 'Pharmacology and drug calculations appear in every NCK paper. Master the formulas, common KEML drugs, and calculation question patterns with worked examples.',
    category: 'Study Guide',
    readTime: '11 min read',
    date: '2026-06-09',
    cadres: ['KRCHN', 'BScN', 'Higher Diploma'],
  },
  {
    slug: 'how-to-apply-nck-licence-kenya',
    title: 'How to Apply for the NCK Practising Licence After Passing (2026)',
    excerpt: 'You passed the NCK exam — congratulations! Now here is the exact step-by-step process for applying for your practising licence on the OSP portal to avoid delays.',
    category: 'Study Guide',
    readTime: '6 min read',
    date: '2026-06-24',
    cadres: ['KRCHN', 'BScN', 'Higher Diploma'],
  },
  {
    slug: 'nursing-politics-leadership-kenya',
    title: 'Nursing and Politics in Kenya: Leadership Opportunities for Practitioners (2026)',
    excerpt: 'As Kenya approaches the 2027 elections, the intersection of nursing and politics has never been more critical. Discover political and leadership seats available for nursing practitioners to advocate for better healthcare policies.',
    category: 'Community',
    readTime: '8 min read',
    date: '2026-07-07',
    cadres: ['KRCHN', 'BScN', 'Higher Diploma'],
  },
  {
    slug: 'nursing-forums-networks-kenya',
    title: 'The Ultimate Guide to Nursing Forums & Networks in Kenya (2026)',
    excerpt: 'Connecting with other nursing professionals is crucial for exam prep, job hunting, and career growth. Explore the top nursing forums, unions, and networks every Kenyan nursing student and practitioner should join.',
    category: 'Community',
    readTime: '7 min read',
    date: '2026-07-07',
    cadres: ['KRCHN', 'BScN', 'Higher Diploma'],
  },
];

export const CATEGORY_STYLES: Record<string, { badge: string }> = {
  'Study Guide':    { badge: 'bg-primary-light text-primary border border-primary/20' },
  'KRCHN':          { badge: 'bg-accent-light text-accent-dark border border-accent/20' },
  'BScN':           { badge: 'bg-primary-light text-primary-mid border border-primary-mid/20' },
  'Study Strategy': { badge: 'bg-accent-light text-accent-dark border border-accent/30' },
  'Exam Day':       { badge: 'bg-[#FFF0F0] text-error border border-error/20 dark:bg-error/10 dark:text-error' },
  'NCK News':       { badge: 'bg-primary-xlight text-primary border border-primary/30' },
  'Community':      { badge: 'bg-accent-light text-accent-dark border border-accent/20' },
};

export const POST_IMAGES: Record<string, string> = {
  'after-nck-exam-kenya': 'https://images.unsplash.com/photo-1584982751601-97dcc096659c?w=1200&q=80&auto=format&fit=crop',
  'nursing-cv-kenyan-jobs': 'https://images.unsplash.com/photo-1584515933487-779824d29309?w=1200&q=80&auto=format&fit=crop',
  'higher-diploma-renal-nursing-kenya': 'https://images.unsplash.com/photo-1628595351029-c2bf17511435?w=1200&q=80&auto=format&fit=crop',
  'nurse-salary-kenya': 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1200&q=80&auto=format&fit=crop',
  'community-health-nursing-kenya': 'https://images.unsplash.com/photo-1631815588090-d4bfec5b1ccb?w=1200&q=80&auto=format&fit=crop',
  'nursing-school-transition-real-practice-kenya': 'https://images.unsplash.com/photo-1579684453423-f84349ef60b0?w=1200&q=80&auto=format&fit=crop',
  'nursing-jobs-in-kenya-legitimate-vacancies': 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=1200&q=80&auto=format&fit=crop',
  'nck-indexing-60-day-deadline-kenya': 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200&q=80&auto=format&fit=crop',
  'surviving-first-clinical-placement-kenyan-public-hospital': 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=1200&q=80&auto=format&fit=crop',
  'nck-exam-foreign-trained-nurses-kenya': 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800&q=80&auto=format&fit=crop',
  'nck-exam-centres-kenya-guide': 'https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80&auto=format&fit=crop',
  'moh-nursing-internship-deployment-kenya-2026': 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&q=80&auto=format&fit=crop',
  'nck-may-2026-exam-results-released': 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80&auto=format&fit=crop',
  'nck-exam-warning-unaccredited-colleges-kenya-2026': 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=1200&q=80&auto=format&fit=crop',
  'nck-june-2026-update':               'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&q=80&auto=format&fit=crop',
  'nursefiti-for-nursing-students-undergrads': 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&q=80&auto=format&fit=crop',
  'fathers-day-appreciation-dads-role': 'https://images.unsplash.com/photo-1596484552834-6a58f850e0a1?w=800&q=80&auto=format&fit=crop',
  'nck-exam-study-internship-guide':   'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=800&q=80&auto=format&fit=crop',
  'nck-august-2026-exam-prep-plan':    'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&q=80&auto=format&fit=crop',
  'nck-latest-news-june-2026':         'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&q=80&auto=format&fit=crop',
  'nck-exam-preparation-guide-kenya':  'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&q=80&auto=format&fit=crop',
  'krchn-exam-revision-tips':          'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&q=80&auto=format&fit=crop',
  'bscn-nursing-exam-kenya':           'https://images.unsplash.com/photo-1551190822-a9333d879b1f?w=800&q=80&auto=format&fit=crop',
  'nck-past-papers-practice':          'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&q=80&auto=format&fit=crop',
  'digiproctor-nck-exam-guide':        'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80&auto=format&fit=crop',
  'nck-exam-anxiety-how-to-manage-it': 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&q=80&auto=format&fit=crop',
  'nck-pharmacology-calculations-guide': 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&q=80&auto=format&fit=crop',
  'how-to-apply-nck-licence-kenya': 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80&auto=format&fit=crop',
  'nursing-politics-leadership-kenya': 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&q=80&auto=format&fit=crop',
  'nursing-forums-networks-kenya': 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&q=80&auto=format&fit=crop',
  'common-pharmacology-mistakes-nck-exam': 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=1200&q=80&auto=format&fit=crop',
};
