// This file will be generated by Supabase CLI after database setup
// For now, we'll create a placeholder type

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          role: 'student' | 'tutor' | 'admin';
          full_name: string;
          email: string;
          phone: string;
          avatar_url: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'created_at'>;
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>;
      };
      // More tables will be added after database setup
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
};
