-- Migration: 20260701000007
-- Source: NCK-NEW-MCQ-Compilation.docx — "Kenya Med Exams compiled set" (Year not stated)
-- exam_year = NULL per §13.1
-- Batch C: Dermatology, ENT, ophthalmology, dental, GI, first aid (Q101–Q160)
-- Paper assignment per §12: all clinical specialties → Paper I both cadres.
-- Audit: verified against Brunner & Suddarth, BNF, MOH Kenya per §14.3.
-- ON CONFLICT (stem, cadre) DO NOTHING on every INSERT.

-- ── Dermis — contains blood vessels, nerves, appendages ──────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Dermatology','Which skin layer contains blood vessels, nerves and appendages such as hair follicles and sweat glands?','Epidermis','Dermis','Hypodermis','Subcutaneous tissue','B','The dermis lies beneath the epidermis and contains blood vessels, lymphatics, nerve endings, hair follicles, sebaceous glands and sweat glands (anatomy/physiology; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Dermatology','Which skin layer contains blood vessels, nerves and appendages such as hair follicles and sweat glands?','Epidermis','Dermis','Hypodermis','Subcutaneous tissue','B','Dermal damage (full-thickness burns, pressure injuries Stage 3+) destroys vascularity and sensation. BScN nurses apply this anatomy in wound classification, wound bed preparation and skin graft care planning (anatomy; Brunner & Suddarth dermatology).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Hemangioma — benign skin tumour of blood vessels ────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Dermatology','What is the medical term for a benign skin tumour composed of blood vessels?','Lipoma','Naevus','Haemangioma','Melanoma','C','A haemangioma is a benign proliferation of blood vessels in the dermis or subcutaneous tissue; common in infants and usually involutes spontaneously (Brunner & Suddarth; dermatology).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Dermatology','What is the medical term for a benign skin tumour composed of blood vessels?','Lipoma','Naevus','Haemangioma','Melanoma','C','Haemangiomas vs vascular malformations: haemangiomas proliferate then involute; malformations persist. BScN nurses educate parents on expected involution timeline and indications for propranolol therapy in problematic infantile haemangiomas (Brunner & Suddarth; paediatric dermatology).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Erosion — loss of top layer of skin ──────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Dermatology','What is the term for loss of the top layer of skin, often as a result of friction or injury?','Ulcer','Erosion','Scar','Callus','B','Erosion is a superficial loss of epidermis that heals without scarring; deeper loss through the dermis creates an ulcer which heals with scarring (Brunner & Suddarth; dermatology skin lesion classification).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Dermatology','What is the term for loss of the top layer of skin, often as a result of friction or injury?','Ulcer','Erosion','Scar','Callus','B','Accurate skin lesion terminology (primary vs secondary lesions) is essential in nursing documentation. BScN nurses systematically describe lesions: type, size, distribution, colour, border, surface, associated symptoms (Brunner & Suddarth; dermatology assessment).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Psoriasis — silvery scales on reddened skin ──────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Dermatology','Which skin condition is characterised by formation of silvery scales on reddened skin, often on the elbows, knees and scalp?','Eczema','Psoriasis','Acne','Rosacea','B','Psoriasis is a chronic immune-mediated inflammatory skin condition characterised by well-demarcated erythematous plaques with silvery scales, typically affecting extensor surfaces and the scalp (Brunner & Suddarth; dermatology).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Dermatology','Which skin condition is characterised by formation of silvery scales on reddened skin, often on the elbows, knees and scalp?','Eczema','Psoriasis','Acne','Rosacea','B','Psoriasis triggers: stress, infection, medications (lithium, beta-blockers), smoking. Treatments: topical corticosteroids, vitamin D analogues, methotrexate, biologics. BScN nurses assess psoriasis severity (PASI), educate on triggers and support psychological impact (Brunner & Suddarth; dermatology EBP).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Vitiligo — autoimmune loss of pigment ────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Dermatology','Which condition is an autoimmune disorder causing loss of pigment in patches of skin, resulting in white spots?','Psoriasis','Eczema','Vitiligo','Rosacea','C','Vitiligo is an autoimmune disorder in which T-cells destroy melanocytes, causing depigmented white patches; it is associated with other autoimmune conditions including thyroid disease and T1DM (Brunner & Suddarth; dermatology).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Dermatology','Which condition is an autoimmune disorder causing loss of pigment in patches of skin, resulting in white spots?','Psoriasis','Eczema','Vitiligo','Rosacea','C','Vitiligo management: sun protection (depigmented skin burns easily), phototherapy (NB-UVB), topical tacrolimus, camouflage cosmetics. Psychological impact is significant; BScN nurses screen for depression and body image disturbance (Brunner & Suddarth; dermatology EBP).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Lipoma — benign tumour of fat cells ──────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Dermatology','What is the medical term for a benign skin tumour composed of fat cells?','Haemangioma','Naevus','Lipoma','Melanoma','C','A lipoma is a benign, encapsulated tumour of mature adipocytes, usually soft and mobile under the skin; it rarely requires treatment unless causing discomfort (Brunner & Suddarth; dermatology).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Dermatology','What is the medical term for a benign skin tumour composed of fat cells?','Haemangioma','Naevus','Lipoma','Melanoma','C','Lipoma vs liposarcoma: lipomas are soft, mobile, well-demarcated; liposarcomas are firm, fixed, growing. BScN nurses assess suspicious lumps using ABCDE criteria and refer for biopsy if malignant features are present (Brunner & Suddarth; surgical oncology nursing).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Rosacea — redness, flushing, visible blood vessels on face ───────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Dermatology','Which skin condition is characterised by redness, flushing and visible blood vessels on the face, often with small pus-filled bumps?','Eczema','Psoriasis','Rosacea','Dermatitis','C','Rosacea is a chronic facial dermatosis characterised by persistent centrofacial erythema, flushing, telangiectases and papulopustules; rhinophyma (nasal thickening) may develop in severe cases (Brunner & Suddarth; dermatology).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Dermatology','Which skin condition is characterised by redness, flushing and visible blood vessels on the face, often with small pus-filled bumps?','Eczema','Psoriasis','Rosacea','Dermatitis','C','Rosacea triggers: sun, spicy food, alcohol, hot drinks, stress. Management: topical metronidazole, azelaic acid, oral doxycycline, sun protection. BScN nurses educate patients on trigger avoidance and differentiate from acne vulgaris (Brunner & Suddarth; dermatology EBP).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Epidermis — outermost layer of skin ──────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Dermatology','Which term refers to the outermost layer of the skin, composed of multiple layers of flat, dead skin cells?','Dermis','Hypodermis','Epidermis','Subcutaneous tissue','C','The epidermis is the outermost avascular layer of skin, composed of stratified squamous epithelium; the stratum corneum (outermost sublayer) consists of anucleate, keratinised cells providing the barrier function (anatomy; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Dermatology','Which term refers to the outermost layer of the skin, composed of multiple layers of flat, dead skin cells?','Dermis','Hypodermis','Epidermis','Subcutaneous tissue','C','Epidermal disruption → infection risk; topical antiseptics and dressings restore barrier. BScN nurses classify burns by depth of epidermal/dermal involvement to guide treatment (superficial epidermal → superficial/deep dermal → full thickness) (anatomy; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Macule — flat discoloured area of skin ────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Dermatology','What is the term for a flat, discoloured area of skin that is darker or lighter than surrounding skin?','Scar','Ulcer','Keloid','Macule','D','A macule is a flat, non-palpable, circumscribed colour change (<1 cm) of the skin — darker (hyperpigmented) or lighter (hypopigmented) than surrounding skin; a patch is similar but >1 cm (Brunner & Suddarth; dermatology lesion classification).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Dermatology','What is the term for a flat, discoloured area of skin that is darker or lighter than surrounding skin?','Scar','Ulcer','Keloid','Macule','D','Primary lesion taxonomy — macule, papule, vesicle, pustule, plaque, nodule, wheal — vs secondary — scale, crust, erosion, ulcer, scar, keloid. BScN nurses document lesions using correct terminology in skin assessments (Brunner & Suddarth; dermatology).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Keloid — thickened scar tissue ───────────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Dermatology','What is the term for a thickened area of scar tissue that forms at the site of a wound or incision?','Macule','Keloid','Ulcer','Vesicle','B','A keloid is an abnormal, raised, exuberant scar that extends beyond the original wound margins due to excessive collagen deposition; more common in dark-skinned individuals and at certain body sites (Brunner & Suddarth; dermatology).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Dermatology','What is the term for a thickened area of scar tissue that forms at the site of a wound or incision?','Macule','Keloid','Ulcer','Vesicle','B','Keloid vs hypertrophic scar: keloid exceeds wound margins; hypertrophic scar stays within. Treatment: intralesional corticosteroids, silicone sheets, pressure therapy. BScN nurses counsel patients with keloid tendency pre-operatively on risk and aftercare (Brunner & Suddarth; wound care).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Shingles — painful dermatome rash ────────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Dermatology','Which skin condition is characterised by a painful rash along a dermatome, often preceded by tingling or burning?','Shingles (herpes zoster)','Eczema','Psoriasis','Rosacea','A','Herpes zoster (shingles) results from reactivation of dormant varicella-zoster virus in a dorsal root ganglion; it presents with unilateral vesicular rash following a dermatome distribution, preceded by prodromal pain (Brunner & Suddarth; dermatology).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Dermatology','Which skin condition is characterised by a painful rash along a dermatome, often preceded by tingling or burning?','Shingles (herpes zoster)','Eczema','Psoriasis','Rosacea','A','Shingles complications: post-herpetic neuralgia (most common), ocular involvement (herpes zoster ophthalmicus — urgent ophthalmology referral), disseminated disease in immunocompromised. Treatment: acyclovir/valaciclovir within 72 hours (BNF; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Papule — raised solid lesion <1 cm ───────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Dermatology','Which term refers to a raised, solid skin lesion less than 1 centimetre in diameter?','Pustule','Nodule','Vesicle','Papule','D','A papule is a raised, solid, palpable skin lesion less than 1 cm in diameter; when >1 cm it is called a plaque (if flat-topped) or nodule (if rounded) (Brunner & Suddarth; dermatology lesion classification).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Dermatology','Which term refers to a raised, solid skin lesion less than 1 centimetre in diameter?','Pustule','Nodule','Vesicle','Papule','D','Papules in acne (comedonal) vs psoriasis (scaly) vs viral warts differ in aetiology and management. BScN nurses apply precise lesion terminology in dermatology referral documentation (Brunner & Suddarth; dermatology assessment).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Vesicle — raised fluid-filled lesion <1 cm ───────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Dermatology','What is the term for a raised, fluid-filled skin lesion less than 1 centimetre in diameter?','Pustule','Nodule','Vesicle','Papule','C','A vesicle is a raised, circumscribed, fluid-filled lesion less than 1 cm; >1 cm is called a bulla. Vesicles contain clear serous fluid (herpes, chickenpox, contact dermatitis) (Brunner & Suddarth; dermatology).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Dermatology','What is the term for a raised, fluid-filled skin lesion less than 1 centimetre in diameter?','Pustule','Nodule','Vesicle','Papule','C','Vesicles (herpes simplex/zoster, varicella) require contact isolation; nurses apply acyclovir per protocol. Bullae (pemphigus, burns) need gentle dressing to preserve roof as biological cover (Brunner & Suddarth; dermatology EBP).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Otitis media — inflammation of middle ear ────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','ENT Disorders','What is the medical term for inflammation of the middle ear seen in children with ear pain, fever and hearing loss?','Tonsillitis','Rhinitis','Otitis media','Laryngitis','C','Otitis media is inflammation/infection of the middle ear, most commonly caused by Streptococcus pneumoniae and H. influenzae in children; it presents with otalgia, fever, conductive hearing loss and sometimes otorrhoea (Brunner & Suddarth; Kenya Basic Paediatric Protocols).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','ENT Disorders','What is the medical term for inflammation of the middle ear seen in children with ear pain, fever and hearing loss?','Tonsillitis','Rhinitis','Otitis media','Laryngitis','C','AOM treatment: amoxicillin first line (Kenya MOH); perforation → topical antibiotic drops. BScN nurses assess hearing in recurrent AOM (risk for developmental delay), refer for audiometry and counsel on breastfeeding/smoke-free home as preventive measures (Brunner & Suddarth; Kenya Basic Paediatric Protocols).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Epiglottis — prevents aspiration during swallowing ───────────────────────
-- Note: stem wording differs from prior epiglottis Q (structure in throat vs function in respiratory) — §14.5
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','ENT Disorders','Which structure in the throat plays a crucial role in preventing food and liquids from entering the trachea during swallowing?','Epiglottis','Tonsils','Uvula','Adenoids','A','The epiglottis folds over the laryngeal inlet during swallowing to prevent aspiration of food and liquids into the airway; dysfunction (e.g. in stroke, epiglottitis) leads to aspiration pneumonia (Brunner & Suddarth; ENT anatomy).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','ENT Disorders','Which structure in the throat plays a crucial role in preventing food and liquids from entering the trachea during swallowing?','Epiglottis','Tonsils','Uvula','Adenoids','A','Dysphagia assessment includes observing for coughing/choking during the water swallow test — a sign of epiglottic dysfunction. BScN nurses implement aspiration precautions (upright position, thickened fluids, SALT referral) for at-risk patients (Brunner & Suddarth; dysphagia management).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Goitre — enlargement of thyroid gland ────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Endocrine Disorders','Which condition is characterised by enlargement of the thyroid gland, resulting in a noticeable swelling in the neck?','Tonsillitis','Rhinitis','Goitre','Sinusitis','C','Goitre is enlargement of the thyroid gland due to iodine deficiency (most common worldwide), Graves'' disease, Hashimoto''s thyroiditis or nodular disease; it may cause tracheal compression in large goitres (Brunner & Suddarth; endocrine nursing).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Endocrine Disorders','Which condition is characterised by enlargement of the thyroid gland, resulting in a noticeable swelling in the neck?','Tonsillitis','Rhinitis','Goitre','Sinusitis','C','Goitre assessment: size, firmness, tenderness, symmetry, bruit (Graves''). BScN nurses educate on iodised salt use for prevention, monitor post-thyroidectomy for hypocalcaemia, RLN injury and hypothyroidism (Brunner & Suddarth; endocrine nursing EBP).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Pharyngitis — inflammation of pharynx ────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','ENT Disorders','What is the medical term for inflammation of the pharynx, often associated with a sore throat?','Laryngitis','Sinusitis','Pharyngitis','Otitis media','C','Pharyngitis is inflammation of the pharynx (back of the throat) commonly caused by viruses (rhinovirus, EBV) or bacteria (Group A Streptococcus); it presents with sore throat, dysphagia and erythema (Brunner & Suddarth; ENT nursing).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','ENT Disorders','What is the medical term for inflammation of the pharynx, often associated with a sore throat?','Laryngitis','Sinusitis','Pharyngitis','Otitis media','C','Centor/McIsaac score guides antibiotic use for GAS pharyngitis; treat with penicillin V 10 days to prevent rheumatic fever. BScN nurses educate on completing the course and recognising quinsy complications (Brunner & Suddarth; Kenya STI/ENT guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Larynx — contains vocal cords ───────────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','ENT Disorders','Which part of the throat contains the vocal cords and is responsible for voice production?','Larynx','Uvula','Tonsils','Epiglottis','A','The larynx (voice box) contains the vocal cords (true and false) and is responsible for phonation; it also protects the lower airway during swallowing (anatomy; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','ENT Disorders','Which part of the throat contains the vocal cords and is responsible for voice production?','Larynx','Uvula','Tonsils','Epiglottis','A','Post-thyroidectomy RLN injury causes hoarseness (unilateral) or stridor/aphonia (bilateral — emergency). BScN nurses assess voice quality immediately post-op as a RLN injury screen (Brunner & Suddarth; ENT/endocrine surgery nursing).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Ossicles — amplify sound vibrations to inner ear ────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','ENT Disorders','Which structure in the ear amplifies sound vibrations and transmits them to the inner ear?','Tympanic membrane','Cochlea','Eustachian tube','Ossicles (ear bones)','D','The three ossicles — malleus, incus and stapes — mechanically amplify and transmit vibrations from the tympanic membrane to the oval window of the cochlea (anatomy; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','ENT Disorders','Which structure in the ear amplifies sound vibrations and transmits them to the inner ear?','Tympanic membrane','Cochlea','Eustachian tube','Ossicles (ear bones)','D','Ossicular chain disruption (trauma, chronic otitis media) causes conductive hearing loss; assessed by audiometry. BScN nurses differentiate conductive from sensorineural hearing loss using Weber and Rinne tests and refer appropriately (Brunner & Suddarth; ENT nursing assessment).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Rhinitis — inflammation of nasal passages ────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','ENT Disorders','Which condition is characterised by inflammation of the nasal passages with a runny or stuffy nose and sneezing?','Tonsillitis','Rhinitis','Sinusitis','Otitis media','B','Rhinitis is inflammation of the nasal mucosa causing rhinorrhoea, nasal obstruction, sneezing and itching; it may be allergic (seasonal/perennial), infectious (viral common cold) or non-allergic (Brunner & Suddarth; ENT nursing).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','ENT Disorders','Which condition is characterised by inflammation of the nasal passages with a runny or stuffy nose and sneezing?','Tonsillitis','Rhinitis','Sinusitis','Otitis media','B','Allergic rhinitis: intranasal corticosteroids first line; antihistamines for itch/sneezing. BScN nurses differentiate allergic from non-allergic rhinitis, assess asthma comorbidity (united airway disease) and review decongestant overuse risk (Brunner & Suddarth; allergy nursing EBP).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Tonsillitis — inflammation of tonsils ────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','ENT Disorders','Which condition is characterised by inflammation of the tonsils, causing a sore throat and difficulty swallowing?','Laryngitis','Rhinitis','Tonsillitis','Otitis media','C','Tonsillitis is inflammation of the palatine tonsils, most commonly caused by Group A Streptococcus or viral pathogens; it presents with severe sore throat, odynophagia, fever and tonsillar exudate (Brunner & Suddarth; ENT nursing).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','ENT Disorders','Which condition is characterised by inflammation of the tonsils, causing a sore throat and difficulty swallowing?','Laryngitis','Rhinitis','Tonsillitis','Otitis media','C','Recurrent tonsillitis (≥7 episodes/year) → tonsillectomy referral. Post-tonsillectomy nursing: monitor for reactionary/secondary haemorrhage, swallowing assessment, analgesia management (Brunner & Suddarth; ENT surgical nursing; Kenya ENT protocols).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Iris — controls amount of light entering eye ─────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Ophthalmology','Which part of the eye controls the amount of light entering the eye by changing the size of the pupil?','Cornea','Lens','Retina','Iris','D','The iris is the pigmented, circular diaphragm of the eye; its radial and circumferential muscles control pupil size — dilating (mydriasis) in dim light and constricting (miosis) in bright light (anatomy; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Ophthalmology','Which part of the eye controls the amount of light entering the eye by changing the size of the pupil?','Cornea','Lens','Retina','Iris','D','Pupil responses (direct, consensual) assess CN II and III integrity. Fixed dilated pupil (blown pupil) = posterior communicating artery aneurysm or transtentorial herniation. BScN nurses document and escalate acute pupil changes in neurological monitoring (anatomy; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Cataract — clouding of the lens ──────────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Ophthalmology','What is the term for clouding of the eye''s natural lens, leading to blurred vision?','Glaucoma','Cataract','Macular degeneration','Retinopathy','B','A cataract is opacity of the crystalline lens, causing progressive painless blurred vision; it is the leading cause of preventable blindness globally (Brunner & Suddarth; Kenya National Eye Care Programme).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Ophthalmology','What is the term for clouding of the eye''s natural lens, leading to blurred vision?','Glaucoma','Cataract','Macular degeneration','Retinopathy','B','Cataract surgery (phacoemulsification + IOL) is day case; post-op care includes eye shield, antibiotic drops, avoiding bending/straining, no rubbing. BScN nurses provide structured pre/post-op education and follow-up (Brunner & Suddarth; Kenya National Eye Care Programme).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Sclera — white of the eye ────────────────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Ophthalmology','Which part of the eye is commonly referred to as the "white of the eye"?','Cornea','Retina','Sclera','Iris','C','The sclera is the tough, opaque white outer coat of the eyeball that provides structural integrity and attachment for extraocular muscles (anatomy; Brunner & Suddarth ophthalmology).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Ophthalmology','Which part of the eye is commonly referred to as the "white of the eye"?','Cornea','Retina','Sclera','Iris','C','Scleral icterus (yellow sclera) is an early sign of jaundice detected when bilirubin >34 µmol/L; BScN nurses assess scleral icterus in liver disease, neonatal jaundice and haemolysis (anatomy; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Macular degeneration — loss of central vision ────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Ophthalmology','Which eye condition is characterised by progressive deterioration of the macula, resulting in loss of central vision?','Cataract','Glaucoma','Macular degeneration','Retinopathy','C','Age-related macular degeneration (AMD) affects the central retina (macula), causing gradual loss of central vision while peripheral vision is preserved; it is the leading cause of severe visual impairment in people over 50 in high-income countries (Brunner & Suddarth; ophthalmology).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Ophthalmology','Which eye condition is characterised by progressive deterioration of the macula, resulting in loss of central vision?','Cataract','Glaucoma','Macular degeneration','Retinopathy','C','Wet AMD: anti-VEGF injections (ranibizumab); dry AMD: no proven treatment but AREDS2 supplements may slow progression. BScN nurses teach Amsler grid self-monitoring for metamorphopsia and counsel on low-vision aids (Brunner & Suddarth; ophthalmology EBP).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Glaucoma — increased intraocular pressure ─────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Ophthalmology','Which condition is characterised by increased pressure within the eye, potentially leading to optic nerve damage and vision loss?','Myopia','Hyperopia','Astigmatism','Glaucoma','D','Glaucoma is characterised by raised intraocular pressure (>21 mmHg in most forms) causing progressive optic nerve damage and characteristic visual field loss — tunnel vision in advanced cases (Brunner & Suddarth; Kenya National Eye Care Programme).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Ophthalmology','Which condition is characterised by increased pressure within the eye, potentially leading to optic nerve damage and vision loss?','Myopia','Hyperopia','Astigmatism','Glaucoma','D','Glaucoma: open-angle (chronic, painless) vs acute closed-angle (painful, emergency). Treatment: prostaglandin analogues, beta-blockers, laser trabeculoplasty, trabeculectomy. BScN nurses teach correct drop instillation technique and nasolacrimal occlusion (Brunner & Suddarth; Kenya Eye Care Programme).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Strabismus — eyes don't align ────────────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Ophthalmology','What is the term for a condition in which the eyes do not align properly and do not work together to focus on an object?','Amblyopia','Strabismus','Nystagmus','Diplopia','B','Strabismus (squint) is misalignment of the eyes due to extraocular muscle imbalance; it may cause amblyopia (lazy eye) if uncorrected in childhood (Brunner & Suddarth; ophthalmology).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Ophthalmology','What is the term for a condition in which the eyes do not align properly and do not work together to focus on an object?','Amblyopia','Strabismus','Nystagmus','Diplopia','B','Early intervention is critical; treatment: patching of the sound eye, glasses, botulinum toxin injection, surgery. BScN nurses conduct cover tests during child health checks and refer promptly to prevent irreversible amblyopia (Brunner & Suddarth; paediatric ophthalmology).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Amblyopia — lazy eye ──────────────────────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Ophthalmology','What is the term for the condition of "lazy eye", occurring in childhood and resulting in reduced vision in one eye?','Amblyopia','Strabismus','Nystagmus','Diplopia','A','Amblyopia ("lazy eye") is reduced visual acuity in one eye due to abnormal visual development in early childhood (from strabismus, anisometropia or visual deprivation); it does not respond to optical correction alone (Brunner & Suddarth; ophthalmology).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Ophthalmology','What is the term for the condition of "lazy eye", occurring in childhood and resulting in reduced vision in one eye?','Amblyopia','Strabismus','Nystagmus','Diplopia','A','Amblyopia treatment: correct the underlying cause (glasses, cataract surgery) + occlusion therapy (patching the good eye) before age 7–8. BScN nurses conduct vision screening in well-child checks and educate parents on patching compliance (Brunner & Suddarth; paediatric ophthalmology).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Vitreous humour — gel between lens and retina ────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Ophthalmology','What is the term for the clear, gel-like substance that fills the space between the lens and retina in the eye?','Sclera','Vitreous humour','Aqueous humour','Conjunctiva','B','The vitreous humour is the clear, gel-like substance filling the posterior chamber of the eye between the lens and the retina; it helps maintain the eye''s shape (anatomy; Brunner & Suddarth ophthalmology).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Ophthalmology','What is the term for the clear, gel-like substance that fills the space between the lens and retina in the eye?','Sclera','Vitreous humour','Aqueous humour','Conjunctiva','B','Vitreous detachment causes floaters; vitreous haemorrhage (diabetic retinopathy) causes sudden vision loss. BScN nurses recognise flashes + floaters as a retinal detachment warning and advise same-day ophthalmology referral (anatomy; Brunner & Suddarth; ophthalmology).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Gingivitis — inflammation of gums ────────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Dental and Oral Health','What is the term for inflammation of the gums?','Gingivitis','Stomatitis','Periodontitis','Thrush','A','Gingivitis is inflammation of the gingiva (gums) caused by plaque accumulation; it is reversible with good oral hygiene and is the precursor to periodontitis (Brunner & Suddarth; oral health nursing).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Dental and Oral Health','What is the term for inflammation of the gums?','Gingivitis','Stomatitis','Periodontitis','Thrush','A','Gingivitis → periodontitis → tooth loss; strongly associated with cardiovascular disease, preterm birth, poorly controlled diabetes. BScN nurses perform oral assessments using the Oral Assessment Guide, provide oral hygiene care for ventilated patients (VAP prevention) and educate on brushing/flossing technique (Brunner & Suddarth; oral health nursing).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Stomatitis — inflammation of oral mucosa ─────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Dental and Oral Health','What is the term for inflammation of the mucous membrane lining the inside of the mouth?','Stomatitis','Gingivitis','Thrush','Glossitis','A','Stomatitis is inflammation of the oral mucosa, which may be caused by infections (herpes, candida), chemotherapy, radiotherapy, nutritional deficiencies or systemic disease (Brunner & Suddarth; oral health nursing).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Dental and Oral Health','What is the term for inflammation of the mucous membrane lining the inside of the mouth?','Stomatitis','Gingivitis','Thrush','Glossitis','A','Chemotherapy-induced stomatitis: grade using WHO mucositis scale, apply ice chips during chemotherapy (cryotherapy), use sodium bicarbonate rinses, manage pain with topical analgesics. BScN oncology nurses implement oral care protocols (Brunner & Suddarth; MASCC/ISOO mucositis guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── GERD — backward flow of stomach acid ─────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Gastrointestinal Disorders','Which medical condition is characterised by backward flow of stomach acid into the oesophagus, causing heartburn?','Appendicitis','Gastritis','Gastroesophageal reflux disease (GERD)','Colitis','C','GERD results from lower oesophageal sphincter incompetence allowing acid reflux into the oesophagus, causing heartburn, regurgitation and potentially Barrett''s oesophagus (Brunner & Suddarth; GI nursing).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Gastrointestinal Disorders','Which medical condition is characterised by backward flow of stomach acid into the oesophagus, causing heartburn?','Appendicitis','Gastritis','Gastroesophageal reflux disease (GERD)','Colitis','C','GERD management: lifestyle (weight loss, head elevation, avoid triggers), PPIs, H2 blockers; Barrett''s oesophagus requires surveillance endoscopy. BScN nurses educate on dietary modifications, medication timing and alarm symptoms requiring urgent referral (Brunner & Suddarth; GI nursing EBP).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Colitis — inflammation of colon ─────────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Gastrointestinal Disorders','Which term refers to inflammation of the colon, often with abdominal pain and diarrhoea?','Gastritis','Enteritis','Appendicitis','Colitis','D','Colitis is inflammation of the colon; causes include ulcerative colitis (IBD), Crohn''s disease, infectious colitis (C. difficile), ischaemic colitis and radiation colitis (Brunner & Suddarth; GI nursing).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Gastrointestinal Disorders','Which term refers to inflammation of the colon, often with abdominal pain and diarrhoea?','Gastritis','Enteritis','Appendicitis','Colitis','D','UC flare management: aminosalicylates, corticosteroids, biologic agents; surgical colectomy for severe/refractory disease. BScN nurses assess stool frequency/consistency using Bristol Stool Chart, monitor for toxic megacolon and support patients during biologic therapy (Brunner & Suddarth; IBD nursing).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Diverticulitis — inflamed pouches in colon wall ──────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Gastrointestinal Disorders','Which condition is characterised by small pouches in the colon wall that can become inflamed?','Diverticulitis','Gastritis','Appendicitis','Enteritis','A','Diverticulitis occurs when diverticula (small pouches protruding through the colonic wall) become inflamed or infected; it typically presents with left iliac fossa pain, fever and altered bowel habit (Brunner & Suddarth; GI nursing).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Gastrointestinal Disorders','Which condition is characterised by small pouches in the colon wall that can become inflamed?','Diverticulitis','Gastritis','Appendicitis','Enteritis','A','Uncomplicated diverticulitis: oral antibiotics, clear fluids; complicated (abscess, perforation): IV antibiotics, surgery. Prevention: high-fibre diet. BScN nurses educate on dietary fibre intake and recognise complications (Brunner & Suddarth; GI nursing EBP).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Hepatitis — inflammation of liver ────────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Gastrointestinal Disorders','Which medical condition is characterised by inflammation of the liver, often caused by viral infections or alcohol abuse?','Hepatitis','Cirrhosis','Pancreatitis','Gallstones','A','Hepatitis is inflammation of the liver parenchyma; common causes include hepatitis A/B/C/D/E viruses, alcohol, non-alcoholic fatty liver disease, autoimmune and drug-induced hepatitis (Brunner & Suddarth; GI nursing).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Gastrointestinal Disorders','Which medical condition is characterised by inflammation of the liver, often caused by viral infections or alcohol abuse?','Hepatitis','Cirrhosis','Pancreatitis','Gallstones','A','HBV: vaccinate healthcare workers, manage with tenofovir/entecavir. HCV: direct-acting antivirals achieve >95% cure. BScN nurses apply standard precautions, offer testing to at-risk patients, support adherence to antivirals per MOH Kenya viral hepatitis guidelines (Brunner & Suddarth; MOH Kenya).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── CPR — 30 compressions : 2 ventilations in adults ─────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Emergency and First Aid','In cardiopulmonary resuscitation, what is the recommended compression-to-ventilation ratio for adults?','15:1','30:2','5:1','10:1','B','The AHA/BLS recommended compression-to-ventilation ratio for adults is 30 compressions to 2 ventilations; compression rate 100–120/min, depth 5–6 cm (AHA/BLS guidelines; Kenya Basic Life Support protocols).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Emergency and First Aid','In cardiopulmonary resuscitation, what is the recommended compression-to-ventilation ratio for adults?','15:1','30:2','5:1','10:1','B','30:2 for single-rescuer adult CPR; once advanced airway placed, continuous compressions at 100–120/min with 1 breath every 6 seconds. BScN nurses lead BLS certification programmes and conduct in-situ mock codes (AHA/BLS; Kenya resuscitation council guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── First aid for bleeding — stop the bleeding ────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Emergency and First Aid','In the context of first aid, what is the primary goal when treating a bleeding wound?','To clean the wound','To stop the bleeding','To prevent infection','To apply a bandage','B','The primary first-aid goal for a bleeding wound is haemostasis — stopping the bleeding by applying direct firm pressure to the wound (first aid; Kenya Basic Life Support protocols).','medium',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Emergency and First Aid','In the context of first aid, what is the primary goal when treating a bleeding wound?','To clean the wound','To stop the bleeding','To prevent infection','To apply a bandage','B','Haemostasis sequence: direct pressure → tourniquet for limb extremity bleeding → wound packing for junctional wounds. BScN nurses teach STOP THE BLEED programme and apply MARCH haemorrhage control sequence in mass casualty scenarios (Kenya BLS; Brunner & Suddarth).','medium',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Cardiac arrest — requires immediate CPR ───────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Emergency and First Aid','What is the term for cessation of the heartbeat and circulation, often requiring immediate CPR?','Stroke','Seizure','Cardiac arrest','Hyperventilation','C','Cardiac arrest is the sudden cessation of effective cardiac mechanical activity resulting in absence of circulation; it requires immediate cardiopulmonary resuscitation and, for shockable rhythms, defibrillation (Brunner & Suddarth; AHA guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Emergency and First Aid','What is the term for cessation of the heartbeat and circulation, often requiring immediate CPR?','Stroke','Seizure','Cardiac arrest','Hyperventilation','C','Cardiac arrest rhythms: shockable (VF, pulseless VT) → defibrillate; non-shockable (asystole, PEA) → CPR + reversible causes (4H4T). BScN nurses lead ACLS teams, interpret arrest rhythms and manage post-ROSC care (Brunner & Suddarth; AHA ACLS guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Defibrillation — restores normal heartbeat ───────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Emergency and First Aid','What is the term for the emergency procedure that uses electrical shock to restore the heart''s normal rhythm?','CPR','Heimlich manoeuvre','Defibrillation','Tracheostomy','C','Defibrillation delivers a controlled electrical shock to terminate ventricular fibrillation or pulseless ventricular tachycardia, allowing the heart''s natural pacemaker to resume normal rhythm (Brunner & Suddarth; AHA defibrillation guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Emergency and First Aid','What is the term for the emergency procedure that uses electrical shock to restore the heart''s normal rhythm?','CPR','Heimlich manoeuvre','Defibrillation','Tracheostomy','C','Early defibrillation within 3–5 minutes of VF → survival >50%. BScN nurses ensure AEDs are accessible, staff are trained and analyse AED use in cardiac arrest audits (Brunner & Suddarth; AHA ACLS guidelines; Kenya resuscitation council).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Syncope — temporary loss of consciousness from BP drop ───────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Emergency and First Aid','Which term refers to loss of consciousness due to a temporary decrease in blood flow to the brain?','Syncope','Seizure','Stroke','Shock','A','Syncope (fainting) is a transient loss of consciousness due to temporary cerebral hypoperfusion, often caused by vasovagal response, orthostatic hypotension or cardiac arrhythmia; rapid spontaneous recovery distinguishes it from stroke (Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Emergency and First Aid','Which term refers to loss of consciousness due to a temporary decrease in blood flow to the brain?','Syncope','Seizure','Stroke','Shock','A','Syncope workup: ECG (arrhythmia), tilt-table test (vasovagal), lying/standing BP (orthostatic), Holter monitor. BScN nurses identify high-risk syncope features (exertional, no prodrome, structural heart disease) requiring urgent cardiac investigation (Brunner & Suddarth; ESC syncope guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Amputation — surgical removal of a limb ──────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Musculoskeletal Disorders','What is the term for a surgical procedure involving the removal of a limb?','Amputation','Arthroscopy','Osteotomy','Fracture reduction','A','Amputation is the surgical removal of a limb or digit, performed for conditions such as critical limb ischaemia, severe trauma, infection (necrotising fasciitis, gas gangrene) or malignancy (Brunner & Suddarth; surgical nursing).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Musculoskeletal Disorders','What is the term for a surgical procedure involving the removal of a limb?','Amputation','Arthroscopy','Osteotomy','Fracture reduction','A','Post-amputation care: stump bandaging (figure-8 to shape for prosthesis), phantom limb pain management (gabapentin, mirror therapy), psychological support, early prosthetic referral. BScN nurses apply rehabilitation-focused nursing care (Brunner & Suddarth; surgical nursing EBP).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Osteoporosis — thinning and weakening of bones ───────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Musculoskeletal Disorders','Which medical condition is characterised by thinning and weakening of bones, making them more susceptible to fractures?','Osteoporosis','Osteoarthritis','Rheumatoid arthritis','Scoliosis','A','Osteoporosis is characterised by decreased bone mineral density and disrupted bone microarchitecture, leading to increased fracture risk, especially at the hip, spine and wrist (Brunner & Suddarth; musculoskeletal nursing).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Musculoskeletal Disorders','Which medical condition is characterised by thinning and weakening of bones, making them more susceptible to fractures?','Osteoporosis','Osteoarthritis','Rheumatoid arthritis','Scoliosis','A','DEXA T-score ≤−2.5 = osteoporosis. Treatment: bisphosphonates, calcium + vitamin D, weight-bearing exercise, fall prevention. BScN nurses use FRAX tool for fracture risk assessment and coordinate bone protection programmes (Brunner & Suddarth; NOF guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;
