-- Migration: 20260701000005
-- Source: NCK-NEW-MCQ-Compilation.docx — "Kenya Med Exams compiled set" (Year not stated)
-- exam_year = NULL per §13.1 (no year stated on source document)
-- Paper assignment per §12 nck-exam-system.md applied per-question.
-- Batch A: Basic sciences — anatomy, physiology, pharmacology foundations (Q1–Q50)
-- Audit: answers and rationales verified against Brunner & Suddarth, BNF,
--        Kenya IMNCI, MOH Kenya guidelines per §14.3.
-- ON CONFLICT (stem, cadre) DO NOTHING on every INSERT.

-- ── Insulin produced by pancreas ─────────────────────────────────────────────
-- Per §12: Anatomy & Physiology → Paper I both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','Which organ is responsible for producing insulin in the human body?','Liver','Pancreas','Kidneys','Stomach','B','Insulin is produced by the beta cells of the islets of Langerhans in the pancreas; it regulates blood glucose by facilitating cellular glucose uptake (anatomy/physiology; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','Which organ is responsible for producing insulin in the human body?','Liver','Pancreas','Kidneys','Stomach','B','Beta cells (islets of Langerhans) secrete insulin; alpha cells secrete glucagon. Destruction of beta cells → T1DM. BScN nurses apply this to distinguish T1DM from T2DM pathophysiology in clinical reasoning (anatomy/physiology; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Primary function of respiratory system — gas exchange ────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','What is the primary function of the respiratory system?','Pump blood throughout the body','Break down food for energy','Exchange oxygen and carbon dioxide','Filter waste from the blood','C','The primary function of the respiratory system is to facilitate gas exchange — delivering oxygen to and removing carbon dioxide from the blood at the alveolar-capillary interface (anatomy/physiology; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','What is the primary function of the respiratory system?','Pump blood throughout the body','Break down food for energy','Exchange oxygen and carbon dioxide','Filter waste from the blood','C','External respiration (lungs) + internal respiration (tissues) constitute complete gas exchange. BScN nurses apply respiratory physiology in managing ARDS, COPD and mechanical ventilation (anatomy/physiology; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Peripheral nerves — NOT part of CNS ──────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','Which of the following is NOT a component of the central nervous system?','Brain','Spinal cord','Peripheral nerves','Cranial nerves','C','The CNS consists of the brain and spinal cord only; peripheral nerves (including cranial nerves outside the skull) form the peripheral nervous system (anatomy/physiology; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','Which of the following is NOT a component of the central nervous system?','Brain','Spinal cord','Peripheral nerves','Cranial nerves','C','CNS = brain + spinal cord; PNS = cranial nerves (outside cranium), spinal nerves, autonomic nervous system. BScN nurses apply this when differentiating UMN (CNS) from LMN (PNS) lesion patterns (anatomy; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Femur — located in the leg ────────────────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','The femur is a bone located in which part of the body?','Arm','Leg','Skull','Chest','B','The femur is the thigh bone, located in the upper leg; it is the longest and strongest bone in the human body (anatomy; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','The femur is a bone located in which part of the body?','Arm','Leg','Skull','Chest','B','Femoral fractures carry significant blood loss risk (up to 2L). BScN nurses apply femoral anatomy in assessment of hip and knee pathology and neurovascular checks post-orthopaedic surgery (anatomy; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Neuron — smallest unit of nervous system ──────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','Which of the following is the basic structural and functional unit of the nervous system?','Neuron','Blood vessel','Muscle fibre','Red blood cell','A','The neuron is the basic structural and functional unit of the nervous system, responsible for transmitting electrical and chemical signals throughout the body (anatomy/physiology; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','Which of the following is the basic structural and functional unit of the nervous system?','Neuron','Blood vessel','Muscle fibre','Red blood cell','A','Neuron components: cell body, dendrites (receive signals), axon (transmit signals), myelin sheath. Demyelination (MS) impairs conduction — BScN nurses apply this to explain MS symptoms to patients (anatomy; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Arteries — carry oxygenated blood away from heart ────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','Which blood vessels carry oxygenated blood away from the heart to the body''s tissues?','Veins','Arteries','Capillaries','Venules','B','Arteries carry oxygenated blood away from the heart to supply body tissues; veins return deoxygenated blood to the heart (exception: pulmonary vessels carry the reverse) (anatomy/physiology; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','Which blood vessels carry oxygenated blood away from the heart to the body''s tissues?','Veins','Arteries','Capillaries','Venules','B','Arteries have thick muscular walls to withstand high pressure; BScN nurses apply arterial anatomy in vascular assessment (pulse sites, ABI) and interpreting arterial blood gas results (anatomy/physiology; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Kidneys — primary function is blood filtration ───────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','What is the main function of the kidneys in the human body?','Digestion','Filtration of blood','Regulation of body temperature','Production of red blood cells','B','The kidneys filter approximately 180 litres of blood per day, removing waste products and regulating fluid, electrolyte and acid-base balance (anatomy/physiology; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','What is the main function of the kidneys in the human body?','Digestion','Filtration of blood','Regulation of body temperature','Production of red blood cells','B','Renal functions: filtration, reabsorption, secretion, excretion + erythropoietin production + renin-angiotensin regulation. BScN nurses interpret GFR, creatinine and BUN trends in AKI/CKD management (anatomy/physiology; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Cerebellum — balance and coordination ────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','What is the function of the cerebellum in the brain?','Memory storage','Balance and coordination','Speech production','Visual processing','B','The cerebellum is primarily responsible for maintaining balance and coordinating voluntary muscle movements, including fine motor control (anatomy/physiology; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','What is the function of the cerebellum in the brain?','Memory storage','Balance and coordination','Speech production','Visual processing','B','Cerebellar lesions cause ataxia, dysmetria and intention tremor. BScN nurses assess cerebellar function (finger-nose test, heel-shin test, Romberg) in neurological assessment (anatomy/physiology; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Septum — separates right and left sides of heart ─────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','What is the name of the structure that separates the right and left sides of the heart?','Pulmonary artery','Aorta','Septum','Valve','C','The interventricular and interatrial septa form the wall separating the right and left sides of the heart, preventing mixing of oxygenated and deoxygenated blood under normal conditions (anatomy/physiology; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','What is the name of the structure that separates the right and left sides of the heart?','Pulmonary artery','Aorta','Septum','Valve','C','Ventricular septal defect (VSD) is the commonest congenital heart defect; atrial septal defect (ASD) causes left-to-right shunting. BScN nurses recognise murmur characteristics in cardiac assessment (anatomy; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Cortisol — produced by adrenal glands ────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','Which of the following hormones is produced by the adrenal glands?','Insulin','Thyroxine','Cortisol','Estrogen','C','Cortisol is produced by the adrenal cortex (zona fasciculata) and is involved in the stress response, metabolism regulation, and immune suppression (anatomy/physiology; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','Which of the following hormones is produced by the adrenal glands?','Insulin','Thyroxine','Cortisol','Estrogen','C','Adrenal cortex hormones: glucocorticoids (cortisol), mineralocorticoids (aldosterone), androgens. Adrenal medulla: catecholamines. Excess cortisol → Cushing syndrome; deficiency → Addison disease (anatomy; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Alveoli — gas exchange in respiratory system ─────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','What is the function of the alveoli in the respiratory system?','Transport oxygen in the bloodstream','Filter out dust and particles from the air','Exchange oxygen and carbon dioxide','Produce mucus for lubrication','C','Alveoli are the tiny air sacs in the lungs where gas exchange occurs across the thin alveolar-capillary membrane — oxygen diffuses into the blood and carbon dioxide diffuses out (anatomy/physiology; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','What is the function of the alveoli in the respiratory system?','Transport oxygen in the bloodstream','Filter out dust and particles from the air','Exchange oxygen and carbon dioxide','Produce mucus for lubrication','C','Alveolar surface area ~70m²; surfactant (type II pneumocytes) prevents collapse. BScN nurses apply alveolar physiology in ARDS management: prone positioning, low tidal volume ventilation (anatomy/physiology; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Medulla oblongata — regulates breathing and heart rate ───────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','Which part of the brain is responsible for regulating basic bodily functions such as breathing and heart rate?','Cerebellum','Medulla oblongata','Thalamus','Hippocampus','B','The medulla oblongata, located in the brainstem, contains the respiratory centre and cardiovascular centre, controlling vital autonomic functions including breathing and heart rate (anatomy/physiology; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','Which part of the brain is responsible for regulating basic bodily functions such as breathing and heart rate?','Cerebellum','Medulla oblongata','Thalamus','Hippocampus','B','Medullary compression (e.g. tonsillar herniation) causes Cushing''s triad (hypertension, bradycardia, irregular breathing) — a late sign of raised ICP. BScN nurses recognise this as a neurosurgical emergency (anatomy; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Red blood cells — transport oxygen to body tissues ───────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','What is the function of red blood cells (erythrocytes) in the circulatory system?','Transport oxygen to body tissues','Fight infections','Carry nutrients to cells','Clot blood','A','Red blood cells contain haemoglobin which binds oxygen in the lungs and releases it to body tissues, enabling cellular respiration (anatomy/physiology; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','What is the function of red blood cells (erythrocytes) in the circulatory system?','Transport oxygen to body tissues','Fight infections','Carry nutrients to cells','Clot blood','A','RBCs: biconcave, anucleate, lifespan 120 days. Low Hb → reduced O2 delivery → tachycardia, dyspnoea, fatigue. BScN nurses interpret FBC and calculate haemoglobin levels to guide transfusion thresholds (anatomy/physiology; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Insulin — regulates blood sugar by allowing glucose into cells ────────────
-- Audit note: stem wording differs from prior insulin Q (which asked which organ produces insulin)
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','Which hormone is responsible for regulating blood sugar levels by allowing glucose to enter cells?','Insulin','Thyroid hormone','Adrenaline','Estrogen','A','Insulin is produced by pancreatic beta cells and facilitates glucose entry into cells (especially muscle and fat) via GLUT4 transporters, lowering blood glucose (anatomy/physiology; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','Which hormone is responsible for regulating blood sugar levels by allowing glucose to enter cells?','Insulin','Thyroid hormone','Adrenaline','Estrogen','A','Insulin deficiency (T1DM) or resistance (T2DM) impairs glucose uptake → hyperglycaemia. BScN nurses apply insulin physiology to explain self-monitoring, injection technique and hypoglycaemia management (anatomy/physiology; Kenya MOH diabetes guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Liver — largest organ in human body ──────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','Which of the following is the largest organ in the human body?','Heart','Brain','Liver','Kidney','C','The liver is the largest internal organ, weighing approximately 1.5 kg, and performs over 500 functions including detoxification, protein synthesis and bile production (anatomy/physiology; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','Which of the following is the largest organ in the human body?','Heart','Brain','Liver','Kidney','C','Liver functions: metabolism, drug biotransformation, clotting factor synthesis, albumin production. Liver failure → jaundice, coagulopathy, hepatic encephalopathy. BScN nurses monitor LFTs and adjust drug doses in hepatic impairment (anatomy; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Pituitary gland — controls growth and development ────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','What is the function of the pituitary gland in the endocrine system?','Regulation of sleep-wake cycles','Control of growth and development','Production of insulin','Regulation of body temperature','B','The pituitary gland (hypophysis) is the "master gland" that produces hormones controlling growth (GH), thyroid function (TSH), adrenal function (ACTH), reproduction (FSH/LH) and water balance (ADH) (anatomy/physiology; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','What is the function of the pituitary gland in the endocrine system?','Regulation of sleep-wake cycles','Control of growth and development','Production of insulin','Regulation of body temperature','B','Anterior pituitary: GH, TSH, ACTH, FSH, LH, prolactin. Posterior: ADH, oxytocin. Pituitary tumours cause acromegaly or hypopituitarism. BScN nurses assess pituitary function in endocrine disorder management (anatomy; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Skeletal muscle — voluntary control ──────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','Which type of muscle is under voluntary control?','Smooth muscle','Cardiac muscle','Skeletal muscle','Visceral muscle','C','Skeletal (striated) muscles are attached to bones and are under conscious (voluntary) control via the somatic nervous system; cardiac and smooth muscle are involuntary (anatomy/physiology; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','Which type of muscle is under voluntary control?','Smooth muscle','Cardiac muscle','Skeletal muscle','Visceral muscle','C','Skeletal muscle atrophies with immobility; BScN nurses institute early mobilisation and physiotherapy to prevent ICU-acquired weakness and plan rehabilitation for immobilised patients (anatomy/physiology; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Lens — focuses light onto retina ─────────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','Which part of the eye is responsible for focusing light onto the retina?','Cornea','Lens','Retina','Iris','B','The crystalline lens changes shape (accommodation) to focus light precisely onto the retina for near and far objects; the cornea provides about two-thirds of total refractive power (anatomy/physiology; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','Which part of the eye is responsible for focusing light onto the retina?','Cornea','Lens','Retina','Iris','B','Lens clouding → cataract; surgical lens replacement (phacoemulsification + IOL). BScN nurses provide pre/post-operative cataract surgery education and monitor for raised IOP (anatomy; Brunner & Suddarth ophthalmology).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Epiglottis — prevents food entering trachea ──────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','What is the function of the epiglottis in the respiratory system?','Regulation of blood pressure','Protection of the lungs from infections','Preventing food from entering the trachea during swallowing','Exchange of oxygen and carbon dioxide','C','The epiglottis is a leaf-shaped cartilaginous flap that covers the laryngeal inlet during swallowing, preventing aspiration of food and liquids into the trachea (anatomy/physiology; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','What is the function of the epiglottis in the respiratory system?','Regulation of blood pressure','Protection of the lungs from infections','Preventing food from entering the trachea during swallowing','Exchange of oxygen and carbon dioxide','C','Epiglottitis is a life-threatening airway emergency; patients adopt tripod position. BScN nurses maintain calm, avoid agitating the patient, prepare for airway management and escalate immediately (anatomy; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── DVT nursing — encourage ambulation and leg exercises ─────────────────────
-- Per §12: Medical-Surgical → Paper I both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Vascular Disorders','Which of the following nursing interventions is appropriate for a patient with deep vein thrombosis (DVT)?','Apply heat to the affected leg','Administer aspirin for pain relief','Encourage ambulation and leg exercises','Elevate the leg above the heart level','C','For DVT, promoting early mobility and leg exercises helps prevent complications, reduces stasis and improves venous return; heat application risks embolisation and aspirin alone is insufficient anticoagulation (Brunner & Suddarth; vascular nursing).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Vascular Disorders','Which of the following nursing interventions is appropriate for a patient with deep vein thrombosis (DVT)?','Apply heat to the affected leg','Administer aspirin for pain relief','Encourage ambulation and leg exercises','Elevate the leg above the heart level','C','DVT management: anticoagulation (LMWH/DOAC), early ambulation, compression stockings, limb elevation (not above heart). BScN nurses assess Wells score, manage anticoagulation and educate on PE warning signs (Brunner & Suddarth; vascular nursing EBP).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Chest tube — monitor water seal chamber fluctuation ──────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Respiratory Disorders','What is the priority nursing action when caring for a patient with a chest tube?','Clamping the tube during patient transport','Milking or stripping the chest tube','Monitoring for fluctuation of the water seal chamber','Changing the dressing around the chest tube daily','C','Monitoring the water seal chamber for tidalling (fluctuation with respiration) is the priority — it confirms tube patency and lung re-expansion; routine clamping and milking are not recommended (Brunner & Suddarth thoracic drainage nursing).','medium',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Respiratory Disorders','What is the priority nursing action when caring for a patient with a chest tube?','Clamping the tube during patient transport','Milking or stripping the chest tube','Monitoring for fluctuation of the water seal chamber','Changing the dressing around the chest tube daily','C','Tidalling stops when lung fully expanded or tube kinked; continuous bubbling in water seal = air leak. BScN nurses troubleshoot chest tube systems, document drainage characteristics and escalate complications (Brunner & Suddarth; thoracic nursing EBP).','medium',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── INR 3.5 — bleeding risk on anticoagulant therapy ─────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Anticoagulant Therapy','Which laboratory value indicates a potential risk for bleeding in a patient receiving anticoagulant therapy?','Haemoglobin 12 g/dL','Platelet count 150,000/mm³','International Normalised Ratio (INR) of 3.5','White blood cell count 8,000/mm³','C','An INR of 3.5 indicates a prolonged clotting time beyond the therapeutic range (usually 2–3 for most indications, 2.5–3.5 for mechanical heart valves), indicating significantly increased bleeding risk (BNF; Brunner & Suddarth anticoagulation).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Anticoagulant Therapy','Which laboratory value indicates a potential risk for bleeding in a patient receiving anticoagulant therapy?','Haemoglobin 12 g/dL','Platelet count 150,000/mm³','International Normalised Ratio (INR) of 3.5','White blood cell count 8,000/mm³','C','INR >3.5 (for AF/DVT indication) warrants dose reduction and assessment for bleeding. BScN nurses interpret INR trends, identify interacting medications and educate patients on consistent vitamin K intake and bleeding precautions (BNF; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Heart failure — oedema and dyspnoea ──────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Cardiovascular Disorders','A patient with heart failure may exhibit which of the following signs and symptoms?','Bradycardia','Hypertension','Oedema and shortness of breath','Increased urine output','C','Heart failure causes fluid retention (oedema) and pulmonary congestion (dyspnoea) due to impaired cardiac pumping and compensatory mechanisms (Brunner & Suddarth; Kenya cardiac care protocols).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Cardiovascular Disorders','A patient with heart failure may exhibit which of the following signs and symptoms?','Bradycardia','Hypertension','Oedema and shortness of breath','Increased urine output','C','HF signs: orthopnoea, PND, JVD, S3 gallop, peripheral oedema. NYHA classification guides management. BScN nurses monitor daily weight, fluid balance, BNP trends and titrate diuretics in collaboration with cardiologists (Brunner & Suddarth; HF guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Pressure ulcers — complication of immobility ─────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Wound Care','What is a potential complication of immobility in a bedridden patient?','Increased muscle strength','Pressure ulcers','Improved lung function','Enhanced joint mobility','B','Immobility leads to sustained pressure on skin bony prominences, reducing blood flow and causing ischaemic tissue breakdown — pressure ulcers (Brunner & Suddarth; wound care guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Wound Care','What is a potential complication of immobility in a bedridden patient?','Increased muscle strength','Pressure ulcers','Improved lung function','Enhanced joint mobility','B','Pressure ulcer prevention: Braden scale risk assessment, 2-hourly repositioning, pressure-relieving mattresses, skin inspection, nutritional optimisation. BScN nurses lead pressure ulcer prevention programmes and audit compliance (Brunner & Suddarth; NPUAP/EPUAP guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── GCS — assesses level of consciousness ────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Neurological Assessment','What is the primary purpose of the Glasgow Coma Scale (GCS)?','Assessing cardiac function','Evaluating cognitive function','Measuring pain intensity','Assessing level of consciousness','D','The Glasgow Coma Scale assesses and quantifies level of consciousness through three components: eye opening, verbal response and motor response; total score ranges from 3 (deep coma) to 15 (fully conscious) (Brunner & Suddarth; neurological nursing).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Neurological Assessment','What is the primary purpose of the Glasgow Coma Scale (GCS)?','Assessing cardiac function','Evaluating cognitive function','Measuring pain intensity','Assessing level of consciousness','D','GCS ≤8 = severe TBI, airway protection needed; trend more important than single value. BScN nurses document GCS serially, recognise deterioration and escalate; accompany with pupil assessment for complete neurological monitoring (Brunner & Suddarth; neurocritical care).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Prophylactic antibiotics — prevent surgical site infection ────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Surgical Nursing','Pre-operative Care','What is the primary purpose of administering prophylactic antibiotics before surgery?','To reduce postoperative pain','To prevent surgical site infection','To promote wound healing','To improve patient comfort','B','Prophylactic antibiotics are given within 60 minutes before surgical incision to achieve tissue concentrations that prevent surgical site infection (SSI); they are not a treatment for active infection (Brunner & Suddarth; surgical nursing; Kenya IPC guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Surgical Nursing','Pre-operative Care','What is the primary purpose of administering prophylactic antibiotics before surgery?','To reduce postoperative pain','To prevent surgical site infection','To promote wound healing','To improve patient comfort','B','Prophylaxis: cefazolin 1–2g IV within 60 minutes of incision (redose if >4 hours); discontinued within 24 hours post-op. BScN nurses verify antibiotic given on surgical checklist (WHO Surgical Safety Checklist; Kenya IPC guidelines; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── NG tube — assess placement and residual volumes ──────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Gastrointestinal Procedures','Which intervention is appropriate to prevent complications in a patient with a nasogastric tube?','Administering the tube with kinks to promote drainage','Taping the tube to the patient''s nose','Irrigating the tube with hot water','Assessing tube placement and residual volumes','D','Regularly verifying NG tube placement (aspirate pH, X-ray confirmation) and checking residual volumes prevents complications such as aspiration, tube misplacement and over-feeding (Brunner & Suddarth; enteral feeding guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Gastrointestinal Procedures','Which intervention is appropriate to prevent complications in a patient with a nasogastric tube?','Administering the tube with kinks to promote drainage','Taping the tube to the patient''s nose','Irrigating the tube with hot water','Assessing tube placement and residual volumes','D','Gastric residual volumes >500 mL suggest delayed gastric emptying; nurses pause feeds and reassess. BScN nurses apply evidence-based enteral feeding protocols including head-of-bed elevation to reduce aspiration risk (Brunner & Suddarth; ESPEN enteral nutrition guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── CVC care — aseptic technique ─────────────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Infection Prevention & Control','What is the primary nursing intervention to prevent complications in a patient with a central venous catheter?','Encouraging the patient to shower daily','Changing the CVC dressing every other day','Using aseptic technique during CVC care','Limiting the use of gloves during CVC care','C','Maintaining strict aseptic (sterile non-touch) technique during all CVC care — insertion, dressing changes and line access — is the most important intervention to prevent catheter-related bloodstream infections (CRBSI) (Brunner & Suddarth; Kenya IPC guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Infection Prevention & Control','What is the primary nursing intervention to prevent complications in a patient with a central venous catheter?','Encouraging the patient to shower daily','Changing the CVC dressing every other day','Using aseptic technique during CVC care','Limiting the use of gloves during CVC care','C','CRBSI prevention bundle: hand hygiene, maximal barrier precautions at insertion, chlorhexidine skin antisepsis, optimal site selection, daily review of catheter necessity. BScN nurses lead CLABSI prevention programmes and audit bundle compliance (CDC; Kenya IPC guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;
