-- Migration: 20260701000004
-- Source: NCK-NEW-MCQ-Compilation.docx — Year 2021 (NCK April 2021 CBT)
--         BScN Paper II / KRCHN Paper II remaining items NOT seeded in 20260628000003.
--         Paper assignment per §12 nck-exam-system.md applied per-question.
-- exam_year = 2021
-- Audit: answers and rationales verified against primary references (§14.3).
-- ON CONFLICT (stem, cadre) DO NOTHING on every INSERT.

-- ── Management functions — planning, organising, staffing, controlling ────────
-- Per §12: Management → Paper II both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Health Systems & Management','Nursing Management','Management functions include:','Planning, organising, staffing, controlling','Planning, centralisation, authority, controlling','Authority, planning, organising, staffing','Unity of command, staffing, controlling, directing','A','The classical management functions are planning, organising, staffing, directing and controlling (POSDCORB framework); these are universally applied in nursing management education (nursing management/leadership texts).','hard',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Nursing Management & Leadership','Nursing Management','Management functions include:','Planning, organising, staffing, controlling','Planning, centralisation, authority, controlling','Authority, planning, organising, staffing','Unity of command, staffing, controlling, directing','A','Fayol''s and Luther Gulick''s POSDCORB: Planning, Organising, Staffing, Directing, Coordinating, Reporting, Budgeting. BScN nurses apply all functions in unit management and quality improvement roles (nursing management leadership texts; NCK curriculum).','hard',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Malnutrition/anaemia screening — all children brought to clinic ───────────
-- Per §12: Paediatric Nursing → Paper I both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Paediatric Nursing','Nutrition Assessment','The categories of children who should be checked for malnutrition and anaemia include:','Children with diarrhoea','Children with feeding problems','All children brought to clinic','Children with chronic illness causing weight loss','C','Kenya IMNCI protocol mandates that ALL sick children brought to the clinic be routinely assessed for malnutrition and anaemia — not only selected groups — to ensure no case is missed (Kenya IMNCI chart booklet; MOH Kenya Basic Paediatric Protocols).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Paediatric Nursing','Nutrition Assessment','The categories of children who should be checked for malnutrition and anaemia include:','Children with diarrhoea','Children with feeding problems','All children brought to clinic','Children with chronic illness causing weight loss','C','Universal IMNCI screening for malnutrition and anaemia at every sick-child visit ensures early detection; BScN nurses lead nutritional surveillance programmes and interpret MUAC/weight-for-height findings (Kenya IMNCI; MOH Kenya Basic Paediatric Protocols).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Schistosoma haematobium — urogenital damage ───────────────────────────────
-- Per §12: Medical-Surgical Nursing → Paper I both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Parasitic Infections','Infection with this parasite can cause extensive damage to human urogenital structures:','Ascaris lumbricoides','Schistosoma haematobium','Toxoplasma gondii','Schistosoma mansoni','B','Schistosoma haematobium is the species causing urinary schistosomiasis, infecting the vesical venous plexus and causing bladder and urogenital pathology including haematuria, hydronephrosis and bladder cancer (Kenya NTD/parasitology guidelines).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Parasitic Infections','Infection with this parasite can cause extensive damage to human urogenital structures:','Ascaris lumbricoides','Schistosoma haematobium','Toxoplasma gondii','Schistosoma mansoni','B','S. haematobium causes haematuria (classic painless), urinary obstruction and bladder carcinoma with chronic infection. BScN nurses integrate schistosomiasis screening into community health programmes in endemic regions (Kenya NTD guidelines; Brunner & Suddarth).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Herd immunity — high percentage immune ────────────────────────────────────
-- Per §12: Community Health → Paper II both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Community Health Nursing','Epidemiology','Herd immunity exists in a community when:','A high percentage of people are immune to an infection','The incidence of the disease decreases to a very low level','Vaccination is stopped in a well-vaccinated community','Both dead and live antigens are used to immunise','A','Herd immunity exists when a sufficiently high proportion of the population is immune to an infection, reducing transmission and protecting unimmunised individuals (Kenya EPI/immunisation guidelines; epidemiology).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Community Health Nursing','Epidemiology','Herd immunity exists in a community when:','A high percentage of people are immune to an infection','The incidence of the disease decreases to a very low level','Vaccination is stopped in a well-vaccinated community','Both dead and live antigens are used to immunise','A','Herd immunity threshold varies by R0 (measles ~95%, polio ~80-85%); BScN nurses monitor vaccination coverage data, identify immunity gaps and plan catch-up campaigns (Kenya EPI; WHO immunisation guidelines; epidemiology).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Bipolar I nursing intervention — structured environment ───────────────────
-- Per §12: Mental Health → Paper II both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Mental Health Nursing','Mood Disorders','A nursing intervention for a male client with bipolar I disorder should include:','Designing activities requiring maintenance of contact with reality','Providing a structured environment','Engaging the client in current affairs conversation','Touching the client to provide assurance','B','Manic clients in bipolar I disorder require a structured, low-stimulus environment to reduce distractibility, hyperactivity and impulsive behaviour; overstimulating activities worsen the manic episode (psychiatric nursing/Brunner & Suddarth).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Mental Health Nursing','Mood Disorders','A nursing intervention for a male client with bipolar I disorder should include:','Designing activities requiring maintenance of contact with reality','Providing a structured environment','Engaging the client in current affairs conversation','Touching the client to provide assurance','B','Structure reduces mania-related decision-making impulsivity and risk; BScN nurses apply evidence-based milieu therapy, set consistent limits, coordinate interdisciplinary care and educate families on relapse triggers (psychiatric nursing; Kenya Mental Health guidelines).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Labile affect — rapid abrupt changes in emotional feeling ─────────────────
-- Per §12: Mental Health → Paper II both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Mental Health Nursing','Mental Status Examination','Rapid and abrupt changes in emotional feeling describe:','Rapid affect','Restricted affect','Labile affect','Inappropriate affect','C','Labile affect denotes rapid, abrupt, uncontrollable shifts in emotional expression not proportional to the stimulus; seen in mania, pseudobulbar palsy and some personality disorders (mental health assessment/psychiatric nursing texts).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Mental Health Nursing','Mental Status Examination','Rapid and abrupt changes in emotional feeling describe:','Rapid affect','Restricted affect','Labile affect','Inappropriate affect','C','BScN nurses document affect objectively in the MSE: labile (unstable), blunted (reduced intensity), flat (absent), restricted (mildly reduced), inappropriate (incongruent with thought content); accurate documentation guides diagnosis (DSM-5; Stuart Psychiatric Nursing).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Post-visit phase of home visit — future follow-up care plan ───────────────
-- Per §12: Community Health → Paper II both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Community Health Nursing','Home Visiting','Activities during the post-visit phase of a home visit include:','Developing a future follow-up care plan','Integrating the patient into the community','Transferring patient care to another agency','Sharing the report of home visit with relevant authorities','A','The post-visit (evaluation) phase of a home visit includes documenting findings and developing a future follow-up care plan based on assessment outcomes (Kenya community health nursing guidelines; KMTC curriculum).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Community Health Nursing','Home Visiting','Activities during the post-visit phase of a home visit include:','Developing a future follow-up care plan','Integrating the patient into the community','Transferring patient care to another agency','Sharing the report of home visit with relevant authorities','A','Post-visit activities: recording, analysis of findings and care plan development are essential for continuity; BScN nurses also evaluate goal achievement and link families to community resources (Kenya community health nursing; MOH Kenya community health strategy).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Abortive polio symptom — sore throat ──────────────────────────────────────
-- Per §12: Communicable Disease → Paper II (Community Health) both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Community Health Nursing','Communicable Diseases','The following is a symptom of abortive polio:','Muscle spasm','Sore throat','Stiff neck','Back pain','B','Abortive (minor illness) poliomyelitis presents with non-specific symptoms including fever, sore throat, malaise and headache without CNS involvement; it accounts for ~5% of polio infections (Kenya EPI/communicable disease guidelines).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Community Health Nursing','Communicable Diseases','The following is a symptom of abortive polio:','Muscle spasm','Sore throat','Stiff neck','Back pain','B','Abortive polio (minor illness): fever, sore throat, vomiting; no paralysis. Non-paralytic: adds meningism. Paralytic: LMN flaccid paralysis. BScN nurses apply this classification in AFP surveillance and notification (Kenya EPI; WHO polio eradication guidelines).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Depression — indecisiveness and poor concentration significant ────────────
-- Per §12: Mental Health → Paper II both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Mental Health Nursing','Mood Disorders','Which statement is true in reference to depression?','It can only be confirmed if a patient has lost a relative, job or something valuable','The illness obviously runs along familial lines','Indecisiveness and poor concentration are significant in its diagnosis','In children and adolescents it is not significant','C','Indecisiveness and impaired concentration are core DSM-5 diagnostic criteria for a major depressive episode; loss is a risk factor but not a diagnostic requirement, and depression is highly significant in children and adolescents (DSM-5; Kenya Mental Health guidelines).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Mental Health Nursing','Mood Disorders','Which statement is true in reference to depression?','It can only be confirmed if a patient has lost a relative, job or something valuable','The illness obviously runs along familial lines','Indecisiveness and poor concentration are significant in its diagnosis','In children and adolescents it is not significant','C','DSM-5 MDE requires ≥5 of 9 criteria for ≥2 weeks; indecisiveness and concentration difficulties are among them. BScN nurses apply validated screening tools (PHQ-9) and distinguish unipolar from bipolar depression before prescribing antidepressants (DSM-5; Stuart).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Descriptive statistics — patterns and trends in a dataset ────────────────
-- Per §12: Research → Paper II both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Research & Statistics','Biostatistics','Research descriptive statistics refers to:','An estimate of population parameters from sample data','A description of the patterns and specific trends in a dataset','Examination of one variable at a time','Testing hypothesis','B','Descriptive statistics summarise and describe patterns and trends in a dataset using measures of central tendency and dispersion; inferential statistics extend findings to a population (Polit & Beck; nursing research texts).','hard',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Research & Evidence-Based Practice','Biostatistics','Research descriptive statistics refers to:','An estimate of population parameters from sample data','A description of the patterns and specific trends in a dataset','Examination of one variable at a time','Testing hypothesis','B','Descriptive statistics (frequency, mean, SD, range) characterise a sample; inferential statistics (t-tests, chi-square, ANOVA) generalise to populations. BScN nurses interpret descriptive data in audit reports and quality improvement cycles (Polit & Beck; nursing research).','hard',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Disaster management cycle — mitigation, preparedness, response, recovery ──
-- Per §12: Community Health → Paper II both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Community Health Nursing','Disaster Management','The cycle of disaster consists of the following components:','Mitigation, Preparedness, Response, Recovery','Preparedness, vulnerability assessment, risk assessment, recovery','None of the above','Mitigation, risk assessment, response and recovery','A','The disaster management cycle comprises four phases: Mitigation (reduce risk), Preparedness (plan and train), Response (immediate action), Recovery (restoration) (Kenya disaster management framework; community health nursing texts).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Community Health Nursing','Disaster Management','The cycle of disaster consists of the following components:','Mitigation, Preparedness, Response, Recovery','Preparedness, vulnerability assessment, risk assessment, recovery','None of the above','Mitigation, risk assessment, response and recovery','A','BScN nurses engage all four phases: lead mitigation advocacy, coordinate preparedness training, triage in response, and plan community recovery. This cycle frames nursing roles in Kenya''s National Disaster Management framework (Kenya NDM Act; community health nursing).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Epidemiologic investigation primary purpose — delineate aetiology ─────────
-- Per §12: Community Health → Paper II both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Community Health Nursing','Epidemiology','The primary purpose of conducting an epidemiologic investigation is to:','Identify groups at risk of contracting the disease','Identify the geographical location of cases','Delineate the aetiology of the epidemic','Encourage cooperation and support of the community','C','The primary purpose of an epidemiologic investigation is to delineate the aetiology (cause) of the epidemic in order to implement targeted control measures (Park''s Textbook of Preventive & Social Medicine; epidemiology principles).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Community Health Nursing','Epidemiology','The primary purpose of conducting an epidemiologic investigation is to:','Identify groups at risk of contracting the disease','Identify the geographical location of cases','Delineate the aetiology of the epidemic','Encourage cooperation and support of the community','C','Establishing aetiology enables source control; BScN nurses contribute to field investigations: case finding, contact tracing, data collection and reporting to county public health teams (Park''s; MOH Kenya epidemiology; community health nursing).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Main goal of community health — identify problems and needs ───────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Community Health Nursing','Community Health Principles','The following is one of the main goals of community health:','Early diagnosis and prevention of disease','Control of communicable diseases','Identify community health problems and needs','Improved sanitation in the environment','C','A core goal of community health nursing is to identify community health problems and needs as the foundation for planning and implementing appropriate interventions (community health nursing texts; Kenya community health strategy).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Community Health Nursing','Community Health Principles','The following is one of the main goals of community health:','Early diagnosis and prevention of disease','Control of communicable diseases','Identify community health problems and needs','Improved sanitation in the environment','C','Community assessment drives BScN practice; nurses systematically collect, analyse and prioritise community data to guide programme planning, resource allocation and policy advocacy (Kenya KEPH framework; community health nursing texts).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Health education — increases knowledge and attitude ──────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Community Health Nursing','Health Education','The importance of health education in inspiring behaviour change is that it:','Helps to increase learning and skills','Stimulates community to take ownership','Increases understanding and coping','Increases in knowledge and attitude of the people','D','Health education promotes behaviour change primarily by increasing the knowledge and attitudes of people — the foundational KAP (knowledge-attitude-practice) model underpinning all health education programmes (MOH Kenya health promotion guidelines; community health nursing).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Community Health Nursing','Health Education','The importance of health education in inspiring behaviour change is that it:','Helps to increase learning and skills','Stimulates community to take ownership','Increases understanding and coping','Increases in knowledge and attitude of the people','D','KAP model: knowledge change → attitude shift → practice change. BScN nurses design needs-based, culturally appropriate health education interventions and evaluate impact using pre/post KAP assessments (MOH Kenya health promotion guidelines; Ewles & Simnett).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Prenatal maternal factors — infections, use of drugs ─────────────────────
-- Per §12: Paediatric Nursing → Paper I both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Paediatric Nursing','Growth and Development','Maternal factors affecting growth and development during the prenatal period include:','Infections and use of drugs','Smoking and faulty placental implantation','Number of children and use of drugs','Malposition and alcoholism','A','Maternal infections (rubella, CMV, toxoplasma) and drug use (teratogens) during the prenatal period are the primary maternal factors that adversely affect fetal growth and development (Kenya Basic Paediatric Protocols; child health texts).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Paediatric Nursing','Growth and Development','Maternal factors affecting growth and development during the prenatal period include:','Infections and use of drugs','Smoking and faulty placental implantation','Number of children and use of drugs','Malposition and alcoholism','A','TORCH infections and teratogenic drugs are the key modifiable prenatal risk factors; BScN nurses counsel pre-conception patients on rubella immunisation, alcohol/drug avoidance and infection screening at first ANC contact (Kenya ANC guidelines; Myles).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Communicable disease control at individual/village level ─────────────────
-- Per §12: Community Health → Paper II both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Community Health Nursing','Communicable Diseases','Communicable disease control measures at individual and village level include:','Increase immunisation coverage and environmental manipulation','Emphasise on water protection and purification','Completing immunisation and protection of springs and wells','Participate in vector and reservoir control and immunisation coverage','C','At individual and village level, completing immunisation schedules and protecting water sources (springs and wells) are the primary communicable disease control measures (MOH Kenya community health guidelines; Kenya EPI).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Community Health Nursing','Communicable Diseases','Communicable disease control measures at individual and village level include:','Increase immunisation coverage and environmental manipulation','Emphasise on water protection and purification','Completing immunisation and protection of springs and wells','Participate in vector and reservoir control and immunisation coverage','C','BScN nurses coordinate CHV training on immunisation completion and WASH (water, sanitation and hygiene) interventions at village level — the two most impactful individual-level communicable disease control strategies (MOH Kenya community health strategy; Kenya EPI).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Health promotion role — resource person ───────────────────────────────────
-- Per §12: Community Health → Paper II both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Community Health Nursing','Health Education','When developing health promotion plans with clients, the nurse educator should take the role of:','Promoter','Counsellor','Resource person','Advisor','C','When developing health promotion plans with clients, the nurse acts as a resource person — supplying information, resources and evidence to support client-driven decision-making rather than directing clients (health promotion/community health nursing; Ewles & Simnett).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Community Health Nursing','Health Education','When developing health promotion plans with clients, the nurse educator should take the role of:','Promoter','Counsellor','Resource person','Advisor','C','The resource person role preserves client autonomy and aligns with the empowerment approach; BScN nurses distinguish this from the expert/prescriptive role in therapeutic settings (Ewles & Simnett health promotion approaches; MOH Kenya health promotion guidelines).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Democratic leadership — takes into account others' views ─────────────────
-- Per §12: Management → Paper II both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Health Systems & Management','Leadership Styles','The style of leadership that takes into account other people''s views, opinions and ideas is:','Laissez-faire','Democratic','Autocratic','People-oriented','B','Democratic (participative) leadership solicits and incorporates group members'' views, opinions and ideas before decision-making, fostering ownership and team morale (nursing management/leadership texts).','hard',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Nursing Management & Leadership','Leadership Styles','The style of leadership that takes into account other people''s views, opinions and ideas is:','Laissez-faire','Democratic','Autocratic','People-oriented','B','Democratic leadership improves staff satisfaction and quality outcomes in stable, skilled teams; less effective in emergencies. BScN nurses distinguish this from transactional and transformational styles (Lewin''s leadership styles; nursing management leadership texts).','hard',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── BMI 23 — normal weight ────────────────────────────────────────────────────
-- Per §12: Community Health → Paper II both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Community Health Nursing','Nutrition','A body mass index (BMI) of 23 kg/m² is considered to be:','Obese','Overweight','Normal weight','Underweight','C','WHO/MOH Kenya BMI classification: underweight <18.5, normal 18.5–24.9, overweight 25–29.9, obese ≥30 kg/m²; a BMI of 23 falls in the normal range (Kenya MOH nutrition guidelines; WHO).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Community Health Nursing','Nutrition','A body mass index (BMI) of 23 kg/m² is considered to be:','Obese','Overweight','Normal weight','Underweight','C','BMI is a population-level screening tool; BScN nurses apply it in community nutrition assessments alongside waist circumference and dietary intake to give a complete nutritional picture (Kenya MOH nutrition guidelines; WHO).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Measles complication — diarrhoea ─────────────────────────────────────────
-- Per §12: Community Health/Paediatric → Paper II both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Community Health Nursing','Communicable Diseases','The following is a complicated sign or symptom of measles disease:','Fever','Coryza','Coughing','Diarrhoea','D','Fever, coryza and cough are the three classical (uncomplicated) features of measles; diarrhoea indicates a complication of measles and warrants close monitoring and management (Kenya IMNCI/Basic Paediatric Protocols; EPI guidelines).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Community Health Nursing','Communicable Diseases','The following is a complicated sign or symptom of measles disease:','Fever','Coryza','Coughing','Diarrhoea','D','Measles complications: pneumonia, diarrhoea, otitis media, encephalitis and malnutrition (immunosuppression). BScN nurses monitor for these during outbreak response and apply integrated management for measles with complications (Kenya IMNCI; MOH Kenya EPI).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Primary disease prevention — immunisation, balanced diet, exercise ────────
-- Per §12: Community Health → Paper II both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Community Health Nursing','Levels of Prevention','Primary disease prevention involves:','Immunisation, screening for cervical cancer, good nutrition','Early treatment, regular medical check-ups, mass treatment','Screening for cervical cancer, early treatment, immunisation','Immunisation, eating a balanced diet, regular exercise','D','Primary prevention acts before disease occurs: immunisation, eating a balanced diet and regular exercise prevent disease development; screening and early treatment are secondary prevention (Kenya community health/epidemiology; levels of prevention).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Community Health Nursing','Levels of Prevention','Primary disease prevention involves:','Immunisation, screening for cervical cancer, good nutrition','Early treatment, regular medical check-ups, mass treatment','Screening for cervical cancer, early treatment, immunisation','Immunisation, eating a balanced diet, regular exercise','D','Leavell and Clark''s levels: primary (health promotion + specific protection), secondary (early diagnosis + prompt treatment), tertiary (disability limitation + rehabilitation). BScN nurses design programmes at each level (Park''s; community health nursing; Kenya KEPH).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Vulnerability analysis — mitigation phase ────────────────────────────────
-- Per §12: Community Health → Paper II both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Community Health Nursing','Disaster Management','Vulnerability analysis comes in which part of the disaster management cycle?','Mitigation','Recovery','Preparedness','Response','A','Vulnerability/risk analysis is conducted during the mitigation phase to identify risks and implement measures to reduce their likelihood or impact before a disaster event (Kenya disaster management/community health texts).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Community Health Nursing','Disaster Management','Vulnerability analysis comes in which part of the disaster management cycle?','Mitigation','Recovery','Preparedness','Response','A','Mitigation phase tools include hazard mapping, vulnerability assessment and risk reduction strategies; BScN nurses use community health assessments to identify at-risk populations (Kenya NDM framework; community health nursing).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Measles vaccine wastage factor — 1/2 ─────────────────────────────────────
-- Per §12: Community Health → Paper II both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Community Health Nursing','Immunisation','The wastage factor for measles vaccine is:','1/5','1/3','1/2','1/4','C','Measles is a lyophilised multi-dose vaccine reconstituted in small volumes with a high wastage allowance of 50% (wastage factor = 1/2) under Kenya EPI vaccine management and quantification guidelines (Kenya EPI; MOH Kenya cold-chain guidelines).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Community Health Nursing','Immunisation','The wastage factor for measles vaccine is:','1/5','1/3','1/2','1/4','C','Wastage factor is used in vaccine quantification: doses needed = target population × coverage ÷ (1 – wastage factor). BScN nurses apply EPI logistics principles in supply chain management and forecasting for outreach sessions (Kenya EPI; MOH Kenya cold-chain guidelines).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Cognitive domain — acquisition of facts, concepts, principles ────────────
-- Per §12: Management/Education → Paper II both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Health Systems & Management','Nursing Education','The learning domain concerned with acquisition of facts, concepts and principles is:','Affective','Cognitive','Evaluative','Psychomotor','B','Bloom''s taxonomy: the cognitive domain covers knowledge acquisition — facts, concepts, principles and their application; the affective domain covers attitudes and values; psychomotor covers skills (Bloom''s taxonomy; nursing education curriculum).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Nursing Management & Leadership','Nursing Education','The learning domain concerned with acquisition of facts, concepts and principles is:','Affective','Cognitive','Evaluative','Psychomotor','B','Bloom''s revised taxonomy: cognitive domain levels — remember, understand, apply, analyse, evaluate, create. BScN nurses align learning objectives to the correct domain when designing in-service training and patient education (Bloom''s taxonomy; nursing education).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Research methodology — study population, design, sampling ────────────────
-- Per §12: Research → Paper II both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Research & Statistics','Research Methodology','Information in the research methodology chapter includes:','Research design, study population, justification of study','Formulating hypothesis, sampling, study design','Study population, research design, analysis of data','Study population, research design, sampling','D','The research methodology chapter comprises the research design, study population and sampling procedure; the justification belongs in the introduction/statement of the problem (Polit & Beck; nursing research methods).','hard',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Research & Evidence-Based Practice','Research Methodology','Information in the research methodology chapter includes:','Research design, study population, justification of study','Formulating hypothesis, sampling, study design','Study population, research design, analysis of data','Study population, research design, sampling','D','Methodology chapter = design + population + sampling + data collection + analysis plan. Justification/rationale belongs in Chapter 1. BScN nurses write and critically appraise methodology sections in clinical audits and research proposals (Polit & Beck; nursing research).','hard',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Occupational health objective — promote highest degree of health ───────────
-- Per §12: Community Health → Paper II both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Community Health Nursing','Occupational Health','The main objective of an occupational health programme is:','To prevent health problems due to normal working conditions','To promote and maintain the highest degree of physical, mental and social health of workers','To assist the injured and disabled for rehabilitation and treatment','To protect workers from factors adverse to their health','B','WHO/ILO define the main objective of occupational health as promoting and maintaining the highest degree of physical, mental and social well-being of workers in all occupations (community health/occupational health texts; Kenya OSH Act).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Community Health Nursing','Occupational Health','The main objective of an occupational health programme is:','To prevent health problems due to normal working conditions','To promote and maintain the highest degree of physical, mental and social health of workers','To assist the injured and disabled for rehabilitation and treatment','To protect workers from factors adverse to their health','B','WHO/ILO 1950 joint committee definition covers promotion, protection and placement — a comprehensive mandate. BScN occupational health nurses design programmes spanning primary, secondary and tertiary prevention for workplace populations (Kenya OSH Act; occupational health texts).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Neuroleptics — major tranquillisers blocking dopamine ────────────────────
-- Per §12: Pharmacology → Paper I both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','CNS Pharmacology','Neuroleptics are:','Minor tranquillisers with mild calming effects on neurotic patients','Major tranquillisers which block dopamine receptors producing calming effects','Mood stabilisers that elevate mood of a depressed patient','Antidepressants','B','Neuroleptics (antipsychotics) are major tranquillisers that block dopamine D2 receptors in the mesolimbic system, reducing psychotic symptoms and producing a calming effect (BNF; Brunner & Suddarth pharmacology).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','CNS Pharmacology','Neuroleptics are:','Minor tranquillisers with mild calming effects on neurotic patients','Major tranquillisers which block dopamine receptors producing calming effects','Mood stabilisers that elevate mood of a depressed patient','Antidepressants','B','Neuroleptics block D2 receptors; atypicals also block 5-HT2A. Adverse effects: EPSEs, metabolic syndrome, NMS. BScN nurses monitor AIMS, fasting glucose, lipids and weight in patients on long-term antipsychotics (BNF; psychiatric nursing pharmacology).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── GI decompression — nasogastric tube to remove gas and fluid ──────────────
-- Per §12: Medical-Surgical Nursing → Paper I both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Gastrointestinal Procedures','Gastrointestinal decompression involves:','Gastrostomy tube suction to remove abdominal content','Insertion of a tube in the ileocaecal valve','Insertion of a trocar in the abdominal cavity','Insertion of a nasogastric tube to remove gas and fluid','D','Gastrointestinal decompression is the insertion of a nasogastric or intestinal tube to remove accumulated gas and fluid from the GI tract, relieving distension and obstruction (Brunner & Suddarth Medical-Surgical Nursing).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Gastrointestinal Procedures','Gastrointestinal decompression involves:','Gastrostomy tube suction to remove abdominal content','Insertion of a tube in the ileocaecal valve','Insertion of a trocar in the abdominal cavity','Insertion of a nasogastric tube to remove gas and fluid','D','NG decompression indications: paralytic ileus, bowel obstruction, post-operative abdominal surgery. BScN nurses verify placement, maintain patency, record drainage and monitor for complications of prolonged tube use (Brunner & Suddarth; surgical nursing).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Benztropine — for EPS from antipsychotic toxicity ────────────────────────
-- Per §12: Pharmacology → Paper I both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','CNS Pharmacology','A schizophrenic patient has been treated with haloperidol, loxapine, thiothixene and lithium and shows signs of poisoning. What should be tried?','Benztropine','Molindone','Clozapine','Trifluoperazine','A','Haloperidol, loxapine and thiothixene are typical antipsychotics causing extrapyramidal/dystonic reactions in overdose; benztropine is the anticholinergic drug of choice to reverse these EPSEs (BNF; Brunner & Suddarth pharmacology).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','CNS Pharmacology','A schizophrenic patient has been treated with haloperidol, loxapine, thiothixene and lithium and shows signs of poisoning. What should be tried?','Benztropine','Molindone','Clozapine','Trifluoperazine','A','Benztropine (anticholinergic) reverses acute dystonia and drug-induced parkinsonism from typical antipsychotics; IV/IM route for acute reactions. BScN nurses assess for NMS separately (fever + rigidity + autonomic instability) which requires different management (BNF; psychiatric nursing).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Directing patients — ensures smooth client flow ───────────────────────────
-- Per §12: Management → Paper II both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Health Systems & Management','Nursing Management','The following is a factor that ensures a smooth flow of clients in a health centre:','Soothing patients','Directing patients','Timely payments','Observing punctuality','B','Directing/guiding patients to the appropriate service points in the correct sequence ensures an orderly, smooth client flow through the health facility, reducing waiting times and improving patient experience (nursing management texts; MOH Kenya facility management).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Nursing Management & Leadership','Nursing Management','The following is a factor that ensures a smooth flow of clients in a health centre:','Soothing patients','Directing patients','Timely payments','Observing punctuality','B','Patient flow management reduces bottlenecks; BScN nurses as charge nurses implement triage systems, signage, CHV coordination and lean principles to optimise client flow and patient safety (MOH Kenya quality improvement standards; nursing management texts).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Non-projected teaching aids — real objects, handouts, pictures ────────────
-- Per §12: Management/Education → Paper II both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Health Systems & Management','Nursing Education','Non-projected teaching aids include:','Diagrams, videos, slides','Slides, videos, pictures','Flipcharts, slides, pictures','Real objects, handouts, pictures','D','Non-projected teaching aids require no projector or power source: real objects, handouts, pictures, charts, flannel boards; slides, videos and films are projected aids (teaching/learning methods; nursing education curriculum).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Nursing Management & Leadership','Nursing Education','Non-projected teaching aids include:','Diagrams, videos, slides','Slides, videos, pictures','Flipcharts, slides, pictures','Real objects, handouts, pictures','D','Non-projected aids are ideal for low-resource community health education settings. BScN nurses select teaching aids based on audience literacy, group size, available resources and learning objectives (nursing education; MOH Kenya health education guidelines).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Mood-congruent psychosis — delusion of guilt, poverty, grandiosity ─────────
-- Per §12: Mental Health → Paper II both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Mental Health Nursing','Mood Disorders','The following are mood-congruent psychotic features in a depressed patient:','Delusion of murder, erotomania, delusion of guilt','Delusion of guilt, delusion of poverty, erotomania','Delusion of guilt, delusion of poverty, delusion of grandiosity','Delusion of persecution, delusion of grandiosity, delusion of guilt','C','Mood-congruent psychotic features in depression carry depressive themes — delusions of guilt (unworthiness) and poverty are congruent with depressed mood; delusion of grandiosity is atypically listed here as the source document intended the group of depressive-themed delusions (DSM-5; psychiatric nursing texts).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Mental Health Nursing','Mood Disorders','The following are mood-congruent psychotic features in a depressed patient:','Delusion of murder, erotomania, delusion of guilt','Delusion of guilt, delusion of poverty, erotomania','Delusion of guilt, delusion of poverty, delusion of grandiosity','Delusion of persecution, delusion of grandiosity, delusion of guilt','C','Mood-congruent vs mood-incongruent distinction guides prognosis and treatment; BScN nurses document psychotic features accurately in MSE and communicate findings during interdisciplinary rounds (DSM-5; Stuart Psychiatric Nursing).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Pre-op fear/anxiety — need for increased anaesthesia ─────────────────────
-- Per §12: Surgical Nursing → Paper I both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Surgical Nursing','Pre-operative Care','Pre-operative fear and anxiety can lead to:','Reduced need for psychological support','Need for increased anaesthesia','Increased speed of recovery','Need for reduced postoperative pain management','B','Preoperative fear and anxiety raise sympathetic activity and catecholamine levels, increasing anaesthetic requirements during surgery; this is well established in Brunner & Suddarth perioperative nursing.','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Surgical Nursing','Pre-operative Care','Pre-operative fear and anxiety can lead to:','Reduced need for psychological support','Need for increased anaesthesia','Increased speed of recovery','Need for reduced postoperative pain management','B','Preoperative psychological preparation (education, breathing exercises, therapeutic communication) reduces anxiety and anaesthetic requirements, improving outcomes. BScN nurses implement evidence-based preoperative anxiety interventions (Brunner & Suddarth; surgical nursing EBP).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Diabetic control before conception — reduces congenital anomalies ─────────
-- Per §12: Midwifery → Paper I both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Midwifery','Diabetes in Pregnancy','Diabetic control is important before conception to reduce the incidence of:','Diabetic ketoacidosis','Congenital anomalies','Maternal nephropathy','Maternal retinopathy','B','Pre-conception glycaemic control (HbA1c <53 mmol/mol) reduces the risk of congenital anomalies linked to first-trimester hyperglycaemia, particularly cardiac defects and neural tube defects (Myles; Kenya MOH diabetes-in-pregnancy guidelines).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Midwifery','Diabetes in Pregnancy','Diabetic control is important before conception to reduce the incidence of:','Diabetic ketoacidosis','Congenital anomalies','Maternal nephropathy','Maternal retinopathy','B','Organogenesis occurs in weeks 3–8 — before many women know they are pregnant; pre-conception HbA1c optimisation is the single most impactful intervention. BScN nurses lead pre-conception counselling for women with known diabetes (Myles; MOH Kenya diabetes-in-pregnancy guidelines).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Purpose of emergency assessment — establish client database ───────────────
-- Per §12: Management/Nursing Process → Paper II both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Health Systems & Management','Nursing Process','The purpose of emergency assessment is to:','Delegate nursing responsibility','Teach the client about their health','Make a diagnostic conclusion','Establish a database concerning the client','D','The purpose of the nursing assessment phase — including emergency assessment — is to systematically collect and organise data to establish a comprehensive database about the client, on which care planning is based (nursing process texts; Brunner & Suddarth).','hard',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Nursing Management & Leadership','Nursing Process','The purpose of emergency assessment is to:','Delegate nursing responsibility','Teach the client about their health','Make a diagnostic conclusion','Establish a database concerning the client','D','Assessment is the first step of the nursing process; the database drives diagnosis, planning, intervention and evaluation. BScN nurses use both subjective and objective data, including electronic health records, to build comprehensive client profiles (nursing process texts; Brunner & Suddarth).','hard',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Oligohydramnios — associated with polycystic kidney ─────────────────────
-- Per §12: Midwifery → Paper I both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Midwifery','Antenatal Complications','Oligohydramnios is associated with:','Hydrocephalus','Omphalocele','Sacral agenesis','Polycystic kidney disease','D','Oligohydramnios results from reduced fetal urine output, most commonly associated with fetal renal anomalies such as polycystic/dysplastic kidneys and renal agenesis (Potter sequence) (Myles Textbook for Midwives; obstetric texts).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Midwifery','Antenatal Complications','Oligohydramnios is associated with:','Hydrocephalus','Omphalocele','Sacral agenesis','Polycystic kidney disease','D','Oligohydramnios: AFI <5 cm or deepest pocket <2 cm on USS. Causes: renal agenesis/dysplasia, PPROM, post-dates, IUGR. BScN nurses recognise USS findings and coordinate obstetric management (Myles; MOH Kenya ANC guidelines).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Eustachian tube — causes middle ear fluid accumulation if blocked ─────────
-- Per §12: Medical-Surgical Nursing → Paper I both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','ENT Disorders','A patient with repeated colds and ear infections has fluid accumulation in the middle ear due to blockage of the:','Utricle','Saccule','Eustachian tube','External ear','C','Blockage of the Eustachian tube prevents middle ear drainage and ventilation, causing fluid accumulation (glue ear/otitis media with effusion) — a common complication of recurrent upper respiratory tract infections (Brunner & Suddarth; ENT nursing).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','ENT Disorders','A patient with repeated colds and ear infections has fluid accumulation in the middle ear due to blockage of the:','Utricle','Saccule','Eustachian tube','External ear','C','Eustachian tube dysfunction impairs pressure equalisation; chronic otitis media with effusion causes conductive hearing loss. BScN nurses assess hearing, refer for audiometry and educate on nasal decongestants and follow-up (Brunner & Suddarth; ENT nursing EBP).','easy',2021,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;
