-- =============================================================================
-- SEED: NCK Paper 3 & Paper 4 Questions — Batch A
-- =============================================================================
-- Sources: NCK-Paper4-MCQs-with-Rationales.docx (Section A BScN Aug 2016,
--          Section B KRCHN Jul 2014, Section C Sets 1-3)
--          NCK-Paper3-MCQs-with-Rationales.docx (Section A KRCHN 2011/2012/2014)
-- Cadre assignment: per nck-exam-system.md criteria (not source labelling alone)
-- Paper assignment: per nck-exam-system.md Section 12 (Roman numerals)
-- All: status = 'approved', contributor_id = NULL (platform-owned)
-- =============================================================================

-- =============================================================================
-- PART 1: BScN Paper 4 Aug 2016 — Nursing Management, Ethics, Mental Health
-- All BScN Paper II (Community/Public Health + Research + Leadership + Mental Health)
-- =============================================================================

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('BScN', 'Professional Ethics & Law', 'Nursing Regulation',
 'The primary purpose for regulating nursing practice is to protect:',
 'The public',
 'Practicing nurses',
 'The employing agency',
 'Professional standards',
 'A',
 'Per the Nurses Act (Cap 257, Kenya) and the Nursing Council of Kenya Act, the PRIMARY purpose of nursing practice regulation is to PROTECT THE PUBLIC from unsafe or incompetent practice. NCK does this by setting standards for nursing education, licensing qualified nurses, defining scope of practice, investigating misconduct, and requiring mandatory CPD. Protection of practising nurses, employers and professional standards are secondary benefits, but the fundamental public-policy reason for regulating a profession is PUBLIC SAFETY.',
 'easy', 'approved', 2016, 'Paper II'),

('BScN', 'Research & Evidence-Based Practice', 'Nursing Process',
 'To utilise the nursing process, the nurse must first:',
 'Identify goals for nursing care',
 'State the client''s nursing needs',
 'Obtain information about the client',
 'Evaluate the effectiveness of nursing actions',
 'C',
 'The NURSING PROCESS (ADPIE) has 5 sequential phases: (1) ASSESSMENT — OBTAIN INFORMATION about the client through history, physical examination, observation, and review of records — option C. This is the foundation of the entire process. (2) DIAGNOSIS — analyse data to formulate nursing diagnoses; (3) PLANNING — set goals/outcomes (option A) and select interventions; (4) IMPLEMENTATION — carry out the plan; (5) EVALUATION — judge effectiveness against goals (option D). Each phase depends on the preceding one; assessment must always come first.',
 'easy', 'approved', 2016, 'Paper II'),

('BScN', 'Nursing Management & Leadership', 'Leadership Styles',
 'Transformational leadership:',
 'Focuses on effecting revolutionary change in the organisation',
 'Values collaborations, teamwork and interpersonal skills',
 'Ensures that individuals share the responsibility for achieving organisational goals',
 'Originates from a desire to serve',
 'A',
 'TRANSFORMATIONAL leadership (Bass/Burns) — the leader INSPIRES followers to transcend self-interest for the good of the organisation, creating REVOLUTIONARY/visionary CHANGE through the 4 I''s: Idealised influence (charisma), Inspirational motivation, Intellectual stimulation, Individualised consideration. Distinct from: TRANSACTIONAL (rewards/punishments); SERVANT leadership (originates from desire to serve — option D, Greenleaf); TEAM/PARTICIPATIVE (options B, C). Option A captures the transformative essence.',
 'medium', 'approved', 2016, 'Paper II'),

('BScN', 'Nursing Management & Leadership', 'Management Theory',
 'The following is an element of classical management theory:',
 'Hawthorne effect',
 'Chain of command',
 'Through put',
 'Ebbing effect',
 'B',
 'CLASSICAL MANAGEMENT THEORY (Taylor, Fayol, Weber) emphasises: scientific management, administrative management (Fayol''s 14 principles), and bureaucracy. Key features: HIERARCHY, CHAIN OF COMMAND (option B), unity of command, division of labour, formal rules, span of control, formal authority. HAWTHORNE EFFECT (option A) is from the HUMAN RELATIONS school (Mayo, 1920s). THROUGH-PUT is a systems theory concept. "Ebbing effect" is not a recognised management term.',
 'medium', 'approved', 2016, 'Paper II'),

('BScN', 'Nursing Management & Leadership', 'Management Functions',
 'The following is a reason for planning in management:',
 'To establish a hierarchy in the organisation',
 'To provide adequate and appropriate personnel',
 'To motivate staff',
 'To focus attention on objectives',
 'D',
 'PURPOSES OF PLANNING in management: (1) FOCUSES ATTENTION ON OBJECTIVES (option D) — directs all efforts toward agreed goals; (2) reduces uncertainty by anticipating the future; (3) ensures economical use of resources; (4) facilitates control; (5) promotes innovation. Hierarchy (option A) is established by ORGANISING; personnel provision (option B) is STAFFING; motivating staff (option C) is DIRECTING/LEADING. These are separate management functions.',
 'easy', 'approved', 2016, 'Paper II');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('BScN', 'Professional Ethics & Law', 'Informed Consent',
 'In relation to obtaining informed consent from a seventeen-year-old adolescent, the nurse should remember that the adolescent:',
 'Does not have the legal capacity to give consent',
 'Is not able to make an acceptable or intelligent choice',
 'Is able to give voluntary consent when parents are not available',
 'Will most likely be unable to choose between alternatives when asked to consent',
 'A',
 'Per Kenyan law (Children Act 2022 and Constitution), a MINOR is anyone under 18 years. A 17-year-old does NOT have full legal capacity to give independent consent for medical treatment — parent/legal guardian must consent (with the minor''s ASSENT). EXCEPTIONS: HIV testing and counselling (12+ years can consent independently per HIV/AIDS Prevention and Control Act 2006); family planning services to sexually active minors; emergencies. Option A reflects the legal default position.',
 'medium', 'approved', 2016, 'Paper II'),

('BScN', 'Research & Evidence-Based Practice', 'Learning Theories',
 'The personality theory suggesting that behaviour and learning occurs through imitation is:',
 'Humanistic',
 'Psychoanalytic',
 'Cognitive',
 'Social-learning',
 'D',
 'SOCIAL-LEARNING theory (Bandura) — behaviour is LEARNED through OBSERVATION AND IMITATION of MODELS (parents, peers, media) — classic Bobo doll experiment. Includes vicarious learning and self-efficacy. HUMANISTIC (Maslow, Rogers) — self-actualisation, personal growth. PSYCHOANALYTIC (Freud) — unconscious mind, id/ego/superego. COGNITIVE (Piaget, Beck) — mental processes, schemas. Option D — social-learning — is specifically defined by imitation.',
 'medium', 'approved', 2016, 'Paper II'),

('BScN', 'Research & Evidence-Based Practice', 'Learning Theories',
 'The learning where we associate a certain behaviour with a specific outcome is:',
 'Contingent learning',
 'Operant conditioning',
 'Classical conditioning',
 'Observational learning',
 'B',
 'OPERANT CONDITIONING (Skinner) — behaviour MODIFIED by its CONSEQUENCES (REWARDS/REINFORCEMENT increase behaviour; punishment decreases). Voluntary behaviour-outcome association — option B. CLASSICAL CONDITIONING (Pavlov) — associating two STIMULI (involuntary, reflexive — e.g. Pavlov''s dogs salivating at bell). OBSERVATIONAL learning (Bandura) — through imitation. Operant is specifically the behaviour-outcome contingency learning.',
 'medium', 'approved', 2016, 'Paper II'),

('BScN', 'Research & Evidence-Based Practice', 'Learning Theories',
 'The humanistic theories of personality development emphasise:',
 'Wish-fulfillment',
 'Self-actualisation',
 'Ego ideal',
 'The unconscious mind',
 'B',
 'HUMANISTIC theories (Maslow, Rogers): emphasise CONSCIOUS experience, FREE WILL, personal growth, and SELF-ACTUALISATION (realising one''s full potential — option B). MASLOW''S HIERARCHY OF NEEDS: physiological → safety → love/belonging → esteem → self-actualisation. ROGERS — unconditional positive regard, congruence between real and ideal self. WISH-FULFILLMENT, EGO IDEAL, UNCONSCIOUS MIND (options A, C, D) are PSYCHOANALYTIC (Freud) concepts.',
 'easy', 'approved', 2016, 'Paper II'),

('BScN', 'Nursing Management & Leadership', 'Teaching Objectives',
 'An appropriate behavioural objective for a teaching session is:',
 'After a teaching session, the client list five tools in the class of proteins',
 'After a teaching session, the client will have knowledge of foods in a class of proteins',
 'After a teaching session, the client will verbalise understanding of foods in the class of proteins',
 'After a teaching session the client will know which foods are proteineous',
 'C',
 'BEHAVIOURAL OBJECTIVES (Mager/Bloom) must contain: AUDIENCE, BEHAVIOUR (observable, measurable action verb — NOT "know", "understand", "appreciate"), CONDITION, and CRITERION. Acceptable verbs: list, describe, demonstrate, identify, verbalise. Option C — "verbalise understanding" uses an observable verb. Options B and D use "have knowledge" and "know" — not measurable. Option A has grammar issues ("tools" should be "examples").',
 'medium', 'approved', 2016, 'Paper II');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('BScN', 'Mental Health Nursing', 'Group Therapy',
 'When providing group therapy, the nurse must focus on:',
 'Jointly experienced stress',
 'Behaviour of individual members',
 'Confrontation between members',
 'Personal feelings affecting behaviour',
 'A',
 'GROUP THERAPY (Yalom''s curative factors) — the therapist focuses on the GROUP PROCESS and JOINTLY EXPERIENCED issues: universality ("we are not alone"), interpersonal learning, cohesion, altruism, catharsis, instillation of hope. The COMMON STRESS/EXPERIENCE shared by group members provides the basis for therapy — option A. Individual behaviour, confrontations and personal feelings are addressed but in the context of the GROUP dynamic.',
 'medium', 'approved', 2016, 'Paper II'),

('BScN', 'Mental Health Nursing', 'Therapeutic Modalities',
 'The most advantageous therapy for a preschool-aged child with a history of physical and sexual abuse would be:',
 'Play therapy',
 'Psychodrama',
 'Group therapy',
 'Family therapy',
 'A',
 'PLAY THERAPY (Axline, Landreth) is the BEST therapy for PRESCHOOL/younger children (developmentally under ~10 years) who lack verbal/cognitive maturity for talk therapy. Play is the child''s natural medium for expressing feelings and processing trauma. Used in abuse, parental separation, illness, behavioural problems. Materials: dolls, art, sand tray, puppets. Psychodrama suits older adolescents/adults; group therapy is generally not first-line for traumatised pre-schoolers.',
 'medium', 'approved', 2016, 'Paper II'),

('BScN', 'Mental Health Nursing', 'Schizophrenia',
 'The foremost aetiology of schizophrenia today is the:',
 'Biologic perspective',
 'Seasonal perspective',
 'Immunologic perspective',
 'Psychoanalytic perspective',
 'A',
 'Current understanding of SCHIZOPHRENIA aetiology is predominantly BIOLOGICAL: (1) GENETIC — strong heritability (~80%), polygenic; (2) DOPAMINE HYPOTHESIS (excess mesolimbic dopamine → positive symptoms; deficient mesocortical → negative symptoms), glutamate (NMDA hypofunction), serotonin; (3) STRUCTURAL brain changes — enlarged ventricles, reduced cortical/hippocampal volume; (4) Neurodevelopmental — perinatal complications, prenatal infections. Psychoanalytic theories (option D) of "schizophrenogenic mother" are LONG DISCREDITED.',
 'medium', 'approved', 2016, 'Paper II'),

('BScN', 'Mental Health Nursing', 'Substance Use',
 'When dealing with addiction, the word "drug" means:',
 'An illegal substance that activates the pleasure centre in the brain',
 'A substance that activates the pleasure centre in the brain',
 'A chemical that produces a pharmacological action when ingested',
 'Any kind of pill that is broken down in the stomach by digestive action',
 'B',
 'In the context of ADDICTION, a "drug" = any SUBSTANCE (legal OR illegal) that ACTIVATES THE BRAIN''S REWARD/PLEASURE CENTRE (mesolimbic dopamine pathway, particularly nucleus accumbens). Includes ILLICIT drugs (cocaine, heroin), PRESCRIPTION drugs (opioids, benzodiazepines), LEGAL substances (alcohol, nicotine, caffeine). Option A restricts to illegal — incorrect (alcohol/nicotine are legal but highly addictive). Option B is the broadest, most accurate definition for addiction.',
 'medium', 'approved', 2016, 'Paper II'),

('BScN', 'Mental Health Nursing', 'Anxiety Disorders',
 'The nurse concludes that a client has agoraphobia after the client states a fear of the following:',
 'Spiders',
 'Being embarrassed in public',
 'Leaving home',
 'Losing control',
 'C',
 'PHOBIAS (DSM-5): SPECIFIC PHOBIA — fear of specific object/situation (spiders = arachnophobia — option A). SOCIAL ANXIETY DISORDER — fear of social situations and BEING EMBARRASSED/SCRUTINISED in public (option B). AGORAPHOBIA — fear of being in PLACES WHERE ESCAPE WOULD BE DIFFICULT or help unavailable in event of panic — leading to AVOIDANCE/being HOUSEBOUND (LEAVING HOME — option C). Often co-occurs with panic disorder. PANIC DISORDER — recurrent unexpected panic attacks with fear of losing control (option D).',
 'medium', 'approved', 2016, 'Paper II');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('BScN', 'Nursing Management & Leadership', 'Teaching Methods',
 'A disadvantage of simulation as an instructional method is:',
 'Allows the student to make their first serious mistake in a simulated situation rather than a real one',
 'Simulation techniques cannot model all dimensions of a real situation',
 'Simulations provide a responsive environment since feedback is given instantly',
 'There is a link between training situation and a real situation',
 'B',
 'SIMULATION as a teaching method has many ADVANTAGES: safe environment for skill practice, errors don''t harm patients (option A), instant feedback (option C), bridge between theory and practice (option D). DISADVANTAGE: simulations are SIMPLIFIED — they CANNOT model ALL DIMENSIONS of complex real clinical situations (psychological pressure of real patients, family dynamics, system failures, ethical dilemmas, unexpected complications) — option B. Also: expensive equipment, requires skilled facilitators.',
 'medium', 'approved', 2016, 'Paper II'),

('BScN', 'Nursing Management & Leadership', 'Curriculum Development',
 'The core factor which would influence the curriculum development process is:',
 'Natural calamities',
 'Political events',
 'Students'' unrests',
 'Teacher characteristics',
 'D',
 'CURRICULUM DEVELOPMENT factors: (1) PHILOSOPHY/values of institution; (2) LEARNERS — needs, characteristics, prior knowledge; (3) SOCIETY — workforce needs, cultural context; (4) DISCIPLINE/profession requirements; (5) ACCREDITATION standards (NCK requirements); (6) TEACHER/FACULTY CHARACTERISTICS — qualifications, experience, philosophical orientation, capacity (option D — core factor — teachers ARE the curriculum implementers); (7) RESOURCES. Natural calamities, political events, student unrest can DISRUPT curriculum delivery but are not "core" factors in the development process.',
 'medium', 'approved', 2016, 'Paper II'),

('BScN', 'Nursing Management & Leadership', 'Bloom''s Taxonomy',
 'An education objective that requires learners to internalise complex values is classified under:',
 'Cognitive domain',
 'Value system domain',
 'Affective domain',
 'Psychomotor domain',
 'C',
 'BLOOM''S TAXONOMY — 3 domains: COGNITIVE (knowledge, comprehension, application, analysis, synthesis, evaluation — thinking/intellectual); PSYCHOMOTOR (physical skills); AFFECTIVE (receiving, responding, VALUING, ORGANISING values, CHARACTERISATION BY value/value system — emotions, attitudes, VALUES). INTERNALISATION of complex values falls under AFFECTIVE domain — option C. "Value system domain" is not a separate Bloom''s domain — it is a LEVEL within the affective domain.',
 'easy', 'approved', 2016, 'Paper II'),

('BScN', 'Nursing Management & Leadership', 'Teaching Methods',
 'Discovery learning approach:',
 'Is more effective than expounding the principles then engaging the students in learning',
 'Takes less time than exposition learning approach',
 'Helps students attain higher level (life skills) or methodological objectives as opposed to passive learners',
 'Is best applied when students need to grasp a few basic concepts',
 'C',
 'DISCOVERY LEARNING (Bruner) — students LEARN BY DISCOVERING for themselves through exploration, experimentation, problem-solving — INDUCTIVE approach. Builds HIGHER-ORDER skills (analytical thinking, problem-solving, lifelong learning, life skills, methodological skills) — option C. DISADVANTAGES: takes MORE TIME than expository teaching (option B wrong); may be confusing for novice learners; not ideal for basic concepts (option D wrong). Not universally "more effective" (option A too strong) — depends on learner readiness and content.',
 'medium', 'approved', 2016, 'Paper II'),

('BScN', 'Nursing Management & Leadership', 'Teaching Methods',
 'Problem-based learning means:',
 'Learning that results from working towards resolution of a problem',
 'Situation where students learn without any assistance from the teacher',
 'Learning that results after the learner gets the solution',
 'Learning where teachers use questions only',
 'A',
 'PROBLEM-BASED LEARNING (PBL — originated at McMaster University 1969) — students LEARN AS THEY WORK TOWARD THE RESOLUTION OF A REAL OR SIMULATED PROBLEM (option A). PROCESS: present trigger problem/case; students identify learning needs; self-directed study; return to discuss findings; apply to problem. TEACHER is FACILITATOR/tutor (not absent — option B wrong, and not only questioning — option D too narrow). Learning happens THROUGHOUT the process, not only after solution (option C wrong).',
 'medium', 'approved', 2016, 'Paper II');

-- =============================================================================
-- PART 2: KRCHN Paper 4 Jul 2014 — Mental Health, Paediatric, Research
-- =============================================================================

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Mental Health Nursing', 'Lithium Toxicity',
 'The initial symptoms of lithium toxicity include:',
 'Tremors, shuffling gait, and rigidity',
 'Stiff neck, occipital headache and increased blood pressure',
 'Ataxia, blurred vision and severe nausea',
 'Fever, sore throat and cardiac arrhythmias',
 'C',
 'LITHIUM has a NARROW THERAPEUTIC INDEX (0.6-1.2 mEq/L; toxic >1.5 mEq/L). EARLY/MILD TOXICITY (1.5-2.0 mEq/L): COARSE TREMOR, nausea/vomiting/diarrhoea, slurred speech, ATAXIA, BLURRED VISION, drowsiness, muscle weakness — option C. MODERATE (2.0-2.5): confusion, dysarthria, hyperreflexia, clonus, marked ataxia. SEVERE (>2.5): seizures, coma, cardiac arrhythmias, renal failure, death. Risk factors: dehydration, NSAIDs/thiazides/ACE-inhibitors (reduce renal clearance), low sodium. Treatment: stop lithium, IV fluids, dialysis if severe.',
 'medium', 'approved', 2014, 'Paper II'),

('KRCHN', 'Mental Health Nursing', 'Mania',
 'In acute mania a patient presents with:',
 'Cheerful and expansive mood',
 'Excessive psychomotor activity',
 'Increased motor activity',
 'Organised thought content and process',
 'B',
 'ACUTE MANIA (DSM-5) — distinct period of abnormally elevated/expansive/IRRITABLE mood + INCREASED ENERGY, with ≥3 of: inflated self-esteem/grandiosity, decreased need for sleep, pressured speech, flight of ideas/racing thoughts, distractibility, PSYCHOMOTOR AGITATION/EXCESSIVE ACTIVITY, excessive involvement in pleasurable risky activities. Mood is often LABILE (not just cheerful — can be irritable/hostile). Thought process is DISORGANISED (flight of ideas — NOT organised, option D wrong). EXCESSIVE psychomotor activity (option B) is more specific and characteristic than just "increased" motor activity (option C).',
 'medium', 'approved', 2014, 'Paper II'),

('KRCHN', 'Mental Health Nursing', 'Personality Disorders',
 'In narcissistic personality disorder there is a pervasive pattern of:',
 'Social discomfort, fear of negative evaluation and timidity',
 'Grandiosity, lack of empathy and hypersensitivity to evaluation by others',
 'Dependence and submissive behaviour beginning by early adulthood',
 'Indifference to social relationships and restricted range of emotional experience and expression',
 'B',
 'DSM-5 PERSONALITY DISORDERS (Cluster B — dramatic/erratic): NARCISSISTIC — pervasive pattern of GRANDIOSITY (in fantasy or behaviour), need for admiration, LACK OF EMPATHY, HYPERSENSITIVITY to criticism/evaluation, sense of entitlement, exploitative — option B. CLUSTER C: AVOIDANT (option A — social discomfort, fear of negative evaluation, timidity), DEPENDENT (option C — submissive, clinging). CLUSTER A: SCHIZOID (option D — detachment from social relationships, restricted emotion).',
 'medium', 'approved', 2014, 'Paper II'),

('KRCHN', 'Research & Statistics', 'Research Ethics',
 'Anonymity in research is aimed at:',
 'Preventing disclosure of privileged information',
 'Conferring protection to the source of information',
 'Selectively disclosing information to specific individuals',
 'Keeping names of respondents only known to the research supervisor',
 'B',
 'ANONYMITY = the researcher CANNOT LINK data back to the individual respondent — no identifying information collected or completely de-identified. PROTECTS the SOURCE/respondent from any consequence of their participation — option B. CONFIDENTIALITY = data may be identifiable but is protected from disclosure to others. Option D (names known to supervisor only) is closer to confidentiality, not anonymity. Both are pillars of research ethics under autonomy/respect for persons.',
 'easy', 'approved', 2014, 'Paper II'),

('KRCHN', 'Research & Statistics', 'Research Design',
 'The study design that is appropriate in observing the behaviour changes of drug addicts under rehabilitation is:',
 'Retrospective study design',
 'Longitudinal design',
 'Prospective study design',
 'Cross-sectional design',
 'B',
 'LONGITUDINAL design tracks SAME subjects OVER TIME — ideal for tracking CHANGES over the rehabilitation period (option B). PROSPECTIVE is similar but emphasises forward direction. CROSS-SECTIONAL = snapshot at one point in time — cannot show changes. RETROSPECTIVE = look back at past records. For tracking change over time during rehabilitation, longitudinal is the best fit.',
 'medium', 'approved', 2014, 'Paper II');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Paediatric Nursing', 'Neonatal Seizures',
 'A convulsing one-month-old infant should be given:',
 'Phenobarbitone 20 mg/kg IM stat',
 'Diazepam 0.3 mg/kg IV over 1 minute',
 'Phenobarbitone 5 mg/kg IM stat',
 'Diazepam 1 mg/kg per rectal stat',
 'B',
 'Per Kenya Basic Paediatric Protocols for ACUTE seizure management in infants: IMMEDIATE — protect airway, position safely, oxygen, check glucose (give 10% dextrose 2 mL/kg if hypoglycaemic), IV access. FIRST-LINE anticonvulsant: DIAZEPAM 0.3 MG/KG IV SLOW (over 1-2 minutes) — option B — or rectally 0.5 mg/kg if no IV access. May repeat after 10 minutes. If seizure persists: PHENOBARBITONE 15-20 MG/KG IV/IM loading dose (NOT 5 mg/kg). The question specifies one-month-old (past neonatal period) — diazepam is appropriate first-line.',
 'hard', 'approved', 2014, 'Paper I'),

('KRCHN', 'Paediatric Nursing', 'Dehydration in Malnutrition',
 'The immediate management for severe dehydration in a child with severe malnutrition according to IMCI strategy includes:',
 'Infusion of half-strength Darrow''s in 5% dextrose 15 mL/kg IV in 1 hour',
 'Infusion of 0.9% normal saline 20 mL/kg in 1 hour',
 'Transfusion of whole blood 40 mL/kg over 3 hours as soon as it is available',
 'NGT feeding with Resomal 15 mL/kg/hr for 10 hours',
 'A',
 'Severe dehydration in a child with SEVERE ACUTE MALNUTRITION (SAM) is managed DIFFERENTLY from non-malnourished children — rapid rehydration can precipitate heart failure. Per Kenya MoH Basic Paediatric Protocols/IMNCI/WHO: IF SHOCK (or unable to drink): IV HALF-STRENGTH DARROW''S in 5% DEXTROSE (or Ringer''s lactate + 5% dextrose) 15 mL/kg over 1 HOUR — option A — then reassess. Avoid plain saline at full rate (option B — risk of heart failure in SAM). Oral ReSoMal is first-line if child can drink. Monitor closely for fluid overload.',
 'hard', 'approved', 2014, 'Paper I'),

('KRCHN', 'Paediatric Nursing', 'Paediatric CPR',
 'The ratio of infant chest compressions to ventilation where 2 rescuers are involved is:',
 '30:2',
 '30:1',
 '15:2',
 '15:1',
 'C',
 'PAEDIATRIC CPR ratios (per AHA/ERC guidelines for infants and children up to puberty): SINGLE RESCUER — 30 COMPRESSIONS : 2 VENTILATIONS (same as adults). TWO HEALTHCARE PROVIDERS — 15 COMPRESSIONS : 2 VENTILATIONS — option C — used for both INFANTS and CHILDREN. Note: this differs from NEONATAL RESUSCITATION (immediately after birth) which uses 3:1 ratio (90 compressions + 30 breaths per minute). Compression rate is 100-120/min, depth 1/3 of AP chest diameter. Two-thumb technique for infants when 2 rescuers.',
 'medium', 'approved', 2014, 'Paper I'),

('KRCHN', 'Paediatric Nursing', 'Bone Marrow Aspiration',
 'Which of the following is correct? (a) The iliac crest is the site of choice for bone marrow aspiration in a 5-year-old child. (b) Acute renal failure is the leading complication associated with acute glomerulonephritis.',
 'Both (a) TRUE and (b) TRUE',
 'Both (a) FALSE and (b) FALSE',
 '(a) TRUE and (b) FALSE',
 '(a) FALSE and (b) TRUE',
 'C',
 '(a) TRUE — for CHILDREN over ~1 year, the POSTERIOR ILIAC CREST (posterior superior iliac spine, PSIS) is the PREFERRED SITE for bone marrow aspiration — easy access, generous marrow, fewer complications. For infants <1 year, the proximal tibia is often used. Sternum is the site for adults but AVOIDED in children. (b) FALSE — the leading complication of ACUTE POST-STREPTOCOCCAL GLOMERULONEPHRITIS (APSGN) is HYPERTENSIVE ENCEPHALOPATHY and HEART FAILURE due to volume overload, NOT acute renal failure. AKI can occur but is less common than cardiovascular complications.',
 'hard', 'approved', 2014, 'Paper I'),

('KRCHN', 'Maternal & Child Health', 'Immunisation',
 'Haemophilus influenzae type B (Hib) vaccine is given to protect against:',
 'Diphtheria and whooping cough',
 'Hepatitis B and whooping cough',
 'Hepatitis B and meningitis',
 'Meningitis and pneumonia',
 'D',
 'HAEMOPHILUS INFLUENZAE TYPE B (Hib) — gram-negative bacterium causing severe invasive disease in children, especially <5 years: MENINGITIS (commonest serious manifestation pre-vaccine), PNEUMONIA, epiglottitis, septic arthritis, septicaemia, cellulitis, pericarditis. So Hib vaccine protects against MENINGITIS AND PNEUMONIA (option D) — also epiglottitis. Given in Kenya as part of PENTAVALENT VACCINE (DPT-HepB-Hib) at 6, 10 and 14 weeks. Since introduction, Hib disease has fallen >95% globally.',
 'easy', 'approved', 2014, 'Paper I');

-- =============================================================================
-- PART 3: Paper 4 Section C — Uncategorised Sets 1 & 2
-- Set 1: KRCHN Paper II (Community Health, Research, Environmental Health)
-- Set 2: KRCHN Paper I & II (mixed clinical and community)
-- =============================================================================

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Community Health Nursing', 'Home-Based Care',
 'The components of home-based care include:',
 'Networking, social support, referral',
 'Clinical care, nursing care, social support',
 'Referral, nursing care, clinical care',
 'Social mobilisation, counselling, nursing care',
 'B',
 'HOME-BASED CARE (HBC) per Kenya MoH guidelines — CORE COMPONENTS: (1) CLINICAL CARE — medical management, symptom relief, palliative care, treatment monitoring; (2) NURSING CARE — wound care, hygiene, positioning, feeding; (3) PSYCHOSOCIAL/SOCIAL SUPPORT — counselling, family support, spiritual care, livelihood; (4) Referrals/linkages to formal health services. Option B — clinical + nursing + social support — captures three of these pillars. HBC team: patient, family caregiver, CHW, nurse, doctor, counsellor, social worker.',
 'easy', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Home Visiting',
 'The main reason for carrying out a home visit is to:',
 'Meet the family at home and tell them how to solve their health problems',
 'Assess social economic status and educational level of the family',
 'Assess family structure and their health behaviour',
 'Establish a working relationship with the family',
 'C',
 'The MAIN PURPOSE of home visiting in community health nursing is to ASSESS THE FAMILY IN THEIR NATURAL ENVIRONMENT — observing family structure, health behaviours, environment, resources, hygiene practices — option C. This enables individualised care planning. Other purposes: health education, continuity of care, follow-up of chronic patients, support for vulnerable groups. Establishing relationship (option D) is supportive but the OBJECTIVE is the assessment for care planning.',
 'easy', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Parasitology',
 'In taeniasis infection, the adult worm lives in the:',
 'Lungs',
 'Large intestines',
 'Small intestines',
 'Rectum',
 'C',
 'TAENIASIS — infection with adult tapeworm (T. saginata — beef tapeworm, up to 10m; T. solium — pork tapeworm, up to 5m). ADULT WORM lives in the HUMAN SMALL INTESTINES (typically jejunum/ileum) — option C — attached by scolex to mucosa, releasing proglottids/eggs in faeces. Most adults are asymptomatic carriers; mild abdominal discomfort, weight loss, malnutrition possible. CYSTICERCOSIS occurs when humans ingest T. solium EGGS — autoinfection or faecal-oral. Treatment: praziquantel or niclosamide single dose.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Health Systems & Management', 'Disaster Management',
 'The main goal of the Kenyan Government in disaster management is to:',
 'Increase community preparedness',
 'Take a leading role when disasters occur',
 'Minimise losses and disruptions to the population and economy',
 'Give early warning information on impending disasters',
 'C',
 'Per Kenya''s National Disaster Management Policy and the National Disaster Management Authority (NDMA), the overarching goal of disaster management is to MINIMISE THE LOSS OF LIFE, PROPERTY AND DISRUPTION to the population, economy and environment — through a CYCLE of prevention, mitigation, preparedness (option A), response (option B), recovery, and rehabilitation. Early warning (option D) is a tool within preparedness. Option C — minimising losses and disruptions — captures the OVERARCHING goal.',
 'easy', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Immunisation',
 'Babies of mothers on anti-TB treatment should not be immunised with BCG because:',
 'Anti-TB drugs can neutralise BCG vaccine administered',
 'The babies have low immunity which can make them develop tuberculosis',
 'They can develop massive drug resistance',
 'They are immune to TB due to maternal antibodies',
 'A',
 'BCG is a LIVE ATTENUATED bovine TB strain. If administered to a baby whose mother is on isoniazid/rifampicin (or whose baby is receiving INH preventive therapy), the anti-TB drugs WILL KILL/NEUTRALISE the live BCG organisms, preventing the desired immune response — option A. Approach: DELAY BCG until the infant has completed INH prophylaxis (3-6 months), then assess and give BCG if mother is TB-negative. The baby is NOT immune from maternal antibodies (option D wrong) — TB immunity is cell-mediated, not transferable transplacentally.',
 'medium', 'approved', NULL, 'Paper II');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Community Health Nursing', 'Community Mobilisation',
 'Community mobilisation is the process:',
 'In which the community is fully involved in identifying their problem and providing solutions',
 'Of raising awareness on specific issues among community members',
 'Of bringing members of the community together for the purpose of taking common action',
 'Of moving the community members from a risky environment to a less risky one',
 'A',
 'COMMUNITY MOBILISATION = a comprehensive process where the community is FULLY INVOLVED in: (1) IDENTIFYING THEIR OWN PROBLEMS (assessing needs); (2) prioritising; (3) PROVIDING SOLUTIONS (planning interventions); (4) implementing and (5) evaluating — option A captures this empowerment model. Option B is awareness-raising (a tool within mobilisation but narrower); option C is bringing together for common action (a step in mobilisation); option D misinterprets "mobilisation" literally as physical movement. The defining feature is COMMUNITY OWNERSHIP and full participation throughout.',
 'easy', 'approved', NULL, 'Paper II'),

('KRCHN', 'Research & Statistics', 'Research Design',
 'An example of an intervention study design is:',
 'Quasi-experiment',
 'Evaluative study',
 'Exploratory study',
 'Descriptive study',
 'A',
 'STUDY DESIGNS by type: OBSERVATIONAL — researcher OBSERVES without intervening (cross-sectional, case-control, cohort); INTERVENTIONAL/EXPERIMENTAL — researcher INTRODUCES AN INTERVENTION: TRUE EXPERIMENT/RCT (with randomisation and control); QUASI-EXPERIMENT — has intervention and (often) control group but NO RANDOMISATION — option A. QUASI-EXPERIMENTAL examples: non-equivalent control group, interrupted time series, before-after with control. Useful when randomisation is unethical/impractical. EXPLORATORY, DESCRIPTIVE, EVALUATIVE are research PURPOSES, not specifically interventional designs.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Research & Statistics', 'Sampling',
 'In longitudinal research, a cohort can be defined as a sample:',
 'Chosen by certain criteria and followed up for a specified period',
 'With shared characteristics like age or date of birth',
 'Chosen after an event',
 'Representative of the whole population',
 'B',
 'COHORT (epidemiology) = a GROUP OF PEOPLE WHO SHARE A COMMON CHARACTERISTIC OR EXPERIENCE within a defined time period — typically BIRTH COHORT (same year of birth), exposure cohort, occupational cohort, disease cohort. Option B captures the defining feature — SHARED CHARACTERISTICS. Cohort STUDY = follow-up of such a group over time to determine incidence of outcomes. Option A describes follow-up of a sample but doesn''t capture the SHARED CHARACTERISTIC essence.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Research & Statistics', 'Research Methodology',
 'Descriptive research:',
 'Refers to the direct study of people in their natural everyday settings',
 'Systematically investigates relations between two or more variables of interest',
 'Involves observation for a specific purpose to test cause and effect relation between variables',
 'Involves collection of data that will provide an account of individuals, groups or situations',
 'D',
 'DESCRIPTIVE research = systematically COLLECTING and ORGANISING DATA to provide a detailed ACCOUNT/PICTURE of individuals, groups, situations or phenomena — answers "WHAT IS" rather than "WHY" — option D. Examples: prevalence surveys, KAP studies, case studies, situation analyses. Distinct from: ANALYTICAL/EXPLANATORY research (options B/C — examines RELATIONSHIPS and CAUSATION); ETHNOGRAPHIC research (option A — naturalistic study in cultural settings). Descriptive is foundational — basis for further analytical work.',
 'easy', 'approved', NULL, 'Paper II'),

('KRCHN', 'Research & Statistics', 'Variables',
 'A measurable characteristic that assumes different values among subjects is referred to as:',
 'Operational definition',
 'Variable',
 'Parameters',
 'Study unit',
 'B',
 'VARIABLE = a CHARACTERISTIC that can take DIFFERENT VALUES across subjects/observations (height, age, blood pressure, disease status, sex). Types: INDEPENDENT (manipulated/exposure); DEPENDENT (outcome measured); CONFOUNDING (associated with both IV and DV — distorts relationship); EXTRANEOUS; MODERATING; mediator. OPERATIONAL DEFINITION = how a variable is measured in a specific study (option A, different concept). PARAMETER = population value (vs statistic = sample). STUDY UNIT = the individual subject/element studied.',
 'easy', 'approved', NULL, 'Paper II');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Research & Statistics', 'Data Collection',
 'The following is true concerning observation as a research method:',
 'It takes less time than self-report approaches',
 'It costs less money than self-report approaches',
 'It is often not possible to determine exactly why the people behave as they do',
 'All of the above',
 'C',
 'OBSERVATION as a research method — advantages: direct, no recall bias, captures non-verbal behaviour, natural setting, suitable for those who cannot self-report. DISADVANTAGES: (1) MORE time-consuming and EXPENSIVE than self-report surveys (options A, B WRONG — observation typically MORE time/money intensive); (2) OBSERVATION captures WHAT people do but NOT WHY (the underlying motivation, beliefs, emotions) — option C TRUE; (3) Hawthorne effect; (4) observer bias; (5) ethical issues with concealed observation. Option C is the true statement; D is wrong because A and B are false.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Research & Statistics', 'Questionnaire Design',
 'When constructing a questionnaire one should:',
 'Use leading or loaded questions',
 'Use double-barrelled questions',
 'Use double negatives',
 'Use multiple items to measure a single construct',
 'D',
 'QUESTIONNAIRE DESIGN — what to AVOID: LEADING/loaded questions (suggest desired answer — option A — AVOID); DOUBLE-BARRELLED questions (asking 2 things in 1 — option B — AVOID); double negatives (confusing — option C — AVOID); ambiguous terms; jargon. RECOMMENDED: clear simple language; one idea per question; balanced response options; USE MULTIPLE ITEMS TO MEASURE A SINGLE CONSTRUCT (option D — TRUE) — improves reliability/internal consistency (Cronbach''s alpha), captures different facets of complex concepts (e.g. depression scales use 10-21 items).',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Research & Statistics', 'Variables',
 'When an extraneous variable systematically varies with the independent variable and influences the dependent variable, it is called:',
 'Another dependent variable',
 'A confounding variable',
 'A moderating variable',
 'An unreliable variable',
 'B',
 'TYPES OF EXTRANEOUS VARIABLES: CONFOUNDING variable — associated with BOTH the INDEPENDENT variable (exposure) AND the DEPENDENT variable (outcome), distorting the apparent relationship between them (option B). E.g. studying coffee → cancer, smoking is a confounder if smokers also drink more coffee. Must be CONTROLLED through randomisation, matching, restriction, or statistical adjustment. MODERATING variable (option C) — affects the STRENGTH/direction of the IV-DV relationship (interaction). MEDIATING variable — lies in the CAUSAL pathway between IV and DV.',
 'hard', 'approved', NULL, 'Paper II'),

('KRCHN', 'Research & Statistics', 'Informed Consent',
 'The following is necessary in obtaining informed consent for research:',
 'A description of the statistical analyses that will be carried out',
 'A description of the purpose of the research',
 'A description of the reliability and validity of test instruments',
 'A list of publications that the researcher has had in the last ten years',
 'B',
 'ELEMENTS OF INFORMED CONSENT (per Belmont Report, Helsinki, GCP): (1) PURPOSE of the research (option B — REQUIRED); (2) Procedures involved; (3) Duration/time commitment; (4) RISKS and DISCOMFORTS; (5) BENEFITS; (6) ALTERNATIVES; (7) CONFIDENTIALITY assurances; (8) Voluntariness — right to refuse/WITHDRAW anytime without penalty; (9) CONTACT info for questions; (10) Compensation/costs. Statistical analyses (option A), reliability/validity details (option C), researcher publications (option D) are NOT routinely required in lay-language consent forms.',
 'easy', 'approved', NULL, 'Paper II');

-- Set 2 questions (unique, non-repeat)
INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Infection Prevention & Control', 'Disinfection',
 'The following are high-level disinfectants:',
 'Lysol, cidex, jik',
 'Chlorine, cidex and jik',
 'Bacterianios, cidex and lysol',
 'Hibitate, jik and chlorine',
 'B',
 'DISINFECTANT CLASSIFICATION by Spaulding: HIGH-LEVEL disinfectants (HLD) — kill ALL microorganisms EXCEPT high numbers of bacterial spores: GLUTARALDEHYDE 2% (Cidex), ortho-phthalaldehyde (OPA), HYDROGEN PEROXIDE 6-7.5%, PERACETIC ACID, hypochlorite at higher concentrations (CHLORINE/JIK at 5000 ppm or 0.5% concentration). Used for SEMI-CRITICAL items (endoscopes, respiratory equipment). INTERMEDIATE-level — phenolics like LYSOL, iodophors. LOW-LEVEL — QUATERNARY AMMONIUM — HIBITATE/chlorhexidine, ethanol. Option B — chlorine + Cidex + Jik (concentrated) — three high-level disinfectants.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Cancer Prevention',
 'Tertiary phase of cancer prevention involves:',
 'Asking people to stop smoking and ingestion of alcohol',
 'Regular screening of people at risk of cancer diseases',
 'Early and quick treatment for those diagnosed',
 'Setting facilities with ionising radiation far from settlements',
 'C',
 'LEVELS OF CANCER PREVENTION: PRIMORDIAL — preventing the EMERGENCE of risk factors (option D — environmental/regulatory). PRIMARY — preventing CANCER from occurring in those at risk (option A — health promotion, lifestyle, immunisation). SECONDARY — early DETECTION through screening (option B — Pap smear, VIA/VILI, mammography). TERTIARY — preventing complications/disability/death once cancer is diagnosed — EARLY/PROMPT TREATMENT (option C — surgery, chemo, radiotherapy), palliative care, rehabilitation, prevention of recurrence.',
 'easy', 'approved', NULL, 'Paper II'),

('KRCHN', 'Medical-Surgical Nursing', 'Oncology',
 'One of the following is NOT true of a malignant tumour. It is:',
 'Invasive',
 'Encapsulated',
 'Frequently undifferentiated',
 'Associated with paraneoplastic syndrome',
 'B',
 'MALIGNANT vs BENIGN tumours: MALIGNANT — INVASIVE (infiltrates surrounding tissues — option A TRUE); METASTASISES via blood/lymph/transcoelomic; rapid uncontrolled growth; poorly differentiated/anaplastic (option C TRUE); high mitotic index; PARANEOPLASTIC syndromes from ectopic hormone secretion or autoimmune reactions (option D TRUE — SIADH, Cushing''s from small cell lung Ca, hypercalcaemia). NOT ENCAPSULATED — invades tissues without a capsule (option B — FALSE for malignant; benign tumours are typically encapsulated). The "NOT TRUE" answer = option B.',
 'medium', 'approved', NULL, 'Paper I'),

('KRCHN', 'Community Health Nursing', 'Epidemiology',
 'Crude birth rate (CBR) measures:',
 'Number of births per 5000 population in a specified period',
 'Number of newborns per 1000 mothers in a year',
 'Number of births per 1000 population in a specified period',
 'Number of births in 100,000 populations in a year',
 'C',
 'CRUDE BIRTH RATE (CBR) = LIVE BIRTHS in 1 year / TOTAL MID-YEAR POPULATION × 1000 — option C. Reflects the OVERALL birth rate including non-childbearing population. Kenya CBR ~28/1000 (declining). GENERAL FERTILITY RATE = births / women 15-49 years × 1000 — more refined. TOTAL FERTILITY RATE = average number of children a woman would have if she went through her childbearing years at current age-specific fertility rates (TFR for Kenya ~3.4 per KDHS 2022). CRUDE DEATH RATE = deaths / population × 1000.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Community Diagnosis',
 'The steps followed in carrying out a community diagnosis are:',
 'Survey, exploration, develop pre-test tools and report writing',
 'Developing pre-testing survey tools, exploration, plan time survey and report writing',
 'Exploration, develop and pre-test tools, survey, report writing and dissemination',
 'Develop and pre-test survey tools, execute the survey, exploration and report dissemination',
 'C',
 'COMMUNITY DIAGNOSIS STEPS in correct sequence: (1) EXPLORATION/situational analysis — preliminary visit, community entry, gather background info; (2) PLANNING — formulate objectives, choose methodology, determine sample, draft tools; (3) DEVELOP AND PRE-TEST INSTRUMENTS — questionnaires, checklists, FGD guides; pilot for clarity, reliability; (4) EXECUTION/SURVEY — data collection; (5) Data ANALYSIS; (6) REPORT WRITING; (7) DISSEMINATION to community and stakeholders; (8) ACTION PLANNING. Option C follows this correct sequence.',
 'medium', 'approved', NULL, 'Paper II');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Community Health Nursing', 'School Health',
 'The following are activities carried out during school health services EXCEPT:',
 'Referral services',
 'Inspection of school environment',
 'Sharing of health messages',
 'Rehabilitation of the handicapped',
 'D',
 'SCHOOL HEALTH PROGRAMME activities (per Kenya MoH/MoEST): (1) HEALTH APPRAISAL/SCREENING — vision, hearing, dental, growth, nutrition; (2) IMMUNISATION catch-up, HPV vaccination for girls 10 years; (3) Deworming; micronutrient supplementation; (4) Treatment of minor ailments and FIRST AID; (5) REFERRAL of identified cases (option A — IS done); (6) HEALTH EDUCATION/MESSAGES (option C — IS done); (7) HEALTHY school ENVIRONMENT — water, sanitation, food safety, INSPECTION of premises (option B — IS done); (8) Mental health support. REHABILITATION OF HANDICAPPED CHILDREN (option D) is NOT typically a school health service — handled by specialised services. The "EXCEPT" answer = D.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Environmental Health', 'Sanitation',
 'The following guidelines should be considered when choosing a site for a pit latrine EXCEPT:',
 'Pit latrines and cesspools to be at least 3 metres above the water table',
 'Latrines should be 6 metres away from buildings',
 'Wells should be located upstream',
 'Pit latrines should be at least 20 feet deep and 10 metres above water table',
 'D',
 'PIT LATRINE SITING GUIDELINES (per Kenya Public Health Act/MoH Sanitation): (1) Pit BOTTOM should be at least 1.5-3 METRES ABOVE highest WATER TABLE (option A — generally correct); (2) Distance from dwellings — at least 6 metres (option B — correct); (3) WELLS UPSTREAM (option C — correct); (4) Pit depth typically 2-3 metres (6-10 feet) — NOT 20 FEET; the 20-feet depth + 10-metre water-table specification in option D is INCONSISTENT and overly deep — practical pit latrines are not excavated 20 feet (~6 m). The "EXCEPT" answer = D — incorrect specification.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Parasitology',
 'The following are roundworms EXCEPT:',
 'Ascaris lumbricoides',
 'Enterobius vermicularis',
 'Strongyloides stercoralis',
 'Echinococcus granulosus',
 'D',
 'Helminth classification: NEMATODES (ROUNDWORMS) — ASCARIS LUMBRICOIDES (option A), ENTEROBIUS vermicularis (pinworm — option B), STRONGYLOIDES stercoralis (option C), Trichuris, hookworms, Wuchereria, Loa loa, Onchocerca, Trichinella. CESTODES (TAPEWORMS, flat segmented) — Taenia saginata, T. solium, Hymenolepis nana, Diphyllobothrium latum, ECHINOCOCCUS GRANULOSUS (option D — causes hydatid cysts — CESTODE not roundworm). TREMATODES (FLUKES) — Schistosoma, Fasciola, Clonorchis, Paragonimus. The "EXCEPT" = D.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Communicable Diseases',
 'The following are true about rabies EXCEPT:',
 'Prodromal phase takes 2-10 days',
 'Presents with seizures in acute stage',
 'Sensitivity to light presents in early stage',
 'Death occurs within 3 days from onset of symptoms',
 'D',
 'RABIES CLINICAL COURSE: INCUBATION 1-3 months (range 4 days to >1 year); PRODROMAL phase 2-10 days (option A — TRUE) — fever, malaise, headache, paraesthesia/tingling at bite site, anxiety, sensitivity to light/photophobia (option C — TRUE); ACUTE NEUROLOGIC phase 2-7 days — furious (hyperexcitability, hydrophobia, aerophobia, hypersalivation, SEIZURES — option B TRUE) or paralytic; COMA and DEATH within 7-14 DAYS of symptom onset, NOT 3 days (option D FALSE — death takes longer than 3 days). The "EXCEPT" = D.',
 'medium', 'approved', NULL, 'Paper II');

-- =============================================================================
-- PART 4: Paper 4 Section C — Set 3 (unique questions only, repeats excluded)
-- =============================================================================

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Mental Health Nursing', 'Self-Concept',
 'Self-concept comprises of the following:',
 'Body image, ego, and ideal self',
 'Superego, ego and ideal self',
 'Self image, body image and ideal self',
 'Ideal self, superego and self-awareness',
 'A',
 'SELF-CONCEPT (Stuart-Sundeen/Townsend framework) — the totality of how one perceives oneself. COMPONENTS: (1) BODY IMAGE — perception of one''s physical self; (2) SELF-ESTEEM — overall evaluation of self-worth; (3) ROLE PERFORMANCE — how well one performs life roles; (4) PERSONAL IDENTITY — sense of who one is; (5) IDEAL SELF — perception of who one would LIKE TO BE; (6) EGO (Freudian — the executive of personality mediating id/superego/reality). Option A — body image + ego + ideal self — captures three core components. Self-concept disturbances underlie many psychiatric conditions.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Mental Health Nursing', 'Psychiatric Models',
 'The psychological conceptual theory of psychiatric nursing assumes that:',
 'Mental illness is as a result of altered levels of neurotransmitters',
 'Abnormal behaviour is learnt and it can therefore be unlearnt',
 'Mental illness originates from repressed feelings and experiences',
 'Abnormal behaviour is as a result of poorly socialised superego',
 'C',
 'CONCEPTUAL/THEORETICAL MODELS in psychiatric nursing (Townsend): (1) PSYCHOANALYTIC/PSYCHODYNAMIC (Freud, Erikson, Sullivan) — focus on UNCONSCIOUS conflicts and REPRESSED FEELINGS/EXPERIENCES from past (especially childhood) — option C. (2) BEHAVIOURAL (Skinner, Pavlov, Bandura) — abnormal behaviour is LEARNED and can be UNLEARNED (option B — behavioural model). (3) COGNITIVE (Beck, Ellis) — thoughts → feelings → behaviour. (4) BIOLOGICAL/NEUROCHEMICAL (option A — neurotransmitter imbalance). The "psychological/PSYCHODYNAMIC" approach emphasises repressed feelings/conflicts.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Mental Health Nursing', 'Mood Disorders',
 'Dysthymia mood disorder:',
 'Is a less severe form of chronic depression',
 'Is diagnosed when a client has had a depressed mood for more than 3 years',
 'Is best managed using ECT',
 'Is treated using psychoanalysis and group therapy',
 'A',
 'DYSTHYMIA / PERSISTENT DEPRESSIVE DISORDER (DSM-5) = a CHRONIC, LESS SEVERE form of depression — depressed mood for MOST of the day, more days than not, for ≥ 2 YEARS (not 3 — option B wrong) in adults (1 year in children/adolescents), plus ≥2 of: poor appetite/overeating, insomnia/hypersomnia, low energy, low self-esteem, poor concentration, hopelessness. Option A — TRUE description. Treatment: SSRIs/SNRIs (first-line antidepressants), psychotherapy (CBT, interpersonal therapy) — NOT primarily ECT (option C — reserved for severe/treatment-resistant major depression).',
 'easy', 'approved', NULL, 'Paper II'),

('BScN', 'Mental Health Nursing', 'Cognitive Therapy',
 'Cognitive therapy:',
 'Is a psychoanalytic approach of therapy',
 'Assumes behaviour is secondary to one''s way of thinking',
 'Helps correct behaviours associated with childhood experiences',
 'Makes a person highly suggestible to the therapist''s commands',
 'B',
 'COGNITIVE THERAPY (Aaron Beck, 1960s) — based on the principle that THOUGHTS (cognitions) INFLUENCE FEELINGS AND BEHAVIOUR. Distorted/dysfunctional thinking patterns ("cognitive distortions" — all-or-nothing thinking, catastrophising, mind-reading, personalisation, negative automatic thoughts) cause emotional and behavioural problems. Therapy IDENTIFIES and CHALLENGES these thoughts, replacing with realistic adaptive ones. Often combined with behavioural techniques as CBT. Distinct from PSYCHOANALYTIC (option A — unconscious conflict), PSYCHODYNAMIC (option C — childhood experiences), HYPNOTHERAPY (option D — suggestibility). Effective for depression, anxiety, OCD, PTSD, eating disorders.',
 'medium', 'approved', NULL, 'Paper II'),

('BScN', 'Mental Health Nursing', 'DSM Classification',
 'Axis IV in DSM-IV criteria of classifying mental illness focuses on:',
 'Psychosocial and environmental stressors',
 'The actual psychiatric illness',
 'The underlying personality disorders',
 'The underlying medical conditions',
 'A',
 'DSM-IV (now superseded by DSM-5 since 2013) used a MULTIAXIAL system: AXIS I — major clinical psychiatric disorders (depression, schizophrenia, bipolar, anxiety — option B); AXIS II — personality disorders and mental retardation (option C); AXIS III — general medical conditions affecting psychiatric (option D); AXIS IV — PSYCHOSOCIAL AND ENVIRONMENTAL STRESSORS/PROBLEMS contributing to the disorder (option A) — e.g. divorce, unemployment, housing, financial, legal, support system; AXIS V — Global Assessment of Functioning (GAF, 0-100). DSM-5 ABOLISHED the multiaxial system.',
 'medium', 'approved', NULL, 'Paper II');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('BScN', 'Nursing Management & Leadership', 'Teaching Methods',
 'Higher teaching and learning techniques include:',
 'Simulations, group discussions, eLearning',
 'Role playing, eLearning, tutorials',
 'Conferences, symposia, workshops',
 'Field trips, lecturing, demonstrations',
 'C',
 'TEACHING METHODS by level: BASIC/foundational — LECTURE, demonstration, discussion, reading, tutorials, role-play. ADVANCED/HIGHER teaching techniques — focused on synthesis, application, peer learning, current developments: CONFERENCES, SEMINARS, SYMPOSIA, WORKSHOPS, journal clubs, case conferences, panel discussions, group projects, expert forums — option C. Often used in postgraduate education, CPD, and advanced undergraduate courses. INNOVATIVE methods — problem-based learning, simulation, e-learning, flipped classroom.',
 'medium', 'approved', NULL, 'Paper II'),

('BScN', 'Nursing Management & Leadership', 'Educational Objectives',
 'The main elements of an educational objective are:',
 'Knowledge, psychomotor, attitude',
 'Performance, criterion, goal',
 'Performance, condition, criterion',
 'Specific, measurable, attainable',
 'C',
 'MAGER''S CRITERIA for behavioural educational objectives ("ABCD" or "PCC"): (1) AUDIENCE — who will perform; (2) PERFORMANCE/BEHAVIOUR — observable, measurable ACTION (verb — e.g. list, demonstrate, calculate, identify); (3) CONDITIONS — circumstances under which performance occurs (e.g. "given a list of drugs"); (4) CRITERION/degree — standard of acceptable performance (e.g. "with 80% accuracy"). Option C — PERFORMANCE + CONDITION + CRITERION — captures Mager''s 3 core elements. Option A lists DOMAINS of objectives. Option D lists SMART criteria — for goal setting, related but broader.',
 'medium', 'approved', NULL, 'Paper II'),

('BScN', 'Nursing Management & Leadership', 'Curriculum Development',
 'The major approaches to curriculum development are:',
 'Integrated, community-based and competency-based',
 'Subject-centred, integrated and competency-based',
 'Subject-centred, community-based and student-centred',
 'Integrated, competency-based, goal-centred',
 'B',
 'CURRICULUM DESIGN APPROACHES: (1) SUBJECT-CENTRED (DISCIPLINE-based) — traditional, content organised by academic subject; (2) INTEGRATED — combines subjects around themes or organ-systems; (3) COMPETENCY-BASED — built around specific competencies the graduate must demonstrate (current nursing trend — KRCHN/BSCN competency-based curricula); (4) COMMUNITY-based/oriented — emphasises community settings and population health; (5) STUDENT-CENTRED — learner needs/interests drive content. Option B — subject-centred + integrated + competency-based — three major approaches. NCK has moved toward competency-based curricula for both KRCHN and BSCN.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Paediatric Nursing', 'Leukaemia',
 'A child with acute lymphoblastic leukaemia has a high risk of infection because:',
 'White blood cells are produced in inadequate numbers',
 'The skin integrity is altered',
 'There is a down-regulation of immune system by catecholamine',
 'The white blood cells are immature',
 'D',
 'ACUTE LYMPHOBLASTIC LEUKAEMIA (ALL) — uncontrolled proliferation of IMMATURE LYMPHOID CELLS (LYMPHOBLASTS) in bone marrow. INFECTION RISK due to: (1) IMMATURE/non-functional white cells — even though WBC count may be HIGH, the cells are BLASTS that CANNOT FUNCTION as competent immune cells — option D — qualitative deficiency (functional immunosuppression); (2) NEUTROPENIA — bone marrow crowded by blasts → reduced normal neutrophils; (3) Treatment-induced (chemotherapy causes profound neutropenia); (4) breach of barriers (mucositis, IV lines). Option A — inadequate numbers — is partly true but not the FULL story. Option D captures the functional issue.',
 'medium', 'approved', NULL, 'Paper I'),

('KRCHN', 'Paediatric Nursing', 'Fluid Overload',
 'The following feature indicates excessive IV fluid infusion in a 3-year-old child:',
 'Worsening dyspnoea',
 'Gastric distension',
 'Nausea and vomiting',
 'Temperature of 102°F (38.9°C)',
 'A',
 'FLUID OVERLOAD in children — children have less cardiovascular reserve and are more vulnerable to volume overload than adults. SIGNS: WORSENING DYSPNOEA (pulmonary oedema — option A — classic sign), tachypnoea, hypoxia/desaturation; bilateral basal lung crepitations; tachycardia; raised JVP/distended neck veins; HEPATOMEGALY (key in infants/young children); PERIPHERAL OEDEMA; RAISED BP; weight gain; PERIORBITAL puffiness. MANAGEMENT: stop/reduce fluids, diuretics (furosemide), oxygen, treat cause. Option B gastric distension — could be from many causes. Option D fever — not a fluid-overload sign.',
 'medium', 'approved', NULL, 'Paper I');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Paediatric Nursing', 'Asthma',
 'The following finding would alert a nurse that a 6-year-old child is at risk for a severe asthma exacerbation:',
 'Oxygen saturation of 95%',
 'Mild work of breathing',
 'Absence of intercostal or substernal retractions',
 'History of steroid-dependent asthma',
 'D',
 'RISK FACTORS for SEVERE/FATAL asthma exacerbation: previous near-fatal/life-threatening attack (ICU admission, intubation); previous hospitalisation in past year; STEROID-DEPENDENT asthma — needing oral/systemic corticosteroids regularly (option D — significant marker of severe persistent asthma, difficult control, increased exacerbation risk); recent emergency department visits; over-reliance on short-acting bronchodilators (>1 canister/month); poor adherence to inhaled corticosteroids; comorbidities; psychosocial issues. Options A, B, C — SpO2 95%, mild work of breathing, no retractions — describe a STABLE state, NOT risk factors.',
 'medium', 'approved', NULL, 'Paper I'),

('KRCHN', 'Paediatric Nursing', 'IM Injection Sites',
 'IM injection to an infant should be administered at:',
 'Deltoid region',
 'Dorsogluteal region',
 'Ventrogluteal region',
 'Vastus lateralis region',
 'D',
 'IM INJECTION SITES by age: INFANTS (<12-24 months) — VASTUS LATERALIS (anterolateral thigh, middle third) — option D — preferred site due to: large muscle relative to age, well-developed at birth, no major nerves/vessels, easy access, can accommodate up to 1 mL safely. TODDLERS/CHILDREN — vastus lateralis or VENTROGLUTEAL (after walking-confidence). DELTOID (option A) — only AFTER muscle is well developed (3 years+). DORSOGLUTEAL (option B) — AVOIDED in young children (sciatic nerve risk; not well developed until child has walked for ≥1 year). Use 23-25G needle, 5/8 to 1 inch, 90° angle.',
 'easy', 'approved', NULL, 'Paper I'),

('KRCHN', 'Paediatric Nursing', 'Nephrotic Syndrome',
 'The primary purpose of administering corticosteroids to a child with nephrotic syndrome is to:',
 'Increase blood pressure',
 'Reduce inflammation',
 'Decrease proteinuria',
 'Prevent infection',
 'C',
 'NEPHROTIC SYNDROME in children — characterised by: heavy PROTEINURIA (>40 mg/m²/hr), HYPOALBUMINAEMIA (<25 g/L), OEDEMA, HYPERLIPIDAEMIA. Commonest type in children = MINIMAL CHANGE DISEASE (80% steroid-responsive). FIRST-LINE TREATMENT: CORTICOSTEROIDS (prednisolone 60 mg/m²/day for 4-6 weeks then taper) — induce REMISSION by REDUCING PROTEINURIA — option C — primary therapeutic goal. Steroids work by reducing podocyte injury and stabilising glomerular filtration barrier. Other measures: salt and fluid restriction, diuretics if needed, ACE inhibitors, treat infections, thromboprophylaxis.',
 'medium', 'approved', NULL, 'Paper I');

-- =============================================================================
-- PART 5: Paper 4 Section C — Sets 4 & 5 (unique questions only)
-- =============================================================================

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('BScN', 'Nursing Management & Leadership', 'Bloom''s Taxonomy',
 'The level of cognitive domain of learning that refers to the ability of the learner to recall information is:',
 'Mastery',
 'Comprehension',
 'Knowledge',
 'Application',
 'C',
 'BLOOM''S TAXONOMY of cognitive domain (original): (1) KNOWLEDGE — RECALL of information/facts/terminology — option C — lowest level; (2) COMPREHENSION — understand the meaning; (3) APPLICATION — use information in new situations; (4) ANALYSIS — break down into parts; (5) SYNTHESIS — combine elements to create new whole; (6) EVALUATION — judge value based on criteria. REVISED TAXONOMY (Anderson & Krathwohl 2001): Remember → Understand → Apply → Analyse → Evaluate → Create. "Mastery" (option A) is not a Bloom level — it is a goal/standard. KNOWLEDGE level uses verbs: list, name, identify, recall, define, state.',
 'easy', 'approved', NULL, 'Paper II'),

('BScN', 'Nursing Management & Leadership', 'Teaching Principles',
 'Repetition in teaching is important because it:',
 'Makes the lesson interesting',
 'Fosters mastery in the learner',
 'Actively involves the learners',
 'Promotes rote learning',
 'B',
 'REPETITION in teaching/learning — fundamental learning principle (Thorndike''s Law of Exercise). FUNCTIONS: (1) Strengthens NEURAL connections and consolidates memory (encoding from working memory to long-term memory through repeated rehearsal); (2) FOSTERS MASTERY — repeated practice leads to automaticity and proficiency (option B) — especially important for skills (psychomotor) and key facts; (3) Reinforces learning; (4) Reduces forgetting (spaced repetition is optimal). EXCESSIVE repetition without variation can promote ROTE memorisation without understanding (option D — a downside if overdone). Repetition does NOT inherently make lessons interesting (option A) — variety does.',
 'easy', 'approved', NULL, 'Paper II'),

('BScN', 'Nursing Management & Leadership', 'Teaching Principles',
 'During a lesson, the teacher reinstated a correct response that had been given by a student. The teacher''s action is best referred to as:',
 'Motivation',
 'Feedback',
 'Reinforcement',
 'Reward',
 'C',
 'BEHAVIOURAL PRINCIPLES in teaching (Skinner): POSITIVE REINFORCEMENT — adding a desirable stimulus following a desired behaviour to INCREASE the likelihood of its recurrence. The teacher RESTATING/highlighting the student''s correct answer publicly is a form of POSITIVE REINFORCEMENT (option C — verbal/social reinforcement) — affirms the response and encourages similar behaviour. FEEDBACK (option B — broader; can be corrective or positive). MOTIVATION (option A — broader internal/external drive). REWARD (option D — specific tangible/intangible item given after behaviour). Reinforcement is the most accurate technical term for the described action.',
 'easy', 'approved', NULL, 'Paper II'),

('BScN', 'Nursing Management & Leadership', 'Curriculum Development',
 'The initial step in the development of a competency-based curriculum is:',
 'Job description',
 'Task analysis',
 'Situation analysis',
 'Objectives formulation',
 'A',
 'COMPETENCY-BASED CURRICULUM (CBC) development — works BACKWARD from competencies needed in practice. STEPS: (1) JOB DESCRIPTION/ANALYSIS — define the JOB/ROLE the graduate will perform (e.g. KRCHN, BSCN nurse — duties, responsibilities, settings) — option A is the foundation; (2) TASK ANALYSIS — break down job into specific tasks/activities; (3) COMPETENCY identification — knowledge, skills, attitudes needed for each task; (4) Performance/learning OBJECTIVES; (5) Content selection; (6) Learning experiences and methods; (7) Assessment strategies; (8) Implementation; (9) Evaluation and revision. NCK has adopted CBCs for KRCHN and BSCN.',
 'medium', 'approved', NULL, 'Paper II'),

('BScN', 'Research & Evidence-Based Practice', 'Research Proposal',
 'A written account of the research study that presents/describes how a particular problem will be investigated is:',
 'Project',
 'Methodology',
 'Design',
 'Proposal',
 'D',
 'RESEARCH PROPOSAL = a WRITTEN DOCUMENT prepared BEFORE conducting the research, describing WHAT the researcher intends to do and HOW — option D. STANDARD STRUCTURE: title, abstract, introduction (background, problem statement, objectives, hypothesis, significance), literature review, methodology (design, setting, population, sample, data collection, analysis, ethics), workplan, budget, references, appendices. Submitted for: ethical approval (KNH-UoN ERC, NACOSTI, KEMRI), funding, academic credit. RESEARCH REPORT/THESIS is written AFTER completion. METHODOLOGY (option B) is a SECTION of the proposal. DESIGN (option C) is a specific aspect of methodology.',
 'easy', 'approved', NULL, 'Paper II');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('BScN', 'Research & Evidence-Based Practice', 'Research Design',
 'The purpose of comparative design is to:',
 'Describe a phenomenon as it occurs in the community',
 'Look for differences in one variable between two groups',
 'Establish causal relationships between two variables',
 'Measure the extent one variable makes changes in another',
 'B',
 'COMPARATIVE RESEARCH design — examines DIFFERENCES (or similarities) BETWEEN TWO OR MORE GROUPS on one or more variables — option B. E.g. compare outcomes in rural vs urban patients; iron-deficient vs non-iron-deficient pregnant women; new method vs traditional method outcomes. Distinct from DESCRIPTIVE (option A — describes one group); EXPERIMENTAL (options C, D — establish causation through intervention with control). CORRELATIONAL — examines association between variables (no manipulation). Comparative designs are observational/quasi-experimental — they identify differences but cannot definitively prove causation.',
 'medium', 'approved', NULL, 'Paper II'),

('BScN', 'Research & Evidence-Based Practice', 'Data Collection',
 'Data collection tools include:',
 'Observation checklist, focus group discussion',
 'Questionnaire, interviewing',
 'Records audit, participant observation',
 'Questionnaire, observation checklist',
 'D',
 'DATA COLLECTION TOOLS (the instruments) vs METHODS (the approaches): TOOLS = the physical/structured INSTRUMENTS used to collect data — QUESTIONNAIRES, OBSERVATION CHECKLISTS, INTERVIEW SCHEDULES/guides, FGD guides, biophysical measurement instruments. METHODS = the broader approaches — interviewing, observation (participant/non-participant), self-administration, FGD, records review. Option D — QUESTIONNAIRE + OBSERVATION CHECKLIST — both are clearly TOOLS. Other options mix tools with methods (FGD, interviewing, records audit, participant observation are methods/approaches).',
 'easy', 'approved', NULL, 'Paper II'),

('BScN', 'Mental Health Nursing', 'Mood Disorders',
 'Unipolar mood disorders include:',
 'Cyclothymia and mixed manic episodes',
 'Major depression and dysthymia',
 'Dysthymia and mixed manic episodes',
 'Cyclothymia and mood disorders related to mania',
 'B',
 'UNIPOLAR mood disorders = mood disturbance in ONE direction (only depressed, no mania/hypomania) — MAJOR DEPRESSIVE DISORDER, PERSISTENT DEPRESSIVE DISORDER (DYSTHYMIA, chronic ≥2 yr), seasonal affective disorder, premenstrual dysphoric disorder. Option B — major depression + dysthymia — both unipolar. BIPOLAR mood disorders = mood disturbance in BOTH directions — Bipolar I, Bipolar II, CYCLOTHYMIA (chronic milder bipolar — hypomanic + dysthymic-level depressive episodes ≥2 years), mixed states. Cyclothymia and mixed manic states (options A, C, D) belong to bipolar spectrum.',
 'medium', 'approved', NULL, 'Paper II'),

('BScN', 'Mental Health Nursing', 'Anxiety Disorders',
 'DSM-IV categories of anxiety disorders include:',
 'Post-traumatic stress disorder and phobic disorders',
 'Generalised anxiety disorder and binge eating',
 'Panic attack and schizophrenia',
 'Obsessive compulsive disorder and pyromania',
 'A',
 'DSM-IV ANXIETY DISORDERS category included: GENERALISED ANXIETY DISORDER (GAD); PANIC DISORDER (with/without agoraphobia); AGORAPHOBIA; SPECIFIC PHOBIA; SOCIAL PHOBIA; OBSESSIVE-COMPULSIVE DISORDER (OCD); POST-TRAUMATIC STRESS DISORDER (PTSD); ACUTE STRESS DISORDER. Option A — PTSD + PHOBIC DISORDERS — both DSM-IV anxiety disorders. DSM-5 (2013) RECLASSIFIED: PTSD into "Trauma and Stressor-Related Disorders"; OCD into "Obsessive-Compulsive and Related Disorders" — separate from anxiety. SCHIZOPHRENIA (option C) is a psychotic disorder. BINGE EATING (option B) is an eating disorder. PYROMANIA (option D) is an impulse control disorder.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Mental Health Nursing', 'Intellectual Disability',
 'In mild mental retardation (MR) there is:',
 'IQ of 50-70, the child is educable and can live independently',
 'IQ is 35-50, the child is trainable and only speaks few words',
 'IQ is 20-34, child is unable to have structured living but is trainable',
 'IQ is below 20, child unable to relate verbally but can live independently',
 'A',
 'INTELLECTUAL DISABILITY severity (DSM-IV based on IQ): MILD — IQ 50-70 (option A) — "EDUCABLE" — can achieve basic academic skills (up to 6th grade), live and work INDEPENDENTLY with support, often go undetected in early childhood; comprise ~85% of intellectual disability cases. MODERATE — IQ 35-49 (option B) — "TRAINABLE" — basic communication and self-help, supervised work, sheltered employment. SEVERE — IQ 20-34 (option C) — limited speech, requires significant support. PROFOUND — IQ <20 — minimal communication, requires total care (option D wrong in saying can live independently). DSM-5 emphasises adaptive functioning over IQ alone.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Mental Health Nursing', 'Milieu Therapy',
 'Milieu therapy includes:',
 'Providing a supportive environment for positive adaptation and personal growth',
 'Teaching skills of everyday living to improve a patient''s general performance',
 'Use of various recreational activities to meet patient treatment goals',
 'Focusing on the here and now interactions rather than repressed childhood experiences',
 'A',
 'MILIEU THERAPY ("therapeutic environment/community" — Maxwell Jones) = USE OF THE PHYSICAL AND SOCIAL ENVIRONMENT OF THE WARD/UNIT as a THERAPEUTIC TOOL — providing a SUPPORTIVE, SAFE, STRUCTURED ENVIRONMENT that promotes POSITIVE ADAPTATION, recovery and PERSONAL GROWTH (option A) — captures the essence. Key principles: safety; clear structure and rules; therapeutic relationships; group activities; community meetings; patient involvement in unit management; consistency; respect; modelling healthy interactions. Option B describes OCCUPATIONAL therapy/life-skills training; option C describes RECREATIONAL therapy; option D describes a focus on PRESENT (here-and-now therapies, e.g. Gestalt).',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Mental Health Nursing', 'Antipsychotics',
 'The mode of action of antipsychotics includes:',
 'Blockage of dopamine receptors in the brain',
 'Stimulation of serotonin receptors in the brain',
 'Blockage of adrenaline and noradrenaline receptors',
 'Stimulation of dopamine receptors in the brain',
 'A',
 'ANTIPSYCHOTICS — mechanism: BLOCKADE OF DOPAMINE D2 RECEPTORS in the mesolimbic pathway (responsible for positive symptoms — hallucinations, delusions) — option A. TYPICAL (first-generation) — chlorpromazine, haloperidol, fluphenazine — strong D2 blockade, more EPS (extrapyramidal side effects — Parkinsonism, dystonia, akathisia, tardive dyskinesia), hyperprolactinaemia. ATYPICAL (second-generation) — risperidone, olanzapine, quetiapine, clozapine, aripiprazole — block D2 AND 5-HT2A serotonin, fewer EPS, but more metabolic side effects (weight gain, diabetes, dyslipidaemia). NEUROLEPTIC MALIGNANT SYNDROME (NMS) — rare, life-threatening — fever, rigidity, autonomic instability, altered consciousness.',
 'medium', 'approved', NULL, 'Paper II');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Paediatric Nursing', 'Acid-Base Balance',
 'Uncontrolled vomiting in an infant can result in:',
 'Tetany',
 'Acidosis',
 'Alkalosis',
 'Hypersensitivity',
 'C',
 'PROLONGED VOMITING — loss of GASTRIC CONTENTS including HYDROCHLORIC ACID (H+ and Cl-) and POTASSIUM — leads to HYPOKALAEMIC, HYPOCHLORAEMIC METABOLIC ALKALOSIS (option C). The kidneys try to compensate but are limited by potassium depletion. Classic example: PYLORIC STENOSIS in 2-6 week old infants — projectile non-bilious vomiting → metabolic alkalosis. Diarrhoea would cause METABOLIC ACIDOSIS (loss of bicarbonate, option B). TETANY (option A) can occur in severe alkalosis (alkalosis reduces ionised calcium) but is downstream consequence, not the primary acid-base disturbance. Treatment: rehydration with normal saline + potassium replacement.',
 'medium', 'approved', NULL, 'Paper I'),

('KRCHN', 'Paediatric Nursing', 'Paediatric Emergencies',
 'In paediatric emergencies, priority signs include:',
 'Poisoning, restlessness, coma',
 'Pallor, pain, oedema of both feet',
 'Convulsion, central cyanosis, poisoning',
 'Pyrexia, severe respiratory distress, coma',
 'C',
 'Per Kenya MoH/WHO ETAT (Emergency Triage Assessment and Treatment) for paediatrics — EMERGENCY SIGNS require IMMEDIATE intervention: obstructed/absent BREATHING, severe respiratory DISTRESS, central CYANOSIS, shock, COMA/convulsing now (CONVULSIONS), severe DEHYDRATION. PRIORITY SIGNS — need urgent attention: Tiny baby (<2 months), Temperature very high, Trauma/urgent surgical, Pallor (severe), Poisoning, Pain (severe), Respiratory distress, Restless/irritable/lethargic, Referral, Malnutrition, Oedema (of both feet), Burns. Option C — convulsion + central cyanosis + POISONING — mixes EMERGENCY (convulsion, cyanosis) with PRIORITY (poisoning). Option B — pallor + pain + bilateral foot oedema — all PRIORITY signs. Option C fits the typical exam-key.',
 'hard', 'approved', NULL, 'Paper I'),

('KRCHN', 'Paediatric Nursing', 'Refractive Errors',
 'Hyperopia in children:',
 'Results from unequal curvature of the cornea',
 'Results from an eyeball that is too long',
 'Occurs due to rays of light being bent in different directions',
 'Occurs due to rays of light being focused behind the retina',
 'D',
 'REFRACTIVE ERRORS: HYPEROPIA (far-sightedness) — light rays from near objects FOCUS BEHIND the retina (option D) — usually because EYEBALL is TOO SHORT or cornea/lens lacks curvature. Children can often accommodate to overcome mild hyperopia → eye strain, headaches. Most children have mild hyperopia at birth which decreases with age. MYOPIA (short-sightedness) — light focuses IN FRONT of retina; eyeball too LONG (option B describes myopia). ASTIGMATISM — UNEQUAL CORNEAL CURVATURE causing light to focus at different points in different planes (option A). Correction: hyperopia — CONVEX (plus) lens; myopia — CONCAVE (minus) lens.',
 'medium', 'approved', NULL, 'Paper I'),

('KRCHN', 'Paediatric Nursing', 'Burns',
 'Features of first-degree burns in children include:',
 'Pain, blistering',
 'Erythema, blanching with pressure',
 'Leathery appearance, blistering',
 'Minimal swelling, erythema',
 'B',
 'BURN CLASSIFICATION by depth: FIRST DEGREE (superficial — epidermis only) — ERYTHEMA (redness), PAIN, BLANCHES with pressure (option B — TRUE), NO BLISTERS, dry, heals 3-7 days without scarring. e.g. sunburn. SECOND DEGREE — SUPERFICIAL PARTIAL THICKNESS — pink/red, BLISTERS (option A), painful, moist, blanches; heals 1-3 weeks, minimal scarring. DEEP PARTIAL THICKNESS — red/white mottled, painful or decreased sensation, may blister; heals 3-6 weeks with scarring. THIRD DEGREE (full thickness) — WHITE, BROWN, CHARRED, LEATHERY (option C), DRY, painless (nerves destroyed), needs grafting. Burns surface area assessed by Lund-Browder chart in children.',
 'easy', 'approved', NULL, 'Paper I'),

('KRCHN', 'Paediatric Nursing', 'Nephrotic Syndrome',
 'The main cause of oedema in nephrotic syndrome is:',
 'Dilatation of blood capillaries',
 'Inflammatory processes',
 'Decreased albumin in blood',
 'Renal failure',
 'C',
 'NEPHROTIC SYNDROME OEDEMA pathophysiology — TRADITIONAL UNDERFILL theory: heavy PROTEINURIA → HYPOALBUMINAEMIA (<25 g/L) → DECREASED PLASMA ONCOTIC PRESSURE → fluid leaks from vessels into interstitium (option C — classic explanation); reduced effective circulating volume → activation of RAAS → sodium and water retention → worsening oedema. OVERFILL theory (more recent) — primary tubular sodium retention drives oedema independent of albumin. Both contribute. Clinically: periorbital and gravity-dependent oedema, ascites, scrotal/labial oedema, sometimes pleural effusion. Treatment: corticosteroids (reduce proteinuria), salt/fluid restriction, diuretics, ACE inhibitors.',
 'medium', 'approved', NULL, 'Paper I');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Paediatric Nursing', 'Nephrotic Syndrome',
 'In nephrotic syndrome, hypovolaemia leads to decreased:',
 'Secretion of antidiuretic hormone',
 'Oncotic pressure',
 'Renal blood flow',
 'Secretion of aldosterone',
 'C',
 'NEPHROTIC SYNDROME pathophysiology — heavy proteinuria → hypoalbuminaemia → decreased plasma oncotic pressure → fluid shifts to interstitium → DECREASED EFFECTIVE CIRCULATING VOLUME (relative HYPOVOLAEMIA) → DECREASED RENAL BLOOD FLOW (option C — TRUE) → activation of compensatory responses: INCREASED renin-angiotensin-aldosterone (option D wrong — aldosterone INCREASES) → sodium retention; INCREASED ADH/vasopressin (option A wrong — ADH INCREASES) → water retention; sympathetic activation. These compensations cause sodium/water retention worsening oedema. Reduced renal blood flow can precipitate ACUTE KIDNEY INJURY in severe cases or with aggressive diuresis.',
 'hard', 'approved', NULL, 'Paper I'),

('KRCHN', 'Medical-Surgical Nursing', 'Blood Transfusion',
 'While monitoring a child on blood transfusion, the nurse notes that the child has developed chills, fever and vomiting. The nurse should:',
 'Stop transfusion immediately',
 'Transfuse the blood more slowly',
 'Place child flat on the bed',
 'Give antihistamines',
 'A',
 'BLOOD TRANSFUSION REACTIONS — chills, fever, vomiting are red-flag signs of a potential TRANSFUSION REACTION (could be acute haemolytic, febrile non-haemolytic, allergic, septic, TRALI). IMMEDIATE NURSING ACTIONS: (1) STOP THE TRANSFUSION IMMEDIATELY (option A — first action — could be life-threatening haemolytic reaction); (2) MAINTAIN IV ACCESS with normal saline (different bag); (3) Notify physician; (4) Recheck patient/blood identification; (5) Send blood bag + post-transfusion sample to lab; (6) Monitor vital signs closely; (7) Treat symptoms (antipyretics, antihistamines, fluids, steroids, vasopressors as needed); (8) Document and report. NEVER slow the transfusion (option B — continued exposure dangerous).',
 'medium', 'approved', NULL, 'Paper I'),

('KRCHN', 'Paediatric Nursing', 'Oesophageal Atresia',
 'The priority nursing diagnosis for an infant with oesophageal atresia is:',
 'Risk for aspiration',
 'Impaired nutrition: less than body requirement',
 'Pain',
 'Altered perfusion',
 'A',
 'OESOPHAGEAL ATRESIA (OA) — congenital anomaly where the oesophagus ends in a blind pouch; usually associated with TRACHEO-OESOPHAGEAL FISTULA (TOF, ~85% of cases). Newborn presents with EXCESSIVE FROTHY SECRETIONS, coughing/choking with feeds, cyanosis, respiratory distress. CRITICAL RISK = ASPIRATION — secretions cannot pass to stomach and accumulate in pouch → spill into airway; with TOF, gastric contents reflux into trachea via fistula. PRIORITY nursing diagnosis = RISK FOR ASPIRATION (option A) → airway/breathing is the immediate Maslow''s basic need at risk. Interventions: NPO, continuous suction of pouch (Replogle tube), head elevated, IV fluids, antibiotics, prepare for urgent surgical repair.',
 'medium', 'approved', NULL, 'Paper I'),

('KRCHN', 'Paediatric Nursing', 'Otitis Media',
 'Middle ear inflammation is common in children. This mainly affects:',
 'Short, horizontal Eustachian tube',
 'Thin tympanic membrane',
 'Permeable tympanic membrane',
 'Short, vertical Eustachian tube',
 'A',
 'OTITIS MEDIA (middle ear inflammation) is COMMONEST in children due to anatomical factors: EUSTACHIAN TUBE in CHILDREN is SHORTER, more HORIZONTAL, and WIDER (option A) than in adults (where it is longer and angled DOWNWARD at ~45°). This anatomy allows easier ascent of nasopharyngeal organisms into the middle ear. Plus IMMATURE IMMUNE SYSTEM, frequent URIs, adenoid hypertrophy obstructing tube, allergies, bottle-feeding while lying flat. Eustachian tube becomes more vertical and longer by ~7-8 years. AOM peaks at 6-24 months. Pathogens: Streptococcus pneumoniae, H. influenzae, Moraxella catarrhalis, viruses.',
 'medium', 'approved', NULL, 'Paper I'),

('KRCHN', 'Paediatric Nursing', 'Immunosuppression',
 'Nursing interventions for a 9-year-old child with immunosuppression include:',
 'Informing the guardian about the condition, catheterisation to monitor urine output',
 'Offering large amounts of fresh fruits and vegetables, nursing the child in isolation',
 'Encouraging child to perform at optimal level, nursing the child in isolation',
 'Nursing the child in isolation, catheterisation to monitor urine output',
 'C',
 'Nursing IMMUNOSUPPRESSED child (chemotherapy, transplant, advanced HIV, congenital immunodeficiency, severe nephrotic): PROTECTIVE/REVERSE ISOLATION — single room, restricted visitors, careful hand hygiene, no fresh flowers/uncooked fruits and vegetables (raw foods carry pathogens — option B WRONG), no live vaccines, mask if leaving room; ENCOURAGE OPTIMAL FUNCTION — psychosocial support, normal age-appropriate activities WITHIN safety limits, school work, family involvement, play (option C TRUE — captures both isolation and optimal functioning); monitor for infection signs; good nutrition (well-cooked); skin/mouth care; AVOID INVASIVE PROCEDURES like CATHETERISATION unless absolutely indicated (introduce infection risk — options A, D wrong).',
 'medium', 'approved', NULL, 'Paper I');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('BScN', 'Nursing Management & Leadership', 'Bloom''s Taxonomy',
 'Cognitive domain of learning:',
 'Embraces development of motor skills and attitudes',
 'Embraces the intellectual abilities of remembering and reasoning',
 'Emphasises the emotional qualities and feelings',
 'Emphasises development of values and reasoning',
 'B',
 'BLOOM''S THREE DOMAINS of learning: COGNITIVE DOMAIN (KNOWING) — INTELLECTUAL/MENTAL abilities — REMEMBERING facts, UNDERSTANDING, APPLYING knowledge, analysing, synthesising, evaluating — option B. Verbs: define, recall, explain, calculate, analyse, judge. PSYCHOMOTOR DOMAIN (DOING) — physical SKILLS, MOTOR abilities (option A — motor skills). AFFECTIVE DOMAIN (FEELING) — EMOTIONS, ATTITUDES, VALUES, FEELINGS (options C, D — emotional qualities, values) — receiving, responding, valuing, organising, characterisation. Effective teaching addresses ALL THREE domains in integrated way for holistic nurse training.',
 'easy', 'approved', NULL, 'Paper II'),

('BScN', 'Nursing Management & Leadership', 'Teaching Aids',
 'Dummy patients (manikins) are examples of:',
 'Projected, real, conventional teaching aids',
 'Unprojected, emerging, artificial teaching aids',
 'Unprojected, conventional, artificial teaching aids',
 'Emerging, projected, artificial teaching aids',
 'C',
 'TEACHING AIDS classification: by MEDIUM — PROJECTED (need projection equipment — slides, transparencies, video projection) vs UNPROJECTED (no projection — chalkboard, posters, charts, models, manikins, real objects). By NATURE — REAL (actual patients, anatomical specimens) vs ARTIFICIAL (substitutes — MODELS, MANIKINS, simulators). By LEVEL of technology — CONVENTIONAL/traditional (chalkboard, posters, models, books) vs EMERGING/modern (computers, e-learning, virtual reality, high-fidelity simulators). MANIKINS (dummy patients used for skill practice — CPR Annie, IV arm trainers, anatomical mannequins) are UNPROJECTED + CONVENTIONAL + ARTIFICIAL — option C.',
 'medium', 'approved', NULL, 'Paper II'),

('BScN', 'Nursing Management & Leadership', 'Assessment Methods',
 'Objective type of tests include:',
 'Completion type, matching format',
 'Restricted response essay test, multiple choice questions',
 'Unrestricted response essay test, multiple choice questions',
 'Matching format, unrestricted response essay test',
 'A',
 'TEST QUESTION TYPES — OBJECTIVE (one correct/best answer, objective scoring): MULTIPLE CHOICE QUESTIONS (MCQ), TRUE/FALSE, MATCHING, COMPLETION/FILL-IN-THE-BLANK, short-answer. Quick to mark, broad content coverage, reliable scoring. SUBJECTIVE (varying acceptable answers, scorer judgement) — ESSAY questions, including RESTRICTED RESPONSE (focused, limited scope) and UNRESTRICTED RESPONSE (extended/free essay — clearly subjective). Option A — COMPLETION + MATCHING — both OBJECTIVE types. Options B, C, D all include ESSAY types (subjective) mixed with objective — incorrect.',
 'medium', 'approved', NULL, 'Paper II');
