-- Migration: 20260701000001
-- Source: NCK-NEW-MCQ-Compilation.docx — Year 2018 (KMTC KRCHN Pharmacology Paper III, Sept 2018)
-- Paper assignment per §12 nck-exam-system.md:
--   Pharmacology → Paper I for BOTH KRCHN and BScN
-- exam_year = 2018 (year stated in source document header)
-- Audit: answers and rationales verified against BNF, Brunner & Suddarth,
--        MOH Kenya guidelines, standard Kenyan nursing pharmacology texts.
-- ON CONFLICT (stem, cadre) DO NOTHING on every INSERT.
-- Note: 2018 BScN Paper II already seeded (20260626000002). This file covers
--       the 2018 pharmacology Paper I set for BOTH cadres — not previously seeded.

-- ── Q1: Cephalosporins — cefixime, loracarbef ─────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Antimicrobials','The drugs classified as cephalosporins include:','Cefixime, Loracarbef','Cephradine, Laroxyl','Ceftriaxone, Lasix','Cefaclor, Clonazepam','A','Cefixime is a 3rd-generation cephalosporin and loracarbef is a carbacephem (structurally related); the distractors pair cephalosporins with non-cephalosporins such as amitriptyline (Laroxyl), furosemide (Lasix) and clonazepam (BNF antibacterials).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Antimicrobials','The drugs classified as cephalosporins include:','Cefixime, Loracarbef','Cephradine, Laroxyl','Ceftriaxone, Lasix','Cefaclor, Clonazepam','A','Cefixime and loracarbef belong to the beta-lactam/cephalosporin class; nurses must distinguish them from other drug classes when selecting antibiotic therapy and monitoring for class-specific reactions (BNF; pharmacology).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q2: Antitussives — relieve dry cough ──────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Respiratory Pharmacology','Antitussive agents are indicated to:','Remove secretions','Relieve rhinitis','Control productive cough','Relieve a dry cough','D','Antitussives suppress the cough reflex and are indicated for a dry, non-productive cough; expectorants (not antitussives) facilitate removal of secretions (BNF/pharmacology).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Respiratory Pharmacology','Antitussive agents are indicated to:','Remove secretions','Relieve rhinitis','Control productive cough','Relieve a dry cough','D','Antitussives (e.g. dextromethorphan, codeine) suppress the cough centre; use in dry cough only — contraindicated when cough is clearing secretions. Nurses differentiate from mucolytics and expectorants (BNF).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q3: Narcotic analgesics — codeine, morphine ───────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Analgesics','The drugs classified as narcotic analgesics include:','Acetylsalicylic acid, Indomethacin','Acetaminophen, Ibuprofen','Codeine, Morphine','Morphine, Diclofenac','C','Codeine and morphine are opioid (narcotic) analgesics; aspirin, paracetamol, ibuprofen and diclofenac are non-opioid/NSAID agents (BNF).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Analgesics','The drugs classified as narcotic analgesics include:','Acetylsalicylic acid, Indomethacin','Acetaminophen, Ibuprofen','Codeine, Morphine','Morphine, Diclofenac','C','Opioid analgesics act on mu/kappa receptors; nurses apply WHO analgesic ladder principles, monitor for respiratory depression and constipation, and manage controlled drug protocols (BNF).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q4: Hypnotics — induce sleep ──────────────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','CNS Pharmacology','The action of hypnotic drugs is to induce:','Vomiting','Appetite','Sleep','Calmness','C','Hypnotic drugs are given specifically to induce sleep; sedatives produce calmness/drowsiness without necessarily inducing sleep (BNF/pharmacology).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','CNS Pharmacology','The action of hypnotic drugs is to induce:','Vomiting','Appetite','Sleep','Calmness','C','Hypnotics (e.g. zolpidem, temazepam) induce and maintain sleep; sedatives reduce anxiety. Nurses assess sleep hygiene, risk of dependence, and residual sedation in older adults (BNF).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q5: Antidote for morphine — naloxone ──────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Antidotes','The antidote for morphine toxicity is:','Methadone','Fentanyl','Amphetamine','Naloxone','D','Naloxone is the specific opioid antagonist used to reverse morphine (opioid) toxicity and respiratory depression (BNF; MOH Kenya poisoning protocols).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Antidotes','The antidote for morphine toxicity is:','Methadone','Fentanyl','Amphetamine','Naloxone','D','Naloxone reverses all opioid effects including respiratory depression; its short half-life may require repeat doses or infusion. Nurses monitor for re-narcotisation and acute withdrawal (BNF; MOH Kenya poisoning protocols).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q6: Bioavailability — absorption and transport to target tissue ────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Pharmacokinetics','The extent to which a drug is absorbed and transported to the target tissue is known as:','Steady-state accumulation','Therapeutic drug level','Bioavailability','Distribution','C','Bioavailability is the proportion of an administered dose that reaches the systemic circulation and thus the target tissue (pharmacokinetics; Brunner & Suddarth).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Pharmacokinetics','The extent to which a drug is absorbed and transported to the target tissue is known as:','Steady-state accumulation','Therapeutic drug level','Bioavailability','Distribution','C','Bioavailability (F) is affected by route, first-pass metabolism and formulation; IV = 100%. Understanding bioavailability guides dose adjustments when switching routes (BNF; pharmacokinetics).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q7: Pharmacokinetics — actions of body on drug ────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Pharmacokinetics','The actions of the body on the drug are referred to as:','Pharmacodynamics','Pharmacokinetics','Pharmacognosy','Pharmacogenomics','B','Pharmacokinetics describes what the body does to the drug — absorption, distribution, metabolism and excretion (ADME); pharmacodynamics is what the drug does to the body (standard pharmacology).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Pharmacokinetics','The actions of the body on the drug are referred to as:','Pharmacodynamics','Pharmacokinetics','Pharmacognosy','Pharmacogenomics','B','Pharmacokinetics (ADME) determines drug plasma levels and dosing intervals; nurses apply PK principles to recognise accumulation in renal/hepatic impairment and adjust timing of monitoring (BNF; pharmacology).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q8: Mannitol — osmotic diuretic ──────────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Diuretics','Mannitol is classified as:','Potassium-wasting diuretic','Loop diuretic','Osmotic diuretic','Potassium-sparing diuretic','C','Mannitol is an osmotic diuretic used to reduce raised intracranial or intraocular pressure by drawing fluid from tissues into the circulation (BNF).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Diuretics','Mannitol is classified as:','Potassium-wasting diuretic','Loop diuretic','Osmotic diuretic','Potassium-sparing diuretic','C','Mannitol osmotically draws water into the vascular space; used in raised ICP and acute closed-angle glaucoma. Nurses monitor serum osmolality and electrolytes (BNF; critical care pharmacology).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q9: Atenolol — beta blocker ───────────────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Cardiovascular Pharmacology','Atenolol is classified as:','Beta-2 agonist','Beta blocker','ACE inhibitor','Calcium channel blocker','B','Atenolol is a cardioselective beta-adrenoceptor blocker used in hypertension, angina and dysrhythmias (BNF cardiovascular drugs).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Cardiovascular Pharmacology','Atenolol is classified as:','Beta-2 agonist','Beta blocker','ACE inhibitor','Calcium channel blocker','B','Atenolol (cardioselective beta-1 blocker) reduces heart rate and BP; contraindicated in asthma and heart block. Nurses monitor pulse before administration (BNF; Brunner & Suddarth).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q10: Penicillins — methicillin sodium, nafcillin sodium ───────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Antimicrobials','The drugs classified as penicillins include:','Methicillin Sodium, Nafcillin Sodium','Penicillin V, Ciprofloxacin','Ampicillin, Doxycycline','Erythromycin, Sotalol','A','Methicillin sodium and nafcillin sodium are both penicillinase-resistant penicillins; other options pair penicillins with fluoroquinolones, tetracyclines or macrolides (BNF antibacterials).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Antimicrobials','The drugs classified as penicillins include:','Methicillin Sodium, Nafcillin Sodium','Penicillin V, Ciprofloxacin','Ampicillin, Doxycycline','Erythromycin, Sotalol','A','Penicillinase-resistant penicillins (methicillin, nafcillin) target MSSA; nurses must distinguish penicillin subclasses for MRSA vs sensitive staphylococci and monitor for anaphylaxis (BNF).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q11: Digitalis toxicity — cardiac arrhythmias ─────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Cardiovascular Pharmacology','The major sign of digitalis toxicity is:','Cardiac arrhythmias','Paraesthesia','Excessive slowing of pulse','Generalised muscle weakness','A','Digitalis (digoxin) toxicity chiefly manifests as cardiac arrhythmias — bradycardia, AV block, atrial tachycardia with block, ectopic beats (BNF; Brunner & Suddarth cardiac glycoside pharmacology).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Cardiovascular Pharmacology','The major sign of digitalis toxicity is:','Cardiac arrhythmias','Paraesthesia','Excessive slowing of pulse','Generalised muscle weakness','A','Digoxin toxicity (narrow therapeutic index) presents with arrhythmias, nausea, visual disturbances; nurses check apical pulse <60 bpm before dosing and monitor digoxin levels and potassium (BNF; Brunner & Suddarth).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q12: Antiulcer agents — famotidine, sucralfate ────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Gastrointestinal Pharmacology','The antiulcer agents include:','Cimetidine, Amitriptyline','Omeprazole, Tramadol','Famotidine, Sucralfate','Praziquantel, Ranitidine Hydrochloride','C','Famotidine (H2-receptor antagonist) and sucralfate (mucosal protectant) are both antiulcer agents; other distractors pair antiulcer drugs with antidepressants, opioids or anthelmintics (BNF).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Gastrointestinal Pharmacology','The antiulcer agents include:','Cimetidine, Amitriptyline','Omeprazole, Tramadol','Famotidine, Sucralfate','Praziquantel, Ranitidine Hydrochloride','C','Famotidine reduces gastric acid secretion; sucralfate forms a protective barrier over ulcer base. Nurses schedule antacids and sucralfate away from other medications to prevent absorption interference (BNF).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q13: Praziquantel contraindication — ocular cysticercosis ─────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Antiparasitic Drugs','The major contraindication to praziquantel is use in patients with:','Hepatic dysfunction','Ocular cysticercosis','Lymphadenopathy','Peptic ulcer disease','B','Praziquantel is contraindicated in ocular cysticercosis because parasite destruction inside the eye triggers an intense inflammatory response that can cause irreparable ocular damage (BNF/anthelmintic guidelines).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Antiparasitic Drugs','The major contraindication to praziquantel is use in patients with:','Hepatic dysfunction','Ocular cysticercosis','Lymphadenopathy','Peptic ulcer disease','B','In ocular cysticercosis, praziquantel-induced parasite lysis in the eye causes local inflammatory destruction; surgical removal is preferred. Nurses screen patients for eye involvement before prescribing (BNF; Kenya NTD guidelines).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q14: Half-life — concentration reduced by half ────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Pharmacokinetics','The time required to reduce the concentration of a drug in the body by one half is called:','Time course','Time period','Half-life','Half lifespan','C','Half-life (t½) is the time for plasma drug concentration to fall by 50%; it determines dosing frequency and time to steady state (pharmacokinetics; Brunner & Suddarth).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Pharmacokinetics','The time required to reduce the concentration of a drug in the body by one half is called:','Time course','Time period','Half-life','Half lifespan','C','t½ governs dosing intervals; ~4–5 half-lives to reach steady state. Extended in renal/hepatic disease — nurses adjust monitoring frequency accordingly (BNF; pharmacokinetics).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q15: Nifedipine mechanism — inhibits calcium influx ───────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Cardiovascular Pharmacology','The mode of action of nifedipine (Adalat) is that it:','Inhibits calcium ion influx across cardiac and smooth muscle cells, decreasing myocardial contractility and oxygen demand','Stabilises neuronal membrane and limits seizure activity by decreasing sodium influx','Depresses monosynaptic transmission in the CNS and raises the seizure threshold','Increases norepinephrine and serotonin in the CNS by blocking their reuptake','A','Nifedipine is a dihydropyridine calcium-channel blocker that inhibits calcium influx across cardiac and vascular smooth muscle, reducing contractility and peripheral resistance (BNF cardiovascular drugs).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Cardiovascular Pharmacology','The mode of action of nifedipine (Adalat) is that it:','Inhibits calcium ion influx across cardiac and smooth muscle cells, decreasing myocardial contractility and oxygen demand','Stabilises neuronal membrane and limits seizure activity by decreasing sodium influx','Depresses monosynaptic transmission in the CNS and raises the seizure threshold','Increases norepinephrine and serotonin in the CNS by blocking their reuptake','A','Nifedipine inhibits L-type Ca²⁺ channels; used in hypertension, angina. Peripheral vasodilation may cause reflex tachycardia. Nurses monitor BP, pulse, and peripheral oedema (BNF; Brunner & Suddarth).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q19: Bronchodilators — amoline, aminophylline ────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Respiratory Pharmacology','The following drugs are bronchodilators:','Aminophylline, Nifedipine','Theophylline, Amiloride','Amoline, Aminophylline','Amiloride, Amitriptyline','C','Amoline and aminophylline are methylxanthine bronchodilators that inhibit phosphodiesterase; nifedipine is a calcium-channel blocker and amiloride is a potassium-sparing diuretic (BNF respiratory drugs).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Respiratory Pharmacology','The following drugs are bronchodilators:','Aminophylline, Nifedipine','Theophylline, Amiloride','Amoline, Aminophylline','Amiloride, Amitriptyline','C','Methylxanthines (aminophylline/theophylline) have a narrow therapeutic index; nurses monitor serum levels, toxicity signs (tachycardia, seizures) and drug interactions (BNF).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q20: Naloxone — pure narcotic antagonist with no agonistic activity ────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Antidotes','Naloxone is the drug of choice for narcotic toxicity because it:','Exerts both antagonist and agonist activity','Is a pure narcotic antagonist with no agonistic activity','Is effective for respiratory depression caused by other CNS depressants','Has no narcotic action','B','Naloxone is a pure opioid receptor antagonist with no intrinsic agonist activity, making it safe and specific for reversing opioid toxicity without producing euphoria or dependence (BNF).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Antidotes','Naloxone is the drug of choice for narcotic toxicity because it:','Exerts both antagonist and agonist activity','Is a pure narcotic antagonist with no agonistic activity','Is effective for respiratory depression caused by other CNS depressants','Has no narcotic action','B','Naloxone''s lack of agonist activity makes it safe; it does NOT reverse benzodiazepine or barbiturate depression. Nurses differentiate mixed overdose presentations and titrate dose carefully to avoid precipitating acute withdrawal (BNF; MOH Kenya poisoning guidelines).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q21: Cephalosporins — cefotaxime, Precef, Cefotan ─────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Antimicrobials','Cephalosporin drugs include:','Cefotaxime sodium, Precef, Cefotan','Cefotan, Cefoxitin sodium, Carbinoxamine','Ceftizoxime sodium, Cefuroxime, Carbamazepine','Cephalexin, Cephradine, Carmustine','A','Cefotaxime sodium (3rd gen), Precef (ceforanide, 2nd gen) and Cefotan (cefotetan, 2nd gen) are all cephalosporins; other options include antihistamines, anticonvulsants or antineoplastics (BNF antibacterials).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Antimicrobials','Cephalosporin drugs include:','Cefotaxime sodium, Precef, Cefotan','Cefotan, Cefoxitin sodium, Carbinoxamine','Ceftizoxime sodium, Cefuroxime, Carbamazepine','Cephalexin, Cephradine, Carmustine','A','Nurses must identify cephalosporin generations to anticipate spectrum of activity and cross-reactivity with penicillin allergy (BNF; Brunner & Suddarth antimicrobial pharmacology).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q22: Emergency route — intravenous injection ──────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Pharmacokinetics','The most appropriate route of drug administration in an emergency is:','Intramuscular injection','Intravenous injection','Oral administration','Per rectum','B','Intravenous injection provides immediate, 100% bioavailability and the most rapid onset of action, making it the preferred route in emergencies (Kenya Basic Paediatric Protocols; Brunner & Suddarth).','medium',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Pharmacokinetics','The most appropriate route of drug administration in an emergency is:','Intramuscular injection','Intravenous injection','Oral administration','Per rectum','B','IV route bypasses absorption, giving immediate drug availability; critical in cardiac arrest, anaphylaxis and status epilepticus. Nurses must maintain IV access and competence in emergency drug administration (BNF; Brunner & Suddarth).','medium',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q23: Suboptimal drug use — dose too small, course too short ───────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Pharmacokinetics','Suboptimal use of a drug may lead to treatment failure due to:','Too small a dose and late treatment','Unstable route and too long an interval between doses','Unsuitable route and high incidence of drug reactions','Duration of course too short and dose too small','D','Sub-therapeutic dosing — course duration too short or dose too small — fails to achieve adequate drug concentration to eliminate the pathogen or resolve the condition, promoting resistance (BNF/pharmacology).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Pharmacokinetics','Suboptimal use of a drug may lead to treatment failure due to:','Too small a dose and late treatment','Unstable route and too long an interval between doses','Unsuitable route and high incidence of drug reactions','Duration of course too short and dose too small','D','Subtherapeutic regimens contribute to antimicrobial resistance — a global public health priority. Nurses provide adherence counselling, ensure complete courses and document therapy accurately (BNF; WHO AMR guidelines).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q24: Nursing intervention for nifedipine — monitor BP ────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Cardiovascular Pharmacology','One nursing intervention for a patient on nifedipine is:','Teach client about drug dosage','Monitor blood pressure','Establish safety precautions for falls','Increase the drug dose if BP remains high','B','Nifedipine lowers blood pressure by vasodilation; the primary nursing action is monitoring BP before and after administration to detect hypotension (Brunner & Suddarth; BNF).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Cardiovascular Pharmacology','One nursing intervention for a patient on nifedipine is:','Teach client about drug dosage','Monitor blood pressure','Establish safety precautions for falls','Increase the drug dose if BP remains high','B','BP monitoring guides nifedipine titration; nurses also assess for peripheral oedema, reflex tachycardia and grapefruit juice interaction. Dose adjustment is a prescriber role (BNF; Brunner & Suddarth).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q25: Amoxicillin — bactericidal, inhibits cell wall synthesis ─────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Antimicrobials','The therapeutic action of amoxicillin is:','Bactericidal, inhibits protein synthesis','Inhibits bacterial cell wall synthesis and binds to sterols','Bactericidal, inhibits cell wall synthesis','Inhibits synthesis of cell wall and binds to sterols','C','Amoxicillin is bactericidal, acting by inhibiting bacterial cell-wall synthesis through binding penicillin-binding proteins (BNF antibacterials).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Antimicrobials','The therapeutic action of amoxicillin is:','Bactericidal, inhibits protein synthesis','Inhibits bacterial cell wall synthesis and binds to sterols','Bactericidal, inhibits cell wall synthesis','Inhibits synthesis of cell wall and binds to sterols','C','Amoxicillin inhibits transpeptidation in cell wall synthesis; binds to sterols describes polyene antifungals. Nurses apply this distinction when interpreting sensitivity reports (BNF; pharmacology).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q26: Therapeutic coagulants — phytonadione, phytomenadione ───────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Anticoagulant Therapy','The following drugs are therapeutic coagulants:','Heparin, Coumarin derivatives','Coumarin derivatives, Vitamin K','Indanedione derivatives, Phytomenadione','Phytonadione, Phytomenadione','D','Phytonadione and phytomenadione are both names for vitamin K1 — a procoagulant used to reverse anticoagulation and treat haemorrhage due to vitamin K deficiency; heparin and coumarins are anticoagulants (BNF).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Anticoagulant Therapy','The following drugs are therapeutic coagulants:','Heparin, Coumarin derivatives','Coumarin derivatives, Vitamin K','Indanedione derivatives, Phytomenadione','Phytonadione, Phytomenadione','D','Vitamin K1 (phytonadione/phytomenadione) reverses warfarin and treats haemorrhagic disease of the newborn. Nurses administer IM at birth per Kenya EPI/newborn care guidelines (BNF).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q27: Potassium-sparing diuretic — spironolactone ─────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Diuretics','An example of a potassium-sparing diuretic is:','Furosemide','Thiazides','Spironolactone','Ethacrynic acid','C','Spironolactone is an aldosterone antagonist and prototype potassium-sparing diuretic; furosemide and ethacrynic acid are loop diuretics (potassium-losing) and thiazides are also potassium-losing (BNF diuretics).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Diuretics','An example of a potassium-sparing diuretic is:','Furosemide','Thiazides','Spironolactone','Ethacrynic acid','C','Spironolactone blocks aldosterone receptors, retaining potassium; used in heart failure, cirrhotic ascites. Nurses monitor K⁺ and avoid co-prescribing ACE inhibitors without close monitoring (BNF; Brunner & Suddarth).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q28: Prazosin — antihypertensive, alpha-adrenergic blocker ───────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Cardiovascular Pharmacology','Prazosin hydrochloride (Minipress) is classified as:','Antihypertensive, alpha-adrenergic blocking drug','Alpha-adrenergic blocking drug, beta blocker','Beta blocker, antihypertensive drug','Calcium channel blocker, beta blocker','A','Prazosin is a selective alpha-1 adrenoceptor blocker used as an antihypertensive; it reduces peripheral vascular resistance without reflexly increasing heart rate significantly (BNF).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Cardiovascular Pharmacology','Prazosin hydrochloride (Minipress) is classified as:','Antihypertensive, alpha-adrenergic blocking drug','Alpha-adrenergic blocking drug, beta blocker','Beta blocker, antihypertensive drug','Calcium channel blocker, beta blocker','A','Prazosin causes first-dose hypotension; nurses instruct patients to take the first dose at bedtime and rise slowly. Also used in BPH to relax urethral smooth muscle (BNF; Brunner & Suddarth).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q29: Ipratropium bromide — anticholinergic for rhinitis and colds ─────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Respiratory Pharmacology','Ipratropium bromide is:','A cholinergic agent used for perennial rhinitis','An anticholinergic used for allergic rhinitis and colds','Only used in patients with asthma','Inappropriate for use in allergic rhinitis','B','Ipratropium bromide is an anticholinergic (muscarinic antagonist) used for rhinorrhoea in allergic/perennial rhinitis and the common cold, as well as for bronchospasm in COPD/asthma (BNF).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Respiratory Pharmacology','Ipratropium bromide is:','A cholinergic agent used for perennial rhinitis','An anticholinergic used for allergic rhinitis and colds','Only used in patients with asthma','Inappropriate for use in allergic rhinitis','B','Ipratropium blocks muscarinic receptors, reducing secretions. Used in COPD (inhaled), rhinitis (nasal spray) and acute severe asthma (nebulised with salbutamol). Nurses assess its additive effect with other anticholinergics (BNF; MOH Kenya asthma/COPD guidelines).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q30: Highest patient compliance — oral route ──────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Pharmacokinetics','The route of drug administration with the highest patient compliance is:','Intravenous','Intramuscular','Oral','Intrathecal','C','The oral route is the most convenient, non-invasive and best-accepted by patients, giving the highest compliance; invasive routes (IV, IM, intrathecal) require healthcare professional administration (BNF; pharmacology).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Pharmacokinetics','The route of drug administration with the highest patient compliance is:','Intravenous','Intramuscular','Oral','Intrathecal','C','Oral bioavailability varies but compliance is highest due to ease and autonomy; nurses promote adherence through patient education and simplifying regimens. Contrast with IV (100% bioavailability, lowest compliance) (BNF; pharmacology).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q31: Erythromycin — inhibits protein synthesis (50S ribosome) ────────────
-- Audit note: Source document states "IDNA synthesis" — this is a transcription error
-- in the source. The correct answer is protein synthesis inhibition at the 50S ribosome.
-- Answer verified against BNF/pharmacology; corrected here.
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Antimicrobials','Erythromycin exerts its antibacterial activity by:','Inhibiting cell wall synthesis','Inhibiting protein synthesis at the 50S ribosomal subunit','Increasing cell wall permeability','Interfering with folic acid utilisation','B','Erythromycin is a macrolide antibiotic that inhibits bacterial protein synthesis by binding to the 50S ribosomal subunit and blocking translocation; it does not inhibit DNA synthesis or cell-wall synthesis (BNF; pharmacology).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Antimicrobials','Erythromycin exerts its antibacterial activity by:','Inhibiting cell wall synthesis','Inhibiting protein synthesis at the 50S ribosomal subunit','Increasing cell wall permeability','Interfering with folic acid utilisation','B','Macrolides (erythromycin, azithromycin) bind 50S ribosome; bacteriostatic against most organisms. Erythromycin is a CYP3A4 inhibitor causing significant drug interactions — nurses review concomitant medications (BNF).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q32: Bulk-forming laxatives — function like dietary fibre ────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Gastrointestinal Pharmacology','Bulk-forming laxatives:','Function like dietary fibre','Act within 2 to 6 hours','Produce a semi-fluid stool','Are used to prepare the bowel for diagnostic procedures','A','Bulk-forming laxatives (e.g. ispaghula husk, methylcellulose) absorb water to increase faecal bulk and stimulate peristalsis, acting like dietary fibre; they require adequate fluid intake (BNF laxatives).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Gastrointestinal Pharmacology','Bulk-forming laxatives:','Function like dietary fibre','Act within 2 to 6 hours','Produce a semi-fluid stool','Are used to prepare the bowel for diagnostic procedures','A','Bulk-formers increase stool volume and soften consistency; onset 12–72 hours. Nurses instruct patients to take with adequate water and not to use if dysphagia or intestinal obstruction (BNF; Brunner & Suddarth).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q33: Praziquantel — drug of choice for schistosomiasis ───────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Antiparasitic Drugs','Praziquantel is the drug of choice in treatment of:','Herpes simplex','Fungal meningitis','Roundworms','Schistosomiasis','D','Praziquantel is the first-line drug for schistosomiasis and other trematode/cestode infections; it is not effective against herpes (antiviral needed), fungal meningitis (antifungal needed), or roundworms (albendazole/mebendazole) (Kenya MOH NTD guidelines; BNF).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Antiparasitic Drugs','Praziquantel is the drug of choice in treatment of:','Herpes simplex','Fungal meningitis','Roundworms','Schistosomiasis','D','Praziquantel causes tegumental damage and muscular contraction in schistosomes; single-dose treatment. Nurses assess for ocular cysticercosis contraindication and monitor for seizures in neurocysticercosis (Kenya MOH NTD guidelines; BNF).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q34: Dronabinol — antiemetic for chemotherapy-induced nausea ──────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Gastrointestinal Pharmacology','The appropriate drug to give a patient with nausea after chemotherapy is:','Loperamide','Ranitidine','Dronabinol','Lorazepam','C','Dronabinol is a cannabinoid antiemetic specifically indicated for chemotherapy-induced nausea and vomiting refractory to conventional antiemetics; loperamide is antidiarrhoeal and ranitidine is an H2 blocker (Brunner & Suddarth; BNF).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Gastrointestinal Pharmacology','The appropriate drug to give a patient with nausea after chemotherapy is:','Loperamide','Ranitidine','Dronabinol','Lorazepam','C','Chemotherapy-induced nausea is managed with 5-HT3 antagonists (ondansetron), dexamethasone and cannabinoids (dronabinol) in resistant cases. Nurses schedule antiemetics prophylactically before each cycle (BNF; oncology nursing guidelines).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q35: Angiotensin II blockers — contraindicated in pregnancy ───────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Cardiovascular Pharmacology','The following statement is true about antihypertensive drugs:','ACE inhibitors are safe in the 2nd and 3rd trimesters of pregnancy','Angiotensin II inhibitors block conversion of angiotensin I to angiotensin II','Angiotensin II blockers are contraindicated in pregnancy','None of the above','C','Both ACE inhibitors and angiotensin II receptor blockers (ARBs) are contraindicated in pregnancy due to fetotoxicity (renal tubular dysplasia, oligohydramnios, neonatal renal failure); ARBs block the receptor, not the converting enzyme (BNF; MOH Kenya hypertension guidelines).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Cardiovascular Pharmacology','The following statement is true about antihypertensive drugs:','ACE inhibitors are safe in the 2nd and 3rd trimesters of pregnancy','Angiotensin II inhibitors block conversion of angiotensin I to angiotensin II','Angiotensin II blockers are contraindicated in pregnancy','None of the above','C','ACEi and ARBs both contraindicated in pregnancy (RAAS inhibition causes fetal renal malformations); safe alternatives include methyldopa, labetalol, nifedipine. Nurses screen antihypertensives at first ANC contact (BNF; MOH Kenya ANC guidelines).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q36: 4-aminoquinolines for malaria — hydroxychloroquine, mefloquine ────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Antiparasitic Drugs','4-aminoquinoline derivatives used in treatment of malaria include:','Quinine, artemisinin','Chloroquine, pyrimethamine','Hydroxychloroquine, mefloquine','Amodiaquine, sulfamethoxazole','C','Hydroxychloroquine is a 4-aminoquinoline and mefloquine is a quinoline-methanol; both target the same class. Pyrimethamine is an antifolate and sulfamethoxazole is a sulphonamide — neither is a 4-aminoquinoline (BNF; Kenya NMCP malaria guidelines).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Antiparasitic Drugs','4-aminoquinoline derivatives used in treatment of malaria include:','Quinine, artemisinin','Chloroquine, pyrimethamine','Hydroxychloroquine, mefloquine','Amodiaquine, sulfamethoxazole','C','4-aminoquinolines disrupt haem detoxification in the parasite food vacuole; resistance to chloroquine is widespread in Kenya necessitating ACT first-line. Nurses apply Kenya NMCP treatment guidelines (BNF; Kenya NMCP).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q37: Sublingual nitroglycerin — avoids first-pass hepatic metabolism ────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Cardiovascular Pharmacology','In a patient with angina, nitroglycerin may be given sublingually because this mode of administration:','Bypasses the coronary circulation','Causes less reflex tachycardia than oral administration','Improves patient compliance','Avoids first-pass hepatic metabolism','D','Sublingual absorption delivers nitroglycerin directly into the systemic circulation, bypassing the extensive first-pass hepatic metabolism that would inactivate most of an orally swallowed dose (BNF; Brunner & Suddarth).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Cardiovascular Pharmacology','In a patient with angina, nitroglycerin may be given sublingually because this mode of administration:','Bypasses the coronary circulation','Causes less reflex tachycardia than oral administration','Improves patient compliance','Avoids first-pass hepatic metabolism','D','Sublingual GTN acts within 1–3 minutes; nurses instruct: sit down, one tablet under tongue, repeat every 5 minutes up to 3 doses, call emergency if pain persists. Hypotension and headache are common side effects (BNF; Brunner & Suddarth).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q38: Warfarin — teratogenic in pregnancy ─────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Anticoagulant Therapy','Regarding warfarin, which statement is true?','It is a rapid-acting anticoagulant','It has poor absorption across membranes','It has teratogenic effects when administered in pregnancy','It is administered through the intravenous route','C','Warfarin crosses the placenta and causes fetal warfarin syndrome (nasal hypoplasia, stippled epiphyses, CNS defects); it is contraindicated especially in the first trimester. It is slow-acting and well-absorbed orally (BNF anticoagulants).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Anticoagulant Therapy','Regarding warfarin, which statement is true?','It is a rapid-acting anticoagulant','It has poor absorption across membranes','It has teratogenic effects when administered in pregnancy','It is administered through the intravenous route','C','Warfarin is teratogenic (contraindicated in pregnancy — use LMWH instead); onset 2–3 days, monitored by INR. Nurses educate on consistent vitamin K intake, drug interactions and bleeding signs (BNF; MOH Kenya anticoagulation guidelines).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q39: Cromolyn — suppresses histamine release from mast cells ─────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Respiratory Pharmacology','Cromolyn is useful in asthma because it:','Suppresses release of histamine from mast cells','Blocks adenosine receptors in bronchiolar smooth muscle','Decreases bronchial hyperactivity','Decreases bacterial load in the bronchioles','A','Cromolyn (sodium cromoglicate) is a mast-cell stabiliser that inhibits degranulation and thus suppresses the release of histamine and other inflammatory mediators (BNF respiratory; Brunner & Suddarth).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Respiratory Pharmacology','Cromolyn is useful in asthma because it:','Suppresses release of histamine from mast cells','Blocks adenosine receptors in bronchiolar smooth muscle','Decreases bronchial hyperactivity','Decreases bacterial load in the bronchioles','A','Sodium cromoglicate stabilises mast cells, used prophylactically (not for acute attacks). Nurses educate patients on consistent use and that it will not relieve acute bronchospasm (BNF; Kenya asthma management guidelines).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q40: Quinine — drug derived from a plant ─────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Pharmacognosy','An example of a drug derived from a plant is:','Glibenclamide','Quinine','Mechlorethamine','Rifapentine','B','Quinine is an alkaloid derived from the bark of the Cinchona tree (Cinchona officinalis), one of the earliest plant-derived antimalarial drugs (Kenya malaria pharmacology; pharmacognosy texts).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Pharmacognosy','An example of a drug derived from a plant is:','Glibenclamide','Quinine','Mechlorethamine','Rifapentine','B','Plant-derived drugs include quinine (Cinchona), morphine (opium poppy), digoxin (foxglove), atropine (belladonna). Understanding botanical origins helps nurses appreciate pharmacognosy and traditional medicine integration (pharmacognosy; Kenya pharmacology curriculum).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q41: Highest bioavailability — intravenous route ─────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Pharmacokinetics','The route of drug administration with the highest drug bioavailability is:','Oral','Intramuscular','Intradermal','Intravenous','D','Intravenous administration delivers the drug directly into the bloodstream, bypassing all absorption barriers, giving 100% bioavailability — the highest of any route (pharmacokinetics; BNF).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Pharmacokinetics','The route of drug administration with the highest drug bioavailability is:','Oral','Intramuscular','Intradermal','Intravenous','D','IV = 100% bioavailability (F=1); other routes involve variable absorption. When calculating equivalent oral doses nurses must account for lower oral bioavailability (e.g. oral morphine bioavailability ~30%) (BNF; pharmacokinetics).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q42: Opioid antagonist — naltrexone ───────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Antidotes','The following is an opioid antagonist:','Flumazenil','Naltrexone','Sufentanil','Methadone','B','Naltrexone is a pure opioid receptor antagonist used for maintenance therapy in opioid and alcohol dependence; flumazenil is a benzodiazepine antagonist, sufentanil and methadone are opioid agonists (BNF).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Antidotes','The following is an opioid antagonist:','Flumazenil','Naltrexone','Sufentanil','Methadone','B','Naltrexone (oral) is used in opioid and alcohol dependence programmes; precipitates withdrawal if opioids are still present. Nurses ensure opioid-free period before initiation (BNF; Kenya substance use management guidelines).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q43: Nifedipine — not used for fluid retention ───────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Cardiovascular Pharmacology','The following condition is NOT treated using nifedipine:','Angina','Arrhythmias','Hypertension','Fluid retention','D','Nifedipine treats angina, hypertension and some arrhythmias, but is not used for fluid retention — it can actually cause peripheral oedema as a side effect due to vasodilation (BNF calcium-channel blockers).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Cardiovascular Pharmacology','The following condition is NOT treated using nifedipine:','Angina','Arrhythmias','Hypertension','Fluid retention','D','Nifedipine-induced peripheral oedema is due to arteriolar vasodilation (not fluid overload); diuretics are used for fluid retention. Nurses distinguish drug-induced oedema from fluid overload in management (BNF; Brunner & Suddarth).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q44: Organophosphate antidote — atropine ──────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Antidotes','The drug used for organophosphate poisoning is:','Atropine','Pilocarpine','Propranolol','Edrophonium','A','Atropine is the antidote for organophosphate poisoning; it antagonises the muscarinic effects (bradycardia, bronchospasm, hypersecretion) of acetylcholine accumulation caused by cholinesterase inhibition (Kenya MOH poisoning protocols; BNF).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Antidotes','The drug used for organophosphate poisoning is:','Atropine','Pilocarpine','Propranolol','Edrophonium','A','Organophosphate poisoning: SLUDGE signs (salivation, lacrimation, urination, defaecation, GI cramps, emesis). Atropine large doses IV + pralidoxime (reactivates cholinesterase if given early). Nurses manage airway and secretions (BNF; Kenya MOH poisoning guidelines).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q45: Sulphonamides — cotrimoxazole, sulfamethoxazole, sulfasalazine ────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Antimicrobials','The drugs classified as sulphonamides include:','Cotrimoxazole, Sulfamethoxazole, Sulfasalazine','Sulfadiazine, Sulfisoxazole, Spironolactone','Sulfinpyrazone, Sulfasalazine, Sulfamethoxazole','Cefpodoxime proxetil, Cotrimoxazole, Sulfadiazine','A','Cotrimoxazole (trimethoprim + sulfamethoxazole), sulfamethoxazole and sulfasalazine are all sulphonamide derivatives; spironolactone and sulfinpyrazone are not sulphonamide antibacterials (BNF antibacterials).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Antimicrobials','The drugs classified as sulphonamides include:','Cotrimoxazole, Sulfamethoxazole, Sulfasalazine','Sulfadiazine, Sulfisoxazole, Spironolactone','Sulfinpyrazone, Sulfasalazine, Sulfamethoxazole','Cefpodoxime proxetil, Cotrimoxazole, Sulfadiazine','A','Sulphonamides inhibit dihydropteroate synthase in folate synthesis; cotrimoxazole is key in Kenya for PCP prophylaxis in HIV. Nurses monitor for hypersensitivity, haematological effects and renal crystalluria (BNF; NASCOP guidelines).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q46: Local anaesthetics — block sodium channels ───────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Anaesthesia Pharmacology','Local anaesthetics work by:','Blocking calcium ion channels to prevent depolarisation','Blocking potassium ion channels to prevent depolarisation','Blocking sodium ion channels to prevent depolarisation','Blocking impulses at the neuromuscular junction','C','Local anaesthetics block voltage-gated sodium channels, preventing membrane depolarisation and nerve impulse conduction, thereby producing reversible loss of sensation (BNF; pharmacology).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Anaesthesia Pharmacology','Local anaesthetics work by:','Blocking calcium ion channels to prevent depolarisation','Blocking potassium ion channels to prevent depolarisation','Blocking sodium ion channels to prevent depolarisation','Blocking impulses at the neuromuscular junction','C','Local anaesthetics (lidocaine, bupivacaine) block Na⁺ channels in a use-dependent manner; systemic toxicity causes CNS excitation then cardiovascular collapse. Nurses monitor for toxicity signs after regional blocks (BNF; Brunner & Suddarth).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q47: Tetracycline in pregnancy — tooth and bone defects ──────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Antimicrobials','Pregnant women should not take tetracycline because it has been associated with:','Grey baby syndrome','Tooth and bone defects in neonates','Acne','Excessive bleeding','B','Tetracyclines chelate calcium and are deposited in developing teeth and bones, causing permanent yellow-brown discolouration and skeletal growth inhibition in the fetus and neonates; contraindicated in pregnancy and children under 12 years (BNF; Kenya MOH guidelines).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Antimicrobials','Pregnant women should not take tetracycline because it has been associated with:','Grey baby syndrome','Tooth and bone defects in neonates','Acne','Excessive bleeding','B','Tetracycline deposits in mineralising tissues; grey baby syndrome is caused by chloramphenicol. Nurses counsel pregnant patients to avoid tetracyclines and use safe alternatives (e.g. azithromycin for chlamydia in pregnancy) (BNF; MOH Kenya ANC guidelines).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q48: Acyclovir — inhibits viral DNA synthesis ────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Antimicrobials','The mode of action of acyclovir as a drug of choice for herpes virus is:','Inhibits viral RNA synthesis','Inhibits viral DNA synthesis','Inhibits viral protein synthesis','Inhibits viral capsule formation','B','Acyclovir is phosphorylated by viral thymidine kinase to acyclovir triphosphate, which inhibits viral DNA polymerase, halting viral DNA replication selectively in infected cells (BNF; Brunner & Suddarth antiviral pharmacology).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Antimicrobials','The mode of action of acyclovir as a drug of choice for herpes virus is:','Inhibits viral RNA synthesis','Inhibits viral DNA synthesis','Inhibits viral protein synthesis','Inhibits viral capsule formation','B','Acyclovir selective toxicity depends on viral thymidine kinase activation; resistance occurs when this enzyme is absent. Nurses administer IV acyclovir for severe herpes encephalitis and monitor renal function and hydration (BNF).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q49: Cromolyn — prevents histamine synthesis/release in mast cells ─────────
-- Audit note: Q39 tested cromolyn in asthma context; Q49 stem is meaningfully different
-- (focuses on mechanism re: mast cell histamine prevention) — seed per §14.5
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Respiratory Pharmacology','A drug that prevents the release of histamine from mast cells is:','Cromolyn','Cetirizine','Aminophylline','Montelukast','A','Cromolyn (sodium cromoglicate) is a mast-cell stabiliser that prevents degranulation and histamine release; cetirizine is an H1-receptor antagonist; aminophylline is a bronchodilator; montelukast is a leukotriene receptor antagonist (BNF).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Respiratory Pharmacology','A drug that prevents the release of histamine from mast cells is:','Cromolyn','Cetirizine','Aminophylline','Montelukast','A','Mast-cell stabilisers prevent IgE-triggered degranulation; prophylactic only. Nurses distinguish them from antihistamines (post-release block) and leukotriene antagonists, applying each appropriately in asthma step-care (BNF; Kenya asthma management guidelines).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q50: Antacid teaching — stagger from other medications ───────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Gastrointestinal Pharmacology','When teaching a client about proper use of antacids, the nurse should instruct them to:','Stagger the administration of antacids with other medications','Take antacids with all other medications simultaneously','Take other medications in the daytime and antacids at night','Drink a glass of water immediately after taking antacids','A','Antacids alter gastric pH and chelate certain drugs (e.g. fluoroquinolones, tetracyclines, iron), significantly reducing their absorption; staggering doses by at least 1–2 hours prevents this interaction (BNF; pharmacology).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Gastrointestinal Pharmacology','When teaching a client about proper use of antacids, the nurse should instruct them to:','Stagger the administration of antacids with other medications','Take antacids with all other medications simultaneously','Take other medications in the daytime and antacids at night','Drink a glass of water immediately after taking antacids','A','Antacids chelate and raise pH impairing absorption of quinolones, tetracyclines, digoxin, iron. Nurses review polypharmacy, apply 2-hour separation rule and educate on symptom management without over-reliance on antacids (BNF; pharmacology).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q51: 4-aminoquinolines — amodiaquine, chloroquine, hydroxychloroquine ────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Antiparasitic Drugs','4-aminoquinoline derivative antimalarial drugs include:','Quinine, amodiaquine, chloroquine','Alphametafloquine, fansidar, hydroxychloroquine','Amodiaquine, chloroquine, hydroxychloroquine','Mefloquine, artesunate, artemether','C','Amodiaquine, chloroquine and hydroxychloroquine are all 4-aminoquinolines; quinine is a quinoline-methanol, mefloquine is a quinoline-methanol, artesunate and artemether are artemisinins (BNF antimalarials; Kenya NMCP guidelines).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Antiparasitic Drugs','4-aminoquinoline derivative antimalarial drugs include:','Quinine, amodiaquine, chloroquine','Alphametafloquine, fansidar, hydroxychloroquine','Amodiaquine, chloroquine, hydroxychloroquine','Mefloquine, artesunate, artemether','C','4-aminoquinolines impair haem polymerisation; widespread P. falciparum chloroquine resistance in Kenya has shifted first-line to ACT. Nurses apply Kenya NMCP protocols for case management (BNF; Kenya NMCP guidelines).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q52: Methotrexate toxicity — folinic acid (leucovorin) rescue ─────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Oncology Pharmacology','The drug used to treat methotrexate toxicity is:','Folic acid','Folinic acid','Vitamin B6','Scopolamine','B','Folinic acid (leucovorin/calcium folinate) rescue bypasses the methotrexate block on dihydrofolate reductase and restores folate supply to normal cells; folic acid itself cannot be activated due to the block (BNF cytotoxic rescue; §14.2 audit: folic acid vs folinic acid is a documented common error).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Oncology Pharmacology','The drug used to treat methotrexate toxicity is:','Folic acid','Folinic acid','Vitamin B6','Scopolamine','B','Leucovorin (folinic acid) rescue is given after high-dose methotrexate to protect normal cells. Nurses time leucovorin doses precisely per protocol and monitor serum methotrexate levels and renal function (BNF; oncology nursing guidelines; §14.2 audit confirmed folinic acid — not folic acid).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;
