-- Migration: 20260701000006
-- Source: NCK-NEW-MCQ-Compilation.docx — "Kenya Med Exams compiled set" (Year not stated)
-- exam_year = NULL per §13.1
-- Batch B: Medical-surgical nursing procedures, pharmacology, oncology (Q51–Q100)
-- Paper assignment per §12 applied per-question.
-- Audit: verified against Brunner & Suddarth, BNF, MOH Kenya per §14.3.
-- ON CONFLICT (stem, cadre) DO NOTHING on every INSERT.

-- ── Sepsis in postoperative patient — tachycardia ────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Post-operative Care','Which of the following is a common sign of sepsis in a postoperative patient?','Increased blood pressure','Elevated body temperature','Rapid heart rate','Decreased respiratory rate','C','Tachycardia is the most consistent early sign of sepsis in postoperative patients; it reflects the systemic inflammatory response and compensatory cardiac output increase (Brunner & Suddarth; Surviving Sepsis Campaign guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Post-operative Care','Which of the following is a common sign of sepsis in a postoperative patient?','Increased blood pressure','Elevated body temperature','Rapid heart rate','Decreased respiratory rate','C','SIRS criteria (now Sepsis-3: SOFA ≥2 + suspected infection); tachycardia is most sensitive early sign. BScN nurses apply the Sepsis Six bundle (oxygen, blood cultures, IV antibiotics, fluids, lactate, urine output monitoring) within 1 hour (Brunner & Suddarth; Kenya sepsis guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Anticoagulant therapy monitoring — bleeding ───────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Anticoagulant Therapy','A patient with a history of DVT is on anticoagulant therapy. What should the nurse monitor for?','Hypertension','Haematuria','Bleeding','Hyperglycaemia','C','The primary complication of anticoagulant therapy is bleeding; nurses monitor for signs of haemorrhage — haematuria, haemoptysis, melena, ecchymoses, prolonged bleeding from minor cuts (BNF; Brunner & Suddarth anticoagulation nursing).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Anticoagulant Therapy','A patient with a history of DVT is on anticoagulant therapy. What should the nurse monitor for?','Hypertension','Haematuria','Bleeding','Hyperglycaemia','C','Anticoagulant bleeding risk: monitor INR (warfarin), anti-Xa (LMWH), CBC. BScN nurses identify high-risk patients (elderly, renal impairment, polypharmacy), initiate reversal agents appropriately and document bleeding events (BNF; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Blood transfusion complication — hyperkalemia ────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Haematological Disorders','Which of the following is a potential complication of receiving a blood transfusion?','Hypovolaemia','Hypertension','Hypernatraemia','Hyperkalaemia','D','Stored blood causes hyperkalaemia because potassium leaks from lysed and ageing red blood cells during storage; this is a recognised complication especially with rapid or massive transfusion (Brunner & Suddarth; MOH Kenya blood transfusion guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Haematological Disorders','Which of the following is a potential complication of receiving a blood transfusion?','Hypovolaemia','Hypertension','Hypernatraemia','Hyperkalaemia','D','Massive transfusion complications include hyperkalaemia, hypocalcaemia (citrate chelation), hypothermia and TACO/TRALI. BScN nurses monitor ECG, electrolytes and temperature during rapid transfusion and activate massive transfusion protocols when indicated (Brunner & Suddarth; MOH Kenya blood transfusion guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Anaphylaxis — epinephrine and emergency assistance ───────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Pharmacology of Allergy','What is the primary nursing intervention for a patient experiencing an anaphylactic reaction to medication?','Administering an antipyretic','Encouraging fluid intake','Administering epinephrine and calling for emergency assistance','Providing a heating pad for comfort','C','Anaphylaxis is a medical emergency; the primary intervention is immediate intramuscular epinephrine (adrenaline) into the outer thigh followed by calling for emergency support (Brunner & Suddarth; MOH Kenya emergency protocols).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Pharmacology of Allergy','What is the primary nursing intervention for a patient experiencing an anaphylactic reaction to medication?','Administering an antipyretic','Encouraging fluid intake','Administering epinephrine and calling for emergency assistance','Providing a heating pad for comfort','C','Anaphylaxis: IM adrenaline 0.5 mg (1:1000) lateral thigh → supine position → O2 → IV fluids → antihistamine/corticosteroid as adjuncts. BScN nurses prepare adrenaline auto-injectors, lead mock drills and document reactions in allergy registers (Brunner & Suddarth; Kenya emergency protocols).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Incentive spirometry — promotes deep breathing and lung expansion ─────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Surgical Nursing','Post-operative Care','What is the primary purpose of incentive spirometry in postoperative patients?','To assess lung sounds','To measure urinary output','To promote deep breathing and lung expansion','To monitor oxygen saturation','C','Incentive spirometry encourages slow, sustained maximum inspiration to inflate alveoli, prevent atelectasis and reduce postoperative pulmonary complications (Brunner & Suddarth; postoperative pulmonary care guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Surgical Nursing','Post-operative Care','What is the primary purpose of incentive spirometry in postoperative patients?','To assess lung sounds','To measure urinary output','To promote deep breathing and lung expansion','To monitor oxygen saturation','C','Incentive spirometry reduces post-op pneumonia and atelectasis; target 10 breaths/hour while awake. BScN nurses teach technique pre-operatively, encourage use post-operatively alongside early mobilisation (Brunner & Suddarth; surgical nursing EBP).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Diuretic therapy monitoring — urine output and fluid intake ───────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Cardiovascular Disorders','A patient with heart failure is on diuretic medication. Which nursing assessment is essential?','Assessing for elevated blood pressure','Monitoring for signs of fluid overload','Measuring urine output and fluid intake','Checking for elevated blood sugar levels','C','Diuretics increase urine output; monitoring both urine output and fluid intake allows assessment of therapy effectiveness and detection of dehydration or electrolyte imbalance (Brunner & Suddarth; cardiac nursing).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Cardiovascular Disorders','A patient with heart failure is on diuretic medication. Which nursing assessment is essential?','Assessing for elevated blood pressure','Monitoring for signs of fluid overload','Measuring urine output and fluid intake','Checking for elevated blood sugar levels','C','Fluid balance charting + daily weight (0.5–1 kg loss/day target) + electrolyte monitoring (K⁺, Na⁺) + renal function. BScN nurses adjust diuretic dosing decisions collaboratively and manage electrolyte replacement (Brunner & Suddarth; HF management guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── IV chemotherapy — strict aseptic technique ───────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Oncology Nursing','Which nursing intervention is crucial for a patient receiving intravenous chemotherapy?','Administering pain medication regularly','Ensuring strict aseptic technique during IV site care','Encouraging a high-fat diet','Administering anticoagulants to prevent clot formation','B','Strict aseptic technique during IV chemotherapy administration prevents infection in immunocompromised patients and reduces the risk of extravasation and phlebitis from vesicant agents (Brunner & Suddarth; oncology nursing guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Oncology Nursing','Which nursing intervention is crucial for a patient receiving intravenous chemotherapy?','Administering pain medication regularly','Ensuring strict aseptic technique during IV site care','Encouraging a high-fat diet','Administering anticoagulants to prevent clot formation','B','Vesicant extravasation causes severe tissue necrosis; central access preferred for vesicants. BScN oncology nurses monitor IV site every 15–30 minutes, know antidotes for common vesicants, and manage chemotherapy-induced nausea and myelosuppression (Brunner & Suddarth; oncology nursing EBP).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Braden Scale — predicts pressure ulcer risk ──────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Wound Care','What is the primary purpose of the Braden Scale in nursing care?','Assessing cognitive function','Evaluating wound healing','Predicting the risk of pressure ulcers','Measuring pain intensity','C','The Braden Scale assesses six factors (sensory perception, moisture, activity, mobility, nutrition, friction/shear) to predict a patient''s risk of developing pressure ulcers, guiding preventive interventions (Brunner & Suddarth; pressure ulcer prevention guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Wound Care','What is the primary purpose of the Braden Scale in nursing care?','Assessing cognitive function','Evaluating wound healing','Predicting the risk of pressure ulcers','Measuring pain intensity','C','Braden Scale score ≤18 = at risk; ≤9 = very high risk. BScN nurses use scores to trigger prevention bundles, document in care plans and lead unit-level pressure ulcer reduction quality improvement projects (Brunner & Suddarth; NPUAP/EPUAP guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Acute respiratory distress — administer prescribed oxygen ────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Respiratory Disorders','Which intervention is appropriate for a patient experiencing acute respiratory distress?','Administering sedatives to promote sleep','Administering oxygen therapy as prescribed','Elevating the patient''s feet to improve blood flow','Encouraging deep breathing exercises','B','Administering prescribed oxygen therapy is the priority in acute respiratory distress — it directly addresses hypoxaemia and improves tissue oxygenation (Brunner & Suddarth; respiratory nursing).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Respiratory Disorders','Which intervention is appropriate for a patient experiencing acute respiratory distress?','Administering sedatives to promote sleep','Administering oxygen therapy as prescribed','Elevating the patient''s feet to improve blood flow','Encouraging deep breathing exercises','B','Target SpO2 88–92% in COPD (hypoxic drive concern), 94–98% otherwise. BScN nurses titrate O2, position upright, prepare for NIV/intubation escalation and communicate deterioration via SBAR (Brunner & Suddarth; respiratory nursing EBP).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Half-life — time for half the drug to be eliminated ──────────────────────
-- Audit: stem wording differs from 2018 Q14 (different context/phrasing) — seed per §14.5
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Pharmacokinetics','Which term is used to describe the time it takes for half of the drug concentration to be eliminated from the body?','Onset of action','Half-life','Peak effect','Duration of action','B','The half-life (t½) of a drug is the time required for its plasma concentration to fall by 50%; it is used to determine dosing intervals and the time needed to reach steady state (BNF; pharmacology).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Pharmacokinetics','Which term is used to describe the time it takes for half of the drug concentration to be eliminated from the body?','Onset of action','Half-life','Peak effect','Duration of action','B','t½ determines when to next dose; 4–5 half-lives to reach steady state. Prolonged in renal/hepatic disease — BScN nurses adjust monitoring frequency and flag accumulation risk in vulnerable patients (BNF; pharmacology).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Albuterol — bronchodilator for asthma ────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Respiratory Pharmacology','Which medication is classified as a bronchodilator commonly used to treat asthma?','Aspirin','Metoprolol','Albuterol','Warfarin','C','Albuterol (salbutamol) is a short-acting beta-2 agonist bronchodilator that relaxes bronchial smooth muscle, used as a first-line reliever in asthma and COPD (BNF; Kenya asthma guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Respiratory Pharmacology','Which medication is classified as a bronchodilator commonly used to treat asthma?','Aspirin','Metoprolol','Albuterol','Warfarin','C','Albuterol SABA: PRN for acute bronchospasm; regular use indicates poor control requiring step-up. BScN nurses teach inhaler technique, spacer use, written asthma action plans and distinguish between reliever and preventer inhalers (BNF; Kenya asthma management guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Anticoagulants — prevent blood clot formation ────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Anticoagulant Therapy','What is the primary action of an anticoagulant medication?','Reducing blood pressure','Preventing blood clot formation','Relieving pain','Lowering blood sugar levels','B','Anticoagulants prevent the formation and extension of blood clots by interfering with the coagulation cascade; they do not dissolve existing clots (thrombolytics do that) (BNF; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Anticoagulant Therapy','What is the primary action of an anticoagulant medication?','Reducing blood pressure','Preventing blood clot formation','Relieving pain','Lowering blood sugar levels','B','Anticoagulant classes: heparin (antithrombin III), warfarin (vitamin K antagonist), DOACs (Xa/IIa inhibitors). BScN nurses select appropriate monitoring (INR vs anti-Xa vs none for DOACs) and manage reversal agents (BNF; anticoagulation guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Oral route — slowest onset of action ─────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Pharmacokinetics','Which medication administration route is associated with the slowest onset of action?','Intravenous','Intramuscular','Sublingual','Oral','D','The oral route has the slowest onset because the drug must be absorbed from the GI tract; IV gives the fastest onset with immediate drug availability in systemic circulation (BNF; pharmacokinetics).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Pharmacokinetics','Which medication administration route is associated with the slowest onset of action?','Intravenous','Intramuscular','Sublingual','Oral','D','Oral absorption varies with GI motility, food, pH; onset typically 30–60 min. Route selection depends on urgency, bioavailability and patient status. BScN nurses anticipate onset times when timing critical medications (BNF; pharmacokinetics).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Antiemetics — prevent nausea and vomiting ────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Gastrointestinal Pharmacology','What is the primary action of an antiemetic medication?','Reducing blood sugar levels','Relieving pain','Preventing nausea and vomiting','Lowering blood pressure','C','Antiemetic medications prevent or relieve nausea and vomiting by acting on the vomiting centre, chemoreceptor trigger zone or peripheral gut receptors (BNF; pharmacology).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Gastrointestinal Pharmacology','What is the primary action of an antiemetic medication?','Reducing blood sugar levels','Relieving pain','Preventing nausea and vomiting','Lowering blood pressure','C','Antiemetic classes: 5-HT3 antagonists (ondansetron — CINV), D2 antagonists (metoclopramide), antihistamines (cyclizine — motion sickness), NK1 antagonists (aprepitant). BScN nurses select based on aetiology and monitor for QT prolongation with metoclopramide (BNF).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Diuretics — treat hypertension ──────────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Cardiovascular Pharmacology','Which medication classification is commonly used to treat high blood pressure?','Antibiotics','Diuretics','Antipyretics','Analgesics','B','Diuretics are a first-line class of antihypertensive medications; they lower blood pressure by reducing blood volume through increased urinary excretion of sodium and water (BNF; MOH Kenya hypertension guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Cardiovascular Pharmacology','Which medication classification is commonly used to treat high blood pressure?','Antibiotics','Diuretics','Antipyretics','Analgesics','B','Thiazides are preferred first-line antihypertensives for uncomplicated hypertension; loop diuretics for hypertension with heart failure or renal impairment. BScN nurses monitor electrolytes, renal function and BP response (BNF; Kenya hypertension guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Beta-blockers — lower blood pressure ─────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Cardiovascular Pharmacology','What is the primary action of a beta-blocker medication?','Lowering blood pressure','Preventing blood clot formation','Treating fungal infections','Relieving pain','A','Beta-blockers lower blood pressure by blocking beta-adrenoceptors, reducing heart rate and cardiac output; they are also used for angina, arrhythmias and heart failure (BNF; cardiovascular pharmacology).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Cardiovascular Pharmacology','What is the primary action of a beta-blocker medication?','Lowering blood pressure','Preventing blood clot formation','Treating fungal infections','Relieving pain','A','Beta-blockers are cardioprotective post-MI and in heart failure; contraindicated in acute decompensated HF, high-degree AV block, severe asthma. BScN nurses check pulse before administration and monitor for bradycardia, hypotension and bronchospasm (BNF; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Antacids — neutralise stomach acid ───────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Gastrointestinal Pharmacology','What is the primary purpose of administering an antacid medication?','Treating bacterial infections','Lowering blood pressure','Reducing fever','Neutralising stomach acid','D','Antacids (aluminium hydroxide, magnesium hydroxide, calcium carbonate) neutralise excess gastric acid, providing rapid symptomatic relief of heartburn and dyspepsia (BNF; pharmacology).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Gastrointestinal Pharmacology','What is the primary purpose of administering an antacid medication?','Treating bacterial infections','Lowering blood pressure','Reducing fever','Neutralising stomach acid','D','Antacids provide rapid but short-lasting relief; PPIs provide more sustained acid suppression. Nurses counsel patients on staggering antacids from other medications (especially quinolones, tetracyclines, iron) by 2 hours (BNF; pharmacology).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Laxatives — promote bowel movement ──────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Gastrointestinal Pharmacology','What is the primary action of a laxative medication?','Lowering blood sugar levels','Relieving pain','Promoting bowel movement','Treating bacterial infections','C','Laxative medications are used to promote bowel movements and relieve constipation through various mechanisms — bulk-forming, osmotic, stimulant or softening (BNF; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Gastrointestinal Pharmacology','What is the primary action of a laxative medication?','Lowering blood sugar levels','Relieving pain','Promoting bowel movement','Treating bacterial infections','C','Laxative selection by mechanism: bulk-formers (first line, diet-related), osmotics (lactulose — hepatic encephalopathy), stimulants (senna — opioid-induced constipation), softeners (docusate). BScN nurses review polypharmacy for constipating drugs and initiate prophylaxis with opioids (BNF; palliative care guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Surgical scrub — sterilise hands and forearms ────────────────────────────
-- Per §12: Surgical Nursing → Paper I both cadres
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Surgical Nursing','Perioperative Care','What is the purpose of the surgical scrub for the surgical team before entering the OR?','To moisturise the skin','To sterilise the hands and forearms','To remove dirt and debris','To reduce friction during surgery','B','The surgical hand scrub is performed to sterilise (achieve surgical antisepsis of) the hands and forearms before gowning and gloving, minimising the risk of wound infection if gloves are punctured (Brunner & Suddarth; WHO perioperative guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Surgical Nursing','Perioperative Care','What is the purpose of the surgical scrub for the surgical team before entering the OR?','To moisturise the skin','To sterilise the hands and forearms','To remove dirt and debris','To reduce friction during surgery','B','WHO 5-minute scrub or ABHR-based surgical hand preparation is equivalent; achieves 3-log reduction in bacterial counts. BScN perioperative nurses audit scrub technique compliance and monitor glove perforation rates (WHO perioperative guidelines; AORN standards).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Local anaesthesia — loss of sensation in specific area ───────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Surgical Nursing','Anaesthesia','What type of anaesthesia is characterised by loss of sensation in a specific area of the body?','General anaesthesia','Local anaesthesia','Regional anaesthesia','Conscious sedation','B','Local anaesthesia provides loss of sensation in a specific, localised, small area by blocking sodium channels in peripheral nerves near the injection site (Brunner & Suddarth; anaesthesia nursing).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Surgical Nursing','Anaesthesia','What type of anaesthesia is characterised by loss of sensation in a specific area of the body?','General anaesthesia','Local anaesthesia','Regional anaesthesia','Conscious sedation','B','Local vs regional: local = small localised area (skin sutures, dental); regional = larger area via nerve block (spinal, epidural, brachial plexus). BScN nurses monitor for systemic toxicity from local anaesthetic absorption (Brunner & Suddarth; anaesthesia nursing).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Sterile supplies — opened before start of procedure ──────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Surgical Nursing','Perioperative Care','Which of the following is a key component of maintaining a sterile field in the OR?','Wearing jewellery and accessories','Using sterile gloves when handling non-sterile items','Turning one''s back to the sterile field','Opening sterile supplies before the start of the procedure','D','Sterile supplies should be opened just before the procedure to maintain sterility; wearing jewellery is prohibited, sterile gloves must not handle non-sterile items, and one must never turn away from the sterile field (Brunner & Suddarth; AORN/MOH Kenya IPC guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Surgical Nursing','Perioperative Care','Which of the following is a key component of maintaining a sterile field in the OR?','Wearing jewellery and accessories','Using sterile gloves when handling non-sterile items','Turning one''s back to the sterile field','Opening sterile supplies before the start of the procedure','D','Sterile field principles: anything below waist level or outside the sterile zone is non-sterile; only open supplies immediately before use; maintain line of sight to sterile field. BScN perioperative nurses enforce these principles and respond to breaks in technique immediately (AORN; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Surgical hypothermia — positioning on cold OR table ──────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Surgical Nursing','Perioperative Care','A potential complication of positioning a patient on the operating table is:','Hypothermia','Hyperglycaemia','Hypertension','Elevated oxygen saturation','A','Hypothermia is a risk because the cold OR environment, anaesthetic vasodilation, exposure of body cavities and cold IV fluids all promote heat loss; perioperative hypothermia increases bleeding, infection and recovery time (Brunner & Suddarth; perioperative nursing).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Surgical Nursing','Perioperative Care','A potential complication of positioning a patient on the operating table is:','Hypothermia','Hyperglycaemia','Hypertension','Elevated oxygen saturation','A','Inadvertent perioperative hypothermia (IPH) causes coagulopathy, impaired drug metabolism and SSI risk. BScN nurses apply NICE IPH guidelines: pre-warming, forced air warming, warmed IV fluids, intraoperative temperature monitoring (Brunner & Suddarth; NICE NG24; perioperative nursing).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Surgical time-out — confirm patient, site, procedure ─────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Surgical Nursing','Perioperative Care','What is the purpose of the surgical time-out before surgery begins?','To administer anaesthesia','To take a break','To confirm the patient''s identity, surgical site and procedure','To conclude the surgery','C','The surgical time-out is a final mandatory verification step — part of the WHO Surgical Safety Checklist — to ensure correct patient identity, correct surgical site and correct procedure before incision (WHO Surgical Safety Checklist; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Surgical Nursing','Perioperative Care','What is the purpose of the surgical time-out before surgery begins?','To administer anaesthesia','To take a break','To confirm the patient''s identity, surgical site and procedure','To conclude the surgery','C','WHO Surgical Safety Checklist has three phases: sign-in (before anaesthesia), time-out (before incision), sign-out (before leaving OR). Implementation reduces surgical mortality by ~47%. BScN perioperative nurses lead checklist completion (WHO Surgical Safety Checklist; MOH Kenya surgical safety guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Circulating nurse — manages and coordinates OR activities ────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Surgical Nursing','Perioperative Care','What is the primary role of the circulating nurse in the operating room?','Assisting with surgical procedures directly','Administering anaesthesia','Ensuring sterile technique is maintained at the field','Managing and coordinating activities in the OR','D','The circulating nurse (non-scrubbed) manages and coordinates all activities in the OR — patient safety, documentation, supplies, team communication — while maintaining the sterile field from outside (Brunner & Suddarth; AORN perioperative standards).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Surgical Nursing','Perioperative Care','What is the primary role of the circulating nurse in the operating room?','Assisting with surgical procedures directly','Administering anaesthesia','Ensuring sterile technique is maintained at the field','Managing and coordinating activities in the OR','D','Circulating nurse responsibilities: patient assessment, consent verification, positioning, surgical count, documentation, specimen labelling, emergency response. BScN perioperative nurses lead this role and mentor perioperative nursing students (Brunner & Suddarth; AORN).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Scrub nurse — passes instruments to surgeon ──────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Surgical Nursing','Perioperative Care','What is the primary role of the scrub nurse in the operating room?','Administering anaesthesia','Managing and coordinating activities in the OR','Assisting with surgical procedures by passing sterile instruments','Providing postoperative care to the patient','C','The scrub nurse (sterile team member) scrubs in, gowns and gloves, and assists the surgeon directly by passing sterile instruments and maintaining the sterile field from inside (Brunner & Suddarth; AORN perioperative standards).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Surgical Nursing','Perioperative Care','What is the primary role of the scrub nurse in the operating room?','Administering anaesthesia','Managing and coordinating activities in the OR','Assisting with surgical procedures by passing sterile instruments','Providing postoperative care to the patient','C','Scrub nurse: anticipates instrument needs, performs surgical count (before/after procedure), maintains sterility of field. BScN nurses in perioperative roles demonstrate advanced instrument knowledge and assist with complex procedures (Brunner & Suddarth; AORN).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Therapeutic communication — promotes well-being ─────────────────────────
-- Per §12: Paper I for both (applied clinical communication)
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Professional Practice','What does the term "therapeutic communication" refer to in nursing practice?','Using medical jargon to communicate with patients','Promoting open and honest communication with patients for therapeutic purposes','Providing written instructions to patients','Documenting patient information in the medical record','B','Therapeutic communication involves creating a supportive and empathetic environment through verbal and non-verbal techniques to promote patient well-being and facilitate the nurse-patient relationship (Brunner & Suddarth; nursing communication texts).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Professional Practice','What does the term "therapeutic communication" refer to in nursing practice?','Using medical jargon to communicate with patients','Promoting open and honest communication with patients for therapeutic purposes','Providing written instructions to patients','Documenting patient information in the medical record','B','Therapeutic communication techniques: active listening, open-ended questions, reflection, silence, empathy, clarification. BScN nurses apply communication theory (Peplau''s interpersonal relations model) in complex patient interactions and teach communication skills to junior staff (Brunner & Suddarth; Peplau).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Nursing process — promotes well-being through ADPIE ─────────────────────
-- Per §12: Paper I for both (fundamentals of nursing)
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Professional Practice','What is the primary goal of the nursing process in patient care?','Administering medications','Monitoring vital signs','Providing emotional support','Promoting patient well-being through systematic assessment, planning, intervention and evaluation','D','The nursing process (ADPIE) is a systematic, evidence-based approach to patient care that promotes patient well-being through assessment, diagnosis, planning, implementation and evaluation (nursing process texts; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Professional Practice','What is the primary goal of the nursing process in patient care?','Administering medications','Monitoring vital signs','Providing emotional support','Promoting patient well-being through systematic assessment, planning, intervention and evaluation','D','ADPIE is cyclical and iterative; BScN nurses apply critical thinking at each step, formulate NANDA nursing diagnoses, set SMART outcomes and evaluate goal achievement using evidence-based interventions (nursing process texts; Brunner & Suddarth).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Patient confidentiality — ethical principle in nursing ───────────────────
-- Per §12: Paper II for both (professional ethics)
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Health Systems & Management','Professional Ethics','Which of the following is an example of an ethical principle in nursing practice?','Administering medications as ordered by the physician','Ensuring patient confidentiality','Monitoring vital signs regularly','Adhering to strict time management','B','Ensuring patient confidentiality is an ethical principle (privacy/autonomy) grounded in the NCK Code of Conduct; it requires nurses to protect patient information from unauthorised disclosure (NCK Scope of Practice; Kenya Data Protection Act; nursing ethics).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Nursing Management & Leadership','Professional Ethics','Which of the following is an example of an ethical principle in nursing practice?','Administering medications as ordered by the physician','Ensuring patient confidentiality','Monitoring vital signs regularly','Adhering to strict time management','B','Confidentiality is a sub-principle of autonomy; BScN nurses apply it in electronic health records, social media use and multidisciplinary communications — disclosing only on a need-to-know basis within the care team (NCK Code of Conduct; Kenya Data Protection Act 2019).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Patient education — teach about condition, treatment, self-care ──────────
-- Per §12: Paper I for both (nursing fundamentals applied at bedside)
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Professional Practice','What is the purpose of the nurse''s role in patient education?','To assess the patient''s physical condition','To provide emotional support','To teach the patient about their health condition, treatment and self-care','To complete paperwork','C','Patient education involves teaching patients about their health condition, treatment options and self-care strategies to promote adherence, self-management and improved health outcomes (Brunner & Suddarth; nursing education principles).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Professional Practice','What is the purpose of the nurse''s role in patient education?','To assess the patient''s physical condition','To provide emotional support','To teach the patient about their health condition, treatment and self-care','To complete paperwork','C','BScN nurses apply adult learning principles (andragogy), assess health literacy, tailor education to individual needs and evaluate understanding using teach-back method before discharge (Brunner & Suddarth; health literacy guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Pressure ulcer prevention — repositioning ────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Wound Care','Which of the following is a nursing intervention for preventing pressure ulcers?','Administering pain medication','Monitoring blood pressure','Turning and repositioning the patient regularly','Providing emotional support','C','Regular 2-hourly turning and repositioning relieves sustained pressure over bony prominences, restoring blood flow and preventing ischaemic tissue damage leading to pressure ulcers (Brunner & Suddarth; NPUAP/EPUAP pressure ulcer prevention guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Wound Care','Which of the following is a nursing intervention for preventing pressure ulcers?','Administering pain medication','Monitoring blood pressure','Turning and repositioning the patient regularly','Providing emotional support','C','2-hourly repositioning is the cornerstone; supplement with pressure-redistributing surfaces, skin inspection, moisture management and nutritional optimisation. BScN nurses lead pressure ulcer prevention programmes and conduct RCAs for hospital-acquired pressure injuries (Brunner & Suddarth; NPUAP/EPUAP guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── End-of-life nursing — comfort, support and dignity ───────────────────────
-- Per §12: Paper I (Medical-Surgical → palliative/end-of-life in clinical context)
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Palliative Care','What is the primary purpose of the nurse''s role in end-of-life care?','To administer curative treatments','To prolong the patient''s life at all costs','To provide comfort, support and dignity to patients and families','To avoid discussions about end-of-life preferences','C','The nurse''s role in end-of-life care focuses on providing comfort, symptom management and psychological/spiritual support while preserving the dignity of the patient and supporting the family (Brunner & Suddarth; Kenya palliative care guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Palliative Care','What is the primary purpose of the nurse''s role in end-of-life care?','To administer curative treatments','To prolong the patient''s life at all costs','To provide comfort, support and dignity to patients and families','To avoid discussions about end-of-life preferences','C','BScN nurses lead advance care planning conversations, coordinate hospice referral, manage total pain (physical, emotional, social, spiritual) and support bereaved families; WHO palliative care principles integrated with Kenya MOH palliative care framework (Brunner & Suddarth; WHO; Kenya palliative care guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── PACU goal — monitor and stabilise from anaesthesia ───────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Surgical Nursing','Post-operative Care','What is the primary goal of nursing care in the immediate post-anaesthesia care unit (PACU)?','To discharge the patient home as quickly as possible','To administer pain medication on schedule','To monitor and stabilise the patient''s vital signs and recovery from anaesthesia','To complete paperwork','C','In the PACU the priority is monitoring and stabilising vital signs, airway, oxygenation, consciousness level and haemodynamic status while the patient recovers from anaesthesia before transfer to the ward (Brunner & Suddarth; perioperative nursing).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Surgical Nursing','Post-operative Care','What is the primary goal of nursing care in the immediate post-anaesthesia care unit (PACU)?','To discharge the patient home as quickly as possible','To administer pain medication on schedule','To monitor and stabilise the patient''s vital signs and recovery from anaesthesia','To complete paperwork','C','PACU Aldrete scoring guides discharge readiness: O2 sat, activity, circulation, consciousness, colour. BScN nurses recognise PACU emergencies (airway obstruction, laryngospasm, malignant hyperthermia) and intervene promptly (Brunner & Suddarth; PACU nursing standards).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Fall prevention — prevent falls and minimise injury ──────────────────────
-- Per §12: Paper I — patient safety is a clinical nursing competency
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Patient Safety','What is the primary purpose of the nurse''s role in fall prevention?','To avoid providing assistance to at-risk patients','To document all patient falls','To prevent patient falls and minimise the risk of injury','To restrict patients to their beds','C','Nurses implement fall prevention strategies — risk assessment, bed alarms, non-slip footwear, call bell within reach, adequate lighting — to prevent falls and injury, a key patient safety indicator (Brunner & Suddarth; Kenya patient safety guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Patient Safety','What is the primary purpose of the nurse''s role in fall prevention?','To avoid providing assistance to at-risk patients','To document all patient falls','To prevent patient falls and minimise the risk of injury','To restrict patients to their beds','C','Falls prevention bundle: Morse/STRATIFY risk scoring, bed lowest position, side rails up, regular toileting, multidisciplinary review of medications causing orthostasis. BScN nurses lead falls prevention QI projects and conduct post-fall root cause analyses (Brunner & Suddarth; JCI/Kenya patient safety standards).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Discharge planning — smooth transition to next care level ────────────────
-- Per §12: Paper I — clinical discharge planning
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Professional Practice','What is the purpose of the nurse''s role in discharge planning?','To discharge the patient home as quickly as possible','To avoid discussing post-discharge care','To ensure a smooth transition to the next level of care and promote patient well-being','To complete paperwork','C','Discharge planning ensures continuity of care, prevents avoidable readmissions and empowers patients for self-management at home; it should begin at admission (Brunner & Suddarth; discharge planning guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Professional Practice','What is the purpose of the nurse''s role in discharge planning?','To discharge the patient home as quickly as possible','To avoid discussing post-discharge care','To ensure a smooth transition to the next level of care and promote patient well-being','To complete paperwork','C','BScN nurses lead structured discharge planning using LACE/HARP tools, coordinate with social workers, CHVs and community nurses, provide medication reconciliation and written action plans; evaluate readmission rates as an outcome indicator (Brunner & Suddarth; Kenya discharge planning guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Oxygen therapy — provides supplemental O2 for respiratory problems ────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Respiratory Disorders','What is the primary goal of administering oxygen therapy in nursing practice?','To decrease oxygen levels in the bloodstream','To increase the risk of respiratory distress','To provide supplemental oxygen to patients with respiratory problems','To minimise communication with the patient','C','Oxygen therapy is administered to correct hypoxaemia and improve tissue oxygenation in patients with respiratory problems (Brunner & Suddarth; respiratory nursing; MOH Kenya oxygen guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Respiratory Disorders','What is the primary goal of administering oxygen therapy in nursing practice?','To decrease oxygen levels in the bloodstream','To increase the risk of respiratory distress','To provide supplemental oxygen to patients with respiratory problems','To minimise communication with the patient','C','Target SpO2 94–98% for most patients (88–92% for COPD with CO2 retention). Delivery devices: nasal cannula (1–6 L/min), simple face mask (6–10 L/min), non-rebreather mask (10–15 L/min). BScN nurses titrate O2 to target, not routinely at maximum (Brunner & Suddarth; British Thoracic Society O2 guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Urinary catheterisation — maintain drainage ──────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Renal Disorders','What is the primary goal of urinary catheterisation in nursing practice?','To increase pain and discomfort','To promote urinary incontinence','To maintain urinary drainage in patients who cannot void spontaneously','To minimise patient comfort','C','Urinary catheterisation drains the bladder when the patient cannot void spontaneously due to urinary retention, obstruction, neurological dysfunction or perioperative need (Brunner & Suddarth; catheter care guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Renal Disorders','What is the primary goal of urinary catheterisation in nursing practice?','To increase pain and discomfort','To promote urinary incontinence','To maintain urinary drainage in patients who cannot void spontaneously','To minimise patient comfort','C','CAUTI prevention: strict asepsis at insertion, closed drainage, daily catheter necessity review, early removal. BScN nurses lead CAUTI prevention bundles, audit compliance and report HAI metrics to infection control committees (Brunner & Suddarth; Kenya IPC catheter care guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── ET tube care — maintain patency and prevent complications ────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Critical Care Nursing','What is the primary purpose of endotracheal tube care and management?','To maintain the ET tube blocked','To promote patient comfort','To increase the risk of respiratory distress','To maintain patency and prevent complications of the ET tube','D','ET tube care maintains airway patency and prevents complications including tube displacement, cuff pressure injuries, VAP (ventilator-associated pneumonia) and mucosal damage (Brunner & Suddarth; critical care nursing).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Critical Care Nursing','What is the primary purpose of endotracheal tube care and management?','To maintain the ET tube blocked','To promote patient comfort','To increase the risk of respiratory distress','To maintain patency and prevent complications of the ET tube','D','VAP prevention bundle: HOB 30–45°, oral care with chlorhexidine, cuff pressure 20–30 cmH2O, daily sedation vacation, early extubation assessment. BScN critical care nurses lead VAP prevention programmes and track VAP rates as quality indicators (Brunner & Suddarth; IHI VAP bundle).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Insulin therapy — maintain glucose within target range ───────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Endocrine Pharmacology','What is the primary goal of administering insulin therapy in nursing practice?','To promote high blood sugar levels','To decrease patient compliance','To maintain blood glucose levels within a target range','To minimise communication with the patient','C','Insulin therapy is administered to maintain blood glucose levels within a therapeutic target range in patients with diabetes mellitus, preventing hyperglycaemia and its complications (BNF; Kenya MOH diabetes management guidelines).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Endocrine Pharmacology','What is the primary goal of administering insulin therapy in nursing practice?','To promote high blood sugar levels','To decrease patient compliance','To maintain blood glucose levels within a target range','To minimise communication with the patient','C','Inpatient glucose targets: 7.8–10 mmol/L (140–180 mg/dL) for most; tighter for selected patients. BScN nurses manage insulin infusion protocols, prevent hypoglycaemia, adjust basal-bolus regimens and deliver structured diabetes education (BNF; Kenya MOH diabetes guidelines; AADE standards).','easy',NULL,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;
