-- Migration: 20260701000002
-- Source: NCK-NEW-MCQ-Compilation.docx — Year 2018 (KMTC KRCHN Pharmacology Paper III, Sept 2018)
--         BScN Paper II 2018 section — all questions are pharmacology, assigned to Paper I
--         per §12 nck-exam-system.md (Pharmacology is a Paper I unit for both cadres).
-- exam_year = 2018
-- Audit: answers and rationales verified against BNF, Brunner & Suddarth,
--        MOH Kenya guidelines, standard Kenyan nursing pharmacology texts.
-- ON CONFLICT (stem, cadre) DO NOTHING on every INSERT.

-- ── Q1: Expectorant — increase fluid intake ───────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Respiratory Pharmacology','The nurse should instruct a client who is taking an expectorant to:','Restrict fluids','Increase fluid intake','Avoid vaporisers','Take an antihistamine','B','Expectorants work by increasing respiratory tract secretion volume, making mucus less viscous and easier to expectorate; adequate fluid intake is essential to facilitate this effect (Brunner & Suddarth; BNF).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Respiratory Pharmacology','The nurse should instruct a client who is taking an expectorant to:','Restrict fluids','Increase fluid intake','Avoid vaporisers','Take an antihistamine','B','Expectorants (e.g. guaifenesin) liquefy secretions; systemic hydration enhances effectiveness. Nurses also assess cough productivity and advise on positioning for drainage (Brunner & Suddarth; BNF).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q2: Glucagon — raises blood sugar by stimulating glycogenolysis ───────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Endocrine Pharmacology','The drug that increases blood sugar by stimulating glycogenolysis in the liver is:','Glimepiride','Glyburide','Miglitol','Glucagon','D','Glucagon raises blood glucose by stimulating hepatic glycogenolysis and gluconeogenesis; it is the treatment of choice for severe hypoglycaemia when IV glucose is unavailable (BNF; pharmacology).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Endocrine Pharmacology','The drug that increases blood sugar by stimulating glycogenolysis in the liver is:','Glimepiride','Glyburide','Miglitol','Glucagon','D','Glucagon (IM/SC/IV) rescues unconscious hypoglycaemic patients; onset 10–15 minutes. Nurses administer followed by oral carbohydrate when patient recovers consciousness (BNF; Kenya MOH diabetes guidelines).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q3: Diclofenac — inhibits prostaglandin synthesis ────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Analgesics','Diclofenac sodium produces anti-inflammatory, analgesic and antipyretic effects by inhibiting the synthesis of:','Dopamine','Prostaglandin','Serotonin','Monoamine oxidase','B','Diclofenac is an NSAID that inhibits cyclo-oxygenase (COX-1 and COX-2), thereby reducing prostaglandin synthesis — the mediators of pain, fever and inflammation (BNF; standard pharmacology).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Analgesics','Diclofenac sodium produces anti-inflammatory, analgesic and antipyretic effects by inhibiting the synthesis of:','Dopamine','Prostaglandin','Serotonin','Monoamine oxidase','B','COX inhibition reduces PGE2 and thromboxane; GI side effects from COX-1 inhibition, renal effects from COX-2 inhibition. Nurses assess renal function, use lowest effective dose, co-prescribe PPI if GI risk (BNF; Brunner & Suddarth).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q4: Indomethacin cardiovascular side effects — hypertension, oedema ──────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Analgesics','The major cardiovascular side effects of indomethacin are:','Venous thrombosis and bleeding','Angina pectoris and hypotension','Endocarditis and atrial fibrillation','Hypertension and oedema','D','Indomethacin, like other NSAIDs, inhibits prostaglandin-mediated renal vasodilation causing sodium and water retention, leading to hypertension and peripheral oedema (BNF; Brunner & Suddarth).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Analgesics','The major cardiovascular side effects of indomethacin are:','Venous thrombosis and bleeding','Angina pectoris and hypotension','Endocarditis and atrial fibrillation','Hypertension and oedema','D','NSAID-induced hypertension and oedema are class effects; NSAIDs also increase cardiovascular event risk with long-term use. Nurses monitor BP, weight and renal function in patients on indomethacin (BNF; Brunner & Suddarth).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q5: Poisons — almost exclusively harmful effects ─────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Pharmacognosy','Drugs that have almost exclusively harmful effects in the body are known as:','Elixirs','Xenobiotics','Toxins','Poisons','D','Poisons are substances whose actions on the body are almost exclusively harmful; toxins are specifically of biological origin; xenobiotics are foreign chemical substances (standard pharmacology/toxicology texts).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Pharmacognosy','Drugs that have almost exclusively harmful effects in the body are known as:','Elixirs','Xenobiotics','Toxins','Poisons','D','Distinguishing poisons, toxins and xenobiotics is foundational pharmacology; nurses apply this in occupational health and poison management contexts (MOH Kenya poisoning guidelines; pharmacology texts).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q6: Teratogenicity — harmful effects on foetus during formative stages ────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Pharmacokinetics','The possibility of harmful effects on the foetus during the formative stages of development is referred to as:','Tetralogy','Teratogenicity','Mutation','Regeneration','B','Teratogenicity is the capacity of an agent to cause structural or functional abnormalities in the developing embryo or fetus during formative/organogenic stages (BNF pharmacology in pregnancy).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Pharmacokinetics','The possibility of harmful effects on the foetus during the formative stages of development is referred to as:','Tetralogy','Teratogenicity','Mutation','Regeneration','B','Teratogenicity risk is highest during organogenesis (weeks 3–8); nurses screen all drug prescriptions at first ANC contact using pregnancy drug safety categories and MOH Kenya prescribing guidelines (BNF; Myles).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q7: Anti-anxiety agents — meprobamate, chlordiazepoxide ──────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','CNS Pharmacology','The anti-anxiety agents include:','Aminophylline, Halazepam','Ranitidine, Buspirone','Meprobamate, Chlordiazepoxide','Prazepam, Simethicone','C','Meprobamate and chlordiazepoxide are recognised anxiolytic (anti-anxiety) agents; ranitidine is an H2 blocker and simethicone is an antiflatulent (BNF; Brunner & Suddarth pharmacology).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','CNS Pharmacology','The anti-anxiety agents include:','Aminophylline, Halazepam','Ranitidine, Buspirone','Meprobamate, Chlordiazepoxide','Prazepam, Simethicone','C','Chlordiazepoxide is a long-acting benzodiazepine also used in alcohol withdrawal; meprobamate is a carbamate anxiolytic. Nurses monitor for dependence and sedation (BNF; psychiatric nursing pharmacology).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q8: Antihistamine side effects — sedation, dizziness, dry mouth ──────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Pharmacology of Allergy','The common side effects of antihistamines include:','Sedation, dizziness, dry mouth','Tremors, fatigue, urticaria','Convulsions, GI disturbance, insomnia','Insomnia, urticaria, dry mouth','A','First-generation antihistamines cross the blood-brain barrier causing sedation and dizziness; anticholinergic activity causes dry mouth, urinary retention, and blurred vision (BNF; pharmacology).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Pharmacology of Allergy','The common side effects of antihistamines include:','Sedation, dizziness, dry mouth','Tremors, fatigue, urticaria','Convulsions, GI disturbance, insomnia','Insomnia, urticaria, dry mouth','A','1st-gen antihistamines (promethazine, chlorpheniramine) cause CNS depression and anticholinergic effects; 2nd-gen (cetirizine, loratadine) are non-sedating. Nurses advise against driving and identify drug interactions (BNF).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q9: Cardioselective beta-blockers — atenolol, acebutolol ─────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Cardiovascular Pharmacology','Cardioselective (beta-1 selective) beta-adrenergic blocking agents include:','Nifedipine, Amlodipine','Atenolol, Acebutolol hydrochloride','Captopril, Enalapril','Labetalol, Prazosin','B','Atenolol and acebutolol are cardioselective (beta-1 selective) blockers; nifedipine and amlodipine are calcium-channel blockers; captopril and enalapril are ACE inhibitors; labetalol is a non-selective alpha/beta blocker (BNF cardiovascular drugs).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Cardiovascular Pharmacology','Cardioselective (beta-1 selective) beta-adrenergic blocking agents include:','Nifedipine, Amlodipine','Atenolol, Acebutolol hydrochloride','Captopril, Enalapril','Labetalol, Prazosin','B','Cardioselective beta-blockers preferentially block cardiac beta-1 receptors with less bronchospasm risk; still use with caution in asthma. Nurses differentiate selectivity when assessing asthma/COPD patients (BNF; Brunner & Suddarth).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q10: Captopril indications — hypertension, hypertensive crisis, CHF ───────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Cardiovascular Pharmacology','Indications of captopril include:','Hypertension, hypotension, rheumatoid arthritis','Hypertension, congestive heart failure, hypotension','Hypotension, hypertensive crisis, proteinuria','Hypertension, hypertensive crisis, congestive heart failure','D','Captopril (ACE inhibitor) is indicated for hypertension (including hypertensive crisis) and congestive heart failure; it lowers, not raises, BP — hypotension is a side effect, not an indication (BNF cardiovascular drugs).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Cardiovascular Pharmacology','Indications of captopril include:','Hypertension, hypotension, rheumatoid arthritis','Hypertension, congestive heart failure, hypotension','Hypotension, hypertensive crisis, proteinuria','Hypertension, hypertensive crisis, congestive heart failure','D','ACE inhibitors reduce afterload and protect kidneys; also indicated in diabetic nephropathy. Nurses monitor for first-dose hypotension, dry cough (class effect), hyperkalaemia (BNF; Brunner & Suddarth).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q11: Thiazide side effects — thrombocytopenia, agranulocytosis ────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Diuretics','Unwanted effects of thiazides include:','Thrombocytopenia and rashes','Agranulocytosis and paraesthesia','Thrombocytopenia and agranulocytosis','Paraesthesia and rashes','C','Thiazide diuretics can cause blood dyscrasias including thrombocytopenia and agranulocytosis as rare but serious adverse effects, in addition to hypokalaemia, hyperuricaemia and hyperglycaemia (BNF diuretics).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Diuretics','Unwanted effects of thiazides include:','Thrombocytopenia and rashes','Agranulocytosis and paraesthesia','Thrombocytopenia and agranulocytosis','Paraesthesia and rashes','C','Thiazides also cause hypokalaemia, hyponatraemia, hyperuricaemia, hyperglycaemia and hypercalcaemia. Nurses perform baseline and periodic FBC and electrolyte monitoring in patients on long-term thiazides (BNF; Brunner & Suddarth).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q12: Salbutamol (Ventolin) — beta-2 selective adrenergic agonist ──────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Respiratory Pharmacology','Ventolin is a bronchodilator as well as:','An inhaler device','A beta-2 selective adrenergic agonist','A vasodilator','A beta-1 receptor agonist','B','Ventolin (salbutamol) is classified as a selective beta-2 adrenoceptor agonist — this defines its pharmacological class; an inhaler is a device, not a pharmacological classification (BNF respiratory drugs).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Respiratory Pharmacology','Ventolin is a bronchodilator as well as:','An inhaler device','A beta-2 selective adrenergic agonist','A vasodilator','A beta-1 receptor agonist','B','Salbutamol''s beta-2 selectivity gives bronchodilation with less cardiac stimulation than non-selective agents; nurses teach correct MDI technique (2-puff SABA PRN, spacer use) and monitor for tachycardia and hypokalaemia at high doses (BNF).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q13: Potentiation — inert drug increases effect of another ────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Pharmacokinetics','The effect of combining drugs where one drug that has no effect of its own increases the effects of another drug is termed:','Potentiation','Antagonism','Addition','Agonism','A','Potentiation occurs when a drug with no intrinsic effect of its own enhances the effect of another drug; this is distinct from additive effects (two drugs with similar effects summing together) (pharmacology texts).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Pharmacokinetics','The effect of combining drugs where one drug that has no effect of its own increases the effects of another drug is termed:','Potentiation','Antagonism','Addition','Agonism','A','Potentiation is important in clinical practice (e.g. probenecid potentiates penicillin by blocking renal tubular secretion). Nurses identify and report potentiation interactions to prevent toxicity (BNF; pharmacology).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q14: Cimetidine — reduced libido and impotence (antiandrogenic) ───────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Gastrointestinal Pharmacology','A patient on anti-ulcer therapy complains of reduced libido and impotence. The nurse informs him this may be associated with:','Nizatidine','Cimetidine','Ranitidine','Famotidine','B','Cimetidine has antiandrogenic effects causing gynaecomastia, reduced libido and impotence — unique among H2-receptor antagonists; newer H2-blockers (ranitidine, famotidine, nizatidine) lack this effect (BNF; Brunner & Suddarth).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Gastrointestinal Pharmacology','A patient on anti-ulcer therapy complains of reduced libido and impotence. The nurse informs him this may be associated with:','Nizatidine','Cimetidine','Ranitidine','Famotidine','B','Cimetidine is a CYP3A4 inhibitor and anti-androgen — significant drug interaction and endocrine side-effect profile. Nurses switch recommendation to ranitidine/famotidine or PPI if sexual dysfunction reported (BNF; Brunner & Suddarth).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q15: Fluconazole — azole for systemic fungal infection ───────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Antimicrobials','An azole derivative indicated for systemic fungal infection is:','Miconazole','Fluconazole','Clotrimazole','Amphotericin B','B','Fluconazole is a triazole antifungal used for systemic infections (candidaemia, cryptococcal meningitis); amphotericin B is a polyene, while miconazole and clotrimazole are primarily topical azoles (BNF antifungals).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Antimicrobials','An azole derivative indicated for systemic fungal infection is:','Miconazole','Fluconazole','Clotrimazole','Amphotericin B','B','Fluconazole inhibits ergosterol synthesis (CYP51); used for oral/oesophageal candidiasis in HIV and cryptococcal meningitis maintenance. Nurses monitor LFTs and significant CYP3A4 drug interactions (BNF; NASCOP guidelines).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q16: Loperamide — indicated for diarrhoea ────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Gastrointestinal Pharmacology','A nurse should administer loperamide to a client who has:','Abdominal pain','Constipation','Diarrhoea','Blood in stool','C','Loperamide is an opioid receptor agonist acting on the gut wall to slow intestinal motility and reduce fluid secretion; it is indicated for non-infective diarrhoea and is not appropriate for blood in stool (dysentery) (BNF).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Gastrointestinal Pharmacology','A nurse should administer loperamide to a client who has:','Abdominal pain','Constipation','Diarrhoea','Blood in stool','C','Loperamide is contraindicated in bloody diarrhoea (infective colitis) as it may prolong infection and cause toxic megacolon; ORS remains the priority in acute diarrhoea. Nurses assess stool characteristics before administration (BNF; Kenya IMNCI guidelines).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q17: Diazepam — binds GABA receptors ─────────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','CNS Pharmacology','Diazepam exerts its effects by:','Binding on GABA receptors in the brain','Inhibiting serotonin action','Blocking acetylcholine on the synaptic cleft','Increasing the influx of sodium ions on neurons','A','Diazepam is a benzodiazepine that potentiates GABA-A receptor-mediated chloride influx by binding to the benzodiazepine site, enhancing inhibitory neurotransmission in the CNS (BNF; pharmacology).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','CNS Pharmacology','Diazepam exerts its effects by:','Binding on GABA receptors in the brain','Inhibiting serotonin action','Blocking acetylcholine on the synaptic cleft','Increasing the influx of sodium ions on neurons','A','Benzodiazepines enhance GABA-A chloride conductance → CNS depression. Flumazenil reverses overdose. Nurses monitor for respiratory depression, dependence risk and paradoxical reactions in elderly (BNF; Brunner & Suddarth).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q18: Ciprofloxacin — treatment of bacillary dysentery in adults ───────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Antimicrobials','The most appropriate drug for treatment of bacillary dysentery in adults is:','Ciprofloxacin','Amoxicillin','Erythromycin','Gentamicin','A','Ciprofloxacin is the recommended first-line agent for bacillary dysentery (Shigella spp.) in adults per Kenya MOH/IMNCI and WHO dysentery management guidelines; amoxicillin resistance is widespread (BNF; Kenya STI/GI guidelines).','medium',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Antimicrobials','The most appropriate drug for treatment of bacillary dysentery in adults is:','Ciprofloxacin','Amoxicillin','Erythromycin','Gentamicin','A','Ciprofloxacin 500 mg BD × 3 days for Shigella dysentery; fluoroquinolone resistance emerging in some settings. Nurses collect stool culture before antibiotic initiation where possible and ensure ORS hydration (BNF; Kenya MOH dysentery guidelines).','medium',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q19: Morphine side effect — constipation ─────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Analgesics','The commonest side effect associated with morphine is:','Development of gastric ulcers','Nausea and vomiting','Constipation','Rapid breathing','C','Constipation is the most common and persistent side effect of morphine because opioid receptors in the gut reduce peristalsis; unlike most other opioid side effects, tolerance does not develop to constipation (BNF; Brunner & Suddarth).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Analgesics','The commonest side effect associated with morphine is:','Development of gastric ulcers','Nausea and vomiting','Constipation','Rapid breathing','C','All patients on regular opioids require concurrent laxative prophylaxis (stimulant laxative ± osmotic); unlike nausea, constipation does not resolve with continued use. Nurses initiate bowel regimen at morphine start (BNF; palliative care guidelines).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q20: HAART — decreases viral RNA in blood ─────────────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','HIV/AIDS Pharmacology','Highly active antiretroviral therapy (HAART) in HIV infection is associated with:','An increase in the rate of emergence of drug resistance','A decrease in CD4 count','A decrease in viral RNA in blood','An increased incidence of opportunistic infections','C','HAART suppresses HIV replication, resulting in decreased plasma viral RNA (viral load) and subsequent rise in CD4 count, reducing opportunistic infections (NASCOP/MOH Kenya ART guidelines; WHO ARV guidelines).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','HIV/AIDS Pharmacology','Highly active antiretroviral therapy (HAART) in HIV infection is associated with:','An increase in the rate of emergence of drug resistance','A decrease in CD4 count','A decrease in viral RNA in blood','An increased incidence of opportunistic infections','C','Target: viral load <50 copies/mL at 6 months. Combination HAART prevents single-drug resistance; adherence is paramount. Nurses support adherence counselling, manage side effects and monitor viral load and CD4 per NASCOP schedule (NASCOP/MOH Kenya ART guidelines).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q21: Ceftriaxone — effective against beta-lactamase producing organisms ───
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Antimicrobials','Beta-lactamase production is a resistance mechanism among strains of Haemophilus influenzae and Neisseria gonorrhoeae. Which drug is effective against these organisms?','Amoxicillin','Ceftriaxone','Clindamycin','Ticarcillin','B','Ceftriaxone is a 3rd-generation cephalosporin that is stable against beta-lactamases and remains effective against beta-lactamase-producing H. influenzae and N. gonorrhoeae (Kenya STI guidelines; BNF cephalosporins).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Antimicrobials','Beta-lactamase production is a resistance mechanism among strains of Haemophilus influenzae and Neisseria gonorrhoeae. Which drug is effective against these organisms?','Amoxicillin','Ceftriaxone','Clindamycin','Ticarcillin','B','Ceftriaxone IM/IV is the Kenya National STI guideline first-line for gonorrhoea due to widespread PPNG resistance. Nurses apply dual STI therapy (ceftriaxone + azithromycin) per current national guidelines (BNF; Kenya National STI Guidelines).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q22: Sulfonylureas — stimulate beta cells to secrete insulin ──────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Endocrine Pharmacology','Oral antidiabetics that work by stimulating beta cells to secrete more insulin and increase receptor sites in tissues are classified as:','Alpha-glucosidase inhibitors','Biguanides','Sulfonylureas','Thiazolidinediones','C','Sulfonylureas (e.g. glibenclamide, glipizide) stimulate pancreatic beta cells to secrete insulin and increase peripheral insulin receptor sensitivity; metformin (biguanide) works via different mechanisms (BNF; Kenya MOH diabetes guidelines).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Endocrine Pharmacology','Oral antidiabetics that work by stimulating beta cells to secrete more insulin and increase receptor sites in tissues are classified as:','Alpha-glucosidase inhibitors','Biguanides','Sulfonylureas','Thiazolidinediones','C','Sulfonylureas require functioning beta cells (ineffective in T1DM); risk of hypoglycaemia especially with renal impairment. Nurses monitor blood glucose, advise on hypoglycaemia recognition and meal timing (BNF; Kenya MOH diabetes management guidelines).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q23: Antipsychotic EPSEs — parkinsonism, tardive dyskinesia, opisthotonos ─
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','CNS Pharmacology','The extrapyramidal side effects of antipsychotic drugs include:','Tardive dyskinesia, opisthotonos, hallucinations','Parkinsonism, tardive dyskinesia, opisthotonos','Hallucinations, excessive appetite, akinesia','Impotence, echolalia, opisthotonos','B','Antipsychotic extrapyramidal effects are drug-induced parkinsonism, akathisia, acute dystonia (including opisthotonos) and tardive dyskinesia; hallucinations are symptoms the drugs are used to treat, not side effects (BNF; Brunner & Suddarth).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','CNS Pharmacology','The extrapyramidal side effects of antipsychotic drugs include:','Tardive dyskinesia, opisthotonos, hallucinations','Parkinsonism, tardive dyskinesia, opisthotonos','Hallucinations, excessive appetite, akinesia','Impotence, echolalia, opisthotonos','B','EPSEs managed with anticholinergics (benztropine) for acute dystonia/parkinsonism; tardive dyskinesia may be irreversible — nurses monitor AIMS (Abnormal Involuntary Movement Scale) and report early signs (BNF; psychiatric nursing pharmacology).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q24: TB combination chemotherapy — prevents drug resistance ───────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Antimicrobials','Combined chemotherapy of tuberculosis is used to:','Decrease mycobacterial drug resistance','Increase mycobacterial drug resistance','Decrease the antimicrobial activity','Decrease the onset of antimycobacterial drug biotransformation','A','Combination TB therapy is used specifically to prevent/decrease the emergence of mycobacterial drug resistance — single-drug therapy rapidly selects resistant mutants in the large mycobacterial population (Kenya NLTP guidelines; BNF antituberculous therapy).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Antimicrobials','Combined chemotherapy of tuberculosis is used to:','Decrease mycobacterial drug resistance','Increase mycobacterial drug resistance','Decrease the antimicrobial activity','Decrease the onset of antimycobacterial drug biotransformation','A','Standard 2RHZE/4RH kills different mycobacterial subpopulations; each drug targets a different physiological state. Nurses support DOT (directly observed therapy), monitor adherence and adverse effects per Kenya NLTP guidelines (BNF; Kenya NLTP).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q25: Praziquantel — drug of choice for taeniasis ─────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Pharmacology','Antiparasitic Drugs','A 9-year-old schoolgirl has been diagnosed with taeniasis. The drug of choice is:','Ivermectin','Praziquantel','Diethylcarbamazine','Albendazole','B','Praziquantel is the drug of choice for intestinal taeniasis (Taenia solium and T. saginata); it causes tegumental damage and contraction leading to worm death and expulsion (Kenya MOH deworming guidance; BNF anthelmintics).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Pharmacology','Antiparasitic Drugs','A 9-year-old schoolgirl has been diagnosed with taeniasis. The drug of choice is:','Ivermectin','Praziquantel','Diethylcarbamazine','Albendazole','B','Praziquantel single dose for taeniasis; albendazole is used for neurocysticercosis alongside corticosteroids. Nurses counsel on strict hand hygiene and proper meat cooking to prevent re-infection (BNF; Kenya MOH NTD guidelines).','easy',2018,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;
