-- =============================================================================
-- SEED: NCK Paper 3 -- Uncategorised Sets (unique questions only)
-- =============================================================================
-- Source: NCK-Paper3-MCQs-with-Rationales.docx Section B (Sets 1-8)
-- Repeats explicitly flagged in source document are EXCLUDED
-- Cadre: KRCHN for community health/basic clinical; BScN for advanced research/management
-- Paper assignment: per nck-exam-system.md Section 12 (Roman numerals)
-- All: status = 'approved', contributor_id = NULL (platform-owned)
-- Special characters replaced with ASCII equivalents for SQL compatibility
-- =============================================================================

-- =============================================================================
-- Set 1 -- Community Health, Research, Management
-- =============================================================================

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Community Health Nursing', 'Epidemiology',
 'The total number of new cases of HIV infection reported in the month of March from X village was 50. This is referred to as:',
 'Incidence',
 'Prevalence',
 'Morbidity',
 'Pandemic',
 'A',
 'EPIDEMIOLOGICAL MEASURES: INCIDENCE = number of NEW cases of disease arising in a defined population during a specified time period (e.g. 50 new HIV cases in March in X village). Used to study disease aetiology, evaluate prevention. PREVALENCE = TOTAL number of EXISTING cases (new + old) at a point in time - useful for chronic disease burden. MORBIDITY is a broader term for disease frequency. PANDEMIC = worldwide epidemic. The question describes new cases in a defined time period = INCIDENCE.',
 'easy', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Water Purification',
 'When using the 3-pot system for water purification, the water is considered safe for drinking after standing for:',
 '24 hours',
 '48 hours',
 '36 hours',
 '30 hours',
 'B',
 'THREE-POT SYSTEM for household water treatment: water is collected and progressively settles/disinfects through three pots over 48 HOURS. Pot 1 (today) - fresh water added; Pot 2 (yesterday''s water) - being used currently; Pot 3 (2 days ago / 48-hour-old water) - at the end of the day this is transferred and used; refilled each day. The 48-hour standing allows sedimentation of particles, pathogen die-off, and water becomes safer to drink. A simple, low-cost intervention for rural settings. Should be combined with chlorination, boiling or SODIS for best safety.',
 'easy', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Primary Health Care',
 'Principles of PHC are:',
 'Manpower development, equity, appropriate technology',
 'Community rehabilitation, equity, science',
 'Culture, science, community participation',
 'Community participation, equity, community rehabilitation',
 'A',
 'PRINCIPLES of PRIMARY HEALTH CARE (Alma Ata 1978): EQUITABLE distribution - services accessible to all; APPROPRIATE TECHNOLOGY - scientifically sound, acceptable, affordable, locally feasible; COMMUNITY participation; INTERSECTORAL coordination - health works with education, agriculture, housing, water; FOCUS ON PREVENTION; HUMAN POWER/MANPOWER DEVELOPMENT - training appropriate cadre at appropriate level. Option A lists 3 of these principles.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Community Mobilisation',
 'The correct order of community mobilisation steps:',
 'Planning, community entry, conducting, monitoring',
 'Community entry, planning, conducting, monitoring',
 'Making reinforcement, community entry, planning, conducting',
 'Community entry, planning, monitoring, conducting',
 'B',
 'COMMUNITY MOBILISATION STEPS in sequence: (1) COMMUNITY ENTRY - establish rapport with gatekeepers (chief, religious leaders, opinion leaders), introduce purpose, get permission/acceptance; (2) PLANNING - together with the community identify needs, set objectives, plan activities, mobilise resources; (3) CONDUCTING/IMPLEMENTING - execute planned activities with community involvement; (4) MONITORING AND EVALUATION - track progress against objectives, document outcomes; (5) reinforcement and sustainability. Option B follows the correct order.',
 'easy', 'approved', NULL, 'Paper II'),

('KRCHN', 'Nutrition', 'Micronutrients',
 'Absorption of iron is enhanced by:',
 'Antacids',
 'Citrus fruits',
 'Tea and coffee',
 'Taking iron tablets with meals',
 'B',
 'IRON ABSORPTION enhancers and inhibitors: ENHANCERS - VITAMIN C (ascorbic acid - in citrus fruits, guavas, dark green vegetables) - converts ferric (Fe3+) to ferrous (Fe2+) form which is better absorbed; ANIMAL PROTEINS (haem iron well absorbed). INHIBITORS - TEA AND COFFEE (tannins/polyphenols form insoluble complexes with iron); CALCIUM (milk, dairy, antacids); PHYTATES (whole grains, legumes); fibre; ANTACIDS (reduce gastric acidity needed for iron solubility). Counsel: take iron 1 hour BEFORE OR 2 hours AFTER meals (especially dairy/tea/coffee/antacids), with vitamin C source (orange juice).',
 'easy', 'approved', NULL, 'Paper II');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Community Health Nursing', 'Disaster Management',
 'Green tags in disaster management means:',
 'Victims need immediate care',
 'Victims can wait up to 3 hours',
 'The victims can wait up to 1 hour',
 'Victims are dead',
 'B',
 'DISASTER TRIAGE TAGS (START system): RED = IMMEDIATE - life-threatening but salvageable - treat first; YELLOW = DELAYED - serious but stable, can WAIT UP TO 1 HOUR for treatment; GREEN = MINOR/WALKING WOUNDED - can wait several hours (commonly up to 3 hours per some protocols) - least urgent; BLACK = EXPECTANT/DECEASED - no signs of life, or unsurvivable injuries given current resources. Option B - 3-hour green-tag waiting time - is a common quoted figure for minor injuries.',
 'easy', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'School Health',
 'The first step when organising a school health programme is:',
 'Planning with the stakeholders',
 'Gathering information',
 'Creating awareness',
 'Establishing partnerships between teachers and health workers',
 'B',
 'ORGANISING A SCHOOL HEALTH PROGRAMME - sequence: (1) GATHERING INFORMATION/BASELINE ASSESSMENT - situational analysis of school (number of pupils, current health status, existing facilities, problems, environment); without this baseline, planning is uninformed; (2) Stakeholder engagement and partnerships (teachers, parents, MOH, NGOs); (3) Awareness creation; (4) Joint planning with stakeholders; (5) Implementation; (6) Monitoring and evaluation. Option B - information-gathering - should always precede planning.',
 'easy', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Community Health',
 'Community health:',
 'Is concerned more with health of individuals',
 'Emphasises more on curative services',
 'Is different from population medicine',
 'Can be affected by education levels',
 'D',
 'COMMUNITY HEALTH: focuses on health of GROUPS/COMMUNITIES (not just individuals - option A wrong); emphasises HEALTH PROMOTION, PREVENTION - not just curative (option B wrong); CLOSELY RELATED TO public health/population health/community medicine - overlapping concepts (option C wrong); influenced by SOCIAL DETERMINANTS - EDUCATION level, income, housing, employment, gender etc. (option D TRUE). Educated communities have better health-seeking behaviour, lower fertility, better nutrition.',
 'easy', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Culture and Health',
 'Elements of culture include:',
 'Language, status, material life',
 'Values, beliefs, roles',
 'Religion, material life, status',
 'Languages, beliefs, social interactions',
 'B',
 'ELEMENTS OF CULTURE: VALUES (shared ideas about what is good/desirable); BELIEFS (ideas about reality, including religious beliefs); NORMS (rules and expectations - folkways, mores, taboos, laws); SYMBOLS and language; MATERIAL CULTURE (artefacts, technology); ROLES; rituals/customs; arts; social institutions (family, religion, education). Option B - VALUES, BELIEFS, ROLES - captures three core non-material elements of culture.',
 'easy', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Community Health Nursing Principles',
 'Principles of community health nursing include:',
 'Prioritising on curative and preventive aspects of health',
 'Minimising vertical programmes',
 'Centralisation of activities',
 'Utilising of only health professionals in health care delivery',
 'B',
 'COMMUNITY HEALTH NURSING (CHN) PRINCIPLES: emphasis on PREVENTION and HEALTH PROMOTION (not curative-first); HOLISTIC care; FAMILY and COMMUNITY-CENTRED; DECENTRALISATION (services brought close to communities - option C wrong); MULTIDISCIPLINARY teams INCLUDING community health volunteers/workers (NOT only professionals - option D wrong); INTEGRATION of services / minimisation of vertical (single-disease) programmes - favours horizontal integrated approach - option B TRUE; equity, accessibility, intersectoral collaboration, evidence-based practice.',
 'medium', 'approved', NULL, 'Paper II');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Health Systems & Management', 'Planning',
 'Planning for daily activities in the ward is an example of:',
 'Operational plan',
 'Tactical plan',
 'Strategic plan',
 'Contingency plan',
 'A',
 'LEVELS OF PLANNING by time horizon: STRATEGIC PLAN - LONG-TERM (3-10+ years), top management, broad organisational direction (vision, mission, goals); TACTICAL PLAN - INTERMEDIATE (1-3 years), middle management, specific objectives to achieve strategy (annual workplans); OPERATIONAL PLAN - SHORT-TERM (daily, weekly, monthly), front-line management, SPECIFIC ACTIVITIES - like daily ward planning, staff rosters - option A. CONTINGENCY PLAN - "what if" plans for emergencies/unexpected events.',
 'easy', 'approved', NULL, 'Paper II'),

('KRCHN', 'Health Systems & Management', 'Management Roles',
 'Management roles include:',
 'Controlling, decision making, directing',
 'Staffing, organising, information sharing',
 'Monitoring, liaison, decision making',
 'Planning, controlling, organising',
 'C',
 'MINTZBERG''S 10 MANAGERIAL ROLES grouped into 3 categories: INTERPERSONAL - figurehead, leader, LIAISON; INFORMATIONAL - MONITOR, disseminator, spokesperson; DECISIONAL - entrepreneur, disturbance handler, resource allocator, negotiator (i.e. DECISION-MAKING). Option C includes MONITORING, LIAISON, DECISION-MAKING - fits Mintzberg roles. Options A and D list management FUNCTIONS (Fayol''s POLC - planning, organising, leading/directing, controlling), not specifically Mintzberg roles.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Health Systems & Management', 'Management Theory',
 'The following theorist emphasised on the use of rules, regulations and policies to govern employees:',
 'Frederick Taylor',
 'Max Weber',
 'Henri Fayol',
 'Douglas McGregor',
 'B',
 'MANAGEMENT THEORISTS: FREDERICK TAYLOR - SCIENTIFIC management (time-motion studies, efficiency, piece-rate pay); HENRI FAYOL - 14 principles of management, classical administrative theory (POLC functions); MAX WEBER - BUREAUCRATIC theory: emphasised RULES, REGULATIONS, POLICIES, hierarchy of authority, impersonality, formal procedures, merit-based selection, division of labour - option B; DOUGLAS McGREGOR - Theory X and Y of human behaviour at work; ELTON MAYO - Hawthorne studies, human relations; ABRAHAM MASLOW - hierarchy of needs; HERZBERG - two-factor theory.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Health Systems & Management', 'Planning',
 'Tactical plans in an organisation:',
 'Focus on single daily action',
 'Are concerned on how to implement operational plans',
 'Are of intermediate time frame',
 'Are mainly developed from the major organisation goals',
 'C',
 'TACTICAL PLANS are MIDDLE-LEVEL plans of INTERMEDIATE TIME FRAME (1-3 years), bridging strategic and operational. They specify HOW to implement parts of the strategic plan - option B is reversed (tactical guides operational, not vice versa). Develop FROM STRATEGIC plans (which embody major organisational goals - option D describes strategic plans). Daily action plans are OPERATIONAL not tactical (option A). The defining feature of tactical plans is INTERMEDIATE time frame - option C.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Health Systems & Management', 'Leadership',
 'The following leadership style has the greatest regard for organisational policies and rules:',
 'Autocratic',
 'Democratic',
 'Bureaucratic',
 'Laissez-faire',
 'C',
 'LEADERSHIP STYLES: AUTOCRATIC - leader makes decisions unilaterally, strict control; DEMOCRATIC/participative - involves team in decisions; LAISSEZ-FAIRE - minimal direction, team autonomy; BUREAUCRATIC - leader manages by-the-book, STRICT ADHERENCE TO RULES, REGULATIONS AND POLICIES, formal procedures - option C; transformational - visionary, inspires change; transactional - rewards/sanctions. Bureaucratic style is best in high-risk standardised settings (safety-critical) but can stifle innovation.',
 'easy', 'approved', NULL, 'Paper II');

-- =============================================================================
-- Set 2 -- Parasitology, Communicable Diseases, Research, Family Planning
-- =============================================================================

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Community Health Nursing', 'Parasitology',
 'Auto-infection is commonly seen in:',
 'Trichuriasis',
 'Enterobiasis',
 'Ascariasis',
 'Schistosomiasis',
 'B',
 'AUTO-INFECTION (self re-infection) is commonly seen in ENTEROBIASIS (pinworm, Enterobius vermicularis): female worm migrates to perianal area at night to lay eggs, scratching transfers eggs to hands, hand-to-mouth ingestion, continuous self-infection cycle. Eggs are immediately infectious. Strongyloides stercoralis also has classic autoinfection (eggs hatch and re-invade host). Trichuriasis, ascariasis, schistosomiasis require an external maturation period before becoming infective.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Parasitology',
 'Examples of cestodes include:',
 'Hymenolepis nana, Taenia saginata, Diphyllobothrium latum',
 'Necator americanus, Ankylostoma duodenale, Taenia solium',
 'Echinococcus granulosus, Brugia malayi, Wuchereria bancrofti',
 'Ankylostoma duodenale, Loa loa, Onchocerca volvulus',
 'A',
 'Classification of helminths: NEMATODES (roundworms) - Ascaris, Trichuris, Enterobius, hookworms (Ancylostoma, Necator), Strongyloides, Loa loa, Wuchereria, Brugia, Onchocerca, Trichinella; CESTODES (tapeworms - flat segmented) - TAENIA (saginata = beef tapeworm; solium = pork tapeworm), HYMENOLEPIS NANA (dwarf tapeworm), DIPHYLLOBOTHRIUM LATUM (fish tapeworm), ECHINOCOCCUS granulosus (hydatid); TREMATODES (flukes) - Schistosoma, Fasciola, Clonorchis, Paragonimus. Option A lists 3 pure cestodes.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Parasitology',
 'Drug of choice for all Schistosomal species is:',
 'Oxamniquine',
 'Metrifonate',
 'Praziquantel',
 'Niclosamide',
 'C',
 'PRAZIQUANTEL is the DRUG OF CHOICE for ALL species of schistosomiasis (S. haematobium, mansoni, japonicum, intercalatum) - single oral dose 40 mg/kg (60 mg/kg for S. japonicum). Used in WHO mass drug administration programmes (preventive chemotherapy). OXAMNIQUINE - older drug effective only against S. mansoni. METRIFONATE - older drug for S. haematobium only. NICLOSAMIDE - for tapeworms (cestodes), not schistosomes. Praziquantel is also effective for tapeworms - broad antihelminthic.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Epidemiology',
 'A disease pandemic is one that:',
 'Few persons acquire over a short period of time',
 'Is always present in a population',
 'Occurs occasionally in a population',
 'Affects many people',
 'D',
 'DISEASE OCCURRENCE TERMINOLOGY: SPORADIC - occurs OCCASIONALLY/scattered (option C); ENDEMIC - habitually PRESENT in a defined area/population at expected levels (option B); HYPER-ENDEMIC - persistently high level; EPIDEMIC/outbreak - occurrence in EXCESS of expected; PANDEMIC - EPIDEMIC SPREAD OVER MULTIPLE COUNTRIES/CONTINENTS/WORLDWIDE affecting LARGE NUMBERS OF PEOPLE (option D). Examples of pandemics: 1918 influenza, HIV/AIDS, COVID-19. WHO declares pandemics.',
 'easy', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'HIV/AIDS',
 'Symptoms in stage 2 of WHO clinical staging of HIV/AIDS for adults include:',
 'Herpes zoster, seborrhoeic dermatitis',
 'Oral candidiasis, pulmonary TB',
 'Thrombocytopenia, pyomyositis',
 'Neutropenia, sinusitis',
 'A',
 'WHO HIV CLINICAL STAGING for adults: STAGE 1 - asymptomatic, generalised lymphadenopathy. STAGE 2 - moderate unexplained weight loss <10%, recurrent respiratory infections (sinusitis, otitis, pharyngitis), HERPES ZOSTER, angular cheilitis, recurrent oral ulcers, papular pruritic eruption, fungal nail infections, SEBORRHOEIC DERMATITIS - option A. STAGE 3 (advanced) - weight loss >10%, chronic diarrhoea >1 month, persistent fever, oral candidiasis, oral hairy leukoplakia, PULMONARY TB, severe bacterial infections (pneumonia, pyomyositis), thrombocytopenia <50, neutropenia - these are STAGE 3, not 2. STAGE 4 (AIDS) - wasting, PCP, oesophageal candida, extrapulm TB, Kaposi''s, toxoplasmosis.',
 'hard', 'approved', NULL, 'Paper II');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Maternal & Child Health', 'Immunisation',
 'Immunisation schedule for Rotavirus vaccine is:',
 '2 mls orally at 6 weeks and 10 weeks',
 '1.5 mls IM at 10 weeks and 14 weeks',
 '2 mls IM at 10 weeks and 14 weeks',
 '1.5 mls orally at 6 weeks and 10 weeks',
 'D',
 'Kenya KEPI ROTAVIRUS VACCINE (Rotarix monovalent) schedule: TWO DOSES, 1.5 mL ORALLY (NOT IM) at 6 weeks AND 10 weeks of age. Must complete by 24 weeks (latest) to minimise intussusception risk. CONTRAINDICATIONS: severe combined immunodeficiency (SCID), history of intussusception, prior severe allergic reaction. Mild gastrointestinal symptoms after vaccination are common. Option D: 1.5 mL orally at 6 and 10 weeks.',
 'medium', 'approved', NULL, 'Paper I'),

('KRCHN', 'Maternal & Child Health', 'Family Planning',
 'An example of a contraceptive method that falls in category 4 of the medical eligibility criteria includes:',
 'Combined oral contraceptives for women with thalassaemia',
 'Implants for women with Systemic Lupus Erythematosus',
 'Progestin-only contraceptives for women with sickle cell disease',
 'Intra-uterine contraceptive device for women with valvular heart disease',
 'D',
 'WHO MEDICAL ELIGIBILITY CRITERIA (MEC) categories: 1 = use without restriction; 2 = advantages outweigh risks (use); 3 = risks outweigh advantages (generally not recommended); 4 = UNACCEPTABLE HEALTH RISK - DO NOT USE. CATEGORY 4 examples: COCs in active breast cancer, active DVT/PE, smokers >35 years smoking >15/day, hypertension >160/100, severe cirrhosis, migraine with aura. IUCD in COMPLICATED VALVULAR HEART DISEASE (with pulmonary HTN, AF, history of subacute bacterial endocarditis) - CATEGORY 4 due to RISK OF BACTERIAL ENDOCARDITIS during insertion - option D. Uncomplicated valvular heart disease is Category 2.',
 'hard', 'approved', NULL, 'Paper I'),

('KRCHN', 'Maternal & Child Health', 'Child Development',
 'Normal developmental milestone for an infant aged 1 month include:',
 'Grasp actively, makes loud voices',
 'Follow object with eyes, play with hands',
 'Lifts head when prone, often smiles',
 'Good head control, grasps actively',
 'C',
 'Developmental milestones at 1 MONTH: GROSS MOTOR - when prone, lifts head briefly (option C); turns head side-to-side; FINE MOTOR - strong grasp reflex (not voluntary grasp); LANGUAGE - coos, gurgles; SOCIAL - first SOCIAL SMILES (often) by 4-6 weeks (option C); fixates on faces; follows objects briefly. Voluntary grasping (3-4 months), playing with hands (3 months), good head control (4 months) - these are later. Option C - lifts head when prone + early smiling - fits 1-month milestone.',
 'easy', 'approved', NULL, 'Paper I'),

('KRCHN', 'Nutrition', 'Micronutrient Deficiencies',
 'Angular stomatitis in children is as a result of deficiency in:',
 'Vitamin B2',
 'Vitamin B12',
 'Calcium',
 'Thiamine',
 'A',
 'ANGULAR STOMATITIS (cheilitis, perlèche) = cracking, fissuring at the corners of the mouth - classic feature of RIBOFLAVIN (VITAMIN B2) DEFICIENCY (other features: glossitis, magenta tongue, seborrhoeic dermatitis around nose/eyes, photophobia, corneal vascularisation). May also occur with iron deficiency, other B-vitamin deficiencies, Candida albicans infection, denture-related drooling. Treatment: vitamin B2 supplementation, identify and treat secondary cause (iron, candida). Sources of B2: milk, eggs, liver, green vegetables, whole grains.',
 'easy', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Social Change',
 'Gradual social change that occurs with very little or no human effort is referred to as:',
 'Evolution',
 'Reform',
 'Diffusion',
 'Revolution',
 'A',
 'TYPES OF SOCIAL CHANGE: EVOLUTION - GRADUAL, NATURAL, often unintentional change over long periods (e.g. demographic transitions, technological evolution) - option A; REFORM - planned, gradual, deliberate change within existing system (e.g. educational reform, health-sector reform); REVOLUTION - RADICAL, ABRUPT change overthrowing existing order; DIFFUSION - spread of cultural traits, innovations or behaviours from one group/society to another (e.g. spread of mobile phones, dietary trends).',
 'easy', 'approved', NULL, 'Paper II');

-- =============================================================================
-- Sets 3-8 -- Unique questions only (repeats excluded per source document)
-- =============================================================================

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Community Health Nursing', 'Malaria',
 'Identify the correct statement below concerning malaria:',
 'Humans are the definitive host for plasmodium',
 'Symptoms appear in the hepatic stage',
 'Malignant type is caused by falciparum species',
 'Artemether lumefantrine is the 1st line therapy for complicated malaria',
 'C',
 'MALARIA LIFE CYCLE: the MOSQUITO (Anopheles) is the DEFINITIVE host (sexual reproduction occurs there); HUMAN is the INTERMEDIATE host (asexual reproduction). Symptoms appear in the ERYTHROCYTIC (blood) stage, NOT hepatic (silent phase). PLASMODIUM FALCIPARUM causes MALIGNANT/SEVERE/COMPLICATED malaria - cerebral malaria, severe anaemia, multi-organ failure, ARDS - option C TRUE. ARTEMETHER-LUMEFANTRINE (AL) is 1st line for UNCOMPLICATED falciparum malaria; IV ARTESUNATE is 1st line for SEVERE/COMPLICATED malaria - option D wrong.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Trachoma',
 'The indications for surgery in trachoma include:',
 'Conjunctivitis and pannus',
 'Pannus and follicles',
 'Entropion and trichiasis',
 'Pannus and entropion',
 'C',
 'TRACHOMA (chronic conjunctivitis from Chlamydia trachomatis) progression and WHO SAFE strategy: S - SURGERY for late-stage scarring complications: TRICHIASIS (inwardly turned lashes scratching cornea) and ENTROPION (inwardly turned eyelid margin) - both threaten vision and need surgical correction (bilamellar tarsal rotation); A - ANTIBIOTICS (azithromycin mass treatment); F - FACIAL cleanliness; E - ENVIRONMENTAL improvement (clean water, sanitation, fly control). Pannus and follicles are EARLIER active stages, treated with antibiotics not surgery.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Primary Health Care',
 'The elements of Primary Health Care are:',
 'Maternal child health, nutrition, appropriate technology',
 'Immunisation, education, community rehabilitation',
 'Malaria control, essential drugs supply, equitable distribution of resources',
 'Mental health, integration of services, local disease control',
 'B',
 'ALMA ATA 8 ELEMENTS of PHC: Education on health problems; Locally endemic disease control; Expanded programme on IMMUNISATION; Maternal and child health (MCH/FP); Essential drugs supply; Nutrition; Treatment of common illnesses; Sanitation and safe water supply. Kenya added 3 more: Mental health, Dental health, HIV/AIDS - plus community-based rehabilitation. Option B lists immunisation, education, community rehabilitation - three accepted elements. APPROPRIATE TECHNOLOGY and EQUITABLE DISTRIBUTION (in options A and C) are PRINCIPLES, not elements.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Epidemiology',
 'The number of deaths from typhoid divided by the total deaths in a year multiplied by 100 is an example of:',
 'Case fatality rate',
 'Mortality rate',
 'Cause-specific death rate',
 'Case-specific death rate',
 'C',
 'MORTALITY RATIOS/RATES: PROPORTIONAL MORTALITY RATIO = deaths from a specific cause / TOTAL DEATHS x 100 - shows what proportion of all deaths are due to that cause (option C - cause-specific proportion); CASE FATALITY RATE = deaths from a disease / cases of that disease x 100 - measures lethality of a disease; CRUDE DEATH RATE/MORTALITY RATE = total deaths / total population x 1000; CAUSE-SPECIFIC DEATH RATE = deaths from a cause / total population x 100,000 (population-based). The question matches the proportional mortality definition - best fitting option C.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Occupational Health',
 'In occupational health, deployment of epileptics away from areas where they can easily injure themselves is an example of:',
 'Primary prevention',
 'Secondary prevention',
 'Tertiary prevention',
 'Mitigation',
 'A',
 'Applying LEVELS OF PREVENTION to occupational health: PRIMARY = preventing injury/disease BEFORE it occurs - pre-placement matching, engineering controls, PPE, training, ENVIRONMENTAL/job modification (e.g. KEEPING EPILEPTICS AWAY FROM heights, machinery, water where they could injure themselves during a seizure) - option A. SECONDARY = early detection (medical exams, screening). TERTIARY = rehabilitation after disease/injury. Pre-placement screening and job allocation to avoid risk = PRIMARY prevention.',
 'medium', 'approved', NULL, 'Paper II');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Community Health Nursing', 'Occupational Health',
 'An employee of a milk processing industry sustained a frost bite while putting milk in a deep freezer. This is an example of:',
 'Biological hazard',
 'Physical hazard',
 'Mechanical hazard',
 'Environmental hazard',
 'B',
 'OCCUPATIONAL HAZARDS classification: PHYSICAL - TEMPERATURE EXTREMES (heat/COLD - including frost bite), noise, vibration, radiation, illumination; CHEMICAL - solvents, dusts, fumes, gases; BIOLOGICAL - bacteria, viruses, fungi (e.g. healthcare-associated infections); MECHANICAL - slips/falls, machinery injuries; ERGONOMIC - repetitive strain, posture; PSYCHOSOCIAL - stress, harassment. Frost bite from sub-zero temperatures is a PHYSICAL hazard - option B.',
 'easy', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Ageing',
 'In Kenya a person is termed as an elderly from the age of:',
 '60 years',
 '55 years',
 '64 years',
 '80 years',
 'A',
 'In Kenya, an ELDERLY person is defined as one aged 60 YEARS AND ABOVE per the Constitution of Kenya 2010 (Article 57) and the Older Persons Act 2014. WHO commonly uses 60+ in developing countries, 65+ in developed countries. Kenya''s Inua Jamii cash transfer programme targets persons aged 70+, but the legal/policy definition of "elderly" starts at 60.',
 'easy', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Parasitology',
 'The infective stage of Taenia species is:',
 'Oncosphere',
 'Cysticerci',
 'Hexacanth',
 'Rhabditiform',
 'B',
 'TAENIA SAGINATA (beef tapeworm) and TAENIA SOLIUM (pork tapeworm) life cycle: HUMAN ingests undercooked meat containing CYSTICERCI (larval stage encysted in muscle), cysticerci attach to small intestine and mature into adult tapeworms, release proglottids/eggs in faeces, eggs ingested by intermediate host (cow for saginata, pig for solium), ONCOSPHERE/HEXACANTH embryo released, invades muscle, encysts as CYSTICERCI. So for HUMANS the INFECTIVE STAGE = CYSTICERCI in meat. Note: T. solium EGGS can also infect humans if ingested causing cysticercosis/neurocysticercosis.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Nutrition', 'Nutritional Assessment',
 'Anthropometry is the science of measuring:',
 'Size and make-up of the body and specific body parts',
 'Nutritional factors needed for growth and development',
 'Patients'' habitual intake of food and liquids',
 'Physical signs and symptoms of inadequate nutrition',
 'A',
 'ANTHROPOMETRY (anthropos = man, metron = measure) = science of measuring the SIZE AND PROPORTIONS of the human body - weight, height/length, MUAC, head circumference, skinfold thickness, BMI. Used for nutritional assessment, growth monitoring, screening for malnutrition (Z-scores against WHO/CDC growth standards). Distinct from: BIOCHEMICAL assessment (lab tests), CLINICAL assessment (signs/symptoms - option D), DIETARY assessment (food intake - option C - 24-hour recall, food frequency).',
 'easy', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Community',
 'A community may be defined as:',
 'Individuals and groups living and interacting within certain boundaries',
 'Groups of people sharing common health problems',
 'Individuals sharing same boundaries',
 'Families sharing common cultural beliefs',
 'A',
 'COMMUNITY definitions in community health: a GROUP OF INDIVIDUALS AND/OR GROUPS LIVING IN A DEFINED GEOGRAPHICAL AREA who INTERACT and have shared interests, characteristics, values, or institutions. Key elements: people + location/boundaries + INTERACTION + sense of belonging. Communities can be: GEOGRAPHIC (village, neighbourhood), FUNCTIONAL (school, workplace), CULTURAL (ethnic, religious), VIRTUAL (online). Option A captures the people + boundaries + interaction triad most completely.',
 'easy', 'approved', NULL, 'Paper II');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Community Health Nursing', 'Cold Chain',
 'Cold chain is defined as a system of:',
 'Immunising children and expectant mothers with a potent vaccine in the facility',
 'Maintaining vaccines in a potent state from the manufacturer to the consumer',
 'Maintaining the vaccine in a potent state in a health facility',
 'Transporting vaccines from the manufacturer to the consumer',
 'B',
 'COLD CHAIN = the SYSTEM (people, equipment, procedures) for MAINTAINING VACCINES at the RECOMMENDED TEMPERATURE (+2 to +8 degrees C, or frozen for some) FROM MANUFACTURER to AIRPORT to CENTRAL STORE to REGIONAL/COUNTY to SUB-COUNTY to FACILITY to CHILD (point of use). All links must be maintained. Tools: refrigerators with thermometers, cold boxes, vaccine carriers, ice packs, VVMs (vaccine vial monitors), temperature charts, freeze indicators. Break in cold chain leads to loss of vaccine potency and vaccination failures.',
 'easy', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Malaria',
 'The following plasmodia develop hypnozoites:',
 'P. ovale, P. vivax',
 'P. malariae, P. vivax',
 'P. malariae, P. falciparum',
 'P. ovale, P. falciparum',
 'A',
 'PLASMODIUM species: P. FALCIPARUM (commonest in Kenya, causes severe malaria, no hypnozoites); P. VIVAX (HYPNOZOITES = dormant liver forms causing relapses weeks-months-years later); P. OVALE (also HYPNOZOITES - relapses); P. MALARIAE (causes quartan fever, may recrudesce from low-level erythrocytic infection but NO hypnozoites); P. KNOWLESI (zoonotic). HYPNOZOITES require PRIMAQUINE (or tafenoquine) for radical cure to prevent relapses - testing for G6PD deficiency first because primaquine causes haemolysis in G6PD-deficient patients.',
 'hard', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Home Visiting',
 'Post-visit activities in home visiting:',
 'Are done in termination phase',
 'Include sharing reports',
 'Include evaluating the client',
 'Are done during every home visit',
 'B',
 'HOME VISITING PHASES and POST-VISIT activities: pre-visit (preparation), in-home (entry, implementation), termination (in-home - concluding the visit with client/family), POST-VISIT (back at the office) - includes DOCUMENTING the visit in client records, SHARING REPORTS/feedback with team and supervisor, PLANNING the NEXT visit, supplies replenishment, supervision/debrief. Evaluating the client (option C) happens DURING the in-home phase. Option B sharing reports - captures the key post-visit activity.',
 'easy', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Primary Health Care',
 'Equity in primary health care means:',
 'Every area should get same quantity of services',
 'Health resources and services should be distributed to everyone fairly',
 'All sectors should be involved in health care delivery',
 'The community should participate in their health',
 'B',
 'EQUITY (fairness) in health: distributing resources and services FAIRLY ACCORDING TO NEED - providing MORE to those with greater need and less to those with lesser need, to achieve equal HEALTH OUTCOMES. Distinct from EQUALITY (same amount to all regardless of need - option A - but this is not equity). Intersectoral collaboration (option C) is another PHC principle. Community participation (option D) is another PHC principle. Equity is about JUST distribution according to need - option B.',
 'easy', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Communicable Diseases',
 'Diseases transmitted through the faecal-oral route include:',
 'Poliomyelitis, mumps, typhoid',
 'Poliomyelitis, bacillary dysentery, viral hepatitis A',
 'Viral hepatitis A, amoebiasis, hydatidosis',
 'Poliomyelitis, cholera, schistosomiasis',
 'B',
 'FAECAL-ORAL transmitted diseases: VIRAL - POLIOMYELITIS, ROTAVIRUS, HEPATITIS A, HEPATITIS E, enteroviruses; BACTERIAL - CHOLERA, TYPHOID, BACILLARY DYSENTERY (shigella), E. coli, salmonella; PROTOZOAL - AMOEBIASIS, giardiasis, cryptosporidiosis; HELMINTHS - ascariasis, trichuriasis, enterobiasis, hookworm. MUMPS is DROPLET/airborne (option A wrong). SCHISTOSOMIASIS is via CERCARIAE in water through skin (option D wrong). Option B - poliomyelitis + bacillary dysentery + viral hepatitis A - all faecal-oral.',
 'medium', 'approved', NULL, 'Paper II');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Community Health Nursing', 'Epidemiology',
 'Enteric fevers are usually common at:',
 'Start of the rains and middle of dry season',
 'Any time of the year',
 'Middle of the dry season till the end',
 'End of the dry season and at the start of the rains',
 'D',
 'ENTERIC FEVERS (typhoid, paratyphoid) - Salmonella typhi/paratyphi A,B,C - transmitted via contaminated food/water. Epidemiologically common at the END OF THE DRY SEASON (when water becomes scarce and contaminated) AND THE START OF THE RAINS (when surface contamination is washed into water sources, but sanitation systems are overwhelmed) - option D. Hence outbreaks often follow these seasonal transitions. Prevention: safe water, sanitation, hand hygiene, food safety, vaccination (Vi polysaccharide or Ty21a oral).',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Parasitology',
 'The migratory phase of Ascaris is associated with:',
 'Cough, vague abdominal discomfort, pneumonitis',
 'Vague abdominal discomfort, vomiting, cough',
 'Fever, cough, allergic dermatitis',
 'Diarrhoea, fever, allergic dermatitis',
 'A',
 'ASCARIS LUMBRICOIDES life cycle: ingested eggs hatch in small intestine, larvae penetrate intestinal wall, MIGRATE via portal vein to LIVER, HEART, LUNGS (during which they cause PNEUMONITIS - LOFFLER''S SYNDROME with cough, wheeze, eosinophilia, transient lung infiltrates), ascend trachea, swallowed, mature into adult worms in small intestine (causing abdominal discomfort, malnutrition, intestinal obstruction). Option A captures pneumonitis + cough + vague abdominal discomfort of migratory phase. Treatment: albendazole or mebendazole.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Epidemiology',
 'The epidemiological triad includes:',
 'Agent, route of transmission, vector',
 'Host, agent, environment',
 'Vector, route of transmission, host',
 'Host, route of transmission, environment',
 'B',
 'EPIDEMIOLOGICAL TRIAD (also called epidemiologic triangle of disease causation): the THREE INTERACTING COMPONENTS necessary for disease: (1) AGENT (the cause - biological, chemical, physical, nutritional, social); (2) HOST (the susceptible individual - age, sex, genetics, immunity, behaviour); (3) ENVIRONMENT (the surroundings - physical, biological, socioeconomic, climate). Disease arises from the interaction. Public health interventions can target any vertex. Vectors and routes of transmission are sub-components of the agent-host-environment interaction.',
 'easy', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Immunisation',
 'Active immunity:',
 'Is acquired after several doses of a vaccine',
 'Is acquired after vaccination with a live vaccine',
 'Is only acquired when organisms invade the body',
 'Is life long',
 'D',
 'ACTIVE IMMUNITY = host''s own immune system produces antibodies/memory cells in response to antigen - NATURAL (after recovery from infection) or ARTIFICIAL (after vaccination, live or killed); develops over WEEKS but is LONG-LASTING, often LIFELONG (option D - generally true for many vaccines/infections; some require boosters). PASSIVE IMMUNITY = pre-formed antibodies transferred (transplacental, breast milk, immunoglobulin injection) - immediate but SHORT-LIVED (weeks-months). Active immunity from a SINGLE dose can suffice (live vaccines often single dose - option A/B not always true) and is NOT limited to live vaccines or natural infection (options B/C too narrow).',
 'easy', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Communicable Diseases',
 'The diseases caused by flukes/worms include:',
 'Leishmaniasis, onchocerciasis, dracunculiasis',
 'Schistosomiasis, trypanosomiasis, onchocerciasis',
 'Schistosomiasis, onchocerciasis, dracunculiasis',
 'Trypanosomiasis, onchocerciasis, dracunculiasis',
 'C',
 'FLUKES/WORMS (HELMINTHS): SCHISTOSOMIASIS (TREMATODE/fluke); ONCHOCERCIASIS (NEMATODE filaria); DRACUNCULIASIS (NEMATODE, guinea worm); ascariasis, hookworm, filariasis (lymphatic - Wuchereria/Brugia), Loa loa, etc. PROTOZOAL diseases (NOT worms): LEISHMANIASIS (Leishmania); TRYPANOSOMIASIS (Trypanosoma); malaria; amoebiasis; giardiasis. Option C - schistosomiasis + onchocerciasis + dracunculiasis - all worms. Options A and B include protozoal diseases (leishmaniasis, trypanosomiasis).',
 'medium', 'approved', NULL, 'Paper II');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Community Health Nursing', 'Zoonotic Diseases',
 'Zoonotic diseases include:',
 'Brucellosis, amoebiasis and anthrax',
 'Brucellosis, anthrax and rabies',
 'Anthrax, rabies and SARS',
 'Anthrax, tetanus and avian flu',
 'B',
 'ZOONOTIC diseases = transmitted from VERTEBRATE ANIMALS to humans: BRUCELLOSIS (cattle, goats, sheep - unpasteurised milk, contact); ANTHRAX (cattle, sheep, goats); RABIES (dogs, bats, wildlife); plague (rodents/fleas); leptospirosis (rats); Q fever; viral haemorrhagic fevers (Ebola/Marburg - bats; Lassa - rodents); avian flu (birds); SARS-CoV/CoV-2 (bats/civet/pangolin); zoonotic TB (cattle - M. bovis); echinococcosis; toxoplasmosis. Option B lists three classic bacterial zoonoses. AMOEBIASIS (option A) is human-to-human faecal-oral, not strictly zoonotic. TETANUS is environmental, not zoonotic.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Occupational Health',
 'In occupational health, secondary prevention services include:',
 'Training of the workforce on how to work with machines',
 'Screening employees at risk of a particular hazard',
 'Provision of crutches for the injured workers',
 'Utilisation of protective clothing in industries',
 'B',
 'OCCUPATIONAL HEALTH PREVENTION levels: PRIMARY = preventing disease/injury BEFORE it occurs - training workforce (option A), PPE (option D), engineering controls, job redesign, pre-placement assessment, immunisation. SECONDARY = EARLY DETECTION and prompt treatment of disease in pre-symptomatic stage - PERIODIC HEALTH SCREENING, biological monitoring, AUDIOMETRY for noise-exposed workers, SPIROMETRY for dust-exposed, PERIODIC examinations (option B). TERTIARY = limiting disability after disease - REHABILITATION, crutches for injured (option C), return-to-work programmes, compensation.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Communicable Diseases',
 'The anti-tuberculosis drug that is known to damage vision is:',
 'Streptomycin',
 'Rifampicin',
 'Isoniazid',
 'Ethambutol',
 'D',
 'FIRST-LINE TB drugs and major adverse effects: ISONIAZID (H) - hepatotoxicity, peripheral neuropathy (give pyridoxine); RIFAMPICIN (R) - hepatotoxicity, ORANGE secretions, drug interactions (enzyme inducer); PYRAZINAMIDE (Z) - hepatotoxicity, hyperuricaemia/gout; ETHAMBUTOL (E) - RETROBULBAR OPTIC NEURITIS leading to DECREASED VISUAL ACUITY, RED-GREEN COLOUR BLINDNESS, central scotoma - option D. Hence patients on ethambutol need baseline and periodic VISUAL ACUITY and colour vision testing; should report any vision changes immediately - usually reversible if stopped early. STREPTOMYCIN - ototoxicity (8th nerve damage, deafness), nephrotoxicity, NOT visual.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Disaster Management',
 'The process of increasing the community''s ability to handle a disaster is referred to as:',
 'Preparedness',
 'Response',
 'Mitigation',
 'Prevention',
 'A',
 'DISASTER MANAGEMENT CYCLE: PREVENTION (avoid disaster - e.g. relocation from flood plain); MITIGATION (reduce impact - e.g. flood walls, building codes); PREPAREDNESS (BUILDING CAPACITY/READINESS to respond - training, drills, stockpiling supplies, early warning systems, evacuation plans, community education - option A); RESPONSE (immediate actions during/after - search/rescue, emergency relief, casualty management); RECOVERY (rehabilitation, reconstruction). Preparedness specifically INCREASES community ABILITY to handle disasters.',
 'easy', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Communicable Diseases',
 'Signs and symptoms of rabies include:',
 'History of a dog bite, dribbling of saliva, difficulty in swallowing',
 'Itching at the site of the wound, fever, irritation and skin rash',
 'Difficulty in swallowing, history of dog bite, slow pulse',
 'Severe pain at site of the wound, difficulty in swallowing, saliva dribbling',
 'A',
 'RABIES clinical features after dog (or other mammal) bite, after incubation of weeks-months-years: PRODROMAL - fever, malaise, paraesthesia at bite site; EXCITATIVE/FURIOUS (commonest) - HYDROPHOBIA (fear of water - spasm of pharyngeal/laryngeal muscles when trying to drink leading to DIFFICULTY SWALLOWING and DRIBBLING OF SALIVA - option A), aerophobia, hyperactivity, hallucinations, seizures, autonomic dysfunction; PARALYTIC (dumb) - ascending paralysis, less common; COMA then DEATH (100% fatal once symptoms appear). PREVENTION: pre-exposure prophylaxis (high-risk groups); POST-EXPOSURE - IMMEDIATE wound washing with soap and water for 15 minutes + rabies immunoglobulin into wound + 4-dose vaccine schedule. Option A captures three classic features.',
 'medium', 'approved', NULL, 'Paper II');

-- BScN research/management questions from uncategorised sets
INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('BScN', 'Research & Evidence-Based Practice', 'Sampling',
 'A sampling method where the researcher picks every nth number is:',
 'Snowball sampling',
 'Stratified sampling',
 'Systematic sampling',
 'Purposive sampling',
 'C',
 'SYSTEMATIC SAMPLING - researcher selects EVERY Nth ELEMENT from an ordered list (sampling frame), starting from a randomly chosen starting point. e.g. every 10th name on patient register. Sampling INTERVAL = N (population size) divided by n (sample size). PROBABILITY method (every element has known chance of selection IF starting point is random). EASY to implement, evenly spread sample. WATCH OUT FOR PERIODICITY - if list has cyclic pattern matching the interval, bias. SNOWBALL (option A - non-probability, referrals from existing subjects - used for hidden populations). STRATIFIED (option B - random from each subgroup/stratum). PURPOSIVE (option D - non-probability, judgmental selection).',
 'medium', 'approved', NULL, 'Paper II'),

('BScN', 'Research & Evidence-Based Practice', 'Statistics',
 'The examination scores for students are as follows: 76, 54, 45, 92, 88, 47, 54. The range would be:',
 '45',
 '54',
 '47',
 '92',
 'C',
 'RANGE = highest value MINUS lowest value = a simple measure of variability/dispersion. Sorted: 45, 47, 54, 54, 76, 88, 92. RANGE = 92 - 45 = 47 - option C. Other dispersion measures: VARIANCE (mean of squared deviations from mean), STANDARD DEVIATION (square root of variance), INTERQUARTILE RANGE (IQR = Q3 - Q1, more robust to outliers). MEAN = (45+47+54+54+76+88+92)/7 = 456/7 approximately 65.1. MEDIAN = middle value (4th of 7) = 54. MODE = most frequent = 54.',
 'medium', 'approved', NULL, 'Paper II'),

('BScN', 'Research & Evidence-Based Practice', 'Research Methodology',
 'A hypothesis is:',
 'The possible application of research results',
 'Measure of degree of relationships between the variables under study',
 'A statement of the predicted relationship between variables under study',
 'Factors that are generally accepted as true',
 'C',
 'HYPOTHESIS = a TESTABLE STATEMENT PREDICTING THE RELATIONSHIP between two or more VARIABLES (option C). E.g., "increased iron supplementation is associated with reduced rates of anaemia in pregnancy." Types: NULL hypothesis (H0 - no relationship/difference, the one statistically tested); ALTERNATIVE hypothesis (H1 - there IS a relationship); DIRECTIONAL vs non-directional. Distinct from THEORY (broader explanatory framework), variables (measurable attributes), correlation (statistical measure of relationship - option B).',
 'easy', 'approved', NULL, 'Paper II'),

('BScN', 'Research & Evidence-Based Practice', 'Statistics',
 'The most frequently occurring score in a distribution is the:',
 'Mean',
 'Mode',
 'Median',
 'Average',
 'B',
 'MEASURES OF CENTRAL TENDENCY: MEAN (arithmetic average - sum / count); MEDIAN (middle value when sorted - robust to outliers); MODE (MOST FREQUENTLY OCCURRING value - option B); also weighted mean, geometric mean. Choice depends on data: NOMINAL data - mode only; ORDINAL - mode and median; INTERVAL/RATIO - all three. Skewed distributions: mean is pulled toward tail, median preferred. "Average" colloquially = mean.',
 'easy', 'approved', NULL, 'Paper II'),

('BScN', 'Research & Evidence-Based Practice', 'Sampling',
 'Cluster sampling requires that:',
 'The population be divided into groups',
 'The proportion of population be identified',
 'Every nth element from the population be selected',
 'All subjects in the population do not have equal chance of being selected',
 'A',
 'PROBABILITY SAMPLING METHODS: SIMPLE RANDOM (every member has equal chance); SYSTEMATIC (every nth - option C); STRATIFIED (population divided into homogeneous strata by characteristic, then random sample from each); CLUSTER (population divided into NATURALLY OCCURRING GROUPS/CLUSTERS - e.g. villages, schools, blocks - then SAMPLE entire clusters randomly; OR MULTI-STAGE - randomly select clusters then individuals within) - option A. Useful when population is geographically dispersed. NON-PROBABILITY: convenience, purposive, snowball, quota.',
 'medium', 'approved', NULL, 'Paper II');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('BScN', 'Research & Evidence-Based Practice', 'Research Report',
 'The logical order of the components of a research report is:',
 'Abstract, title, introduction, literature review, methodology, results, discussion',
 'Title, abstract, introduction, literature review, methodology, results, discussion',
 'Introduction, title, abstract, literature review, methodology, results, discussion',
 'Title, abstract, introduction, literature review, methodology, discussion, results',
 'B',
 'STANDARD RESEARCH REPORT structure (IMRAD-extended): TITLE PAGE, ABSTRACT, INTRODUCTION (background, problem, objectives, hypothesis, significance), LITERATURE REVIEW, METHODOLOGY (design, setting, population, sampling, data collection, analysis, ethics), RESULTS, DISCUSSION (interpret findings, compare to literature, limitations, implications), CONCLUSION, RECOMMENDATIONS, REFERENCES, APPENDICES. Option B follows this order correctly. The Discussion ALWAYS comes AFTER Results - results precede their interpretation.',
 'medium', 'approved', NULL, 'Paper II'),

('BScN', 'Nursing Management & Leadership', 'Nursing Care Models',
 'In functional nursing:',
 'Each nurse in a unit is assigned one or more nursing tasks for a number of patients or all patients in the ward',
 'The nurse is accountable for the total care of one or more patients for the period of her work shift',
 'Patients in a unit are divided to various groups under care of certain individual nurses',
 'There is comprehensive, continuous, coordinated and individualised nursing care',
 'A',
 'NURSING CARE DELIVERY MODELS: FUNCTIONAL NURSING - task-orientated; EACH NURSE assigned SPECIFIC TASKS (e.g. medications, observations, dressings) FOR ALL PATIENTS in unit - efficient but fragmented care, low job satisfaction - option A. TOTAL PATIENT CARE/case method - one nurse responsible for total care of one or more patients in a shift - option B. TEAM NURSING - patients DIVIDED INTO GROUPS, each group cared for by a small TEAM of mixed-skill nurses under team leader - option C. PRIMARY NURSING - one primary nurse responsible for complete 24-hour care planning of assigned patients - comprehensive, continuous, coordinated, individualised - option D.',
 'medium', 'approved', NULL, 'Paper II'),

('BScN', 'Nursing Management & Leadership', 'Disciplinary Process',
 'The first four steps in the disciplinary process are:',
 'Investigation to find cause, formal written warning and suspension, discussion and brief warning',
 'Investigation to find cause, discussion and brief warning, strong verbal warning, formal written warning',
 'Suspension from job, investigation to find the cause, formal written warning, strong verbal warning',
 'Strong verbal warning, interdiction without pay, discharge with opportunity to appeal, formal written warning',
 'B',
 'PROGRESSIVE DISCIPLINARY PROCESS: (1) INVESTIGATION to find cause/facts; (2) INFORMAL DISCUSSION/counselling and BRIEF WARNING; (3) STRONG VERBAL warning (more formal); (4) WRITTEN WARNING (formal documentation); (5) FINAL WRITTEN warning with suspension if appropriate; (6) Termination/dismissal with right to appeal. Process must follow employment law and labour relations principles - natural justice (notice, right to be heard, right to representation, appeal). Option B follows the standard sequence.',
 'medium', 'approved', NULL, 'Paper II'),

('BScN', 'Nursing Management & Leadership', 'Staffing',
 'The process of assigning competent people to fill the roles designed in the organisational hierarchy is:',
 'Staffing',
 'Scheduling',
 'Recruitment',
 'Induction',
 'A',
 'STAFFING - broader management function - ASSIGNING COMPETENT PEOPLE TO FILL ROLES designed in the organisational structure (overall human resource function). Sub-processes: WORKFORCE PLANNING (determining numbers/skills needed); RECRUITMENT (attracting candidates); SELECTION (assessing and choosing); APPOINTMENT; INDUCTION/orientation; deployment/scheduling; performance management; staff development; retention. Option A staffing is the umbrella term for the entire process. Recruitment is only one component.',
 'easy', 'approved', NULL, 'Paper II'),

('BScN', 'Nursing Management & Leadership', 'Motivation',
 'Motivational factors according to Herzberg''s two-factor theory include:',
 'Possibility of growth, the work itself',
 'Company policy, working conditions',
 'Interpersonal relationship, recognition',
 'Responsibility, good salary',
 'A',
 'HERZBERG''S TWO-FACTOR THEORY of motivation: MOTIVATORS (intrinsic) - factors that lead to JOB SATISFACTION and motivation: ACHIEVEMENT, RECOGNITION, WORK ITSELF (challenge, interest), RESPONSIBILITY, ADVANCEMENT, POSSIBILITY OF GROWTH/personal development - option A. HYGIENE/MAINTENANCE FACTORS (extrinsic) - factors that, if absent, cause DISSATISFACTION but if present don''t motivate: COMPANY POLICY, supervision, WORKING CONDITIONS, INTERPERSONAL relationships, SALARY/benefits, status, job security. So options B, C, D include hygiene factors. Option A - growth + work itself - are both motivators.',
 'medium', 'approved', NULL, 'Paper II');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('BScN', 'Research & Evidence-Based Practice', 'Research Ethics',
 'The principle of beneficence in research ethics involves:',
 'Researcher minimising harm to maximise the benefits of the study',
 'The right to full disclosure',
 'The right to fair treatment during research',
 'The right to privacy and confidentiality',
 'A',
 'FOUR PRINCIPLES OF RESEARCH ETHICS (Belmont Report, Helsinki Declaration): RESPECT FOR PERSONS/AUTONOMY - informed consent, full disclosure (option B); BENEFICENCE - do good, MAXIMISE BENEFITS AND MINIMISE HARM/risk to participants (option A - TRUE); NON-MALEFICENCE - do no harm; JUSTICE - FAIR SELECTION of participants, equitable distribution of benefits/burdens of research (option C); also: confidentiality and privacy protections (option D). Beneficence is specifically the risk-benefit assessment principle.',
 'easy', 'approved', NULL, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Immunisation',
 'According to KEPI schedule of immunisation, the correct dose for vitamin A at six months is:',
 '50,000 IU',
 '100,000 IU',
 '200,000 IU',
 '500,000 IU',
 'B',
 'KENYA MoH VITAMIN A SUPPLEMENTATION schedule (per Kenya Demographic Health Surveys and KEPI): 6-11 MONTHS - 100,000 IU (oral) every 6 months (option B); 12-59 MONTHS - 200,000 IU every 6 months; POSTPARTUM mothers within 8 weeks of delivery - 200,000 IU single dose. Vitamin A reduces child mortality (especially from measles and diarrhoeal disease), prevents xerophthalmia/night blindness. Question option B 100,000 IU is correct for 6-month dose.',
 'medium', 'approved', NULL, 'Paper II'),

('KRCHN', 'Research & Statistics', 'Statistics',
 'The test scores for an end of module examination were as follows: 85, 65, 75, 65, 70. The median value is:',
 '65',
 '72',
 '70',
 '85',
 'C',
 'MEDIAN = middle value when data is ARRANGED IN ORDER. Sorted ascending: 65, 65, 70, 75, 85. Number of values (n) = 5 (odd). Median position = (n+1)/2 = 3rd value = 70 - option C. Mean = (85+65+75+65+70)/5 = 360/5 = 72 (option B - but that''s mean, not median). Mode = 65 (most frequent, option A). For even n, median = average of two middle values.',
 'easy', 'approved', NULL, 'Paper II');
