-- Migration: 20260701000003
-- Source: NCK-NEW-MCQ-Compilation.docx — Year 2017 (NCK BScN Paper IV / KRCHN Paper I, April 2017)
-- Paper assignment per §12 nck-exam-system.md:
--   Q1 (AA/alcoholism rehab)     → Mental Health → Paper II both cadres
--   Q2 (forensic risk assessment)→ Mental Health → Paper II both cadres
--   Q3 (brain development)       → Anatomy & Physiology → Paper I both cadres
--   Q4 (strategic change mgmt)   → Nursing Management → Paper II both cadres
--   Q5 (HRM definition)          → Nursing Management → Paper II both cadres
--   Q6 (healthcare concern)      → Community Health → Paper II both cadres
-- exam_year = 2017
-- Audit: answers verified against primary references (§14.3).
-- ON CONFLICT (stem, cadre) DO NOTHING on every INSERT.
-- Note: 2017 BScN Paper II (Q1–Q14) already seeded in 20260628000002.
--       These 6 questions are from 2017 BScN Paper I / KRCHN Paper I — not yet seeded.

-- ── Q1: AA Step 1 — admit powerlessness over alcohol ─────────────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Mental Health Nursing','Substance Use Disorders','Dan, age 32, has been admitted for in-patient treatment of alcoholism. The doctor recommends he join AA. Dan must first:','Resolve to abstain from alcohol and help others do so','Admit he is powerless over alcohol and that he needs help','Make amends to the people he harmed while under the influence','Ask God to help him overcome his shortcomings','B','AA Step 1 requires the member to admit being powerless over alcohol and that life has become unmanageable — this is the foundational first step before any other recovery work can proceed (AA Twelve Steps; Mental Health Act Kenya rehabilitation principles).','medium',2017,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Mental Health Nursing','Substance Use Disorders','Dan, age 32, has been admitted for in-patient treatment of alcoholism. The doctor recommends he join AA. Dan must first:','Resolve to abstain from alcohol and help others do so','Admit he is powerless over alcohol and that he needs help','Make amends to the people he harmed while under the influence','Ask God to help him overcome his shortcomings','B','AA Step 1 (admission of powerlessness) is the prerequisite for engagement with the 12-step programme; nurses apply motivational interviewing and stage-of-change model to support readiness for Step 1 (AA Twelve Steps; Kenya mental health nursing).','medium',2017,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q2: Forensic risk assessment — index offence, history, insight, compliance
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Mental Health Nursing','Forensic Nursing','Factors to consider in risk assessment for dual-diagnosis violent offenders are:','Index offence, post-offending history, insight, treatment compliance','Index offence, post-offending history, insight, number of first-rank symptoms','Post-offending history, insight, treatment, orientation','Insight, treatment compliance, number of first-rank symptoms','A','Forensic risk assessment of dual-diagnosis violent offenders weighs four key domains: the index offence severity, post-offending history, degree of insight into illness and compliance with treatment (forensic psychiatric nursing texts; Kenya Mental Health Act).','medium',2017,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Mental Health Nursing','Forensic Nursing','Factors to consider in risk assessment for dual-diagnosis violent offenders are:','Index offence, post-offending history, insight, treatment compliance','Index offence, post-offending history, insight, number of first-rank symptoms','Post-offending history, insight, treatment, orientation','Insight, treatment compliance, number of first-rank symptoms','A','BScN nurses use structured professional judgement tools (HCR-20) incorporating historical (index offence, post-offending history), clinical (insight) and risk-management factors (treatment compliance) (forensic psychiatric nursing; Kenya Mental Health Act).','medium',2017,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q3: Early childhood brain development — abstract reasoning, response inhibition
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','Neuropsychologists believe that brain development in early childhood leads to increased capacities for:','Sexual expression and procreation','Intelligence and emotional expression','Egocentrism and perception-bound reasoning','Abstract reasoning and response inhibition','D','Prefrontal cortex maturation during early childhood increases capacity for abstract reasoning and response inhibition (executive function), forming the neurological basis for self-regulation and higher-order thinking (developmental neuropsychology).','easy',2017,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper I','Medical-Surgical Nursing','Anatomy and Physiology','Neuropsychologists believe that brain development in early childhood leads to increased capacities for:','Sexual expression and procreation','Intelligence and emotional expression','Egocentrism and perception-bound reasoning','Abstract reasoning and response inhibition','D','Prefrontal cortex myelination enables abstract reasoning and inhibitory control — the basis for paediatric health education approaches. BScN nurses apply developmental neuroscience in child assessment and family education (developmental neuropsychology; Kenya Basic Paediatric Protocols).','easy',2017,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q4: Strategic change management — no one right formula ───────────────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Health Systems & Management','Nursing Management','It is important to understand the organisational context in thinking about management of strategic change because:','There is no one right formula for managing strategic change — it must differ according to organisational context','It is important to analyse the environment to develop strategies','Understanding the time scale of change is important','Understanding managerial capabilities to manage change is important','A','Johnson & Scholes (strategic management texts used in nursing leadership) state there is no single right way to manage strategic change; the approach must be contingent on the specific organisational context (nursing management/strategy texts).','easy',2017,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Nursing Management & Leadership','Nursing Management','It is important to understand the organisational context in thinking about management of strategic change because:','There is no one right formula for managing strategic change — it must differ according to organisational context','It is important to analyse the environment to develop strategies','Understanding the time scale of change is important','Understanding managerial capabilities to manage change is important','A','Contingency theory underpins change management: BScN nurses leading change initiatives must assess organisational readiness, culture and capacity before selecting a change strategy (Johnson & Scholes; nursing management leadership texts).','easy',2017,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q5: HRM definition — strategic deployment of committed workforce ──────────
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Health Systems & Management','Nursing Management','Human resource management:','Seeks to achieve competitive advantage through the strategic deployment of a highly committed and capable workforce using an integrated array of cultural, structural and personnel techniques','Is simply an approach to managing people','Focuses on people as the resource of competitive advantage','Contributes to business strategy and plays an important role in implementation','A','Storey''s HRM definition (used in nursing management education) defines HRM as achieving competitive advantage through strategic deployment of a committed, capable workforce via integrated cultural, structural and personnel techniques (nursing management/leadership texts).','easy',2017,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Nursing Management & Leadership','Nursing Management','Human resource management:','Seeks to achieve competitive advantage through the strategic deployment of a highly committed and capable workforce using an integrated array of cultural, structural and personnel techniques','Is simply an approach to managing people','Focuses on people as the resource of competitive advantage','Contributes to business strategy and plays an important role in implementation','A','Storey''s strategic HRM model emphasises integration of HRM into organisational strategy; BScN nurses in management roles apply HRM principles in workforce planning, staff development and performance management (nursing management leadership texts; NCK curriculum).','easy',2017,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

-- ── Q6: Most frequently voiced healthcare concern — lack of health insurance ───
INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('KRCHN','Paper II','Community Health Nursing','Health Systems in Kenya','The most frequently voiced concern regarding health care is:','Lack of discounted rates','Poor choices in health management','Lack of access to health insurance','Dramatic changes in quality','C','Health policy and community health texts identify lack of access to health insurance (coverage) as the most frequently voiced public concern about health care — directly relevant to Kenya''s Universal Health Coverage agenda (Kenya MOH UHC strategy; community health nursing texts).','easy',2017,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;

INSERT INTO questions (cadre,paper,unit,topic,stem,option_a,option_b,option_c,option_d,correct_option,rationale,difficulty,exam_year,status,contributor_id)
VALUES('BScN','Paper II','Community Health Nursing','Health Systems in Kenya','The most frequently voiced concern regarding health care is:','Lack of discounted rates','Poor choices in health management','Lack of access to health insurance','Dramatic changes in quality','C','Access to health insurance remains a major barrier to care in Kenya; BScN nurses advocate for UHC, NHIF enrolment and community health financing as part of health systems strengthening roles (Kenya MOH UHC strategy; community health nursing).','easy',2017,'approved',NULL)ON CONFLICT(stem,cadre)DO NOTHING;
