-- =============================================================================
-- SEED: NCK Paper 3 — KRCHN Labelled Sets (2011, 2012, 2014)
-- =============================================================================
-- Source: NCK-Paper3-MCQs-with-Rationales.docx Section A
-- All confirmed KRCHN cadre
-- Paper assignment: per nck-exam-system.md Section 12 (Roman numerals)
-- All: status = 'approved', contributor_id = NULL (platform-owned)
-- =============================================================================

-- =============================================================================
-- KRCHN Paper 3 — August 2011
-- =============================================================================

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Community Health Nursing', 'Social Determinants of Health',
 'Socio-economic factors that have a bearing on health include:',
 'Education, live birth, blood test',
 'Blood test, housing, beliefs',
 'Housing, education, food',
 'Fertility, beliefs, live birth',
 'C',
 'The classic SOCIO-ECONOMIC DETERMINANTS OF HEALTH include: EDUCATION (literacy, health-seeking behaviour, child survival); HOUSING (overcrowding, ventilation, sanitation — affecting TB, ARI); FOOD AND NUTRITION (security and quality); income, employment, occupation; access to safe water; gender; culture and beliefs. Live birth and blood test are individual outcomes/investigations, not socio-economic determinants. Option C — housing + education + food — captures three core socio-economic determinants.',
 'easy', 'approved', 2011, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Immunisation',
 'The type of immunity a child acquires after receiving measles vaccine is:',
 'Humoral immunity',
 'Artificial active immunity',
 'Natural active immunity',
 'Innate immunity',
 'B',
 'Types of acquired immunity: NATURAL ACTIVE — from infection (e.g. having measles); NATURAL PASSIVE — transplacental IgG, breast milk; ARTIFICIAL ACTIVE — VACCINATION (immune system makes its own antibodies in response to vaccine antigen) — applies to measles vaccine — option B; ARTIFICIAL PASSIVE — immunoglobulin (e.g. rabies, tetanus immunoglobulin). Measles vaccine = artificial active immunity because the child''s own immune system is stimulated to produce antibodies and memory cells.',
 'easy', 'approved', 2011, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Cold Chain',
 'Vaccine potency can be maintained in the refrigerator by:',
 'Placing vaccines in the correct compartments, defrosting the refrigerator regularly, ensuring the maintenance of ideal temperature of 0° to 8°C',
 'Defrosting the refrigerator regularly, packing vaccines with enough space in-between to allow circulation of air, opening refrigerator only when necessary',
 'Avoiding contact of vaccines with evaporator, regulating the thermostat regularly, lining frozen icepacks in the inner walls of the refrigerator',
 'Ensuring the maintenance of ideal temperature of between +2° to +8°C, lining frozen icepacks in the inner walls of the refrigerator, placing vaccines in the correct compartments',
 'D',
 'KEPI cold-chain standards: vaccines stored at +2 to +8°C in the refrigerator (NOT 0-8°C — freezing damages DPT, Hib, Hepatitis B, Pentavalent, PCV); ice packs lined in inner walls (cold-life buffer for power outages); BCG and measles in TOP shelf; OPV in middle; DPT/HepB/Penta on lower shelf (AWAY from evaporator/freezer); cold-chain monitor (VVM); never re-freeze freeze-sensitive vaccines (Shake test). Option D lists the correct temperature range (+2 to +8°C) with proper storage practices.',
 'medium', 'approved', 2011, 'Paper II'),

('KRCHN', 'Nutrition', 'Vitamin Deficiencies',
 'Deficiency of vitamin B1 (Thiamine) leads to:',
 'Heart failure, abnormal nerve and brain function, emotional disturbances',
 'Rupture of red blood cells, muscle spasm, bleeding',
 'Night blindness, heart failure, impaired sensory perception',
 'Emotional disturbances, rupture of red blood cells, nerve damage',
 'A',
 'Thiamine (Vit B1) deficiency causes BERIBERI: WET beriberi — cardiovascular (high-output HEART FAILURE, peripheral oedema, dilated cardiomyopathy); DRY beriberi — neurological (peripheral polyneuropathy, paresthesia, weakness, foot drop — ABNORMAL NERVE AND BRAIN FUNCTION); CEREBRAL beriberi (Wernicke-Korsakoff in alcoholics) — confusion, ataxia, ophthalmoplegia, memory loss (EMOTIONAL DISTURBANCES). Sources: whole grains, legumes, pork. Risk groups: alcoholics, infants of malnourished mothers, polished-rice diets, hyperemesis gravidarum. Option A captures all three manifestations.',
 'medium', 'approved', 2011, 'Paper II'),

('KRCHN', 'Medical-Surgical Nursing', 'Electrolyte Imbalances',
 'Hypokalaemia is a condition characterised by low:',
 'Blood calcium levels',
 'Magnesium in the blood',
 'Potassium in the blood',
 'Sodium levels in the blood',
 'C',
 'HYPO-KAL-EMIA = LOW POTASSIUM (kalium = potassium; K+) in blood (serum K <3.5 mmol/L). Causes: diarrhoea, vomiting, diuretics (loop, thiazides), aldosteronism, refeeding syndrome, insulin therapy, alkalosis. Features: muscle weakness, cramps, paralytic ileus, paraesthesia, ECG changes (flat T waves, U waves, ST depression, prolonged PR), arrhythmias. Treatment: oral or IV K+ replacement (slow — never bolus). Hyponatraemia/hypocalcaemia/hypomagnesaemia are different deficiencies.',
 'easy', 'approved', 2011, 'Paper I');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Medical-Surgical Nursing', 'Sexually Transmitted Infections',
 'The stage of syphilis characterised by the presence of gumma lesions is:',
 'Primordial',
 'Latent',
 'Tertiary',
 'Secondary',
 'C',
 'Syphilis stages: PRIMARY (3 weeks post-infection — painless chancre at site of inoculation, regional adenopathy); SECONDARY (6 weeks-6 months — generalised rash including palms/soles, condylomata lata, mucous patches, systemic features); LATENT (asymptomatic, serologically positive — early <2 yrs, late >2 yrs); TERTIARY (years later — GUMMAS = chronic granulomatous lesions of skin, bone, viscera; CARDIOVASCULAR syphilis = aortitis, aneurysms; NEUROSYPHILIS = tabes dorsalis, general paresis). Gumma lesions are pathognomonic of TERTIARY syphilis — option C.',
 'medium', 'approved', 2011, 'Paper I'),

('KRCHN', 'Medical-Surgical Nursing', 'STI Management',
 'The recommended second-line treatment of urethritis in an adult is:',
 'Norfloxacin 800 mg stat plus doxycycline 100 mg BD for 7 days',
 'Norfloxacin 800 mg twice a day for 7 days and spectinomycin 2 mg IM stat',
 'Erythromycin 100 mg BD for 14 days and ceftriaxone 62.5 mg IM stat',
 'Spectinomycin 2 g IM stat and doxycycline 100 mg BD for 7 days',
 'D',
 'Urethritis in adults — Kenya MoH guidelines treat as syndromic management for gonococcal + non-gonococcal urethritis (chlamydia). FIRST line: ceftriaxone 250 mg IM stat + doxycycline 100 mg BD × 7 days (or azithromycin 1g stat). SECOND line (for cephalosporin allergy or treatment failure): SPECTINOMYCIN 2 g IM STAT (for gonorrhoea) + DOXYCYCLINE 100 mg BD × 7 DAYS (for chlamydia) — option D. Always treat partners, screen for other STIs (HIV, syphilis), and counsel on prevention.',
 'medium', 'approved', 2011, 'Paper I'),

('KRCHN', 'Community Health Nursing', 'Occupational Health',
 'The occupational disease that persons working in information technology are likely to develop is:',
 'Lead poisoning',
 'Radiation sickness',
 'Carpal tunnel syndrome',
 'Mesothelioma',
 'C',
 'Occupational diseases by sector: IT/clerical/repetitive keyboard work — CARPAL TUNNEL SYNDROME (median nerve compression at wrist from repetitive movements — numbness, tingling, weakness in thumb/index/middle fingers); also neck/back pain, computer vision syndrome. Lead poisoning — battery workers, painters. Radiation sickness — radiographers, nuclear workers. Mesothelioma — asbestos-exposed workers (mining, construction, insulation). Carpal tunnel is the classic IT-related occupational disease.',
 'easy', 'approved', 2011, 'Paper II'),

('KRCHN', 'Health Systems & Management', 'Management Principles',
 'The principle of unity of command in any organisation is important because:',
 'The superior is able to assign part of his job domain to his/her subordinate, thus avoids overworking',
 'It avoids divided loyalty since each employee receives orders from one superior',
 'Employees are self-disciplined and self-controlled, so require very little supervision',
 'It ensures smooth working at all levels of the organisation',
 'B',
 'Fayol''s 14 PRINCIPLES OF MANAGEMENT: UNITY OF COMMAND = each employee should receive orders from ONLY ONE SUPERIOR — avoids conflicts, divided loyalty, confusion, contradictory instructions. Distinct from UNITY OF DIRECTION = all activities working toward same objective should have one head and one plan. Option B captures the essence — single line of authority preserves accountability and clear loyalty. This principle is fundamental to classical management theory and remains relevant in nursing management.',
 'easy', 'approved', 2011, 'Paper II'),

('KRCHN', 'Health Systems & Management', 'Management Theory',
 'Which of the following is correct? (a) According to Douglas McGregor''s Theory X, an employee will exercise self-discipline and self-control in certain circumstances. (b) When reprimanding an employee, the supervisor should avoid arguments and listen carefully to all comments.',
 '(a) TRUE and (b) TRUE',
 '(a) FALSE and (b) TRUE',
 '(a) TRUE and (b) FALSE',
 '(a) FALSE and (b) FALSE',
 'B',
 '(a) FALSE — McGregor''s THEORY X assumes employees DISLIKE work, AVOID responsibility, NEED COERCION, threats and CLOSE SUPERVISION (because they will NOT exercise self-discipline). THEORY Y is the opposite — assumes employees enjoy work, are self-motivated, seek responsibility and exercise self-control. So self-discipline belongs to Theory Y, not X. (b) TRUE — effective reprimanding: be private, factual, prompt, listen carefully to the employee''s perspective, avoid arguments, focus on behaviour not personality, end positively. Option B: (a) FALSE and (b) TRUE.',
 'medium', 'approved', 2011, 'Paper II');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Environmental Health', 'Food Preservation',
 'Methods of food preservation which inhibit multiplication of bacteria include:',
 'Smoking, pasteurisation, salting',
 'Pasteurisation, canning, salting',
 'Canning, blanching, drying',
 'Drying, freezing, smoking',
 'D',
 'Food preservation methods: KILL bacteria — pasteurisation, canning, irradiation, sterilisation. INHIBIT MULTIPLICATION (bacteriostatic) — DRYING (removes water — pathogens need water), FREEZING (low temperature halts enzymatic and microbial activity), SMOKING (combination of dehydration and antimicrobial chemicals from smoke); SALTING (high osmotic pressure draws water out of microbes). Blanching is a brief pre-treatment, not preservation per se. Option D — all three INHIBIT multiplication without necessarily killing. Pasteurisation and canning KILL bacteria, so options A, B, C are incorrect.',
 'medium', 'approved', 2011, 'Paper II'),

('KRCHN', 'Medical-Surgical Nursing', 'Communicable Diseases',
 'Clinical features of typhoid fever in the first week following the prodromal phase include:',
 'Meningism, constipation, enlarged spleen',
 'Pea-soup diarrhoea, meningism, stepwise rise in temperature',
 'Constipation, abdominal distension, broncho-pneumonia',
 'Mental confusion, enlarged spleen, pea-soup diarrhoea',
 'B',
 'Typhoid fever (Salmonella typhi) clinical course: WEEK 1 — STEPWISE/staircase rise in temperature (rises each day, falls each morning), headache, malaise, dry cough; relative bradycardia (Faget''s sign); pea-soup DIARRHOEA or constipation; sometimes meningism. WEEK 2 — sustained high fever, rose spots on trunk, HEPATOSPLENOMEGALY, mental confusion ("typhoid state"). WEEK 3 — complications: INTESTINAL PERFORATION, haemorrhage, myocarditis, encephalopathy. WEEK 4 — convalescence. Diagnosis: blood culture (best week 1), Widal (week 2). Treatment: ciprofloxacin/ceftriaxone.',
 'medium', 'approved', 2011, 'Paper I'),

('KRCHN', 'Maternal & Child Health', 'Family Planning',
 'Progestin-only pills work primarily by:',
 'Thickening cervical mucus, thus blocking sperm from meeting an egg',
 'Causing a chemical change that damages sperms and eggs before they can meet',
 'Suppressing the release of gonadotrophins',
 'Plugging the fallopian tubes thus preventing egg from meeting sperm',
 'A',
 'Mechanism of action of PROGESTIN-ONLY PILLS (POPs/mini-pills): PRIMARY action is THICKENING OF CERVICAL MUCUS (making it hostile to sperm penetration); also thins the endometrium (reduces implantation); slows tubal motility; inhibits ovulation in ~50% of cycles (variable — unlike combined COCs which reliably suppress ovulation). Because cervical-mucus effect is the primary mechanism and is time-sensitive, POPs must be taken at the SAME TIME EACH DAY (window only 3 hours). Option A is the correct primary mechanism.',
 'medium', 'approved', 2011, 'Paper I'),

('KRCHN', 'Community Health Nursing', 'Disaster Management',
 'The goals of triaging in disaster management are:',
 'Early patient assessment, control infection, determination of urgency of need of care',
 'Document initial patient assessment, teach health care to the patient, notify care providers of incoming patients',
 'Obtain past history records if needed, teach health care to patient, control infection',
 'Brief overall patient assessment, control the flow of patients and visitors, take phone calls regarding incoming patients',
 'A',
 'TRIAGE (French for "to sort") in disasters/emergencies: rapid INITIAL ASSESSMENT of all incoming casualties, DETERMINING URGENCY of treatment, prioritising those most likely to benefit from limited resources. Standard triage categories (e.g. START): RED (immediate, life threats); YELLOW (delayed — serious but stable); GREEN (minor — "walking wounded"); BLACK (expectant/deceased). Also includes infection control, identification and documentation. Option A — early patient assessment + infection control + determination of urgency — captures the three core goals.',
 'medium', 'approved', 2011, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Dental Health',
 'A tooth cavity that gets close to or reaches the pulp causes:',
 'Pain only when one drinks something cold or eats candy',
 'Sensitivity to the tooth when one bites',
 'Lingering pain even after a stimulus (e.g. cold water) is removed',
 'Swelling due to pus in the adjacent gum',
 'C',
 'Dental caries progression: ENAMEL caries (superficial) = no symptoms or transient cold/sweet sensitivity that resolves immediately. DENTIN caries = sharper pain to cold/sweet, brief, resolves on removal of stimulus. PULPAL involvement (PULPITIS) — early reversible = transient sensitivity; LATE/IRREVERSIBLE PULPITIS = LINGERING PAIN after the stimulus is removed (sometimes spontaneous, throbbing), heat-aggravated — needs root canal or extraction. PERIAPICAL ABSCESS = gum swelling with pus — option D. Option C correctly describes irreversible pulpitis.',
 'medium', 'approved', 2011, 'Paper II');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Maternal & Child Health', 'Growth and Development',
 'Growth and development increases in a rapid spurt at ages of:',
 '2 to 5 years',
 '9 to 12 years',
 '6 to 12 months',
 '5 to 8 years',
 'B',
 'Periods of RAPID GROWTH (growth spurts) in human development: (1) INFANCY 0-12 months — first major spurt (triples birth weight by 12 months); (2) ADOLESCENCE — second major spurt: girls 9-13 years (peak velocity ~12 years), boys 11-15 years (peak ~14 years). Period 9-12 years aligns with pre-pubertal/early-pubertal spurt particularly in girls. Toddler/preschool/early-school years (1-9 years) is steady but slower growth. Option B fits the adolescent spurt.',
 'easy', 'approved', 2011, 'Paper I'),

('KRCHN', 'Health Systems & Management', 'Health System Structure',
 'Primary Health Care activities at the district level are co-ordinated by the:',
 'Medical officer of health',
 'District development committee',
 'Public health officer',
 'District health management team',
 'D',
 'Per Kenya health system structure, at the DISTRICT (now COUNTY/sub-county) level, the DISTRICT HEALTH MANAGEMENT TEAM (DHMT) coordinates all health activities — chaired typically by the District Medical Officer of Health, but it is a TEAM (DMOH, nursing officer, public health officer, pharmacist, finance officer, health records officer, etc.) that collectively coordinates planning, supervision, monitoring, and implementation. The DHMT is the operational coordinating body for PHC at district level. With devolution, equivalent bodies are at sub-county level (SCHMT) and County Health Management Team (CHMT).',
 'easy', 'approved', 2011, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Home Visiting',
 'Activities of the pre-visit phase of home visiting include:',
 'Sharing information on reason and purpose of visit with the family, gathering information on the location of the house, assessing the family needs and planning nursing care with them',
 'Recording important events about the family, gathering some information on need of visit, introducing oneself to the family',
 'Gathering information on the location of the house, gathering some information on need of visit, assembling supplies needed for the visit',
 'Investigating community resources, establishing nurse-patient relationship, transferring the client to another nurse for care',
 'C',
 'Phases of HOME VISITING: (1) PRE-VISIT — REVIEW CLIENT RECORDS/find out client/family background, GATHER INFORMATION on the need and purpose of visit, plan objectives, contact family to schedule visit, ASSEMBLE SUPPLIES (home-visiting bag with relevant equipment), get directions/LOCATION of house, transport arrangements. (2) IN-HOME (initiation) — greet, introduce self, establish rapport. (3) IMPLEMENTATION — assessment, intervention, health education. (4) TERMINATION — summary, plan next visit. (5) POST-VISIT — DOCUMENTATION, plan follow-up. Option C lists three classic pre-visit activities.',
 'medium', 'approved', 2011, 'Paper II'),

('KRCHN', 'Maternal & Child Health', 'Child Development',
 'Factors that promote development in children include:',
 'Good nutrition, emotional support, play',
 'Child spacing, nutrition, immunisation',
 'Good antenatal care, play, follow-up clinic',
 'Birth order, child spacing, emotional support',
 'A',
 'Factors PROMOTING child development: GOOD NUTRITION (especially first 1000 days — protein, energy, micronutrients, breast milk); EMOTIONAL SUPPORT/secure attachment (responsive caregiving, low chronic stress); PLAY AND STIMULATION (cognitive, language, motor development); good health (immunisation, prevention/treatment of illness); safe physical environment. Per UNICEF Nurturing Care Framework: good health + adequate nutrition + responsive caregiving + opportunities for early learning + security and safety. Option A captures three of the most fundamental factors.',
 'easy', 'approved', 2011, 'Paper I');

-- =============================================================================
-- KRCHN Paper 3 — August 2012
-- =============================================================================

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Community Health Nursing', 'Community Diagnosis',
 'Community diagnosis is carried out:',
 'With active participation of members of the community',
 'With active participation of the leaders in the community',
 'With active participation of health workers only',
 'By strictly looking at medical problems',
 'A',
 'COMMUNITY DIAGNOSIS (community health assessment) is the process of identifying the health status, needs and priorities of a community. The KEY PRINCIPLE is ACTIVE COMMUNITY PARTICIPATION — community members must be partners in identifying their own problems, ranking priorities, and developing solutions (per Alma Ata declaration). Health workers facilitate and bring technical expertise but the process is community-led. Community diagnosis goes beyond medical problems to encompass SOCIAL, ENVIRONMENTAL, ECONOMIC determinants.',
 'easy', 'approved', 2012, 'Paper II'),

('KRCHN', 'Research & Statistics', 'Epidemiology',
 'Incidence rate:',
 'Is used to record protracted diseases',
 'Shows the magnitude/burden of disease in the community',
 'Is useful for planning and administration of health care services',
 'Shows the rate of development of disease in the community',
 'D',
 'INCIDENCE RATE = (number of NEW cases occurring in a defined population over a specified time period) / (population at risk during that period). Measures the RATE OF DEVELOPMENT of new disease cases — useful for ACUTE diseases, outbreak detection, and epidemiology research. PREVALENCE (option B) = total cases existing at a point — shows burden — useful for chronic diseases and service planning. Incidence is preferred for studying causation and acute disease dynamics.',
 'easy', 'approved', 2012, 'Paper II'),

('KRCHN', 'Maternal & Child Health', 'Immunisation',
 'The common side effect a nurse should counsel a mother for after giving her child pneumococcal vaccine is:',
 'Unusual crying',
 'Loss of appetite',
 'Diarrhoea and vomiting',
 'Blood clot at the site of injection',
 'A',
 'PCV (pneumococcal conjugate vaccine) is given at 6, 10 and 14 weeks in Kenya KEPI. Common side effects: PAIN/redness/swelling at injection site; FEVER (low grade); FUSSINESS/IRRITABILITY/UNUSUAL CRYING; mild loss of appetite; drowsiness. Most resolve within 24-48 hours. Severe reactions are rare. Counsel mother: warm/cold compress to site, paracetamol if febrile/distressed, expected to settle. Diarrhoea/vomiting is more typical of OPV/rotavirus. Blood clot is not a vaccine effect.',
 'easy', 'approved', 2012, 'Paper I'),

('KRCHN', 'Community Health Nursing', 'Immunisation',
 'A special consideration for immunocompromised persons regarding immunisation is that:',
 'Asymptomatic HIV-infected children should not receive BCG vaccine',
 'Live vaccines can safely be given to persons on corticosteroid therapy',
 'Asymptomatic children infected with HIV should receive all standard KEPI vaccines',
 'Pentavalent vaccine can be administered to a child with neurologic disease so long as they are monitored closely',
 'C',
 'Per Kenya MoH PMTCT and KEPI guidelines for HIV-EXPOSED/INFECTED children: ASYMPTOMATIC HIV-INFECTED CHILDREN should RECEIVE ALL STANDARD KEPI VACCINES at the routine times (including LIVE vaccines — BCG, OPV, measles) — the benefits outweigh the risks. SYMPTOMATIC HIV infection or severe immunosuppression — DEFER live vaccines (BCG, OPV, measles, yellow fever). Persons on high-dose corticosteroids — DEFER live vaccines. Children with progressive neurological disease — defer pertussis-containing (DPT/Penta) until stable. Option C is the correct general rule for asymptomatic HIV.',
 'medium', 'approved', 2012, 'Paper II'),

('KRCHN', 'Environmental Health', 'Sanitation',
 'When constructing a septic tank for 15 users, the recommended dimensions are:',
 'Length 300 cm, Breadth 60 cm, Width 150 cm',
 'Length 200 cm, Breadth 60 cm, Width 100 cm',
 'Length 360 cm, Breadth 60 cm, Width 160 cm',
 'Length 450 cm, Breadth 60 cm, Width 150 cm',
 'A',
 'Per Kenya public health/environmental health design standards, a septic tank for 15 users is typically designed using formulae based on daily sewage production (~120 L/person) and required retention time (~24 hours), plus sludge storage capacity. Standard dimensions for ~15-user household septic tank: LENGTH ~3 m (300 cm), BREADTH ~0.6 m (60 cm), DEPTH/WIDTH ~1.5 m (150 cm). Length:breadth ratio typically 2:1 to 3:1; depth 1.5-2 m. Two-chamber design for solids settling and liquid effluent.',
 'hard', 'approved', 2012, 'Paper II');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Medical-Surgical Nursing', 'Communicable Diseases',
 'A typical case of severe cholera presents with:',
 'Profuse watery stool preceding vomiting',
 'High fever with severe abdominal cramps',
 'Vomiting preceding profuse watery stool',
 'Decreased urine production preceding profuse watery stool',
 'A',
 'CHOLERA (Vibrio cholerae O1/O139): incubation 12-72 hours; classic presentation begins with SUDDEN ONSET PROFUSE WATERY DIARRHOEA (rice-water stools — pale, flecked, odourless, isotonic with plasma), 10-20 stools/day, with subsequent vomiting. NO blood, NO mucus, USUALLY AFEBRILE, NO abdominal cramps (or mild). Rapid dehydration → hypovolaemic shock → death within hours if untreated. Treatment: aggressive ORAL or IV REHYDRATION (Ringer''s lactate); doxycycline (children: erythromycin/azithromycin); zinc in children. Notifiable disease.',
 'medium', 'approved', 2012, 'Paper I'),

('KRCHN', 'Medical-Surgical Nursing', 'Communicable Diseases',
 'Amoebic dysentery:',
 'Is spread by infected persons who pass infective trophozoites in faeces',
 'Presents with very severe tenesmus',
 'May present with bottle-shaped ulcers on the intestinal wall',
 'Has an epidemic occurrence',
 'C',
 'AMOEBIC DYSENTERY (Entamoeba histolytica): transmission = ingestion of CYSTS (not trophozoites — trophozoites are fragile and die outside host) in faecally-contaminated food/water — option A is partially wrong. Clinical: gradual onset bloody diarrhoea with mucus, abdominal cramps, MILD tenesmus (severe tenesmus is more classical of shigellosis/bacillary dysentery — option B wrong). PATHOLOGY: classic FLASK-SHAPED/BOTTLE-SHAPED ULCERS in colon (narrow neck, broad base — option C correct). Sporadic, NOT typically epidemic (option D wrong). Treatment: metronidazole + luminal agent (diloxanide/paromomycin).',
 'medium', 'approved', 2012, 'Paper I'),

('KRCHN', 'Nutrition', 'Micronutrient Deficiencies',
 'A child who presents with widening of the wrists, recurrent pneumonia and has prominent costochondral joints is likely to have:',
 'Vitamin A deficiency',
 'Vitamin B deficiency',
 'Vitamin C deficiency',
 'Vitamin D deficiency',
 'D',
 'VITAMIN D DEFICIENCY in children → RICKETS. Classic clinical features: WIDENED WRISTS AND ANKLES (epiphyseal widening); RACHITIC ROSARY (prominent costochondral junctions); pigeon-chest, Harrison''s sulcus; bowed legs/knock knees (genu varum/valgum); craniotabes; delayed dental eruption; SHORT STATURE/delayed milestones; muscle weakness; RECURRENT CHEST INFECTIONS (PNEUMONIA — soft chest wall and weak muscles). Causes: lack of sunlight exposure, dietary deficiency, malabsorption, dark skin, breastfed beyond 6 months without supplementation. Treatment: vitamin D + calcium supplementation.',
 'medium', 'approved', 2012, 'Paper II'),

('KRCHN', 'Nutrition', 'Nutritional Assessment',
 'Measurement of the mid-upper arm circumference is performed:',
 'When the child''s age is under one year',
 'With or without a weighing scale',
 'As a screening method for in-patients',
 'During field surveys',
 'D',
 'MUAC (mid-upper arm circumference) is a quick, simple, low-tech NUTRITIONAL SCREENING tool. Best used in CHILDREN 6-59 MONTHS for screening acute malnutrition. WHO/Kenya cut-offs: <11.5 cm = SEVERE acute malnutrition (red zone); 11.5-12.5 cm = moderate (yellow); ≥12.5 cm = normal (green). Used in FIELD SURVEYS, mass screening, mother-led screening ("family MUAC"), and emergency settings — IDEAL where weighing scales and height boards are impractical. NOT specifically for under-1s (used 6-59 months); CAN be done without scale (its strength); used both inpatient and outpatient.',
 'easy', 'approved', 2012, 'Paper II'),

('KRCHN', 'Pharmacology', 'Drug Interactions',
 'Drugs that are known to reduce the efficacy of hormonal contraceptives are:',
 'Artemether lumefantrine, rifampicin',
 'Pyrazinamide, phenytoin',
 'Phenytoin, rifampicin',
 'Ethambutol, co-trimoxazole',
 'C',
 'CYP3A4 ENZYME INDUCERS reduce the plasma concentration and efficacy of hormonal contraceptives (especially combined OCs): RIFAMPICIN, RIFABUTIN (TB drugs — major inducers); ANTI-EPILEPTICS — PHENYTOIN, carbamazepine, phenobarbitone, primidone, topiramate; St John''s wort; some antiretrovirals (efavirenz, nevirapine). Women on these drugs need higher-dose pills, alternative methods (Cu-IUD, depot, or condoms in addition), or non-hormonal contraception. AL, pyrazinamide, ethambutol, cotrimoxazole do NOT significantly induce CYP3A4.',
 'hard', 'approved', 2012, 'Paper I');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Medical-Surgical Nursing', 'STI Management',
 'The WHO recommended treatment of uncomplicated Neisseria gonorrhoea is:',
 'Benzyl penicillin 3g intramuscularly as a single dose',
 'Ofloxacin 400 mg orally as a single dose',
 'Ceftriaxone 250 mg intramuscularly as a single dose',
 'Azithromycin 1g orally as a single dose',
 'C',
 'WHO/Kenya STI guidelines for UNCOMPLICATED GONOCOCCAL infection: CEFTRIAXONE 250 mg IM stat (some current protocols 500 mg-1g due to rising MICs) — single dose. Often given WITH AZITHROMYCIN 1 g orally stat (dual therapy — covers chlamydia co-infection AND helps slow resistance). Older fluoroquinolones (ofloxacin, ciprofloxacin) NO LONGER RECOMMENDED — widespread resistance. Penicillin no longer effective due to PPNG (penicillinase-producing N. gonorrhoeae). Always treat partners, screen for other STIs, counsel on prevention.',
 'medium', 'approved', 2012, 'Paper I'),

('KRCHN', 'Infection Prevention & Control', 'Needlestick Injury',
 'When managing accidental exposure to body fluids and possible HIV infection after a needle prick, the action that should be taken in correct sequence is:',
 'Wash the wound under running water with soap, take emergency ARVs, undergo HIV test',
 'Take emergency ARVs, wash the wound under running water with soap, undergo HIV test',
 'Wash the wound under running water with soap, undergo HIV test, take emergency ARVs',
 'Undergo HIV test, wash the wound under running water with soap, take emergency ARVs',
 'C',
 'Post-Exposure Prophylaxis (PEP) protocol for needlestick injury: (1) IMMEDIATE FIRST AID — encourage bleeding (don''t squeeze tissue), WASH the wound thoroughly with SOAP AND RUNNING WATER for several minutes; irrigate eyes with saline if eye exposure; (2) RISK ASSESSMENT — type of exposure, source patient HIV/HBV/HCV status; (3) Source patient HIV test (with consent); EXPOSED PERSON BASELINE HIV TEST; (4) Start PEP if indicated (within 72 hours, ideally 1-2 hours) — TDF/FTC + DTG for 28 days; (5) Follow-up HIV testing at 6 weeks and 3 months. Option C reflects this sequence: wash → test → PEP.',
 'medium', 'approved', 2012, 'Paper II'),

('KRCHN', 'Health Systems & Management', 'Management Functions',
 'Controlling function in management involves:',
 'Performance appraisal, quality management',
 'Determining philosophy and goals, managing action',
 'Recruiting, interviewing and orientating staff',
 'Establishing structures, grouping activities',
 'A',
 'MANAGEMENT FUNCTIONS (Fayol/POSDCORB): PLANNING (philosophy, goals, objectives — option B); ORGANISING (structures, grouping — option D); STAFFING (recruiting, interviewing, orientating — option C); DIRECTING/LEADING (motivating, supervising, communicating); CONTROLLING (monitoring performance against standards) — includes PERFORMANCE APPRAISAL, QUALITY MANAGEMENT/audits, budget monitoring, taking corrective action — option A. Controlling closes the feedback loop and ensures organisational goals are being met.',
 'easy', 'approved', 2012, 'Paper II'),

('KRCHN', 'Health Systems & Management', 'Primary Health Care',
 'After the Alma Ata Declaration, three elements of primary health care that were added in Kenya are:',
 'Mental health, immunisation, dental health',
 'Mental health, HIV and AIDS, dental health',
 'Mental health, provision of essential drugs, HIV and AIDS',
 'Mental health, provision of essential drugs, immunisation',
 'B',
 'Original 8 ELEMENTS of PHC (Alma Ata 1978): Education on health problems, Locally endemic disease control, MCH including family planning, Essential drugs, Nutrition, Treatment of common conditions, Sanitation and safe water, Immunisation. Kenya added 3 more (totalling 11): MENTAL HEALTH, DENTAL HEALTH, HIV AND AIDS — option B. Some references also cite community-based rehabilitation. Immunisation and essential drugs are part of the original 8, not added.',
 'medium', 'approved', 2012, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Community Participation',
 'Community participation in organisation of health services in ascending order includes:',
 'Information, discussion, consultation, full control',
 'Consultation, information, discussion, full control',
 'Consultation, discussion, information, full control',
 'Information, consultation, discussion, full control',
 'D',
 'LADDER/CONTINUUM OF COMMUNITY PARTICIPATION (ascending — lowest to highest involvement): (1) INFORMATION (one-way — community told what''s happening); (2) CONSULTATION (community asked for views — final decision elsewhere); (3) DISCUSSION/dialogue (two-way exchange, community input considered); (4) PARTNERSHIP/joint decision; (5) FULL CONTROL/empowerment (community decides and acts). Lowest = tokenism; highest = empowerment. Option D correctly orders: information → consultation → discussion → full control.',
 'medium', 'approved', 2012, 'Paper II');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Community Health Nursing', 'School Health',
 'Specific functions of school health include:',
 'Conducting special screening programs, treatment of cases by teachers and school nurse',
 'Determining the health status of each child, continuously appraising changes in health status of a child',
 'Continuously appraising changes in each child, case management of a sick child',
 'Determining the health status of each child, case management of a sick child',
 'B',
 'SCHOOL HEALTH PROGRAMME functions (per Kenya MoH/MoEST): (1) school HEALTH ASSESSMENT/screening — DETERMINING HEALTH STATUS at entry and periodically; (2) CONTINUOUS MONITORING — APPRAISING CHANGES in health, growth and development; (3) immunisation catch-up; (4) deworming, micronutrient supplementation; (5) treatment of minor ailments; (6) health education (life skills, hygiene, nutrition, SRH); (7) healthy school environment (sanitation, water); (8) referral. Option B captures the surveillance functions of school health most accurately.',
 'medium', 'approved', 2012, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Occupational Health',
 'Primary prevention of occupational health care hazards includes:',
 'Emphasis on first aid to minimise complications',
 'Dealing with substances inhaled or contracted because of employee''s poor attitudes',
 'General screening of non-occupational illness before a person is hired',
 'Screening of the working environment to check that recommended preventive measures are put in place',
 'D',
 'Levels of prevention applied to occupational health: PRIMARY = preventing disease from occurring — workplace hazard identification/assessment, ENGINEERING controls, administrative controls (job rotation, shorter shifts), PPE, employee training, ENVIRONMENTAL SCREENING/monitoring of workplace (noise, dust, chemicals — option D). SECONDARY = early detection and treatment — periodic medical examination, biological monitoring. TERTIARY = preventing complications and disability after disease — rehabilitation, return-to-work, first aid (option A is tertiary, not primary). PRE-EMPLOYMENT screening (option C) is more selection/baseline, not prevention.',
 'medium', 'approved', 2012, 'Paper II'),

('KRCHN', 'Maternal & Child Health', 'Child Development',
 'A child aged 9-12 months is able to:',
 'Stand without assistance and throw balls',
 'Walk without support and grasp small objects with thumb and fingers',
 'Enjoy imitation and take objects out of a container',
 'Walk and can say some sentences',
 'C',
 'Developmental milestones at 9-12 MONTHS: motor — crawls well, pulls to stand, stands holding on, cruises (walks holding furniture), some take first independent steps by 12 m; FINE motor — pincer grasp (thumb-index), bangs objects together, places/removes objects from container; LANGUAGE — first words ("mama", "dada") with meaning, responds to name; SOCIAL/COGNITIVE — IMITATES SIMPLE ACTIONS (waves bye-bye, claps), object permanence, plays peekaboo, ENJOYS IMITATION. Option C is the most age-typical. Walking unsupported (B) and sentences (D) are older skills.',
 'medium', 'approved', 2012, 'Paper I');

-- =============================================================================
-- KRCHN Paper 3 — July 2014
-- =============================================================================

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Community Health Nursing', 'Communicable Diseases',
 'An example of a disease that does not pass from human to human is:',
 'Tuberculosis',
 'Diphtheria',
 'Tetanus',
 'Malaria',
 'C',
 'Modes of disease transmission: HUMAN-TO-HUMAN (communicable) — TB (airborne droplets), diphtheria (respiratory droplets), measles, cholera, HIV, etc. ARTHROPOD VECTOR-borne (often human-to-human via vector) — malaria (anopheles), dengue (aedes), trypanosomiasis (tsetse). ENVIRONMENTAL (NOT human-to-human) — TETANUS (Clostridium tetani spores in soil/dust enter via wounds — no human-to-human transmission), botulism, brucellosis (animal source). Tetanus is the only one in the list that is acquired from the ENVIRONMENT (soil), not from another human.',
 'easy', 'approved', 2014, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Tuberculosis Control',
 'In the treatment of tuberculosis "DOT" means:',
 'Patient getting TB treatment as close to home as possible',
 'Patient adheres to treatment during the intensive phase only',
 'Directly observed treatment with weekly monitoring',
 'Patient takes every drug dosage under supervision during the intensive phase',
 'D',
 'DOT = DIRECTLY OBSERVED TREATMENT — a TB treatment strategy where a trained observer (health worker or trained treatment supporter) WATCHES THE PATIENT SWALLOW EVERY DOSE of anti-TB medication, especially during the INTENSIVE PHASE (first 2 months — 2HRZE). Continuation phase (4HR) is usually self-administered with periodic follow-up. DOT improves adherence, reduces relapse, prevents drug resistance, and is one of the five elements of WHO''s DOTS strategy (commitment, case detection by smear, DOT, drug supply, monitoring). Option D is most precise — every dose under supervision during intensive phase.',
 'easy', 'approved', 2014, 'Paper II'),

('KRCHN', 'Health Systems & Management', 'Health System Structure',
 'All health care services and activities within the district are monitored and supervised by the district:',
 'Health management team',
 'The Nursing Officers',
 'Medical Officer of Health',
 'Clinical Officer',
 'A',
 'The DISTRICT HEALTH MANAGEMENT TEAM (DHMT) is the multidisciplinary body coordinating, monitoring and supervising ALL district-level health services and activities. Chaired by DMOH but it is a team (DMOH, DNO, DPHO, DCO, DPHN, finance, pharmacy, health records, etc.) — collectively responsible. With Kenya''s devolved system since 2013, equivalent bodies are at sub-county level (SCHMT) and County Health Management Team (CHMT).',
 'easy', 'approved', 2014, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Disaster Management',
 'Triaging may best be defined as the process of:',
 'Assessing all incoming casualties of a disaster',
 'Initiating diagnostic measures for casualties of a disaster',
 'Determining the urgency of need of care for casualties of a disaster',
 'Setting priorities and assigning urgency ratings for casualties of a disaster',
 'D',
 'TRIAGE = the process of SORTING/CATEGORISING casualties based on URGENCY OF NEED FOR CARE, ASSIGNING PRIORITY RATINGS and RESOURCES based on likelihood of benefit — particularly when resources are limited. Option D is more complete than C — triage includes BOTH determining urgency AND assigning priority ratings/category (red/yellow/green/black). Various triage tools: START (Simple Triage and Rapid Treatment) for adults; JumpSTART for paediatrics; SALT (Sort, Assess, Lifesaving interventions, Treatment/Transport).',
 'medium', 'approved', 2014, 'Paper II'),

('KRCHN', 'Maternal & Child Health', 'Child Health',
 'Non-organic growth failure (failure to thrive) in a child may be attributed to:',
 'A poor mother-child bond of attachment',
 'Altered physiology due to improper feeding',
 'Congenital disorders of metabolism',
 'High incidence of child abuse',
 'A',
 'FAILURE TO THRIVE (FTT) classifications: ORGANIC FTT — identifiable medical/physiological cause (malabsorption, congenital heart disease, chronic infection like TB/HIV, metabolic disorders, GORD, neurological problems); NON-ORGANIC FTT (often called "psychosocial" FTT) — caused by PSYCHOSOCIAL FACTORS — POOR MOTHER-CHILD ATTACHMENT/bonding, neglect, maternal depression, poverty, food insecurity, inadequate feeding practices. Treatment requires multidisciplinary approach — feeding support, social work, mental health support, child protection if abuse. Option A is the classic non-organic cause.',
 'medium', 'approved', 2014, 'Paper I');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Community Health Nursing', 'Dental Health',
 'The acid-generating bacterium in our mouth that is the most common cause of tooth decay (dental caries) is the:',
 'Streptococcus viridans',
 'Neisseria catarrhalis',
 'Streptococcus mutans',
 'Staphylococcus aureus',
 'C',
 'DENTAL CARIES (tooth decay) pathogenesis: bacterial PLAQUE (biofilm) metabolises dietary sugars producing ACIDS that demineralise tooth enamel. The primary cariogenic bacterium is STREPTOCOCCUS MUTANS — converts sucrose to lactic acid (and synthesises insoluble glucans that anchor plaque). Lactobacilli also contribute, particularly in advanced caries. Prevention: oral hygiene (brushing with FLUORIDE toothpaste, flossing); REDUCED FREQUENCY of sugar consumption; FLUORIDE (water fluoridation, varnish); fissure sealants on molars; regular dental check-ups.',
 'medium', 'approved', 2014, 'Paper II'),

('KRCHN', 'Health Systems & Management', 'Professional Practice',
 'The term "role" may be defined as:',
 'Community''s expectation of a trained person',
 'Legal and moral binding of a professional',
 'Capacity to run health care activities',
 'Activities one is expected to perform as a professional',
 'D',
 'ROLE (sociology/professional) = the SET OF EXPECTED ACTIVITIES, BEHAVIOURS and RESPONSIBILITIES that a person is expected to perform by virtue of their POSITION (e.g., nurse, doctor, teacher). Includes role expectations from self, colleagues, patients, profession, employer, society. SCOPE OF PRACTICE is the legally-defined role boundary. Role conflict, role strain, role ambiguity are challenges. Option D is the most precise professional definition. Option A is closer to a layperson''s view; option B is professional accountability; option C is competence/capability.',
 'easy', 'approved', 2014, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Ageing',
 'Currently in Kenya the problems associated with old age are made worse by the:',
 'Early retirement and meagre pension',
 'Inability to acquire new marketable skills',
 'Poor health, poverty and dependency',
 'Disintegration of traditional social support systems',
 'D',
 'Kenya''s elderly population (≥60 years) is growing rapidly. PROBLEMS faced: poverty (no/inadequate pension), declining health (NCDs, sensory loss, mobility), social isolation, neglect, elder abuse, lack of geriatric services. The DISTINCTIVE CONTEMPORARY FACTOR making things worse is the DISINTEGRATION OF TRADITIONAL SOCIAL SUPPORT SYSTEMS — traditionally elders were cared for within extended family/communal structures. Urbanisation, migration, modernisation, smaller families have eroded these systems, leaving many elders without care or support. National Older Persons Cash Transfer (Inua Jamii) and the Older Persons Act 2014 aim to address gaps.',
 'medium', 'approved', 2014, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Immunisation',
 'A major cause of "missed opportunity" in the immunisation programme is:',
 'Failure of the cold chain',
 'Use of vaccines that have lost potency',
 'High drop-out of immunisable target group',
 'Vaccine stock out',
 'C',
 'MISSED OPPORTUNITIES in immunisation (per WHO/KEPI): occasions when an eligible child/woman comes into contact with a health service but DOES NOT RECEIVE the vaccines they need. Major causes: HIGH DROP-OUT/incomplete immunisation (started but didn''t return for later doses — option C); not screening for vaccination status at every contact; service contraindications/myths; provider not knowing schedule; vaccine stock-outs at the visit (option D also a cause). High dropout (especially between Penta 1 and 3, or measles) is the LEADING cause of incomplete immunisation. Strategies: defaulter tracing, every-contact screening, integrated services.',
 'medium', 'approved', 2014, 'Paper II'),

('KRCHN', 'Research & Statistics', 'Data Analysis',
 'The process in community diagnosis in which data is separated and categorised in order to help one understand its meaning is known as data:',
 'Handling',
 'Analysis',
 'Cleaning',
 'Presentation',
 'B',
 'Data processing stages: COLLECTION → CLEANING (option C — checking for errors, missing values, inconsistencies) → ANALYSIS (option B — SEPARATING, CATEGORISING, CALCULATING, INTERPRETING data to extract meaning — descriptive statistics, comparisons, trends, hypothesis testing) → PRESENTATION (option D — graphs, tables, narratives for dissemination); HANDLING (option A — broad term, less specific). Analysis is the cognitive step transforming raw data into INFORMATION → understanding.',
 'easy', 'approved', 2014, 'Paper II');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Nutrition', 'Vitamins',
 'Vitamins found in the watery parts of the foods we eat:',
 'Vit K, Niacin, Riboflavin, pantothenic acid',
 'Pantothenic acid, Thiamine, Pyridoxine, Vit E',
 'Vit K, Pantothenic acid, Thiamine, Pyridoxine',
 'Folate, Cyanocobalamine, Thiamine, Riboflavin',
 'D',
 'Vitamins are classified by solubility: WATER-SOLUBLE — B-complex vitamins (B1 THIAMINE, B2 RIBOFLAVIN, B3 niacin, B5 pantothenic acid, B6 pyridoxine, B7 biotin, B9 FOLATE/folic acid, B12 CYANOCOBALAMINE) and Vitamin C. Found in "watery" parts of food. Not stored extensively (except B12 in liver) — daily intake needed; excess excreted in urine. FAT-SOLUBLE — A, D, E, K — found in fatty parts, stored in liver/adipose, risk of toxicity at high doses. Option D lists 4 water-soluble vitamins (folate, B12, B1, B2). Options A and C contain Vit K (fat-soluble — incorrect). Option B contains Vit E (fat-soluble — incorrect).',
 'medium', 'approved', 2014, 'Paper II'),

('KRCHN', 'Nutrition', 'Proteins',
 'Essential amino acids can be defined as amino acids that:',
 'Cannot be made by the body',
 'Body can make if nitrogen is available',
 'Are unique in their primary structure',
 'Are the basic building blocks of proteins',
 'A',
 'Amino acids classified by dietary requirement: ESSENTIAL (indispensable) amino acids — CANNOT BE SYNTHESISED BY THE BODY in sufficient quantities and MUST BE OBTAINED FROM THE DIET. 9 essential AAs: HISTIDINE, ISOLEUCINE, LEUCINE, LYSINE, METHIONINE, PHENYLALANINE, THREONINE, TRYPTOPHAN, VALINE. Conditionally essential — needed extra under stress/disease (e.g. arginine in burns/sepsis; cysteine/tyrosine in liver disease). NON-ESSENTIAL — synthesised from other AAs/nitrogen. Complete protein sources contain all 9 essential AAs (animal proteins, soya); plant proteins often have one limiting AA.',
 'easy', 'approved', 2014, 'Paper II'),

('KRCHN', 'Maternal & Child Health', 'PMTCT',
 'The dosage of drugs in primary level ARV prophylaxis for prevention of mother-to-child transmission of HIV is:',
 'Nevirapine (NVP) 200mg to mother at onset of labour, infant NVP 2mg/kg as soon as possible within 72 hours of delivery',
 'Nevirapine (NVP) 200mg to mother during labour, infant NVP 2mg/kg immediately after birth plus 4 weeks of AZT 4mg/kg BD',
 'AZT 300mg BD plus NVP 200mg to mother during labour, infant 2mg/kg after birth plus AZT 4mg/kg BD for one week',
 'AZT 600mg to mother at onset of labour, infant NVP 2mg/kg immediately after birth',
 'B',
 'This question references OLDER PMTCT prophylaxis regimens (Option A/Option B/Option B+ ladder, pre-2014). Single-dose Nevirapine (sdNVP) to mother + infant was a primary regimen historically but had resistance concerns. CURRENT Kenya PMTCT (since 2014, Option B+ then "Treat All" 2016): LIFELONG TRIPLE ART for all HIV+ pregnant women regardless of CD4 (first-line: TDF/3TC/DTG or TDF/3TC/EFV). INFANT prophylaxis: NVP daily for 6 weeks (high-risk: up to 12 weeks) for breastfeeding HIV-exposed infants. The question represents historical knowledge; option B approximates the older Option B regimen.',
 'hard', 'approved', 2014, 'Paper I'),

('KRCHN', 'Community Health Nursing', 'Water and Disease',
 'Water-related diseases include:',
 'Typhoid, malaria, cholera',
 'Malaria, cholera, schistosomiasis',
 'Cholera, schistosomiasis, diarrhoea',
 'Malaria, schistosomiasis, onchocerciasis',
 'D',
 'WHO classification of water and disease: (1) WATER-BORNE — pathogen in water — cholera, typhoid, hepatitis A, dysentery, polio (faecal-oral); (2) WATER-WASHED (water-scarce) — diseases of poor personal hygiene from inadequate water for washing — trachoma, scabies, skin/eye infections; (3) WATER-BASED — pathogen has obligate aquatic host — SCHISTOSOMIASIS (snail intermediate host), guinea worm; (4) WATER-RELATED (vector breeds in/near water) — MALARIA (anopheles in water), DENGUE, ONCHOCERCIASIS (simulium near fast-flowing rivers), filariasis, trypanosomiasis. Option D lists three vector-related/water-based diseases.',
 'medium', 'approved', 2014, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Health Services',
 'When health care is geographically, financially and culturally within easy reach to the entire community the service is said to be:',
 'Available to the community',
 'Acceptable to the community',
 'Accessible to the community',
 'Affordable to the community',
 'C',
 'The "4 As" framework of health service quality/access: AVAILABILITY — services exist (clinic open, drugs in stock, staff present); ACCESSIBILITY — services are within REACH — GEOGRAPHIC (distance, transport), FINANCIAL (cost-affordability), socio-CULTURAL/SOCIAL acceptability (option C — comprehensive concept); ACCEPTABILITY — services align with cultural beliefs, dignity, language; AFFORDABILITY — services not financially prohibitive. Option C encompasses all dimensions of "easy reach" — geographic, financial, cultural — by definition of accessibility (a broader concept than just affordability or acceptability alone).',
 'easy', 'approved', 2014, 'Paper II');

INSERT INTO questions (cadre, unit, topic, stem, option_a, option_b, option_c, option_d, correct_option, rationale, difficulty, status, exam_year, paper) VALUES

('KRCHN', 'Community Health Nursing', 'Screening',
 'The purpose of a screening test is to:',
 'Diagnose persons with the disease',
 'Detect persons with risk factors of sub-clinical disease',
 'Check whether a population is at risk of a disease',
 'Collect the data for a mass campaign',
 'B',
 'SCREENING vs DIAGNOSTIC TESTS: SCREENING — applied to ASYMPTOMATIC persons to IDENTIFY THOSE AT HIGHER RISK or with SUB-CLINICAL DISEASE (pre-clinical detectable phase) — does NOT diagnose, only identifies people needing further evaluation. Examples: Pap smear, VIA/VILI, mammography, HIV testing, BP screening. DIAGNOSTIC — applied to SYMPTOMATIC or screen-positive people to CONFIRM diagnosis. Wilson-Jungner criteria for good screening: important condition, accepted treatment, facilities for diagnosis/treatment available, recognisable latent/early phase, suitable test, acceptable to population.',
 'medium', 'approved', 2014, 'Paper II'),

('KRCHN', 'Community Health Nursing', 'Immunisation',
 'Herd immunity may be said to exist in a community when:',
 'Both dead and live antigens are used to immunise',
 'Vaccination is stopped in a community that has been well vaccinated',
 'The incidence of the disease decreases to a very low level',
 'A high percentage of people are immune to an infection',
 'D',
 'HERD (community) IMMUNITY = the indirect protection of unimmunised individuals when a SUFFICIENTLY HIGH PROPORTION of the population is IMMUNE (via vaccination or natural infection), interrupting transmission chains. Required threshold (the "herd immunity threshold") varies by R0: measles (R0 12-18) requires ~95%; pertussis ~94%; polio ~80%; influenza ~70%. Protects: those who can''t be vaccinated (infants, immunocompromised), vaccine failures, those refusing. Disease cases drop sharply, sometimes to elimination. Option D is the definition.',
 'easy', 'approved', 2014, 'Paper II'),

('KRCHN', 'Maternal & Child Health', 'Family Planning',
 'Emergency hormonal contraception is usually effective following unprotected sex when taken within a period of:',
 '120 hours',
 '72 hours',
 '24 hours',
 '12 hours',
 'A',
 'Emergency contraception (EC) options and time windows: LEVONORGESTREL 1.5 mg single dose — most effective within 72 hours but can be used UP TO 120 HOURS (5 days) with declining efficacy; ULIPRISTAL ACETATE 30 mg single dose — effective up to 120 hours with sustained efficacy; YUZPE METHOD (combined COCs) — within 72 hours, less effective and more side effects; COPPER IUD — most effective method (>99%), within 120 HOURS (5 days). The widest window ("120 hours") covers ulipristal and copper IUD — option A. Time matters — sooner is more effective.',
 'medium', 'approved', 2014, 'Paper I');
